export default {
    // UI
    game_title: 'Các Thế Hệ',
    game_subtitle: 'Một Tiểu Thuyết Trực Quan Về Cuộc Sống',
    family_fund_label: 'Ngân quỹ gia đình',
    family_log_title: 'Nhật ký gia đình',
    year_label: 'Năm',
    family_tree_title: 'Cây phả hệ',
    default_family_name_placeholder: 'Tên gia đình',
    family_suffix: ' gia đình',
    settings_button: 'Cài đặt',
    settings_modal_title: 'Cài đặt trò chơi',
    language_label: 'Ngôn ngữ',
    game_speed_label: 'Tốc độ trò chơi',
    play_again_button: 'Chơi lại',
    how_to_play_button: 'Hướng dẫn',
    quit_game_button: 'Thoát',
    resume_button: 'Tiếp tục',
    pause_button: 'Tạm dừng',
    speed_slow: 'Chậm',
    speed_normal: 'Bình thường',
    speed_fast: 'Nhanh',
    speed_very_fast: 'Rất nhanh',
    tab_log: 'Nhật ký',
    tab_assets: 'Tài sản',
    tab_businesses: 'Kinh doanh',
    tab_details: 'Chi tiết',
    tab_life_events: 'Sự kiện cuộc đời',
    scene_tree: 'Gia phả',
    scene_log: 'Nhật ký',
    scene_assets: 'Tài sản',
    scene_business: 'Kinh doanh',
    event_for: 'Sự kiện cho',
    for_char_label: 'Cho',
    cost_label: 'Chi phí',
    cancel_button: 'Hủy',
    back_button: 'Quay lại',
    // Stats
    stat_iq: 'IQ',
    stat_happiness: 'Hạnh phúc',
    stat_eq: 'EQ',
    stat_health: 'Sức khỏe',
    stat_skill: 'Kỹ năng',
    // Character Details
    age_short: 'tuổi',
    deceased_at: 'Mất lúc',
    relationship_label: 'Tình trạng',
    with_person: 'với',
    pet_label: 'Thú cưng',
    the_pet_type: '',
    education_label: 'Học vấn',
    major_label: 'Chuyên ngành',
    career_label: 'Sự nghiệp',
    working_at_label: 'Làm việc tại',
    clubs_label: 'Câu lạc bộ',
    life_events_label: 'Sự kiện cuộc đời',
    education_none: 'Chưa có',
    education_high_school: 'Bằng tốt nghiệp cấp 3',
    education_vocational_diploma: 'Chứng chỉ nghề',
    education_university_display: 'Đại học ({major_name})',
    // Welcome Back & Start Menu
    welcome_back_title: 'Chào mừng trở lại!',
    welcome_back_subtitle: 'Lượt chơi trước của bạn đã được lưu.',
    continue_game_button: 'Tiếp tục chơi',
    start_new_game_button: 'Bắt đầu mới',
    // Instructions
    instructions_title: 'Hướng dẫn chơi',
    instructions_objective_title: 'Mục tiêu',
    instructions_objective_desc: 'Mục tiêu của bạn là dẫn dắt một dòng họ và tồn tại cho đến khi thế hệ thứ 6 được sinh ra.',
    instructions_gameplay_title: 'Cách chơi',
    instructions_gameplay_desc: 'Trò chơi tự động chạy theo từng ngày. Bạn có thể tạm dừng, tiếp tục và thay đổi tốc độ. Thời gian sẽ dừng lại khi có một sự kiện ngẫu nhiên hoặc một lựa chọn cuộc đời quan trọng (như chọn trường học) xảy ra, yêu cầu bạn đưa ra quyết định.',
    instructions_events_title: 'Sự Kiện & Lựa Chọn',
    instructions_events_desc: "Cuộc sống đầy rẫy những lựa chọn. Khi một sự kiện xảy ra, bạn phải quyết định cách nhân vật của mình phản ứng. Mỗi lựa chọn đều có hậu quả, có cái tức thì, có cái sâu rộng. Hãy lựa chọn một cách khôn ngoan.",
    instructions_stats_title: 'Chỉ số & Hình đại diện',
    instructions_stats_desc: 'Nhấp vào hình đại diện của bất kỳ nhân vật nào để xem chi tiết các chỉ số của họ (IQ, Hạnh phúc, v.v.).',
    instructions_phases_title: 'Các giai đoạn cuộc đời',
    instructions_phases_desc: 'Các nhân vật sẽ trải qua các giai đoạn khác nhau của cuộc đời, từ Sơ sinh đến Nghỉ hưu. Mỗi giai đoạn sẽ mở ra các sự kiện và cơ hội mới.',
    instructions_finance_title: 'Gia đình & Tài chính',
    instructions_finance_desc: 'Các nhân vật có thể kết hôn và sinh con. Vợ/chồng sẽ có việc làm và đóng góp vào Ngân quỹ chung của gia đình. Hãy sử dụng nó một cách khôn ngoan cho giáo dục, kinh doanh và các nhu cầu khác.',
    // Summary Screen
    summary_victory_title: 'Chúc mừng!',
    summary_gameover_title: 'Trò chơi kết thúc',
    summary_victory_desc: 'Bạn đã duy trì thành công dòng họ của mình đến thế hệ thứ 6.',
    summary_gameover_desc: 'Dòng họ của bạn đã phá sản vì hết tiền. Bạn phải quản lý tài chính khôn ngoan hơn vào lần sau.',
    summary_gameover_desc_debt: "Dòng họ của bạn đã sụp đổ dưới gánh nặng nợ nần sau khi không thể trả được khoản vay.",
    summary_total_generations: 'Tổng số thế hệ',
    summary_total_members: 'Tổng số thành viên',
    summary_living_members: 'Thành viên còn sống',
    summary_deceased_members: 'Thành viên đã mất',
    summary_highest_education: 'Học vấn cao nhất',
    summary_highest_career: 'Sự nghiệp cao nhất',
    summary_final_funds: 'Ngân quỹ cuối cùng',
    summary_asset_value: 'Giá trị tài sản',
    summary_ending_year: 'Năm kết thúc',
    // Modals
    modal_school_title: 'Chọn trường học',
    modal_school_desc: 'Đã đến lúc {name} phải đi học! Hãy chọn một con đường học vấn.',
    modal_university_title: 'Học vấn cao hơn',
    modal_university_desc: '{name} có nên học Đại học không? Việc này sẽ tốn kém nhưng có thể mở ra những cơ hội nghề nghiệp tốt hơn.',
    university_choice_yes: 'Có, đầu tư cho tương lai',
    university_choice_no: 'Không, đi làm ngay bây giờ',
    modal_major_title: 'Chọn chuyên ngành',
    modal_major_desc: '{name} sẽ học gì ở trường Đại học?',
    modal_major_no_money: 'Bạn không đủ tiền để học bất kỳ chuyên ngành nào trong số này.',
    modal_career_title: 'Chọn một con đường sự nghiệp',
    modal_career_desc: '{name} đã hoàn thành chương trình học. Họ nên theo đuổi con đường sự nghiệp nào?',
    modal_loan_title: "Hỗ trợ tài chính",
    modal_loan_desc: "Ngân quỹ gia đình của bạn đã bị âm! Để tránh phá sản ngay lập tức, bạn phải vay một khoản tín dụng. Vui lòng chọn số tiền và thời hạn trả nợ.",
    loan_amount_label: "Số tiền vay",
    loan_term_label: "Thời hạn trả (Năm)",
    accept_loan_button: "Chấp nhận khoản vay",
    modal_promotion_title: "Cơ hội thăng tiến!",
    modal_promotion_desc: "Sự chăm chỉ của {name} đã được ghi nhận! Họ đã được đề bạt lên vị trí {title}. Chúc mừng!",
    accept_promotion_button: "Tuyệt vời!",
    modal_underqualified_title: 'Không đủ điều kiện cho vị trí',
    modal_underqualified_desc: '{name} có chuyên ngành phù hợp với ngành {careerName}, nhưng không đáp ứng đủ các yêu cầu. Họ nên tiến hành như thế nào?',
    underqualified_choice_trainee: 'Trở thành Thực tập sinh',
    underqualified_choice_trainee_desc: 'Bắt đầu với mức lương rất thấp. Các chỉ số cần thiết của bạn sẽ tăng theo thời gian cho đến khi bạn đủ điều kiện cho vị trí chính thức.',
    underqualified_choice_penalized: 'Chấp nhận vị trí bị phạt',
    underqualified_choice_penalized_desc: 'Bắt đầu ở mức lương thấp nhất. Tốc độ tăng kỹ năng và thăng chức của bạn sẽ bị phạt dựa trên mức độ thiếu hụt chỉ số.',
    underqualified_tooltip: 'Thiếu yêu cầu:',
    underqualified_tooltip_iq: 'IQ ({shortfall} điểm)',
    underqualified_tooltip_conf: 'Tự tin ({shortfall} điểm)',
    modal_club_choice_title: 'Chọn một câu lạc bộ',
    modal_club_choice_desc: 'Đã đến lúc {name} tham gia một câu lạc bộ sau giờ học! Điều này có thể giúp định hình sự nghiệp tương lai của họ.',
    join_club: 'Tham gia',
    skip_clubs: 'Bỏ qua bây giờ',
    // Assets & Businesses
    family_assets_title: 'Tài sản gia đình',
    total_value_label: 'Tổng giá trị',
    no_assets_message: 'Chưa có tài sản nào. Bạn có thể mua tài sản bên dưới.',
    family_businesses_title: 'Doanh nghiệp gia đình',
    no_businesses_message: 'Chưa sở hữu doanh nghiệp nào. Hãy mua một cái bên dưới!',
    level_label: 'Cấp',
    upgrade_button: 'Nâng cấp',
    req_major_label: 'Yêu cầu',
    unskilled_major: 'Không yêu cầu',
    unassigned_option: 'Chưa chỉ định',
    hire_robot_option: 'Thuê Robot',
    family_members_label: 'Thành viên gia đình',
    purchase_business_title: 'Mua doanh nghiệp mới',
    base_revenue_label: 'Doanh thu cơ bản',
    buy_button: 'Mua',
    manage_button: 'Quản lý',
    manage_business_title: 'Quản lý Doanh nghiệp',
    select_business_to_manage: 'Chọn doanh nghiệp bạn muốn quản lý',
    business_map_intro: 'Xem bản đồ thành phố để mua hoặc quản lý các doanh nghiệp của bạn.',
    salary_label: 'Lương',
    sell_button: 'Bán',
    // Life Phases
    phase_Newborn: 'Sơ sinh',
    phase_Elementary_School: 'Tiểu học',
    phase_Middle_School: 'Trung học cơ sở',
    phase_High_School: 'Trung học phổ thông',
    phase_University: 'Đại học',
    phase_Working_Life: 'Đi làm',
    phase_Retired: 'Nghỉ hưu',
    // Character Status
    status_Idle: 'Rảnh rỗi',
    status_In_Education: 'Đang đi học',
    status_Working: 'Đang đi làm',
    status_Unemployed: 'Thất nghiệp',
    status_Internship: 'Thực tập',
    status_Vocational_Training: 'Học nghề',
    status_Retired: 'Đã nghỉ hưu',
    status_Trainee: 'Thực tập sinh',
    // Relationship Status
    relationship_Single: 'Độc thân',
    relationship_Married: 'Đã kết hôn',
    // Scenarios
    scenario_classic_name: 'Cổ điển',
    scenario_classic_desc: 'Bắt đầu một cuộc sống mới từ khi sinh ra và dẫn dắt gia đình bạn qua các thế hệ.',
    scenario_alone_name: 'Một mình',
    scenario_alone_desc: 'Bắt đầu ở tuổi 24 sau tốt nghiệp với 50.000 đô la. Tùy bạn xây dựng một di sản từ đầu.',
    scenario_mila_name: 'Gia đình Mila',
    scenario_mila_desc: 'Bước vào cuộc sống của một gia đình có sẵn, vượt qua thử thách và dẫn dắt họ đến sự thịnh vượng.',
    // Schools
    school_public: 'Trường công',
    school_private: 'Trường tư',
    school_royal: 'Học viện Hoàng gia',
    school_public_high: 'Trường THPT công lập',
    school_private_high: 'Trường THPT tư thục',
    school_royal_high: 'Học viện Hoàng gia (cấp 3)',
    // Majors
    major_business: 'Kinh doanh',
    major_business_desc: 'Mở ra cơ hội nghề nghiệp trong quản lý và kinh doanh.',
    major_finance: 'Tài chính',
    major_finance_desc: 'Mở ra cơ hội nghề nghiệp trong tài chính và kế toán.',
    major_marketing: 'Marketing',
    major_marketing_desc: 'Mở ra cơ hội nghề nghiệp trong marketing và PR.',
    major_technology: 'Công nghệ',
    major_technology_desc: 'Mở ra cơ hội nghề nghiệp trong lập trình và CNTT.',
    major_engineering: 'Kỹ thuật',
    major_engineering_desc: 'Mở ra cơ hội nghề nghiệp trong các lĩnh vực kỹ thuật khác nhau.',
    major_arts: 'Nghệ thuật',
    major_arts_desc: 'Mở ra các ngành nghề sáng tạo như thiết kế và viết lách.',
    major_medicine: 'Y khoa',
    major_medicine_desc: 'Mở ra các ngành y tế có thu nhập cao.',
    major_culinary: 'Nghệ thuật ẩm thực',
    major_culinary_desc: 'Mở ra cơ hội nghề nghiệp trong nấu ăn và quản lý nhà hàng.',
    major_kinesiology: 'Khoa học vận động',
    major_kinesiology_desc: 'Mở ra cơ hội nghề nghiệp trong thể hình và huấn luyện.',
    major_agriculture: 'Nông nghiệp',
    major_agriculture_desc: 'Mở ra cơ hội nghề nghiệp trong nông nghiệp và chăn nuôi.',
    major_logistics: 'Logistics',
    major_logistics_desc: 'Mở ra cơ hội nghề nghiệp trong quản lý kho và chuỗi cung ứng.',
    // Careers - Unskilled
    career_unskilled_1: 'Lao công',
    career_unskilled_2: 'Thu ngân',
    career_unskilled_3: 'Nhân viên bán hàng',
    career_unskilled_4: 'Giám sát cửa hàng',
    // Careers - Trade
    career_trade_1: 'Thợ điện tập sự',
    career_trade_2: 'Thợ điện lành nghề',
    career_trade_3: 'Thợ điện bậc thầy',
    career_trade_4: 'Quản đốc',
    // Careers - Business
    career_business_1: 'Chuyên viên phân tích cấp dưới',
    career_business_2: 'Chuyên viên phân tích cấp cao',
    career_business_3: 'Quản lý',
    career_business_4: 'Giám đốc',
    // Careers - Technology
    career_technology_1: 'Lập trình viên cấp dưới',
    career_technology_2: 'Kỹ sư phần mềm',
    career_technology_3: 'Kỹ sư cấp cao',
    career_technology_4: 'Kỹ sư chính',
    // Careers - Arts
    career_arts_1: 'Trợ lý nghệ sĩ',
    career_arts_2: 'Nhà thiết kế đồ họa',
    career_arts_3: 'Giám đốc nghệ thuật',
    career_arts_4: 'Giám đốc sáng tạo',
    // Careers - Medicine
    career_medicine_1: 'Bác sĩ nội trú',
    career_medicine_2: 'Bác sĩ đa khoa',
    career_medicine_3: 'Bác sĩ phẫu thuật',
    career_medicine_4: 'Trưởng khoa',
    // Career Options
    career_option_job: 'Tìm việc',
    career_option_job_desc: 'Bắt đầu tìm kiếm một công việc cấp thấp ngay lập tức.',
    career_option_internship: 'Thực tập',
    career_option_internship_desc: 'Một kỳ thực tập 1 năm. Lương thấp nhưng có cơ hội nhận được lời mời làm việc.',
    career_option_vocational: 'Học nghề',
    career_option_vocational_desc: 'Một chương trình 3 năm để học một nghề.',
    major_match_tooltip: 'Phù hợp với chuyên ngành của bạn',
    // Pets
    pet_dog: 'Chó',
    pet_cat: 'Mèo',
    pet_parrot: 'Vẹt',
    pet_horse: 'Ngựa',
    pet_fish: 'Cá/Rùa',
    // Business Roles
    role_nurse: 'Y tá',
    role_doctor: 'Bác sĩ',
    role_head_nurse: 'Y tá trưởng',
    role_surgeon: 'Bác sĩ phẫu thuật',
    role_admin_staff: 'Nhân viên hành chính',
    role_chief_physician: 'Trưởng khoa nội',
    role_chief_surgeon: 'Trưởng khoa ngoại',
    role_researcher: 'Nhà nghiên cứu',
    role_manager: 'Quản lý',
    role_bank_teller: 'Giao dịch viên',
    role_loan_officer: 'Chuyên viên tín dụng',
    role_financial_analyst: 'Chuyên viên phân tích tài chính',
    role_investment_analyst: 'Chuyên viên phân tích đầu tư',
    role_it_support: 'Hỗ trợ IT',
    role_senior_manager: 'Quản lý cấp cao',
    role_chief_accountant: 'Kế toán trưởng',
    role_director: 'Giám đốc',
    role_lead_developer: 'Trưởng nhóm lập trình',
    role_copywriter: 'Người viết quảng cáo',
    role_designer: 'Nhà thiết kế',
    role_account_manager: 'Quản lý khách hàng',
    role_media_planner: 'Chuyên viên hoạch định truyền thông',
    role_art_director: 'Giám đốc nghệ thuật',
    role_marketing_lead: 'Trưởng phòng Marketing',
    role_pr_manager: 'Trưởng phòng PR',
    role_senior_editor: 'Biên tập viên cấp cao',
    role_qa_tester: 'Nhân viên kiểm thử',
    role_project_manager: 'Quản lý dự án',
    role_devops_engineer: 'Kỹ sư DevOps',
    role_machine_maintenance: 'Bảo trì máy móc',
    role_mechanical_engineer: 'Kỹ sư cơ khí',
    role_civil_engineer: 'Kỹ sư xây dựng',
    role_production_engineer: 'Kỹ sư sản xuất',
    role_quality_control: 'Quản lý chất lượng',
    role_receptionist: 'Lễ tân',
    role_curator: 'Người phụ trách (bảo tàng)',
    role_art_historian: 'Nhà sử học nghệ thuật',
    role_art_teacher: 'Giáo viên mỹ thuật',
    role_cashier: 'Thu ngân',
    role_service_staff: 'Nhân viên phục vụ',
    role_head_chef: 'Bếp trưởng',
    role_mixologist: 'Chuyên gia pha chế',
    role_head_trainer: 'Huấn luyện viên trưởng',
    role_lifeguard: 'Nhân viên cứu hộ',
    role_swimming_coach: 'Huấn luyện viên bơi lội',
    role_kinesiologist: 'Nhà khoa học vận động',
    role_general_laborer: 'Lao động phổ thông',
    role_farm_manager: 'Quản lý nông trại',
    role_agronomist: 'Nhà nông học',
    role_agricultural_engineer: 'Kỹ sư nông nghiệp',
    role_supply_chain_manager: 'Quản lý chuỗi cung ứng',
    role_stocker: 'Nhân viên kho',
    role_forklift_operator: 'Người vận hành xe nâng',
    role_warehouse_manager: 'Quản lý kho',
    role_logistics_coordinator: 'Điều phối viên logistics',
    // Business Names (Tiers 1-3)
    business_medicine_t1_name: 'Phòng khám địa phương',
    business_medicine_t2_name: 'Bệnh viện cộng đồng',
    business_medicine_t3_name: 'Trung tâm nghiên cứu y học',
    business_finance_t1_name: 'Quỹ tín dụng',
    business_finance_t2_name: 'Công ty đầu tư',
    business_finance_t3_name: 'Trụ sở ngân hàng lớn',
    business_marketing_t1_name: 'Công ty quảng cáo địa phương',
    business_marketing_t2_name: 'Công ty marketing kỹ thuật số',
    business_marketing_t3_name: 'Tập đoàn quảng cáo toàn cầu',
    business_technology_t1_name: 'Cửa hàng hỗ trợ CNTT',
    business_technology_t2_name: 'Studio phát triển phần mềm',
    business_technology_t3_name: 'Khuôn viên công nghệ lớn',
    business_engineering_t1_name: 'Xưởng sửa chữa',
    business_engineering_t2_name: 'Công ty xây dựng',
    business_engineering_t3_name: 'Nhà máy sản xuất tiên tiến',
    business_arts_t1_name: 'Phòng trưng bày nghệ thuật',
    business_arts_t2_name: 'Studio thiết kế',
    business_arts_t3_name: 'Nhà xuất bản lớn',
    business_culinary_t1_name: 'Quán ăn',
    business_culinary_t2_name: 'Nhà hàng sang trọng',
    business_culinary_t3_name: 'Khách sạn & Nhà hàng 5 sao',
    business_kinesiology_t1_name: 'Trung tâm Gym & Fitness',
    business_kinesiology_t2_name: 'Bể bơi công cộng',
    business_kinesiology_t3_name: 'Khu liên hợp thể thao chuyên nghiệp',
    business_agriculture_t1_name: 'Nông trại gia đình',
    business_agriculture_t2_name: 'Nông trại thương mại',
    business_agriculture_t3_name: 'Tập đoàn công nghệ nông nghiệp',
    business_logistics_t1_name: 'Kho nhỏ',
    business_logistics_t2_name: 'Trung tâm phân phối',
    business_logistics_t3_name: 'Cảng vận chuyển quốc tế',
     // Log Event Titles
    event_birthday_title: 'Sinh nhật',
    event_new_phase_title: 'Giai đoạn mới',
    event_retirement_title: 'Nghỉ hưu',
    event_school_choice_title: 'Chọn trường',
    event_university_decision_title: 'Quyết định Đại học',
    event_major_choice_title: 'Chọn chuyên ngành',
    event_career_choice_title: 'Chọn nghề',
    event_underqualified_decision_title: 'Quyết định nghề nghiệp',
    event_loan_decision_title: 'Quyết định vay tiền',
    event_promotion_title: 'Thăng chức',
    event_business_assignment_title: 'Phân công kinh doanh',
    event_business_upgrade_title: 'Nâng cấp kinh doanh',
    event_business_purchase_title: 'Mua kinh doanh',
    event_asset_purchase_title: 'Mua tài sản',
    event_marriage_title: 'Kết hôn',
    event_birth_title: 'Chào đời',
    event_death_title: 'Qua đời',
    event_pet_adoption_log_title: 'Nhận nuôi thú cưng',
    event_club_join_title: 'Đã tham gia câu lạc bộ',
    // Game Log Messages
    log_first_generation: '{name} đã ra đời, bắt đầu thế hệ đầu tiên.',
    log_alone_start: '{name} đã tốt nghiệp và bắt đầu một cuộc sống mới với 50.000 đô la.',
    log_mila_start: 'Bạn bắt đầu hành trình của mình với gia đình của Mila.',
    log_birthday: '{name} đã tròn {age} tuổi.',
    log_new_phase: '{name} bây giờ đang trong giai đoạn {phase}.',
    log_retired: '{name} đã nghỉ hưu.',
    log_promoted: '{name} đã được thăng chức lên {title}!',
    log_internship_success: 'Kỳ thực tập của {name} đã thành công! Họ được mời làm việc với vị trí {title}.',
    log_internship_fail: 'Kỳ thực tập của {name} đã kết thúc mà không có lời mời làm việc.',
    log_status_end_unemployed: '{name} đã hoàn thành {status} và hiện đang thất nghiệp.',
    log_passed_away: '{name} đã qua đời ở tuổi {age}.',
    log_business_position_vacant: 'Vị trí của {name} tại {businessName} đã bị bỏ trống.',
    log_enrolled_public_elementary: '{name} đã được ghi danh vào Trường tiểu học công lập.',
    log_enrolled_private_elementary: '{name} đã được ghi danh vào một Trường tiểu học tư thục danh tiếng.',
    log_enrolled_royal_elementary: '{name} đã được nhận vào Học viện Tiểu học Hoàng gia độc quyền.',
    log_enrolled_public_middle: '{name} hiện đang theo học Trường THCS công lập.',
    log_enrolled_private_middle: '{name} hiện đang theo học một Trường THCS tư thục tốt.',
    log_enrolled_royal_middle: '{name} tiếp tục học tại Học viện THCS Hoàng gia.',
    log_enrolled_public_high: '{name} đã bắt đầu học tại Trường THPT công lập địa phương.',
    log_enrolled_private_high: '{name} đã bắt đầu học tại một Trường THPT tư thục được đánh giá cao.',
    log_enrolled_royal_high: '{name} đã bước vào giai đoạn cuối của chương trình học tại Học viện Hoàng gia.',
    log_graduated_enter_workforce: '{name} đã tốt nghiệp và bây giờ sẵn sàng để đi làm.',
    log_vocational_enter_workforce: '{name} đã hoàn thành khóa học nghề và bây giờ sẵn sàng để đi làm.',
    log_enrolled_university: '{name} đã đăng ký vào Đại học để học ngành {major}.',
    log_abandon_university_for_work: '{name} không đủ tiền học bất kỳ chuyên ngành nào và phải đi làm.',
    log_found_job: '{name} đã tìm được việc làm là {title}.',
    log_became_trainee: '{name} đã trở thành Thực tập sinh tại {careerName} để tích lũy kinh nghiệm cần thiết.',
    log_accepted_penalized_job: '{name} đã chấp nhận một vị trí bị phạt với chức danh {title} do thiếu một số yêu cầu.',
    log_accepted_mismatched_job: '{name} đã chấp nhận công việc {title}. Do thiếu chuyên ngành phù hợp, tiến độ thăng tiến sự nghiệp của họ sẽ chậm hơn.',
    log_accepted_severely_underqualified_job: '{name} đã chấp nhận công việc {title}. Do thiếu cả chuyên ngành và chỉ số yêu cầu, tiến độ thăng tiến sự nghiệp của họ sẽ bị phạt rất nặng.',
    log_promoted_from_trainee: 'Sau một thời gian đào tạo, {name} đã được thăng chức lên vị trí {title} chính thức!',
    log_started_internship: '{name} đã bắt đầu một kỳ thực tập.',
    log_enrolled_vocational: '{name} đã đăng ký học nghề.',
    log_left_business_unemployed: '{name} đã rời khỏi vị trí của mình tại {businessName} và hiện đang thất nghiệp.',
    log_quit_job_for_business: '{name} đã nghỉ việc {oldJob} để làm việc tại {businessName}.',
    log_started_at_business: '{name} đã bắt đầu làm việc tại {businessName}.',
    log_business_upgraded: '{businessName} đã được nâng cấp!',
    log_business_upgrade_fail: 'Không đủ tiền để nâng cấp {businessName}.',
    log_business_purchase_fail: 'Không đủ tiền để mua {businessName}.',
    log_business_purchased: 'Gia đình đã mua {businessName}!',
    log_married: '{name1} đã kết hôn với {name2}!',
    log_spouse_joined_family: '{name} đã gia nhập gia đình, làm việc với vị trí {title}.',
    log_had_child: '{parent1} và {parent2} đã có một đứa con tên là {childName}.',
    log_had_twins: '{parent1} và {parent2} đã may mắn sinh đôi: {childName1} và {childName2}.',
    log_had_triplets: '{parent1} và {parent2} đã chào đón một cặp sinh ba: {childName1}, {childName2}, và {childName3}.',
    log_pet_already_owned: '{name} đã cân nhắc nuôi thêm thú cưng, nhưng quyết định một là đủ rồi.',
    log_pet_adopted: '{name} đã nhận nuôi một {petType} tên là {petName}!',
    log_loan_taken: "Gia đình đã vay một khoản {amount}$ với thời hạn trả là {term} năm.",
    log_loan_repaid: "Gia đình đã trả thành công khoản vay {amount}$.",
    log_loan_repayment_due: "Một khoản vay {amount}$ sắp đến hạn trả trong năm nay.",
        log_joined_club: '{name} đã tham gia {clubName}.',
    club_sports: 'Câu lạc bộ Thể thao',
    club_sports_desc: 'Tham gia câu lạc bộ thể thao để cải thiện sức khỏe và kỹ năng thể chất của bạn.',
    club_art: 'Câu lạc bộ Nghệ thuật',
    club_art_desc: 'Giải phóng sự sáng tạo và trí tuệ cảm xúc của bạn trong câu lạc bộ nghệ thuật.',
    club_science: 'Câu lạc bộ Khoa học',
    club_science_desc: 'Khám phá những điều kỳ diệu của khoa học và tăng cường IQ và kỹ năng giải quyết vấn đề của bạn.',
};
