export default {
    // Main Events
    event_highschool_late_for_school_title: 'Đi học muộn',
    event_highschool_late_for_school_desc: 'Bạn đi học muộn vì kẹt xe.',
    choice_highschool_late_for_school_1: 'Xin lỗi giáo viên',
    log_highschool_late_for_school_1: 'Tôi đã xin lỗi và được vào lớp.',
    choice_highschool_late_for_school_2: 'Đổ lỗi cho giao thông',
    log_highschool_late_for_school_2: 'Tôi giải thích là do kẹt xe, nhưng giáo viên vẫn tỏ ra nghi ngờ.',
    choice_highschool_late_for_school_3: 'Lẻn vào lớp',
    log_highschool_late_for_school_3: 'Tôi đã cố gắng lẻn vào mà không bị chú ý.',

    event_highschool_forgot_presentation_book_title: 'Quên sách thuyết trình',
    event_highschool_forgot_presentation_book_desc: 'Bạn quên mang theo sách cần thiết cho bài thuyết trình của mình.',
    choice_highschool_forgot_presentation_book_1: 'Mượn bạn',
    log_highschool_forgot_presentation_book_1: 'Một người bạn đã cho tôi mượn sách, cứu nguy cho tôi.',
    choice_highschool_forgot_presentation_book_2: 'Xin thầy cô cho qua',
    log_highschool_forgot_presentation_book_2: 'Tôi đã xin lỗi thầy cô, và họ đã thông cảm.',
    choice_highschool_forgot_presentation_book_3: 'Giấu nhẹm',
    log_highschool_forgot_presentation_book_3: 'Tôi đã cố gắng thuyết trình mà không ai nhận ra.',

    event_highschool_football_practice_title: 'Tập bóng bầu dục',
    event_highschool_football_practice_desc: 'Đã đến giờ tập bóng bầu dục.',
    choice_highschool_football_practice_1: 'Tập trung luyện tập',
    log_highschool_football_practice_1: 'Tôi đã cống hiến hết mình trong buổi tập.',
    choice_highschool_football_practice_2: 'Lười biếng',
    log_highschool_football_practice_2: 'Tôi đã lơ là trong các bài tập.',
    choice_highschool_football_practice_3: 'Nói chuyện với bạn',
    log_highschool_football_practice_3: 'Tôi đã dành phần lớn thời gian tập luyện để nói chuyện với đồng đội.',

    event_highschool_college_prep_workshop_title: 'Buổi hướng nghiệp đại học',
    event_highschool_college_prep_workshop_desc: 'Trường đang tổ chức một buổi hướng nghiệp để chuẩn bị cho việc nộp đơn vào đại học.',
    choice_highschool_college_prep_workshop_1: 'Tham gia nghiêm túc',
    log_highschool_college_prep_workshop_1: 'Tôi đã tham gia nghiêm túc và học được rất nhiều.',
    choice_highschool_college_prep_workshop_2: 'Ngồi chơi',
    log_highschool_college_prep_workshop_2: 'Tôi đã chán và chỉ nghịch điện thoại.',
    choice_highschool_college_prep_workshop_3: 'Trốn ra ngoài',
    log_highschool_college_prep_workshop_3: 'Tôi đã lẻn ra ngoài khi không ai để ý.',

    event_highschool_sat_act_test_title: 'Bài thi thử SAT/ACT',
    event_highschool_sat_act_test_desc: 'Bạn đang làm một bài thi thử cho kỳ thi tuyển sinh đại học.',
    choice_highschool_sat_act_test_1: 'Làm nghiêm túc',
    log_highschool_sat_act_test_1: 'Tôi đã tập trung và cố gắng hết sức để chuẩn bị cho kỳ thi thật.',
    choice_highschool_sat_act_test_2: 'Nói chuyện trong giờ',
    log_highschool_sat_act_test_2: 'Tôi bị bắt gặp đang thì thầm với một người bạn.',
    choice_highschool_sat_act_test_3: 'Làm qua loa cho xong',
    log_highschool_sat_act_test_3: 'Tôi không coi trọng nó và chỉ muốn làm cho xong.',

    event_highschool_promposal_title: 'Rủ crush đi prom',
    event_highschool_promposal_desc: 'Đã đến lúc rủ crush của bạn đi prom.',
    choice_highschool_promposal_1: 'Chuẩn bị lãng mạn',
    log_highschool_promposal_1: 'Tôi đã lên kế hoạch cho một lời mời prom hoành tráng, lãng mạn.',
    choice_highschool_promposal_2: 'Nói vội vàng',
    log_highschool_promposal_2: 'Tôi chỉ hỏi họ một cách nhanh chóng và vụng về.',
    choice_highschool_promposal_3: 'Nhờ bạn bè phụ',
    log_highschool_promposal_3: 'Bạn bè đã giúp tôi nghĩ ra một ý tưởng hay.',

    event_highschool_prom_cafeteria_title: 'Tìm bạn nhảy prom',
    event_highschool_prom_cafeteria_desc: 'Bạn đang ở trong căng tin, và crush của bạn đang ở gần. Đây là cơ hội tốt để nói về prom.',
    choice_highschool_prom_cafeteria_1: 'Ngồi với bạn thân',
    log_highschool_prom_cafeteria_1: 'Tôi quyết định ngồi với bạn mình thay vào đó.',
    choice_highschool_prom_cafeteria_2: 'Ngồi cạnh crush',
    log_highschool_prom_cafeteria_2: 'Tôi đã lấy hết can đảm và ngồi cạnh họ.',
    choice_highschool_prom_cafeteria_3: 'Ngồi một mình',
    log_highschool_prom_cafeteria_3: 'Tôi quá lo lắng và cuối cùng ngồi một mình.',

    event_highschool_homecoming_game_title: 'Diễu hành & Trận đấu Homecoming',
    event_highschool_homecoming_game_desc: 'Hôm nay là ngày của trận đấu và diễu hành homecoming lớn.',
    choice_highschool_homecoming_game_1: 'Cổ vũ nhiệt tình',
    log_highschool_homecoming_game_1: 'Tôi đã thể hiện tinh thần trường học và cổ vũ hết mình.',
    choice_highschool_homecoming_game_2: 'Bỏ trốn đi chơi',
    log_highschool_homecoming_game_2: 'Trận đấu chán quá, nên tôi đã đi chơi với vài người bạn.',
    choice_highschool_homecoming_game_3: 'Ngồi một góc xem',
    log_highschool_homecoming_game_3: 'Tôi đã xem trận đấu một cách lặng lẽ từ khán đài.',

    event_highschool_class_test_title: 'Kiểm tra trên lớp',
    event_highschool_class_test_desc: 'Bạn có một bài kiểm tra trên lớp.',
    choice_highschool_class_test_1: 'Làm nghiêm túc',
    log_highschool_class_test_1: 'Tôi tập trung làm bài của mình.',
    choice_highschool_class_test_2: 'Nhìn bài bạn',
    log_highschool_class_test_2: 'Tôi đã liếc bài của bạn cho một câu hỏi khó.',
    choice_highschool_class_test_3: 'Viết đại vài dòng',
    log_highschool_class_test_3: 'Tôi không biết câu trả lời, nên chỉ viết bừa.',

    event_highschool_literature_discussion_title: 'Thảo luận nhóm môn văn',
    event_highschool_literature_discussion_desc: 'Nhóm của bạn đang thảo luận về một cuốn sách trong giờ văn.',
    choice_highschool_literature_discussion_1: 'Đưa ý kiến',
    log_highschool_literature_discussion_1: 'Tôi đã tích cực tham gia và chia sẻ phân tích của mình.',
    choice_highschool_literature_discussion_2: 'Ngồi im lắng nghe',
    log_highschool_literature_discussion_2: 'Tôi thích nghe ý kiến của người khác hơn.',
    choice_highschool_literature_discussion_3: 'Tranh luận gay gắt',
    log_highschool_literature_discussion_3: 'Tôi đã tranh luận nảy lửa về chủ đề của cuốn sách.',

    // Triggered Events
    event_highschool_late_slip_title: 'Bị ghi sổ đi muộn',
    event_highschool_late_slip_desc: 'Bạn đã bị ghi tên vì đi học muộn.',
    choice_highschool_late_slip_1: 'Xin lỗi và hứa không tái phạm',
    log_highschool_late_slip_1: 'Tôi đã xin lỗi và hứa sẽ không tái phạm.',
    choice_highschool_late_slip_2: 'Chấp nhận phạt',
    log_highschool_late_slip_2: 'Tôi đã chấp nhận bị phạt.',
    choice_highschool_late_slip_3: 'Cãi lại vì lý do chính đáng',
    log_highschool_late_slip_3: 'Tôi đã cãi rằng kẹt xe là lý do chính đáng.',

    event_highschool_teacher_discovers_hiding_title: 'Thầy cô phát hiện',
    event_highschool_teacher_discovers_hiding_desc: 'Giáo viên phát hiện bạn không có sách và đang cố giấu diếm.',
    choice_highschool_teacher_discovers_hiding_1: 'Xin lỗi',
    log_highschool_teacher_discovers_hiding_1: 'Tôi đã xin lỗi vì đã quên và không thành thật.',
    choice_highschool_teacher_discovers_hiding_2: 'Tìm cớ biện minh',
    log_highschool_teacher_discovers_hiding_2: 'Tôi đã cố gắng tìm một lý do.',
    choice_highschool_teacher_discovers_hiding_3: 'Chấp nhận bị trừ điểm',
    log_highschool_teacher_discovers_hiding_3: 'Tôi chấp nhận điểm của mình sẽ bị hạ.',

    event_highschool_coach_punishment_title: 'Bị huấn luyện viên phạt',
    event_highschool_coach_punishment_desc: 'Huấn luyện viên đã phạt bạn vì lười biếng trong lúc tập.',
    choice_highschool_coach_punishment_1: 'Chạy thêm vòng',
    log_highschool_coach_punishment_1: 'Tôi đã phải chạy thêm vòng phạt.',
    choice_highschool_coach_punishment_2: 'Ngồi nghỉ phạt',
    log_highschool_coach_punishment_2: 'Tôi phải ngồi ngoài trong phần còn lại của buổi tập.',
    choice_highschool_coach_punishment_3: 'Cố gắng tập nghiêm túc',
    log_highschool_coach_punishment_3: 'Tôi bắt đầu tập luyện chăm chỉ hơn để bù đắp.',

    event_highschool_counselor_reprimand_title: 'Bị cố vấn nhắc nhở',
    event_highschool_counselor_reprimand_desc: 'Cố vấn học tập đã nhắc nhở bạn vì không tham gia nghiêm túc.',
    choice_highschool_counselor_reprimand_1: 'Quay lại tham gia',
    log_highschool_counselor_reprimand_1: 'Tôi đã tham gia lại buổi hướng nghiệp và chú ý.',
    choice_highschool_counselor_reprimand_2: 'Giả vờ ghi chép',
    log_highschool_counselor_reprimand_2: 'Tôi giả vờ như đang tham gia.',
    choice_highschool_counselor_reprimand_3: 'Lén tiếp tục lướt điện thoại',
    log_highschool_counselor_reprimand_3: 'Tôi cứ tiếp tục nhìn vào điện thoại của mình.',

    event_highschool_invigilator_warning_test_title: 'Bị giám thị nhắc nhở',
    event_highschool_invigilator_warning_test_desc: 'Giám thị đã cảnh cáo bạn trong giờ thi.',
    choice_highschool_invigilator_warning_test_1: 'Cúi đầu làm tiếp',
    log_highschool_invigilator_warning_test_1: 'Tôi tập trung vào bài thi của mình.',
    choice_highschool_invigilator_warning_test_2: 'Cãi lại “em chỉ hỏi bạn”',
    log_highschool_invigilator_warning_test_2: 'Tôi đã cố gắng tự bào chữa.',
    choice_highschool_invigilator_warning_test_3: 'Im lặng chịu trừ điểm',
    log_highschool_invigilator_warning_test_3: 'Tôi chấp nhận hậu quả.',

    event_highschool_crush_rejects_promposal_title: 'Bị crush từ chối',
    event_highschool_crush_rejects_promposal_desc: 'Crush của bạn đã từ chối lời mời đi prom.',
    choice_highschool_crush_rejects_promposal_1: 'Cười cho qua',
    log_highschool_crush_rejects_promposal_1: 'Tôi đã tỏ ra ngầu và cười cho qua.',
    choice_highschool_crush_rejects_promposal_2: 'Ngại ngùng tránh mặt',
    log_highschool_crush_rejects_promposal_2: 'Quá xấu hổ để đối mặt với họ.',
    choice_highschool_crush_rejects_promposal_3: 'Vẫn rủ đi chơi nhóm',
    log_highschool_crush_rejects_promposal_3: 'Tôi đề nghị chúng ta có thể đi cùng nhau như những người bạn.',

    event_highschool_teased_by_friends_crush_title: 'Bị bạn bè trêu',
    event_highschool_teased_by_friends_crush_desc: 'Bạn bè đang trêu chọc bạn vì ngồi cạnh crush.',
    choice_highschool_teased_by_friends_crush_1: 'Cười trừ',
    log_highschool_teased_by_friends_crush_1: 'Tôi chỉ cười cùng họ.',
    choice_highschool_teased_by_friends_crush_2: 'Chuyển chỗ',
    log_highschool_teased_by_friends_crush_2: 'Tôi đã bối rối và chuyển đi.',
    choice_highschool_teased_by_friends_crush_3: 'Đùa lại',
    log_highschool_teased_by_friends_crush_3: 'Tôi đã trêu lại họ.',

    event_highschool_caught_skipping_title: 'Bị bắt gặp khi bỏ trốn',
    event_highschool_caught_skipping_desc: 'Một giám thị đã bắt gặp bạn trốn xem trận đấu.',
    choice_highschool_caught_skipping_1: 'Biện minh “em đi vệ sinh”',
    log_highschool_caught_skipping_1: 'Tôi đã bịa ra một lý do.',
    choice_highschool_caught_skipping_2: 'Chấp nhận bị ghi tên',
    log_highschool_caught_skipping_2: 'Tôi chấp nhận bị phạt.',
    choice_highschool_caught_skipping_3: 'Lén quay lại lớp',
    log_highschool_caught_skipping_3: 'Tôi đã cố gắng lẻn về để tránh gặp thêm rắc rối.',

    event_highschool_teacher_reprimand_cheating_title: 'Bị nhắc khi nhìn bài bạn',
    event_highschool_teacher_reprimand_cheating_desc: 'Giáo viên đã nhắc nhở bạn vì nhìn bài của bạn.',
    choice_highschool_teacher_reprimand_cheating_1: 'Xin lỗi',
    log_highschool_teacher_reprimand_cheating_1: 'Tôi đã thừa nhận lỗi và xin lỗi.',
    choice_highschool_teacher_reprimand_cheating_2: 'Giải thích “em chỉ nhìn quanh”',
    log_highschool_teacher_reprimand_cheating_2: 'Tôi đã cố gắng viện cớ.',
    choice_highschool_teacher_reprimand_cheating_3: 'Chấp nhận bị trừ điểm',
    log_highschool_teacher_reprimand_cheating_3: 'Tôi chấp nhận bị phạt.',

    event_highschool_argument_with_friend_title: 'Cãi nhau với bạn',
    event_highschool_argument_with_friend_desc: 'Bạn đã cãi nhau với bạn mình trong lúc thảo luận.',
    choice_highschool_argument_with_friend_1: 'Xin lỗi',
    log_highschool_argument_with_friend_1: 'Tôi đã xin lỗi để mọi chuyện êm xuôi.',
    choice_highschool_argument_with_friend_2: 'Tiếp tục tranh luận',
    log_highschool_argument_with_friend_2: 'Chúng tôi tiếp tục tranh luận về quan điểm của mình.',
    choice_highschool_argument_with_friend_3: 'Rút lui im lặng',
    log_highschool_argument_with_friend_3: 'Tôi quyết định bỏ qua chủ đề này.',

    // Independent Events
    event_highschool_club_activity_title: 'Hoạt động câu lạc bộ',
    event_highschool_club_activity_desc: 'Bạn đang ở một buổi họp câu lạc bộ.',
    choice_highschool_club_activity_1: 'Tham gia sôi nổi',
    log_highschool_club_activity_1: 'Tôi đã rất tích cực trong các hoạt động của câu lạc bộ.',
    choice_highschool_club_activity_2: 'Chỉ ngồi nghe',
    log_highschool_club_activity_2: 'Lần này tôi chỉ muốn ngồi nghe.',
    choice_highschool_club_activity_3: 'Thử một buổi rồi nghỉ',
    log_highschool_club_activity_3: 'Câu lạc bộ này không dành cho tôi.',

    event_highschool_playing_sports_title: 'Chơi thể thao ở sân trường',
    event_highschool_playing_sports_desc: 'Bạn đang chơi thể thao ở sân trường.',
    choice_highschool_playing_sports_1: 'Tham gia đá bóng',
    log_highschool_playing_sports_1: 'Tôi đã tham gia một trận đá bóng.',
    choice_highschool_playing_sports_2: 'Làm cổ động viên',
    log_highschool_playing_sports_2: 'Tôi đã cổ vũ cho bạn bè.',
    choice_highschool_playing_sports_3: 'Ngồi ăn quà vặt',
    log_highschool_playing_sports_3: 'Tôi chỉ thư giãn và ăn vặt.',

    event_highschool_lunchtime_title: 'Giờ ăn trưa',
    event_highschool_lunchtime_desc: 'Đã đến giờ ăn trưa.',
    choice_highschool_lunchtime_1: 'Ăn với nhóm bạn thân',
    log_highschool_lunchtime_1: 'Tôi đã ăn trưa với những người bạn thân nhất.',
    choice_highschool_lunchtime_2: 'Ngồi cùng lớp khác',
    log_highschool_lunchtime_2: 'Tôi ngồi với vài người bạn ở lớp khác.',
    choice_highschool_lunchtime_3: 'Ăn nhanh rồi đi',
    log_highschool_lunchtime_3: 'Tôi có việc khác phải làm, nên đã ăn nhanh.',

    event_highschool_surprise_oral_exam_title: 'Kiểm tra miệng bất ngờ',
    event_highschool_surprise_oral_exam_desc: 'Giáo viên bất ngờ kiểm tra miệng.',
    choice_highschool_surprise_oral_exam_1: 'Trả lời được',
    log_highschool_surprise_oral_exam_1: 'Tôi đã có thể trả lời câu hỏi.',
    choice_highschool_surprise_oral_exam_2: 'Ú ớ',
    log_highschool_surprise_oral_exam_2: 'Tôi bị bất ngờ và không trả lời tốt.',
    choice_highschool_surprise_oral_exam_3: 'Cười xin thầy cô bỏ qua',
    log_highschool_surprise_oral_exam_3: 'Tôi đã cố gắng dùng sự quyến rũ để thoát khỏi nó.',

    event_highschool_library_study_group_title: 'Buổi học nhóm ở thư viện',
    event_highschool_library_study_group_desc: 'Bạn đang trong một nhóm học ở thư viện.',
    choice_highschool_library_study_group_1: 'Ôn tập chăm chỉ',
    log_highschool_library_study_group_1: 'Chúng tôi đã rất hiệu quả.',
    choice_highschool_library_study_group_2: 'Vừa học vừa nói chuyện',
    log_highschool_library_study_group_2: 'Chúng tôi học một chút, nhưng chủ yếu là tán gẫu.',
    choice_highschool_library_study_group_3: 'Ngồi nghe là chính',
    log_highschool_library_study_group_3: 'Tôi để người khác nói nhiều hơn.',

    event_highschool_teacher_praise_title: 'Thầy cô khen trước lớp',
    event_highschool_teacher_praise_desc: 'Giáo viên đã khen bạn trước cả lớp.',
    choice_highschool_teacher_praise_1: 'Ngại ngùng',
    log_highschool_teacher_praise_1: 'Tôi xấu hổ vì lời khen.',
    choice_highschool_teacher_praise_2: 'Tự hào',
    log_highschool_teacher_praise_2: 'Thật tuyệt khi được công nhận.',
    choice_highschool_teacher_praise_3: 'Giả vờ thờ ơ',
    log_highschool_teacher_praise_3: 'Tôi đã hành động như thể đó không phải là chuyện lớn.',

    event_highschool_teacher_criticism_title: 'Thầy cô phê bình',
    event_highschool_teacher_criticism_desc: 'Giáo viên đã phê bình bạn.',
    choice_highschool_teacher_criticism_1: 'Im lặng nghe',
    log_highschool_teacher_criticism_1: 'Tôi đã chấp nhận lời phê bình.',
    choice_highschool_teacher_criticism_2: 'Cãi lại',
    log_highschool_teacher_criticism_2: 'Tôi đã cố gắng tự bào chữa.',
    choice_highschool_teacher_criticism_3: 'Suy nghĩ buồn bã',
    log_highschool_teacher_criticism_3: 'Lời phê bình làm tôi buồn.',

    event_highschool_class_trip_title: 'Dã ngoại cùng lớp',
    event_highschool_class_trip_desc: 'Bạn đang đi dã ngoại cùng lớp.',
    choice_highschool_class_trip_1: 'Chụp ảnh kỷ niệm',
    log_highschool_class_trip_1: 'Tôi đã chụp rất nhiều ảnh để ghi nhớ chuyến đi.',
    choice_highschool_class_trip_2: 'Tham gia trò chơi',
    log_highschool_class_trip_2: 'Tôi đã tham gia tất cả các hoạt động vui vẻ.',
    choice_highschool_class_trip_3: 'Ngồi nói chuyện riêng',
    log_highschool_class_trip_3: 'Tôi đã dành thời gian trò chuyện với một người bạn thân.',

    event_highschool_class_debate_title: 'Tranh luận trên lớp',
    event_highschool_class_debate_desc: 'Bạn đang trong một cuộc tranh luận trên lớp.',
    choice_highschool_class_debate_1: 'Đưa ý kiến mạnh mẽ',
    log_highschool_class_debate_1: 'Tôi đã bảo vệ quan điểm của mình một cách mạnh mẽ.',
    choice_highschool_class_debate_2: 'Lắng nghe bạn',
    log_highschool_class_debate_2: 'Tôi đã lắng nghe những gì người khác nói.',
    choice_highschool_class_debate_3: 'Nói xen vài câu',
    log_highschool_class_debate_3: 'Tôi đã thêm một vài nhận xét vào cuộc thảo luận.',

    event_highschool_class_birthday_party_title: 'Lớp tổ chức sinh nhật',
    event_highschool_class_birthday_party_desc: 'Lớp của bạn đang tổ chức sinh nhật.',
    choice_highschool_class_birthday_party_1: 'Hát chúc mừng',
    log_highschool_class_birthday_party_1: 'Tôi đã hát cùng mọi người.',
    choice_highschool_class_birthday_party_2: 'Ăn bánh',
    log_highschool_class_birthday_party_2: 'Bánh kem là phần tuyệt nhất.',
    choice_highschool_class_birthday_party_3: 'Đùa giỡn',
    log_highschool_class_birthday_party_3: 'Tôi là người khuấy động bữa tiệc.',

    event_highschool_sports_day_title: 'Ngày hội thể thao',
    event_highschool_sports_day_desc: 'Hôm nay là ngày hội thể thao của trường.',
    choice_highschool_sports_day_1: 'Thi chạy',
    log_highschool_sports_day_1: 'Tôi đã tham gia một cuộc thi chạy.',
    choice_highschool_sports_day_2: 'Nhảy xa',
    log_highschool_sports_day_2: 'Tôi đã cố gắng hết sức trong môn nhảy xa.',
    choice_highschool_sports_day_3: 'Làm cổ động viên',
    log_highschool_sports_day_3: 'Tôi đã cổ vũ cho bạn bè.',

    event_highschool_chemistry_test_title: 'Bài kiểm tra hóa học',
    event_highschool_chemistry_test_desc: 'Bạn có một bài kiểm tra hóa học.',
    choice_highschool_chemistry_test_1: 'Làm đúng quy trình',
    log_highschool_chemistry_test_1: 'Tôi đã cẩn thận làm theo các bước.',
    choice_highschool_chemistry_test_2: 'Thử sáng tạo',
    log_highschool_chemistry_test_2: 'Tôi đã thử nghiệm một chút.',
    choice_highschool_chemistry_test_3: 'Hỏi bạn bên cạnh',
    log_highschool_chemistry_test_3: 'Tôi cần một chút giúp đỡ từ bạn cùng lớp.',

    event_highschool_meeting_teacher_outside_title: 'Gặp thầy cô ngoài trường',
    event_highschool_meeting_teacher_outside_desc: 'Bạn gặp một giáo viên ở ngoài trường.',
    choice_highschool_meeting_teacher_outside_1: 'Chào hỏi',
    log_highschool_meeting_teacher_outside_1: 'Tôi đã chào giáo viên của mình.',
    choice_highschool_meeting_teacher_outside_2: 'Cười gượng',
    log_highschool_meeting_teacher_outside_2: 'Hơi khó xử một chút.',
    choice_highschool_meeting_teacher_outside_3: 'Giả vờ không thấy',
    log_highschool_meeting_teacher_outside_3: 'Tôi đã tránh ánh mắt.',

    event_highschool_international_visitor_title: 'Có khách quốc tế tới lớp',
    event_highschool_international_visitor_desc: 'Có một vị khách quốc tế trong lớp của bạn.',
    choice_highschool_international_visitor_1: 'Nói chuyện tiếng Anh',
    log_highschool_international_visitor_1: 'Tôi đã thực hành tiếng Anh của mình với vị khách.',
    choice_highschool_international_visitor_2: 'Cười chào',
    log_highschool_international_visitor_2: 'Tôi đã chào đón họ một cách thân thiện.',
    choice_highschool_international_visitor_3: 'Ngồi im',
    log_highschool_international_visitor_3: 'Tôi quá nhút nhát để nói bất cứ điều gì.',

    event_highschool_parent_teacher_meeting_title: 'Buổi họp phụ huynh',
    event_highschool_parent_teacher_meeting_desc: 'Hôm nay là ngày họp phụ huynh.',
    choice_highschool_parent_teacher_meeting_1: 'Ngồi im lắng nghe',
    log_highschool_parent_teacher_meeting_1: 'Tôi đã lắng nghe những gì giáo viên nói.',
    choice_highschool_parent_teacher_meeting_2: 'Hồi hộp',
    log_highschool_parent_teacher_meeting_2: 'Tôi lo lắng về những gì giáo viên sẽ nói.',
    choice_highschool_parent_teacher_meeting_3: 'Thì thầm với bạn',
    log_highschool_parent_teacher_meeting_3: 'Bạn tôi và tôi đã thì thầm trong suốt cuộc họp.',

    event_highschool_museum_trip_title: 'Dã ngoại bảo tàng',
    event_highschool_museum_trip_desc: 'Bạn đang đi dã ngoại ở một bảo tàng.',
    choice_highschool_museum_trip_1: 'Chăm chú nghe',
    log_highschool_museum_trip_1: 'Tôi thấy các hiện vật rất thú vị.',
    choice_highschool_museum_trip_2: 'Chỉ nhìn quanh',
    log_highschool_museum_trip_2: 'Tôi chủ yếu chỉ đi lang thang.',
    choice_highschool_museum_trip_3: 'Đùa giỡn nhỏ',
    log_highschool_museum_trip_3: 'Tôi đã đùa giỡn với bạn bè.',

    event_highschool_prom_prep_title: 'Chuẩn bị prom',
    event_highschool_prom_prep_desc: 'Prom sắp đến và bạn cần chuẩn bị.',
    choice_highschool_prom_prep_1: 'Mua quần áo',
    log_highschool_prom_prep_1: 'Tôi đã đi mua sắm để tìm bộ trang phục hoàn hảo.',
    choice_highschool_prom_prep_2: 'Rủ nhóm bạn cùng đi',
    log_highschool_prom_prep_2: 'Tôi quyết định đi prom cùng bạn bè.',
    choice_highschool_prom_prep_3: 'Ngồi nhà xem phim',
    log_highschool_prom_prep_3: 'Prom không phải là sở thích của tôi.',

    event_highschool_talent_show_title: 'Lớp có thi văn nghệ',
    event_highschool_talent_show_desc: 'Lớp của bạn có một buổi thi văn nghệ.',
    choice_highschool_talent_show_1: 'Tham gia hát múa',
    log_highschool_talent_show_1: 'Tôi quyết định biểu diễn trong chương trình.',
    choice_highschool_talent_show_2: 'Làm hậu cần',
    log_highschool_talent_show_2: 'Tôi đã giúp đỡ công tác hậu cần.',
    choice_highschool_talent_show_3: 'Ngồi xem',
    log_highschool_talent_show_3: 'Tôi thích xem các bạn cùng lớp biểu diễn.',

    event_highschool_exam_results_title: 'Nhận kết quả thi',
    event_highschool_exam_results_desc: 'Bạn đã nhận được kết quả thi của mình.',
    choice_highschool_exam_results_1: 'Vui mừng khoe',
    log_highschool_exam_results_1: 'Tôi tự hào về kết quả của mình.',
    choice_highschool_exam_results_2: 'Im lặng giữ',
    log_highschool_exam_results_2: 'Tôi giữ kết quả cho riêng mình.',
    choice_highschool_exam_results_3: 'Buồn bã',
    log_highschool_exam_results_3: 'Tôi thất vọng với điểm số của mình.',

    event_highschool_sharing_food_title: 'Chia sẻ đồ ăn',
    event_highschool_sharing_food_desc: 'Bạn đang chia sẻ đồ ăn với bạn bè.',
    choice_highschool_sharing_food_1: 'Cho bạn một phần',
    log_highschool_sharing_food_1: 'Tôi đã chia sẻ đồ ăn nhẹ của mình với một người bạn.',
    choice_highschool_sharing_food_2: 'Đổi món ăn',
    log_highschool_sharing_food_2: 'Chúng tôi đã trao đổi một số món trong bữa trưa.',
    choice_highschool_sharing_food_3: 'Giữ phần mình',
    log_highschool_sharing_food_3: 'Hôm nay tôi đói quá không chia sẻ được.',
};
