
export default {
    event_flu_title: 'Bị Cảm Cúm',
    event_flu_desc: 'Bạn bị cúm nặng, cảm thấy yếu và đau nhức.',
    choice_flu_1: 'Đi khám và uống thuốc.',
    log_flu_1: 'Thuốc giúp tôi hồi phục nhanh chóng.',
    choice_flu_2: 'Nghỉ ngơi ở nhà và uống nhiều nước.',
    log_flu_2: 'Tôi quyết định tự chữa ở nhà.',
    event_sickness_worsens_title: 'Bệnh Nặng Hơn',
    event_sickness_worsens_desc: 'Tình trạng của bạn đã trở nên tồi tệ hơn. Bạn cảm thấy yếu đi nhiều.',
    choice_sickness_worsens_1: 'Đến bệnh viện ngay lập tức.',
    log_sickness_worsens_1: 'Tôi đã được điều trị đúng cách tại bệnh viện và bắt đầu cảm thấy tốt hơn.',
    choice_sickness_worsens_2: 'Tiếp tục nghỉ ngơi ở nhà, hy vọng nó sẽ qua.',
    log_sickness_worsens_2: 'Tôi hy vọng nó sẽ tự khỏi, nhưng không.',
    event_chronic_illness_title: 'Bệnh mãn tính',
    event_chronic_illness_desc: 'Bác sĩ chẩn đoán bạn mắc một căn bệnh mãn tính.',
    choice_chronic_illness_1: 'Tuân thủ điều trị và sống lạc quan.',
    log_chronic_illness_1: 'Tôi học cách sống chung với bệnh và không để nó ảnh hưởng đến cuộc sống.',
    choice_chronic_illness_2: 'Cảm thấy tuyệt vọng và bỏ bê sức khỏe.',
    log_chronic_illness_2: 'Căn bệnh này đã lấy đi niềm vui sống của tôi.',
    event_traffic_accident_title: 'Tai nạn giao thông',
    event_traffic_accident_desc: 'Bạn vừa dính vào một vụ tai nạn giao thông nhỏ.',
    choice_traffic_accident_1: 'Giải quyết ôn hòa và bồi thường.',
    log_traffic_accident_1: 'May mắn là không ai bị thương nặng.',
    choice_traffic_accident_2: 'Cãi vã và đổ lỗi cho người khác.',
    log_traffic_accident_2: 'Cuộc cãi vã không giải quyết được gì và chỉ làm mọi thứ tồi tệ hơn.',
    event_sued_title: 'Bị kiện',
    event_sued_desc: 'Bạn nhận được một lá thư triệu tập từ tòa án.',
    choice_sued_1: 'Thuê luật sư và giải quyết.',
    log_sued_1: 'Vụ kiện đã được giải quyết ổn thỏa.',
    choice_sued_2: 'Tự mình bào chữa.',
    log_sued_2: 'Tôi đã thua kiện và phải bồi thường một khoản lớn.',
    event_lottery_win_title: 'Trúng số!',
    event_lottery_win_desc: 'Bạn đã trúng một giải xổ số lớn!',
    choice_lottery_win_1: 'Đầu tư một cách khôn ngoan.',
    log_lottery_win_1: 'Số tiền này sẽ đảm bảo tương lai cho gia đình tôi.',
    choice_lottery_win_2: 'Tiêu xài và tận hưởng.',
    log_lottery_win_2: 'Tiền đến rồi lại đi, quan trọng là phải vui!',
    event_friends_exploit_title: 'Bạn bè lợi dụng',
    event_friends_exploit_desc: 'Sau khi bạn trúng số, nhiều người bạn cũ bỗng nhiên xuất hiện và hỏi vay tiền.',
    choice_friends_exploit_1: 'Giúp đỡ họ.',
    log_friends_exploit_1: 'Tôi đã cho họ vay một khoản.',
    choice_friends_exploit_2: 'Từ chối một cách khéo léo.',
    log_friends_exploit_2: 'Tôi nhận ra ai là bạn thật sự của mình.',
    event_lose_friend_title: 'Mất một người bạn',
    event_lose_friend_desc: 'Một người bạn đã không còn nói chuyện với bạn nữa.',
    choice_lose_friend_1: 'Cảm thấy buồn.',
    log_lose_friend_1: 'Tôi đã mất một người bạn tốt.',
    choice_lose_friend_2: 'Không quan tâm.',
    log_lose_friend_2: 'Nếu họ không muốn làm bạn, tôi cũng không cần.',
    event_lost_wallet_title: 'Mất ví',
    event_lost_wallet_desc: 'Bạn nhận ra mình đã làm mất ví.',
    choice_lost_wallet_1: 'Báo cảnh sát và làm lại giấy tờ.',
    log_lost_wallet_1: 'Thật là một ngày xui xẻo.',
    choice_lost_wallet_2: 'Hy vọng ai đó sẽ trả lại.',
    log_lost_wallet_2: 'Ví của tôi đã không bao giờ được tìm thấy.',
    event_buy_house_title: 'Mua nhà',
    event_buy_house_desc: 'Gia đình bạn đang cân nhắc việc mua một ngôi nhà mới.',
    choice_buy_house_1: 'Mua một ngôi nhà lớn.',
    log_buy_house_1: 'Chúng tôi đã mua một ngôi nhà mơ ước.',
    choice_buy_house_2: 'Mua một ngôi nhà nhỏ.',
    log_buy_house_2: 'Một ngôi nhà ấm cúng là đủ cho chúng tôi.',
    choice_buy_house_3: 'Tiếp tục đi thuê.',
    log_buy_house_3: 'Bây giờ chưa phải là lúc thích hợp để mua nhà.',
    event_buy_car_title: 'Mua xe',
    event_buy_car_desc: 'Bạn đang nghĩ đến việc mua một chiếc xe hơi.',
    choice_buy_car_1: 'Mua một chiếc xe sang trọng.',
    log_buy_car_1: 'Chiếc xe mới thật tuyệt vời.',
    choice_buy_car_2: 'Mua một chiếc xe tiêu chuẩn.',
    log_buy_car_2: 'Chiếc xe phục vụ tốt cho nhu cầu của gia đình.',
    choice_buy_car_3: 'Sử dụng phương tiện công cộng.',
    log_buy_car_3: 'Tôi không thực sự cần một chiếc xe hơi.',
    event_burglary_title: 'Trộm vào nhà',
    event_burglary_desc: 'Nhà của bạn đã bị trộm đột nhập.',
    choice_burglary_1: 'Báo cảnh sát và tăng cường an ninh.',
    log_burglary_1: 'Chúng tôi đã lắp đặt hệ thống báo động mới.',
    choice_burglary_2: 'Đối mặt với tên trộm.',
    log_burglary_2: 'Đó là một hành động dại dột, tôi đã bị thương.',
    event_online_scam_title: 'Lừa đảo trực tuyến',
    event_online_scam_desc: 'Bạn nhận được một email có vẻ đáng ngờ nhưng hứa hẹn một khoản lợi nhuận lớn.',
    choice_online_scam_1: 'Bị lừa.',
    log_online_scam_1: 'Tôi đã mất một khoản tiền lớn vì quá tin người.',
    choice_online_scam_2: 'Nhận ra đó là lừa đảo.',
    log_online_scam_2: 'May mắn là tôi đã đủ tỉnh táo để nhận ra.',
    event_charity_donation_title: 'Quyên góp từ thiện',
    event_charity_donation_desc: 'Một tổ chức từ thiện đang kêu gọi quyên góp.',
    choice_charity_donation_1: 'Quyên góp một khoản lớn.',
    log_charity_donation_1: 'Tôi hạnh phúc khi có thể giúp đỡ người khác.',
    choice_charity_donation_2: 'Quyên góp một khoản nhỏ.',
    log_charity_donation_2: 'Của ít lòng nhiều.',
    choice_charity_donation_3: 'Không quyên góp.',
    log_charity_donation_3: 'Tôi cần phải lo cho gia đình mình trước.',
    event_job_loss_social_crisis_title: 'Mất việc do khủng hoảng',
    event_job_loss_social_crisis_desc: 'Do khủng hoảng kinh tế, công ty của bạn phải cắt giảm nhân sự và bạn nằm trong số đó.',
    choice_job_loss_social_crisis_1: 'Chấp nhận và tìm cơ hội mới.',
    log_job_loss_social_crisis_1: 'Đây là một thử thách, nhưng tôi sẽ vượt qua.',
    choice_job_loss_social_crisis_2: 'Cảm thấy tuyệt vọng.',
    log_job_loss_social_crisis_2: 'Tôi không biết phải làm gì bây giờ.',
    event_natural_disaster_title: 'Thiên tai',
    event_natural_disaster_desc: 'Một trận thiên tai đã xảy ra trong khu vực của bạn.',
    choice_natural_disaster_1: 'Gia đình bạn an toàn.',
    log_natural_disaster_1: 'Thật may mắn vì mọi người đều an toàn.',
    choice_natural_disaster_2: 'Nhà của bạn bị hư hại.',
    log_natural_disaster_2: 'Chúng tôi sẽ phải sửa chữa lại nhà cửa.',
    event_street_assault_title: 'Bị tấn công trên đường',
    event_street_assault_desc: 'Bạn bị một kẻ lạ mặt tấn công trên đường.',
    choice_street_assault_1: 'Chống cự và bỏ chạy.',
    log_street_assault_1: 'May mắn là tôi đã thoát được.',
    choice_street_assault_2: 'Bị cướp và bị thương.',
    log_street_assault_2: 'Đó là một trải nghiệm kinh hoàng.',
    log_asset_lost_robbery: '{name} đã bị cướp và mất một món đồ có giá trị: {assetName}.',
    event_getting_lost_title: 'Bị lạc đường',
    event_getting_lost_desc: 'Bạn bị lạc ở một nơi xa lạ.',
    choice_getting_lost_1: 'Tìm được đường về nhà.',
    log_getting_lost_1: 'Cuối cùng tôi cũng tìm được đường về.',
    choice_getting_lost_2: 'Gặp phải nguy hiểm.',
    log_getting_lost_2: 'Tôi đã gặp rắc rối khi bị lạc.',
    event_unpaid_debt_title: 'Nợ chưa trả',
    event_unpaid_debt_desc: 'Một người bạn cũ đòi một khoản nợ mà bạn đã quên.',
    choice_unpaid_debt_1: 'Trả lại tiền.',
    log_unpaid_debt_1: 'Tôi đã trả lại đầy đủ số tiền đã vay.',
    choice_unpaid_debt_2: 'Trốn tránh.',
    log_unpaid_debt_2: 'Tôi không có tiền để trả lúc này.',
    event_tax_evasion_discovered_title: 'Bị phát hiện trốn thuế',
    event_tax_evasion_discovered_desc: 'Cơ quan thuế đã phát hiện ra sai sót trong hồ sơ của bạn.',
    choice_tax_evasion_discovered_1: 'Nộp phạt và tuân thủ.',
    log_tax_evasion_discovered_1: 'Tôi đã phải trả một khoản tiền phạt lớn.',
    choice_tax_evasion_discovered_2: 'Cố gắng chối cãi.',
    log_tax_evasion_discovered_2: 'Việc này chỉ làm mọi thứ tồi tệ hơn.',
    event_investment_opportunity_title: 'Cơ hội đầu tư',
    event_investment_opportunity_desc: 'Bạn có một cơ hội đầu tư có vẻ hứa hẹn.',
    choice_investment_opportunity_1: 'Đầu tư một khoản lớn.',
    log_investment_opportunity_1: 'Rủi ro cao, lợi nhuận cao.',
    choice_investment_opportunity_2: 'Đầu tư một khoản nhỏ.',
    log_investment_opportunity_2: 'Thử một chút cho biết.',
    choice_investment_opportunity_3: 'Bỏ qua.',
    log_investment_opportunity_3: 'Tôi không muốn mạo hiểm.',
    event_investment_failure_title: 'Đầu tư thất bại',
    event_investment_failure_desc: 'Khoản đầu tư của bạn đã thất bại.',
    choice_investment_failure_1: 'Mất hết tiền.',
    log_investment_failure_1: 'Đó là một bài học đắt giá.',
    choice_investment_failure_2: 'May mắn là chỉ mất một phần.',
    log_investment_failure_2: 'Có lẽ tôi không nên đầu tư nữa.',
    event_small_lottery_title: 'Trúng số nhỏ',
    event_small_lottery_desc: 'Bạn trúng một giải xổ số nhỏ.',
    choice_small_lottery_1: 'Một khoản tiền nhỏ cũng vui.',
    log_small_lottery_1: 'Tôi sẽ dùng số tiền này để mua một bữa ăn ngon.',
    choice_small_lottery_2: 'Mua thêm vé số.',
    log_small_lottery_2: 'Tôi đã dùng hết số tiền trúng thưởng để mua thêm vé số và không trúng gì cả.',
    event_get_a_pet_title: 'Nuôi thú cưng',
    event_get_a_pet_desc: 'Bạn đang cân nhắc việc nuôi một con thú cưng.',
    choice_get_a_pet_1: 'Mang lại niềm vui.',
    log_get_a_pet_1: 'Thú cưng đã trở thành một thành viên không thể thiếu trong gia đình.',
    choice_get_a_pet_2: 'Gây ra nhiều phiền toái.',
    log_get_a_pet_2: 'Nuôi thú cưng tốn nhiều công sức hơn tôi nghĩ.',
    event_loan_shark_title: 'Vay nặng lãi',
    event_loan_shark_desc: 'Do thiếu tiền, bạn đã nghĩ đến việc vay nặng lãi.',
    choice_loan_shark_1: 'Không, quá nguy hiểm.',
    log_loan_shark_1: 'Tôi sẽ tìm một giải pháp khác.',
    choice_loan_shark_2: 'Vay một khoản nhỏ.',
    log_loan_shark_2: 'Tôi hy vọng có thể trả lại sớm.',
    event_loan_shark_enforcers_title: 'Bị đòi nợ',
    event_loan_shark_enforcers_desc: 'Bọn cho vay nặng lãi đến đòi nợ.',
    choice_loan_shark_enforcers_1: 'Trả tiền.',
    log_loan_shark_enforcers_1: 'Tôi đã phải trả một khoản tiền lớn hơn nhiều so với số tiền đã vay.',
    choice_loan_shark_enforcers_2: 'Bị đánh đập.',
    log_loan_shark_enforcers_2: 'Tôi đã học được một bài học đau đớn.',
    event_relative_is_sick_title: 'Người thân bị ốm',
    event_relative_is_sick_desc: 'Một người thân của bạn bị ốm nặng.',
    choice_relative_is_sick_1: 'Giúp đỡ chi phí y tế.',
    log_relative_is_sick_1: 'Gia đình là quan trọng nhất.',
    choice_relative_is_sick_2: 'Chỉ có thể động viên tinh thần.',
    log_relative_is_sick_2: 'Tôi ước mình có thể làm được nhiều hơn.',
    event_self_development_seminar_title: 'Hội thảo phát triển bản thân',
    event_self_development_seminar_desc: 'Bạn được mời tham gia một hội thảo phát triển bản thân.',
    choice_self_development_seminar_1: 'Tham gia và học hỏi.',
    log_self_development_seminar_1: 'Tôi đã học được nhiều điều bổ ích.',
    choice_self_development_seminar_2: 'Từ chối.',
    log_self_development_seminar_2: 'Tôi không tin vào những thứ này.',
    event_minor_accident_title: 'Tai nạn nhỏ',
    event_minor_accident_desc: 'Bạn bị một tai nạn nhỏ trong sinh hoạt hàng ngày.',
    choice_minor_accident_1: 'Đi khám và điều trị.',
    log_minor_accident_1: 'Vết thương không nghiêm trọng lắm.',
    choice_minor_accident_2: 'Tự chữa ở nhà.',
    log_minor_accident_2: 'Vết thương có vẻ nặng hơn tôi nghĩ.',
    event_pyramid_scheme_title: 'Đa cấp',
    event_pyramid_scheme_desc: 'Một người bạn giới thiệu cho bạn một mô hình kinh doanh đa cấp.',
    choice_pyramid_scheme_1: 'Tham gia.',
    log_pyramid_scheme_1: 'Tôi đã mất hết tiền.',
    choice_pyramid_scheme_2: 'Từ chối.',
    log_pyramid_scheme_2: 'Tôi không tin vào những lời hứa hẹn đó.',
    event_relative_death_title: 'Người thân qua đời',
    event_relative_death_desc: 'Bạn nhận được tin buồn rằng một người họ hàng xa (không có trong cây phả hệ) đã qua đời.',
    choice_relative_death_1: 'Tổ chức tang lễ.',
    log_relative_death_1: 'Đó là một sự mất mát lớn.',
    choice_relative_death_2: 'Cảm thấy suy sụp.',
    log_relative_death_2: 'Tôi không thể chấp nhận được sự thật này.',
    event_large_gift_title: 'Món quà lớn',
    event_large_gift_desc: 'Bạn nhận được một món quà lớn từ một người thân.',
    choice_large_gift_1: 'Cảm thấy biết ơn.',
    log_large_gift_1: 'Món quà này rất có ý nghĩa với tôi.',
    choice_large_gift_2: 'Cảm thấy ngại ngùng.',
    log_large_gift_2: 'Tôi không biết phải làm gì để đáp lại.',
    event_stranger_asks_for_help_title: 'Người lạ nhờ giúp đỡ',
    event_stranger_asks_for_help_desc: 'Một người lạ mặt nhờ bạn giúp đỡ.',
    choice_stranger_asks_for_help_1: 'Giúp đỡ họ.',
    log_stranger_asks_for_help_1: 'Làm việc tốt khiến tôi cảm thấy vui.',
    choice_stranger_asks_for_help_2: 'Từ chối.',
    log_stranger_asks_for_help_2: 'Tôi không muốn gặp rắc rối.',
    event_social_movement_title: 'Phong trào xã hội',
    event_social_movement_desc: 'Một phong trào xã hội đang phát triển mạnh mẽ trong thành phố. Nhiều người đang xuống đường biểu tình đòi thay đổi.',
    choice_social_movement_1: 'Tham gia phong trào và đấu tranh cho lẽ phải.',
    log_social_movement_1: 'Tôi cảm thấy được tiếp thêm sức mạnh khi tham gia phong trào xã hội.',
    choice_social_movement_2: 'Tránh xa nó ra. Quá rủi ro.',
    log_social_movement_2: 'Tôi quyết định tốt nhất là nên tránh xa các cuộc biểu tình.',
    event_homeless_person_title: 'Người vô gia cư',
    event_homeless_person_desc: 'Bạn gặp một người vô gia cư trên đường.',
    choice_homeless_person_1: 'Cho họ một ít tiền.',
    log_homeless_person_1: 'Tôi hy vọng nó sẽ giúp họ một phần nào.',
    choice_homeless_person_2: 'Đi qua.',
    log_homeless_person_2: 'Tôi không có gì để cho.',
    event_lost_valuable_item_title: 'Mất đồ có giá trị',
    event_lost_valuable_item_desc: 'Bạn làm mất một món đồ có giá trị.',
    choice_lost_valuable_item_1: 'Tìm thấy lại.',
    log_lost_valuable_item_1: 'Thật may mắn!',
    choice_lost_valuable_item_2: 'Mất hẳn.',
    log_lost_valuable_item_2: 'Tôi đã rất buồn.',
    event_rescued_from_accident_title: 'Được cứu khỏi tai nạn',
    event_rescued_from_accident_desc: 'Bạn suýt gặp tai nạn nhưng được một người lạ cứu.',
    choice_rescued_from_accident_1: 'Cảm thấy biết ơn.',
    log_rescued_from_accident_1: 'Tôi đã cảm ơn người đó rất nhiều.',
    choice_rescued_from_accident_2: 'Cảm thấy sốc.',
    log_rescued_from_accident_2: 'Tôi vẫn còn run rẩy.',
    event_falsely_accused_title: 'Bị vu oan',
    event_falsely_accused_desc: 'Bạn bị vu oan một việc mà bạn không làm.',
    choice_falsely_accused_1: 'Chứng minh mình trong sạch.',
    log_falsely_accused_1: 'Cuối cùng sự thật cũng được làm sáng tỏ.',
    choice_falsely_accused_2: 'Không thể chứng minh.',
    log_falsely_accused_2: 'Không ai tin tôi.',
    event_surprise_gift_title: 'Món quà bất ngờ',
    event_surprise_gift_desc: 'Bạn nhận được một món quà bất ngờ.',
    choice_surprise_gift_1: 'Rất vui.',
    log_surprise_gift_1: 'Món quà thật tuyệt!',
    choice_surprise_gift_2: 'Hơi bối rối.',
    log_surprise_gift_2: 'Tôi không biết tại sao mình lại nhận được nó.',
    // Trigger-only
    event_investment_success_large_title: 'Đầu tư thành công!',
    event_investment_success_large_desc: 'Khoản đầu tư lớn của bạn đã mang lại lợi nhuận khổng lồ!',
    choice_investment_success_large_1: 'Tuyệt vời!',
    log_investment_success_large_1: 'Sự mạo hiểm đã được đền đáp.',
    choice_investment_success_large_2: 'Tái đầu tư ngay.',
    log_investment_success_large_2: 'Tôi sẽ dùng số tiền này để tiếp tục đầu tư.',
    event_investment_success_small_title: 'Đầu tư thành công',
    event_investment_success_small_desc: 'Khoản đầu tư nhỏ của bạn đã mang lại một khoản lợi nhuận kha khá.',
    choice_investment_success_small_1: 'Một khởi đầu tốt.',
    log_investment_success_small_1: 'Đây là một dấu hiệu tốt.',
    choice_investment_success_small_2: 'Ăn mừng thành công này.',
    log_investment_success_small_2: 'Tôi sẽ tự thưởng cho mình một chút.',
};
