export default {
event_flu_title: 'Bị cúm',
event_flu_desc: 'Bạn bị cúm, người mệt mỏi và đau nhức.',
choice_flu_1: 'Đi khám bác sĩ và uống thuốc.',
log_flu_1: 'Thuốc giúp tôi hồi phục nhanh chóng.',
choice_flu_2: 'Nghỉ ngơi ở nhà và uống nhiều nước.',
log_flu_2: 'Tôi tự điều trị, hồi phục chậm hơn.',
choice_flu_3: 'Phớt lờ và vẫn đi học/đi làm.',
log_flu_3: 'Bệnh nặng thêm và bị người khác phàn nàn.',

event_sickness_worsens_title: 'Bệnh trở nặng',
event_sickness_worsens_desc: 'Tình trạng sức khỏe của bạn xấu đi rõ rệt.',
choice_sickness_worsens_1: 'Đi bệnh viện ngay lập tức.',
log_sickness_worsens_1: 'Tôi được chữa trị và dần hồi phục.',
choice_sickness_worsens_2: 'Tiếp tục nằm nghỉ ở nhà.',
log_sickness_worsens_2: 'Bệnh kéo dài dai dẳng.',
choice_sickness_worsens_3: 'Nhờ gia đình chăm sóc.',
log_sickness_worsens_3: 'Tinh thần khá hơn, nhưng vẫn yếu.',

event_chronic_illness_title: 'Bệnh mãn tính',
event_chronic_illness_desc: 'Bác sĩ chẩn đoán bạn mắc bệnh mãn tính.',
choice_chronic_illness_1: 'Tuân thủ điều trị nghiêm túc.',
log_chronic_illness_1: 'Tôi kiểm soát bệnh ổn định.',
choice_chronic_illness_2: 'Bỏ qua lời khuyên của bác sĩ.',
log_chronic_illness_2: 'Tình trạng trở nên tệ hơn.',
choice_chronic_illness_3: 'Tham gia nhóm hỗ trợ bệnh nhân.',
log_chronic_illness_3: 'Tôi tìm được sự động viên và an ủi.',

event_traffic_accident_title: 'Tai nạn giao thông',
event_traffic_accident_desc: 'Bạn gặp một vụ va chạm nhỏ.',
choice_traffic_accident_1: 'Hòa giải và đền bù hợp lý.',
log_traffic_accident_1: 'Mọi việc kết thúc êm đẹp.',
choice_traffic_accident_2: 'Cãi nhau, đổ lỗi cho người khác.',
log_traffic_accident_2: 'Tranh cãi chỉ làm mất thời gian.',
choice_traffic_accident_3: 'Gọi công an giao thông.',
log_traffic_accident_3: 'Xử lý lâu hơn nhưng công bằng.',

event_sued_title: 'Bị kiện',
event_sued_desc: 'Bạn nhận được giấy triệu tập ra tòa.',
choice_sued_1: 'Thuê luật sư bào chữa.',
log_sued_1: 'Vụ việc được giải quyết ổn thỏa.',
choice_sued_2: 'Tự biện hộ.',
log_sued_2: 'Tôi thua kiện và thiệt hại nặng.',
choice_sued_3: 'Thương lượng với bên kia.',
log_sued_3: 'Chúng tôi dàn xếp nhưng tôi mất uy tín.',

event_lottery_win_title: 'Trúng số độc đắc',
event_lottery_win_desc: 'Bạn trúng một khoản tiền lớn.',
choice_lottery_win_1: 'Đầu tư dài hạn.',
log_lottery_win_1: 'Tiền sinh lợi, tương lai ổn định.',
choice_lottery_win_2: 'Tiêu xài thoải mái.',
log_lottery_win_2: 'Vui sướng ngắn ngủi, tiền vơi nhanh.',
choice_lottery_win_3: 'Gửi ngân hàng.',
log_lottery_win_3: 'Tiền an toàn nhưng lãi ít.',

event_friends_exploit_title: 'Bạn bè lợi dụng',
event_friends_exploit_desc: 'Sau khi bạn trúng số, nhiều người đến vay tiền.',
choice_friends_exploit_1: 'Cho vay một ít.',
log_friends_exploit_1: 'Có người biết ơn, có người không trả.',
choice_friends_exploit_2: 'Từ chối khéo léo.',
log_friends_exploit_2: 'Tôi nhận ra ai mới thật sự là bạn.',
choice_friends_exploit_3: 'Cắt đứt liên lạc.',
log_friends_exploit_3: 'Tránh rắc rối nhưng thấy cô đơn.',

event_lose_friend_title: 'Mất bạn',
event_lose_friend_desc: 'Một người bạn không còn nói chuyện với bạn.',
choice_lose_friend_1: 'Chủ động hỏi lý do.',
log_lose_friend_1: 'Chúng tôi nói chuyện lại, hơi gượng gạo.',
choice_lose_friend_2: 'Chấp nhận và buông bỏ.',
log_lose_friend_2: 'Tôi buồn nhưng tiếp tục sống.',
choice_lose_friend_3: 'Làm ngơ lại.',
log_lose_friend_3: 'Tình bạn lặng lẽ chấm dứt.',

event_lost_wallet_title: 'Mất ví',
event_lost_wallet_desc: 'Bạn phát hiện mình bị mất ví.',
choice_lost_wallet_1: 'Báo công an và làm lại giấy tờ.',
log_lost_wallet_1: 'Mất công sức nhưng an toàn.',
choice_lost_wallet_2: 'Hy vọng có người trả lại.',
log_lost_wallet_2: 'Ví không bao giờ quay về.',
choice_lost_wallet_3: 'Mượn tiền bạn bè tạm thời.',
log_lost_wallet_3: 'Bạn bè giúp tôi vượt khó.',

event_buy_house_title: 'Mua nhà',
event_buy_house_desc: 'Gia đình bạn tính mua nhà mới.',
choice_buy_house_1: 'Mua nhà lớn.',
log_buy_house_1: 'Sống rộng rãi nhưng nợ nần chồng chất.',
choice_buy_house_2: 'Mua nhà nhỏ vừa túi tiền.',
log_buy_house_2: 'Ấm cúng, dễ quản lý.',
choice_buy_house_3: 'Tiếp tục thuê.',
log_buy_house_3: 'Linh hoạt nhưng không ổn định.',

event_buy_car_title: 'Mua xe',
event_buy_car_desc: 'Bạn đang cân nhắc mua xe hơi.',
choice_buy_car_1: 'Mua xe sang.',
log_buy_car_1: 'Xe đẹp nhưng hao tài.',
choice_buy_car_2: 'Mua xe phổ thông.',
log_buy_car_2: 'Phục vụ tốt nhu cầu hàng ngày.',
choice_buy_car_3: 'Đi phương tiện công cộng.',
log_buy_car_3: 'Tiết kiệm nhưng bất tiện.',

event_burglary_title: 'Trộm đột nhập',
event_burglary_desc: 'Nhà bạn bị kẻ trộm lẻn vào.',
choice_burglary_1: 'Báo công an và lắp bảo mật.',
log_burglary_1: 'Chúng tôi lắp hệ thống chống trộm mới.',
choice_burglary_2: 'Đối mặt với tên trộm.',
log_burglary_2: 'Tôi bị thương, quyết định liều lĩnh.',
choice_burglary_3: 'Trốn và gọi hàng xóm.',
log_burglary_3: 'Được giúp kịp thời và an toàn.',

event_online_scam_title: 'Lừa đảo trực tuyến',
event_online_scam_desc: 'Bạn nhận được email hứa hẹn lợi nhuận lớn.',
choice_online_scam_1: 'Tin và nhấp vào.',
log_online_scam_1: 'Tôi mất tiền vì quá cả tin.',
choice_online_scam_2: 'Phớt lờ.',
log_online_scam_2: 'Tôi an toàn, không dính bẫy.',
choice_online_scam_3: 'Báo cáo là lừa đảo.',
log_online_scam_3: 'Người khác cũng được cảnh báo.',

event_charity_donation_title: 'Quyên góp từ thiện',
event_charity_donation_desc: 'Một tổ chức kêu gọi ủng hộ.',
choice_charity_donation_1: 'Quyên góp nhiều.',
log_charity_donation_1: 'Tôi hạnh phúc vì giúp được nhiều người.',
choice_charity_donation_2: 'Quyên góp ít.',
log_charity_donation_2: 'Ít nhưng ý nghĩa.',
choice_charity_donation_3: 'Không quyên góp.',
log_charity_donation_3: 'Tôi giữ tiền lo cho gia đình.',

event_job_loss_social_crisis_title: 'Mất việc vì khủng hoảng',
event_job_loss_social_crisis_desc: 'Công ty cắt giảm, bạn bị cho nghỉ.',
choice_job_loss_social_crisis_1: 'Nhanh chóng tìm việc mới.',
log_job_loss_social_crisis_1: 'Tôi có cơ hội nhưng rất căng thẳng.',
choice_job_loss_social_crisis_2: 'Tạm nghỉ ngơi.',
log_job_loss_social_crisis_2: 'Tôi thoải mái nhưng mất thu nhập.',
choice_job_loss_social_crisis_3: 'Học nghề mới.',
log_job_loss_social_crisis_3: 'Khó khăn ban đầu nhưng mở lối khác.',

event_natural_disaster_title: 'Thiên tai',
event_natural_disaster_desc: 'Một thảm họa thiên nhiên ập đến.',
choice_natural_disaster_1: 'Bảo vệ gia đình trước tiên.',
log_natural_disaster_1: 'Mọi người an toàn nhưng hoảng sợ.',
choice_natural_disaster_2: 'Cứu đồ đạc.',
log_natural_disaster_2: 'Giữ được tài sản nhưng rất nguy hiểm.',
choice_natural_disaster_3: 'Tham gia cứu trợ cộng đồng.',
log_natural_disaster_3: 'Khó khăn nhưng tôi tự hào đã giúp.',

event_street_assault_title: 'Bị tấn công trên phố',
event_street_assault_desc: 'Bạn bị một kẻ lạ tấn công.',
choice_street_assault_1: 'Chống trả và bỏ chạy.',
log_street_assault_1: 'Tôi thoát được nhưng bị thương.',
choice_street_assault_2: 'Đưa đồ để bảo toàn tính mạng.',
log_street_assault_2: 'Tôi an toàn nhưng mất tài sản.',
choice_street_assault_3: 'La hét cầu cứu.',
log_street_assault_3: 'Người xung quanh đến giúp.',
log_asset_lost_robbery: '{name} bị cướp mất: {assetName}.',

event_getting_lost_title: 'Lạc đường',
event_getting_lost_desc: 'Bạn bị lạc ở nơi xa lạ.',
choice_getting_lost_1: 'Dùng bản đồ/GPS.',
log_getting_lost_1: 'Tôi tìm được đường về.',
choice_getting_lost_2: 'Hỏi người lạ.',
log_getting_lost_2: 'Lời khuyên hữu ích giúp tôi thoát.',
choice_getting_lost_3: 'Đi bừa đến khi quen đường.',
log_getting_lost_3: 'Tôi mất nhiều giờ mới về được.',

event_unpaid_debt_title: 'Nợ cũ chưa trả',
event_unpaid_debt_desc: 'Một người bạn nhắc bạn về khoản nợ cũ.',
choice_unpaid_debt_1: 'Trả hết ngay.',
log_unpaid_debt_1: 'Tôi giữ được uy tín nhưng mất tiền.',
choice_unpaid_debt_2: 'Lẩn tránh.',
log_unpaid_debt_2: 'Khoản nợ ám ảnh tôi.',
choice_unpaid_debt_3: 'Thỏa thuận trả góp.',
log_unpaid_debt_3: 'Chúng tôi thống nhất trả dần.',  

event_tax_evasion_discovered_title: 'Phát hiện trốn thuế',
event_tax_evasion_discovered_desc: 'Cơ quan thuế phát hiện sai sót trong hồ sơ của bạn.',
choice_tax_evasion_discovered_1: 'Nộp phạt ngay.',
log_tax_evasion_discovered_1: 'Tôi mất tiền nhưng tránh được rắc rối lớn hơn.',
choice_tax_evasion_discovered_2: 'Chối bỏ trách nhiệm.',
log_tax_evasion_discovered_2: 'Mức phạt tăng lên sau khi điều tra.',
choice_tax_evasion_discovered_3: 'Thuê kế toán sửa chữa hồ sơ.',
log_tax_evasion_discovered_3: 'Sự giúp đỡ chuyên nghiệp giảm thiểu rủi ro.',

event_investment_opportunity_title: 'Cơ hội đầu tư',
event_investment_opportunity_desc: 'Bạn thấy một cơ hội đầu tư hứa hẹn.',
choice_investment_opportunity_1: 'Đầu tư số tiền lớn.',
log_investment_opportunity_1: 'Tiềm năng cao nhưng rủi ro.',
choice_investment_opportunity_2: 'Đầu tư nhỏ để thử.',
log_investment_opportunity_2: 'Tôi thận trọng nhưng lợi nhuận ít.',
choice_investment_opportunity_3: 'Bỏ qua lời đề nghị.',
log_investment_opportunity_3: 'Tôi tránh được rủi ro nhưng mất cơ hội.',

event_investment_failure_title: 'Đầu tư thất bại',
event_investment_failure_desc: 'Khoản đầu tư gần đây của bạn đã thất bại.',
choice_investment_failure_1: 'Chấp nhận thua lỗ và dừng lại.',
log_investment_failure_1: 'Tôi dừng lại trước khi mất thêm.',
choice_investment_failure_2: 'Phân tích sai lầm để học hỏi.',
log_investment_failure_2: 'Tốn kém nhưng có kinh nghiệm.',
choice_investment_failure_3: 'Đầu tư nơi khác để gỡ gạc.',
log_investment_failure_3: 'Tôi liều lĩnh hơn với hy vọng gỡ lại.',

event_small_lottery_title: 'Trúng số nhỏ',
event_small_lottery_desc: 'Bạn trúng một giải thưởng nhỏ trong xổ số.',
choice_small_lottery_1: 'Tự thưởng một bữa ngon.',
log_small_lottery_1: 'Tôi dùng nó cho một bữa ăn ngon.',
choice_small_lottery_2: 'Mua thêm vé số.',
log_small_lottery_2: 'Tôi đánh cược và không được gì.',
choice_small_lottery_3: 'Tiết kiệm.',
log_small_lottery_3: 'Một khoản nhỏ cho tiền tiết kiệm của tôi.',

event_get_a_pet_title: 'Nuôi thú cưng',
event_get_a_pet_desc: 'Bạn đang cân nhắc nhận nuôi một con thú cưng.',
choice_get_a_pet_1: 'Nhận nuôi và chăm sóc cẩn thận.',
log_get_a_pet_1: 'Thú cưng trở thành thành viên gia đình.',
choice_get_a_pet_2: 'Nhận nuôi nhưng bỏ bê trách nhiệm.',
log_get_a_pet_2: 'Thú cưng gây ra nhiều căng thẳng hơn là niềm vui.',
choice_get_a_pet_3: 'Nhận nuôi tạm thời trước.',
log_get_a_pet_3: 'Tôi thử nghiệm trước khi cam kết lâu dài.',

event_loan_shark_title: 'Vay nặng lãi',
event_loan_shark_desc: 'Bạn nghĩ đến việc vay tiền từ một kẻ cho vay nặng lãi.',
choice_loan_shark_1: 'Từ chối, quá nguy hiểm.',
log_loan_shark_1: 'Tôi an toàn dù vẫn thiếu tiền.',
choice_loan_shark_2: 'Vay một khoản nhỏ.',
log_loan_shark_2: 'Giải quyết tạm thời nhưng rủi ro sau này.',
choice_loan_shark_3: 'Tìm khoản vay ngân hàng hoặc gia đình.',
log_loan_shark_3: 'Tôi tìm được một giải pháp an toàn hơn.',

event_loan_shark_enforcers_title: 'Kẻ đòi nợ',
event_loan_shark_enforcers_desc: 'Những kẻ đòi nợ đến yêu cầu trả tiền.',
choice_loan_shark_enforcers_1: 'Trả hết cho họ.',
log_loan_shark_enforcers_1: 'Tôi trả nhiều hơn số tiền đã vay.',
choice_loan_shark_enforcers_2: 'Từ chối và đối mặt với bạo lực.',
log_loan_shark_enforcers_2: 'Tôi bị thương và sợ hãi.',
choice_loan_shark_enforcers_3: 'Gọi cảnh sát giúp đỡ.',
log_loan_shark_enforcers_3: 'Chính quyền bảo vệ tôi nhưng tôi vẫn nợ tiền.',

event_relative_is_sick_title: 'Người thân bị ốm',
event_relative_is_sick_desc: 'Một người thân của bạn bị bệnh nặng.',
choice_relative_is_sick_1: 'Giúp chi phí y tế.',
log_relative_is_sick_1: 'Tốn kém nhưng gia đình là quan trọng.',
choice_relative_is_sick_2: 'Chỉ hỗ trợ tinh thần.',
log_relative_is_sick_2: 'Tôi ở bên cạnh họ, dù không có tiền.',
choice_relative_is_sick_3: 'Tổ chức quyên góp.',
log_relative_is_sick_3: 'Sự hỗ trợ của cộng đồng đã giảm bớt gánh nặng.',

event_self_development_seminar_title: 'Hội thảo phát triển bản thân',
event_self_development_seminar_desc: 'Bạn được mời tham gia một hội thảo phát triển cá nhân.',
choice_self_development_seminar_1: 'Tham dự và ghi chép.',
log_self_development_seminar_1: 'Tôi học được những kỹ năng và ý tưởng mới.',
choice_self_development_seminar_2: 'Từ chối lịch sự.',
log_self_development_seminar_2: 'Tôi đã bỏ lỡ những lời khuyên hữu ích.',
choice_self_development_seminar_3: 'Học trực tuyến thay thế.',
log_self_development_seminar_3: 'Tôi có được kiến thức một cách rẻ hơn.',

event_minor_accident_title: 'Tai nạn nhỏ',
event_minor_accident_desc: 'Bạn gặp một tai nạn nhỏ.',
choice_minor_accident_1: 'Đến bác sĩ điều trị.',
log_minor_accident_1: 'Tôi được điều trị nhanh chóng và khỏi bệnh.',
choice_minor_accident_2: 'Tự chữa ở nhà.',
log_minor_accident_2: 'Nó trở nên tồi tệ hơn trước khi lành.',
choice_minor_accident_3: 'Yêu cầu bồi thường bảo hiểm.',
log_minor_accident_3: 'Giấy tờ chậm nhưng hữu ích sau này.',

event_pyramid_scheme_title: 'Đa cấp lừa đảo',
event_pyramid_scheme_desc: 'Một người bạn mời bạn tham gia một mô hình đa cấp.',
choice_pyramid_scheme_1: 'Tham gia và đầu tư.',
log_pyramid_scheme_1: 'Tôi mất tiền vì lừa đảo.',
choice_pyramid_scheme_2: 'Từ chối tham gia.',
log_pyramid_scheme_2: 'Tôi an toàn và giữ khoảng cách.',
choice_pyramid_scheme_3: 'Cảnh báo người khác.',
log_pyramid_scheme_3: 'Tôi đã bảo vệ một số người bạn khỏi mất tiền.',

event_relative_death_title: 'Người thân qua đời',
event_relative_death_desc: 'Một người họ hàng xa đã qua đời.',
choice_relative_death_1: 'Giúp tổ chức tang lễ.',
log_relative_death_1: 'Đó là một nhiệm vụ nặng nề nhưng quan trọng.',
choice_relative_death_2: 'Đau buồn sâu sắc.',
log_relative_death_2: 'Tôi suy sụp trong nhiều tuần.',
choice_relative_death_3: 'Hỗ trợ tinh thần cho gia đình.',
log_relative_death_3: 'Cùng nhau chúng tôi vượt qua mất mát.',

event_large_gift_title: 'Quà lớn',
event_large_gift_desc: 'Bạn nhận được một món quà lớn từ người thân.',
choice_large_gift_1: 'Nhận và biết ơn.',
log_large_gift_1: 'Tôi cảm thấy biết ơn và được trân trọng.',
choice_large_gift_2: 'Cảm thấy khó xử.',
log_large_gift_2: 'Tôi không chắc phải phản ứng thế nào.',
choice_large_gift_3: 'Tặng lại quà hoặc thư.',
log_large_gift_3: 'Tôi thể hiện sự trân trọng một cách tôn trọng.',

event_stranger_asks_for_help_title: 'Người lạ nhờ giúp đỡ',
event_stranger_asks_for_help_desc: 'Một người lạ trên đường nhờ giúp đỡ.',
choice_stranger_asks_for_help_1: 'Giúp họ trực tiếp.',
log_stranger_asks_for_help_1: 'Làm việc tốt khiến tôi vui.',
choice_stranger_asks_for_help_2: 'Từ chối và đi tiếp.',
log_stranger_asks_for_help_2: 'Tôi tránh rủi ro nhưng cảm thấy tội lỗi.',
choice_stranger_asks_for_help_3: 'Hướng dẫn họ đến nơi hỗ trợ.',
log_stranger_asks_for_help_3: 'Họ nhận được sự giúp đỡ đúng cách.',

event_social_movement_title: 'Phong trào xã hội',
event_social_movement_desc: 'Một cuộc biểu tình lớn đang diễn ra trong thành phố.',
choice_social_movement_1: 'Tham gia biểu tình.',
log_social_movement_1: 'Tôi cảm thấy mạnh mẽ khi đứng cùng người khác.',
choice_social_movement_2: 'Tránh xa nó.',
log_social_movement_2: 'Tôi tránh nguy hiểm nhưng cảm thấy bất lực.',
choice_social_movement_3: 'Hỗ trợ trực tuyến hoặc quyên góp.',
log_social_movement_3: 'Tôi đóng góp một cách an toàn từ nhà.',

event_homeless_person_title: 'Người vô gia cư',
event_homeless_person_desc: 'Bạn gặp một người vô gia cư.',
choice_homeless_person_1: 'Cho tiền.',
log_homeless_person_1: 'Tôi hy vọng nó giúp được một chút.',
choice_homeless_person_2: 'Đi qua.',
log_homeless_person_2: 'Tôi cảm thấy tội lỗi vì đã lờ đi.',
choice_homeless_person_3: 'Mua thức ăn hoặc chỉ đến nơi trú ẩn.',
log_homeless_person_3: 'Tôi đã giúp đỡ một cách thiết thực.',

event_lost_valuable_item_title: 'Mất đồ quý giá',
event_lost_valuable_item_desc: 'Bạn mất một món đồ quan trọng.',
choice_lost_valuable_item_1: 'Tìm kiếm kỹ lưỡng.',
log_lost_valuable_item_1: 'Tôi tìm thấy nó sau khi căng thẳng.',
choice_lost_valuable_item_2: 'Chấp nhận mất mát.',
log_lost_valuable_item_2: 'Tôi buồn nhưng đã vượt qua.',
choice_lost_valuable_item_3: 'Dán thông báo hoặc treo thưởng.',
log_lost_valuable_item_3: 'Tôi tăng cơ hội tìm lại được.',

event_rescued_from_accident_title: 'Được cứu khỏi tai nạn',
event_rescued_from_accident_desc: 'Một người lạ đã cứu bạn khỏi một tai nạn.',
choice_rescued_from_accident_1: 'Cảm ơn họ chân thành.',
log_rescued_from_accident_1: 'Tôi thể hiện lòng biết ơn sâu sắc.',
choice_rescued_from_accident_2: 'Vẫn còn sốc.',
log_rescued_from_accident_2: 'Tôi không thể bình tĩnh lại trong nhiều giờ.',
choice_rescued_from_accident_3: 'Tặng quà hoặc liên lạc.',
log_rescued_from_accident_3: 'Tôi đã xây dựng mối quan hệ với người cứu mình.',

event_falsely_accused_title: 'Bị vu oan',
event_falsely_accused_desc: 'Bạn bị buộc tội về điều bạn không làm.',
choice_falsely_accused_1: 'Cung cấp bằng chứng vô tội.',
log_falsely_accused_1: 'Sự thật đã minh oan cho tôi.',
choice_falsely_accused_2: 'Im lặng và chịu đựng.',
log_falsely_accused_2: 'Không ai tin tôi.',
choice_falsely_accused_3: 'Tìm kiếm sự giúp đỡ pháp lý.',
log_falsely_accused_3: 'Một luật sư đã giúp tôi bào chữa.',

event_surprise_gift_title: 'Quà bất ngờ',
event_surprise_gift_desc: 'Bạn nhận được một món quà bất ngờ.',
choice_surprise_gift_1: 'Nhận với niềm vui.',
log_surprise_gift_1: 'Món quà làm tôi rất vui.',
choice_surprise_gift_2: 'Cảm thấy bối rối.',
log_surprise_gift_2: 'Tôi tự hỏi tại sao mình lại nhận được nó.',
choice_surprise_gift_3: 'Chia sẻ niềm vui với người khác.',
log_surprise_gift_3: 'Tôi lan tỏa hạnh phúc bằng cách khoe nó với bạn bè.',

    // Trigger-only
    event_investment_success_large_title: 'Đầu tư lớn thành công!',
    event_investment_success_large_desc: 'Khoản đầu tư lớn của bạn đã mang lại lợi nhuận khổng lồ!',
    choice_investment_success_large_1: 'Thật tuyệt vời!',
    log_investment_success_large_1: 'Rủi ro đã được đền đáp xứng đáng.',
    choice_investment_success_large_2: 'Tái đầu tư ngay lập tức.',
    log_investment_success_large_2: 'Tôi dùng số tiền này để tiếp tục đầu tư.',
    choice_investment_success_large_3: 'Giữ tiền an toàn trong ngân hàng.',
    log_investment_success_large_3: 'Tôi quyết định bảo toàn lợi nhuận vừa có.',
    
    event_investment_success_small_title: 'Đầu tư nhỏ thành công',
    event_investment_success_small_desc: 'Khoản đầu tư nhỏ của bạn đã mang lại lợi nhuận khá.',
    choice_investment_success_small_1: 'Một khởi đầu tốt.',
    log_investment_success_small_1: 'Đây là dấu hiệu đáng mừng.',
    choice_investment_success_small_2: 'Ăn mừng thành công này.',
    log_investment_success_small_2: 'Tôi tự thưởng cho mình một chút.',
    choice_investment_success_small_3: 'Tiếp tục đầu tư có kiểm soát.',
    log_investment_success_small_3: 'Tôi dùng kinh nghiệm này để phát triển dần dần.',
};