export default {
    // Main Events
    event_middleschool_late_for_school_title: 'Đi học muộn',
    event_middleschool_late_for_school_desc: 'Bạn đi học muộn vì kẹt xe bus.',
    choice_middleschool_late_for_school_1: 'Xin lỗi giáo viên',
    log_middleschool_late_for_school_1: 'Tôi đã xin lỗi và được vào lớp.',
    choice_middleschool_late_for_school_2: 'Lẻn vào lớp',
    log_middleschool_late_for_school_2: 'Tôi đã cố lẻn vào mà không để giáo viên thấy.',
    choice_middleschool_late_for_school_3: 'Giải thích lý do với cô',
    log_middleschool_late_for_school_3: 'Cô giáo đã hiểu cho hoàn cảnh của tôi.',

    event_middleschool_locker_trouble_title: 'Quên mở locker',
    event_middleschool_locker_trouble_desc: 'Bạn đã quên mở locker đúng giờ.',
    choice_middleschool_locker_trouble_1: 'Nhờ bạn mở giúp',
    log_middleschool_locker_trouble_1: 'Bạn tôi đã giúp tôi lấy sách vở.',
    choice_middleschool_locker_trouble_2: 'Đi hỏi giám thị',
    log_middleschool_locker_trouble_2: 'Tôi đã đi tìm giám thị để mở locker.',
    choice_middleschool_locker_trouble_3: 'Chờ ra chơi mới mở',
    log_middleschool_locker_trouble_3: 'Tôi quyết định đợi đến giờ ra chơi, dù có thể bị lỡ bài.',

    event_middleschool_science_project_title: 'Bài tập nhóm khoa học',
    event_middleschool_science_project_desc: 'Bạn đang làm một bài tập nhóm môn khoa học.',
    choice_middleschool_science_project_1: 'Làm việc cùng nhau',
    log_middleschool_science_project_1: 'Chúng tôi đã hợp tác tốt và có tiến triển tốt.',
    choice_middleschool_science_project_2: 'Làm ít việc cho có',
    log_middleschool_science_project_2: 'Tôi đã không đóng góp nhiều cho dự án.',
    choice_middleschool_science_project_3: 'Tranh luận gay gắt với bạn',
    log_middleschool_science_project_3: 'Chúng tôi đã có một cuộc tranh cãi lớn về chi tiết dự án.',

    event_middleschool_pe_basketball_title: 'Giờ thể dục bóng rổ',
    event_middleschool_pe_basketball_desc: 'Đã đến giờ học bóng rổ trong tiết thể dục.',
    choice_middleschool_pe_basketball_1: 'Chơi hết mình',
    log_middleschool_pe_basketball_1: 'Tôi đã có một khoảng thời gian tuyệt vời và tập luyện tốt.',
    choice_middleschool_pe_basketball_2: 'Nói mệt xin ngồi ngoài',
    log_middleschool_pe_basketball_2: 'Hôm nay tôi không có hứng thú.',
    choice_middleschool_pe_basketball_3: 'Ngồi ngoài cổ vũ',
    log_middleschool_pe_basketball_3: 'Tôi đã ủng hộ bạn bè từ băng ghế dự bị.',

    event_middleschool_english_presentation_title: 'Thuyết trình tiếng Anh',
    event_middleschool_english_presentation_desc: 'Bạn phải thuyết trình trong giờ học tiếng Anh.',
    choice_middleschool_english_presentation_1: 'Chuẩn bị kỹ càng',
    log_middleschool_english_presentation_1: 'Tôi đã chuẩn bị kỹ và thuyết trình một cách tự tin.',
    choice_middleschool_english_presentation_2: 'Đọc chép từ giấy',
    log_middleschool_english_presentation_2: 'Tôi chỉ đọc ghi chú mà không nhìn vào khán giả.',
    choice_middleschool_english_presentation_3: 'Nói ngập ngừng thiếu tự tin',
    log_middleschool_english_presentation_3: 'Tôi quá lo lắng để nói rõ ràng.',

    event_middleschool_student_council_title: 'Hội học sinh',
    event_middleschool_student_council_desc: 'Bạn đang cân nhắc ứng cử vào hội học sinh.',
    choice_middleschool_student_council_1: 'Ứng cử nghiêm túc',
    log_middleschool_student_council_1: 'Tôi đã có một bài phát biểu nghiêm túc và vận động hết mình.',
    choice_middleschool_student_council_2: 'Nói hứa hẹn hơi quá',
    log_middleschool_student_council_2: 'Có lẽ tôi đã hứa nhiều hơn những gì tôi có thể làm.',
    choice_middleschool_student_council_3: 'Phát biểu ít, chủ yếu lắng nghe',
    log_middleschool_student_council_3: 'Tôi quyết định quan sát năm nay thay vì ứng cử.',

    event_middleschool_cafeteria_lunch_title: 'Bữa trưa ở căn-tin',
    event_middleschool_cafeteria_lunch_desc: 'Đã đến giờ ăn trưa. Bạn ngồi với ai?',
    choice_middleschool_cafeteria_lunch_1: 'Ngồi với bạn thân',
    log_middleschool_cafeteria_lunch_1: 'Tôi đã có một cuộc trò chuyện vui vẻ với bạn thân trong bữa trưa.',
    choice_middleschool_cafeteria_lunch_2: 'Ngồi với crush',
    log_middleschool_cafeteria_lunch_2: 'Tim tôi đập thình thịch suốt thời gian đó!',
    choice_middleschool_cafeteria_lunch_3: 'Ngồi một mình yên tĩnh',
    log_middleschool_cafeteria_lunch_3: 'Tôi đã tận hưởng một chút thời gian yên bình một mình.',

    event_middleschool_school_dance_title: 'Vũ hội nhỏ ở trường',
    event_middleschool_school_dance_desc: 'Có một vũ hội nhỏ ở trường đang diễn ra.',
    choice_middleschool_school_dance_1: 'Rủ bạn khiêu vũ',
    log_middleschool_school_dance_1: 'Chúng tôi đã có rất nhiều niềm vui khi khiêu vũ cùng nhau.',
    choice_middleschool_school_dance_2: 'Ngại ngùng đứng ngoài',
    log_middleschool_school_dance_2: 'Tôi quá nhút nhát để mời ai đó khiêu vũ.',
    choice_middleschool_school_dance_3: 'Đứng một góc quan sát',
    log_middleschool_school_dance_3: 'Tôi thích thú quan sát mọi người vui vẻ.',

    event_middleschool_science_experiment_title: 'Thí nghiệm khoa học',
    event_middleschool_science_experiment_desc: 'Bạn đang tiến hành một thí nghiệm khoa học.',
    choice_middleschool_science_experiment_1: 'Làm theo hướng dẫn',
    log_middleschool_science_experiment_1: 'Thí nghiệm đã diễn ra suôn sẻ.',
    choice_middleschool_science_experiment_2: 'Làm thử cách riêng',
    log_middleschool_science_experiment_2: 'Tôi quyết định thử nghiệm một chút theo cách riêng của mình.',
    choice_middleschool_science_experiment_3: 'Quan sát để học hỏi',
    log_middleschool_science_experiment_3: 'Tôi đã quan sát các bạn cùng lớp để xem họ làm thế nào.',

    event_middleschool_pop_quiz_title: 'Kiểm tra bất ngờ',
    event_middleschool_pop_quiz_desc: 'Giáo viên thông báo một bài kiểm tra bất ngờ.',
    choice_middleschool_pop_quiz_1: 'Làm theo sức mình',
    log_middleschool_pop_quiz_1: 'Tôi đã trả lời hết khả năng của mình.',
    choice_middleschool_pop_quiz_2: 'Nhìn bài bạn',
    log_middleschool_pop_quiz_2: 'Tôi đã cố gắng nhận một chút trợ giúp từ bạn tôi.',
    choice_middleschool_pop_quiz_3: 'Viết đại cho xong',
    log_middleschool_pop_quiz_3: 'Tôi chỉ muốn làm cho xong.',

    // Triggered Events
    event_middleschool_late_slip_title: 'Bị ghi sổ đi muộn',
    event_middleschool_late_slip_desc: 'Bạn bị bắt quả tang khi lẻn vào và bị ghi sổ đi muộn.',
    choice_middleschool_late_slip_1: 'Xin cô cho cơ hội',
    log_middleschool_late_slip_1: 'Tôi đã năn nỉ cô giáo, nhưng vẫn bị ghi sổ.',
    choice_middleschool_late_slip_2: 'Chấp nhận phạt',
    log_middleschool_late_slip_2: 'Tôi đã chấp nhận hậu quả của hành động của mình.',
    choice_middleschool_late_slip_3: 'Giải thích do bus hỏng',
    log_middleschool_late_slip_3: 'Tôi đã cố gắng giải thích tình hình của mình.',

    event_middleschool_punished_for_tardiness_title: 'Bị phạt vì trễ vào lớp',
    event_middleschool_punished_for_tardiness_desc: 'Bạn đã bị phạt vì trễ vào lớp do locker.',
    choice_middleschool_punished_for_tardiness_1: 'Xin lỗi giáo viên',
    log_middleschool_punished_for_tardiness_1: 'Tôi đã xin lỗi vì đã đến muộn.',
    choice_middleschool_punished_for_tardiness_2: 'Chấp nhận viết bản kiểm điểm',
    log_middleschool_punished_for_tardiness_2: 'Tôi đã phải viết bản kiểm điểm.',
    choice_middleschool_punished_for_tardiness_3: 'Đề nghị đổi giờ mở locker',
    log_middleschool_punished_for_tardiness_3: 'Tôi đã đề nghị thay đổi quy định của trường.',

    event_middleschool_group_ostracized_title: 'Bị nhóm tẩy chay',
    event_middleschool_group_ostracized_desc: 'Các thành viên trong nhóm đang lờ bạn đi vì không đóng góp.',
    choice_middleschool_group_ostracized_1: 'Xin lỗi và làm bù',
    log_middleschool_group_ostracized_1: 'Tôi đã xin lỗi và hứa sẽ làm phần việc của mình.',
    choice_middleschool_group_ostracized_2: 'Tìm nhóm khác',
    log_middleschool_group_ostracized_2: 'Tôi quyết định tìm một nhóm khác để làm việc.',
    choice_middleschool_group_ostracized_3: 'Cố gắng chứng minh năng lực',
    log_middleschool_group_ostracized_3: 'Tôi đã cố gắng cho họ thấy tôi có thể là một thành viên có giá trị.',

    event_middleschool_teacher_reprimand_pe_title: 'Bị giáo viên nhắc nhở',
    event_middleschool_teacher_reprimand_pe_desc: 'Giáo viên đã nhắc nhở bạn vì trốn học thể dục.',
    choice_middleschool_teacher_reprimand_pe_1: 'Quay lại tham gia',
    log_middleschool_teacher_reprimand_pe_1: 'Tôi đã tham gia lại hoạt động của lớp.',
    choice_middleschool_teacher_reprimand_pe_2: 'Giải thích mình thực sự mệt',
    log_middleschool_teacher_reprimand_pe_2: 'Tôi khẳng định rằng tôi không khỏe.',
    choice_middleschool_teacher_reprimand_pe_3: 'Chấp nhận bị trừ điểm',
    log_middleschool_teacher_reprimand_pe_3: 'Tôi chấp nhận rằng điểm của mình sẽ bị hạ.',

    event_middleschool_teacher_reprimand_presentation_title: 'Bị cô giáo nhắc nhở',
    event_middleschool_teacher_reprimand_presentation_desc: 'Cô giáo đã nhắc nhở bạn vì đọc trực tiếp từ giấy.',
    choice_middleschool_teacher_reprimand_presentation_1: 'Cố gắng nói lại bằng lời mình',
    log_middleschool_teacher_reprimand_presentation_1: 'Tôi đã cố gắng ứng biến phần còn lại của bài thuyết trình.',
    choice_middleschool_teacher_reprimand_presentation_2: 'Xin lỗi và tiếp tục',
    log_middleschool_teacher_reprimand_presentation_2: 'Tôi đã xin lỗi và tiếp tục đọc.',
    choice_middleschool_teacher_reprimand_presentation_3: 'Ngồi xuống chờ lượt khác',
    log_middleschool_teacher_reprimand_presentation_3: 'Tôi quá xấu hổ để tiếp tục.',

    event_middleschool_teased_by_friends_council_title: 'Bị bạn bè trêu chọc',
    event_middleschool_teased_by_friends_council_desc: 'Bạn bè đang trêu chọc bạn vì những lời hứa hẹn quá mức của bạn.',
    choice_middleschool_teased_by_friends_council_1: 'Đùa lại cho nhẹ không khí',
    log_middleschool_teased_by_friends_council_1: 'Tôi đã cười cùng họ.',
    choice_middleschool_teased_by_friends_council_2: 'Giải thích ý tốt của mình',
    log_middleschool_teased_by_friends_council_2: 'Tôi đã cố gắng giải thích ý của mình.',
    choice_middleschool_teased_by_friends_council_3: 'Im lặng bỏ qua',
    log_middleschool_teased_by_friends_council_3: 'Tôi không để lời trêu chọc của họ làm phiền.',

    event_middleschool_teased_by_friends_crush_title: 'Bị bạn bè trêu',
    event_middleschool_teased_by_friends_crush_desc: 'Bạn bè đang trêu chọc bạn vì ngồi với crush.',
    choice_middleschool_teased_by_friends_crush_1: 'Giả vờ không nghe thấy',
    log_middleschool_teased_by_friends_crush_1: 'Tôi đã hành động như không nghe thấy họ.',
    choice_middleschool_teased_by_friends_crush_2: 'Cười và tiếp tục ngồi',
    log_middleschool_teased_by_friends_crush_2: 'Tôi sẽ không để họ phá hỏng khoảnh khắc này.',
    choice_middleschool_teased_by_friends_crush_3: 'Chuyển bàn khác',
    log_middleschool_teased_by_friends_crush_3: 'Tôi đã bối rối và chuyển đi.',

    event_middleschool_dragged_to_dance_title: 'Bị bạn bè kéo ra nhảy',
    event_middleschool_dragged_to_dance_desc: 'Bạn bè đã kéo bạn ra sàn nhảy.',
    choice_middleschool_dragged_to_dance_1: 'Tham gia nhảy cho vui',
    log_middleschool_dragged_to_dance_1: 'Tôi quyết định thả lỏng và đã có một khoảng thời gian tuyệt vời.',
    choice_middleschool_dragged_to_dance_2: 'Cười trừ rồi đứng ngoài',
    log_middleschool_dragged_to_dance_2: 'Tôi vẫn cảm thấy quá nhút nhát để nhảy.',
    choice_middleschool_dragged_to_dance_3: 'Thử nhảy một chút rồi nghỉ',
    log_middleschool_dragged_to_dance_3: 'Tôi đã nhảy một bài rồi quay lại bên lề.',

    event_middleschool_minor_incident_title: 'Bị sự cố nhỏ',
    event_middleschool_minor_incident_desc: 'Đã có một sự cố nhỏ trong quá trình thí nghiệm của bạn.',
    choice_middleschool_minor_incident_1: 'Báo cô giáo',
    log_middleschool_minor_incident_1: 'Tôi đã báo cho giáo viên biết ngay lập tức.',
    choice_middleschool_minor_incident_2: 'Sửa lại cho đúng',
    log_middleschool_minor_incident_2: 'Tôi đã cố gắng sửa lỗi của mình.',
    choice_middleschool_minor_incident_3: 'Cười cho qua và tiếp tục',
    log_middleschool_minor_incident_3: 'Đó không phải là chuyện lớn, nên tôi cứ tiếp tục.',

    event_middleschool_invigilator_warning_quiz_title: 'Bị giám thị nhắc nhở',
    event_middleschool_invigilator_warning_quiz_desc: 'Giám thị đã cảnh cáo bạn vì gian lận.',
    choice_middleschool_invigilator_warning_quiz_1: 'Xin lỗi',
    log_middleschool_invigilator_warning_quiz_1: 'Tôi đã xin lỗi và ngừng gian lận.',
    choice_middleschool_invigilator_warning_quiz_2: 'Cãi lại',
    log_middleschool_invigilator_warning_quiz_2: 'Tôi khẳng định rằng tôi không gian lận.',
    choice_middleschool_invigilator_warning_quiz_3: 'Chấp nhận điểm kém',
    log_middleschool_invigilator_warning_quiz_3: 'Tôi đã chấp nhận hậu quả và nhận điểm không.',

    // Independent Events
    event_middleschool_class_debate_title: 'Tranh luận trong lớp',
    event_middleschool_class_debate_desc: 'Có một cuộc tranh luận trong lớp.',
    choice_middleschool_class_debate_1: 'Đưa ý kiến rõ ràng',
    log_middleschool_class_debate_1: 'Tôi đã tham gia tích cực vào cuộc tranh luận.',
    choice_middleschool_class_debate_2: 'Im lặng lắng nghe',
    log_middleschool_class_debate_2: 'Tôi thích lắng nghe ý kiến của người khác hơn.',
    choice_middleschool_class_debate_3: 'Tham gia một chút rồi thôi',
    log_middleschool_class_debate_3: 'Tôi đã chia sẻ một ý kiến rồi lắng nghe.',

    event_middleschool_after_school_sports_title: 'Chơi thể thao ngoài giờ',
    event_middleschool_after_school_sports_desc: 'Bạn đang chơi thể thao sau giờ học.',
    choice_middleschool_after_school_sports_1: 'Tham gia đội bóng',
    log_middleschool_after_school_sports_1: 'Tôi quyết định tham gia đội tuyển của trường.',
    choice_middleschool_after_school_sports_2: 'Chơi vui cùng bạn',
    log_middleschool_after_school_sports_2: 'Chúng tôi đã có một trận đấu vui vẻ với bạn bè.',
    choice_middleschool_after_school_sports_3: 'Ngồi xem cổ vũ',
    log_middleschool_after_school_sports_3: 'Tôi đã xem bạn bè mình chơi.',

    event_middleschool_bookstore_trip_title: 'Lớp đi nhà sách',
    event_middleschool_bookstore_trip_desc: 'Lớp của bạn có chuyến đi đến nhà sách.',
    choice_middleschool_bookstore_trip_1: 'Mua sách giáo khoa',
    log_middleschool_bookstore_trip_1: 'Tôi đã mua những cuốn sách cần thiết cho việc học.',
    choice_middleschool_bookstore_trip_2: 'Mua truyện tranh',
    log_middleschool_bookstore_trip_2: 'Tôi đã tìm thấy vài cuốn truyện tranh mới thú vị.',
    choice_middleschool_bookstore_trip_3: 'Đi loanh quanh ngắm',
    log_middleschool_bookstore_trip_3: 'Tôi chỉ thích thú ngắm nhìn tất cả các cuốn sách.',

    event_middleschool_doing_homework_title: 'Làm bài tập về nhà',
    event_middleschool_doing_homework_desc: 'Đã đến lúc làm bài tập về nhà.',
    choice_middleschool_doing_homework_1: 'Hoàn thành đủ',
    log_middleschool_doing_homework_1: 'Tôi đã hoàn thành tất cả bài tập của mình.',
    choice_middleschool_doing_homework_2: 'Làm một nửa',
    log_middleschool_doing_homework_2: 'Tôi chỉ làm những phần dễ.',
    choice_middleschool_doing_homework_3: 'Hỏi bạn rồi chép',
    log_middleschool_doing_homework_3: 'Tôi đã chép bài của bạn tôi.',

    event_middleschool_teacher_praise_title: 'Thầy cô khen',
    event_middleschool_teacher_praise_desc: 'Giáo viên đã khen bạn.',
    choice_middleschool_teacher_praise_1: 'Cười tự hào',
    log_middleschool_teacher_praise_1: 'Thật tuyệt khi được khen.',
    choice_middleschool_teacher_praise_2: 'Ngại đỏ mặt',
    log_middleschool_teacher_praise_2: 'Tôi hơi xấu hổ vì sự chú ý.',
    choice_middleschool_teacher_praise_3: 'Giả vờ thờ ơ',
    log_middleschool_teacher_praise_3: 'Tôi đã hành động như thể đó không phải là chuyện lớn.',

    event_middleschool_teacher_criticism_title: 'Thầy cô phê bình',
    event_middleschool_teacher_criticism_desc: 'Giáo viên đã phê bình bạn.',
    choice_middleschool_teacher_criticism_1: 'Im lặng nghe',
    log_middleschool_teacher_criticism_1: 'Tôi đã im lặng nhận lời phê bình.',
    choice_middleschool_teacher_criticism_2: 'Giải thích lý do',
    log_middleschool_teacher_criticism_2: 'Tôi đã cố gắng giải thích quan điểm của mình.',
    choice_middleschool_teacher_criticism_3: 'Buồn bã suy nghĩ',
    log_middleschool_teacher_criticism_3: 'Lời phê bình khiến tôi cảm thấy buồn.',

    event_middleschool_extracurricular_activity_title: 'Tham gia ngoại khóa',
    event_middleschool_extracurricular_activity_desc: 'Bạn đang tham gia một hoạt động ngoại khóa.',
    choice_middleschool_extracurricular_activity_1: 'Nhiệt tình hoạt động',
    log_middleschool_extracurricular_activity_1: 'Tôi đã rất tích cực tham gia hoạt động.',
    choice_middleschool_extracurricular_activity_2: 'Tham gia một phần',
    log_middleschool_extracurricular_activity_2: 'Tôi chỉ tham gia những phần tôi thích.',
    choice_middleschool_extracurricular_activity_3: 'Ngồi nhìn bạn làm',
    log_middleschool_extracurricular_activity_3: 'Tôi thích quan sát hơn.',

    event_middleschool_class_picnic_title: 'Lớp đi dã ngoại',
    event_middleschool_class_picnic_desc: 'Lớp đang có một buổi dã ngoại.',
    choice_middleschool_class_picnic_1: 'Tham gia trò chơi tập thể',
    log_middleschool_class_picnic_1: 'Các trò chơi tập thể rất vui.',
    choice_middleschool_class_picnic_2: 'Ngồi ăn riêng',
    log_middleschool_class_picnic_2: 'Tôi muốn có chút thời gian yên tĩnh.',
    choice_middleschool_class_picnic_3: 'Đi tham quan chụp ảnh',
    log_middleschool_class_picnic_3: 'Tôi đã khám phá khu vực và chụp một số bức ảnh.',

    event_middleschool_helping_a_friend_title: 'Giúp bạn học',
    event_middleschool_helping_a_friend_desc: 'Một người bạn cần giúp đỡ trong học tập.',
    choice_middleschool_helping_a_friend_1: 'Giải thích cho bạn',
    log_middleschool_helping_a_friend_1: 'Tôi rất vui khi giúp bạn tôi hiểu bài.',
    choice_middleschool_helping_a_friend_2: 'Cho mượn vở',
    log_middleschool_helping_a_friend_2: 'Tôi đã cho họ mượn vở ghi chép của mình.',
    choice_middleschool_helping_a_friend_3: 'Học chung cùng nhau',
    log_middleschool_helping_a_friend_3: 'Chúng tôi đã học cùng nhau và cả hai đều học được rất nhiều.',

    event_middleschool_final_exam_day_title: 'Ngày thi cuối kỳ',
    event_middleschool_final_exam_day_desc: 'Hôm nay là ngày thi cuối kỳ.',
    choice_middleschool_final_exam_day_1: 'Ôn kỹ',
    log_middleschool_final_exam_day_1: 'Tôi cảm thấy đã chuẩn bị tốt cho kỳ thi.',
    choice_middleschool_final_exam_day_2: 'Ôn sơ sài',
    log_middleschool_final_exam_day_2: 'Tôi đã xem lại bài nhanh trước kỳ thi.',
    choice_middleschool_final_exam_day_3: 'Vừa làm vừa đoán',
    log_middleschool_final_exam_day_3: 'Tôi đã phải đoán nhiều câu hỏi.',

    event_middleschool_class_meeting_title: 'Buổi sinh hoạt lớp',
    event_middleschool_class_meeting_desc: 'Có một buổi sinh hoạt lớp.',
    choice_middleschool_class_meeting_1: 'Tham gia phát biểu',
    log_middleschool_class_meeting_1: 'Tôi đã chia sẻ suy nghĩ của mình với cả lớp.',
    choice_middleschool_class_meeting_2: 'Ngồi nghe',
    log_middleschool_class_meeting_2: 'Tôi đã lắng nghe những gì người khác nói.',
    choice_middleschool_class_meeting_3: 'Đùa với bạn',
    log_middleschool_class_meeting_3: 'Tôi đã bị phân tâm và không chú ý.',

    event_middleschool_meeting_teacher_outside_title: 'Gặp thầy cô ngoài trường',
    event_middleschool_meeting_teacher_outside_desc: 'Bạn gặp một giáo viên ở ngoài trường.',
    choice_middleschool_meeting_teacher_outside_1: 'Chào hỏi lễ phép',
    log_middleschool_meeting_teacher_outside_1: 'Tôi đã chào hỏi giáo viên một cách kính trọng.',
    choice_middleschool_meeting_teacher_outside_2: 'Cười gượng',
    log_middleschool_meeting_teacher_outside_2: 'Hơi khó xử một chút.',
    choice_middleschool_meeting_teacher_outside_3: 'Giả vờ không thấy',
    log_middleschool_meeting_teacher_outside_3: 'Tôi đã cố gắng tránh họ.',

    event_middleschool_new_student_title: 'Bạn mới chuyển đến',
    event_middleschool_new_student_desc: 'Một học sinh mới đã chuyển đến lớp bạn.',
    choice_middleschool_new_student_1: 'Chủ động làm quen',
    log_middleschool_new_student_1: 'Tôi đã tự giới thiệu và làm cho họ cảm thấy được chào đón.',
    choice_middleschool_new_student_2: 'Ngồi cùng bàn',
    log_middleschool_new_student_2: 'Chúng tôi đã ngồi cùng nhau và có một cuộc trò chuyện vui vẻ.',
    choice_middleschool_new_student_3: 'Đợi bạn tự bắt chuyện',
    log_middleschool_new_student_3: 'Tôi đã đợi họ nói chuyện với tôi trước.',

    event_middleschool_online_gaming_title: 'Chơi game trực tuyến',
    event_middleschool_online_gaming_desc: 'Bạn đang chơi game trực tuyến.',
    choice_middleschool_online_gaming_1: 'Chơi vui với bạn',
    log_middleschool_online_gaming_1: 'Chúng tôi đã có một khoảng thời gian tuyệt vời khi chơi cùng nhau trực tuyến.',
    choice_middleschool_online_gaming_2: 'Chơi quá giờ',
    log_middleschool_online_gaming_2: 'Tôi đã chơi quá lâu và cảm thấy mệt mỏi vào ngày hôm sau.',
    choice_middleschool_online_gaming_3: 'Không tham gia',
    log_middleschool_online_gaming_3: 'Tôi không hứng thú với game trực tuyến.',

    event_middleschool_sports_festival_title: 'Ngày hội thể thao',
    event_middleschool_sports_festival_desc: 'Đó là ngày hội thể thao của trường.',
    choice_middleschool_sports_festival_1: 'Thi chạy',
    log_middleschool_sports_festival_1: 'Tôi đã tham gia cuộc thi chạy.',
    choice_middleschool_sports_festival_2: 'Thi nhảy xa',
    log_middleschool_sports_festival_2: 'Tôi đã tham gia môn nhảy xa.',
    choice_middleschool_sports_festival_3: 'Làm cổ động viên',
    log_middleschool_sports_festival_3: 'Tôi đã cổ vũ cho các bạn cùng lớp.',

    event_middleschool_chemistry_experiment_title: 'Thí nghiệm hóa học',
    event_middleschool_chemistry_experiment_desc: 'Bạn đang làm một thí nghiệm hóa học.',
    choice_middleschool_chemistry_experiment_1: 'Làm theo hướng dẫn',
    log_middleschool_chemistry_experiment_1: 'Tôi đã cẩn thận làm theo các bước.',
    choice_middleschool_chemistry_experiment_2: 'Sáng tạo thêm chi tiết',
    log_middleschool_chemistry_experiment_2: 'Tôi đã thêm một vài bước bổ sung để xem điều gì sẽ xảy ra.',
    choice_middleschool_chemistry_experiment_3: 'Quan sát bạn làm',
    log_middleschool_chemistry_experiment_3: 'Tôi đã quan sát cách bạn bè tôi làm thí nghiệm.',

    event_middleschool_foreign_visitor_title: 'Lớp có khách nước ngoài',
    event_middleschool_foreign_visitor_desc: 'Có một vị khách nước ngoài trong lớp của bạn.',
    choice_middleschool_foreign_visitor_1: 'Chủ động bắt chuyện',
    log_middleschool_foreign_visitor_1: 'Tôi đã có một cuộc trò chuyện tuyệt vời với vị khách.',
    choice_middleschool_foreign_visitor_2: 'Mỉm cười chào',
    log_middleschool_foreign_visitor_2: 'Tôi đã chào đón họ một cách thân thiện.',
    choice_middleschool_foreign_visitor_3: 'Im lặng',
    log_middleschool_foreign_visitor_3: 'Tôi quá nhút nhát để nói chuyện với họ.',

    event_middleschool_art_class_title: 'Giờ nghệ thuật',
    event_middleschool_art_class_desc: 'Đến giờ học nghệ thuật.',
    choice_middleschool_art_class_1: 'Vẽ theo bài',
    log_middleschool_art_class_1: 'Tôi đã làm theo bài tập để vẽ.',
    choice_middleschool_art_class_2: 'Vẽ sáng tạo',
    log_middleschool_art_class_2: 'Tôi đã vẽ một cái gì đó từ trí tưởng tượng của mình.',
    choice_middleschool_art_class_3: 'Ngồi nhìn',
    log_middleschool_art_class_3: 'Hôm nay tôi không có tâm trạng để vẽ.',

    event_middleschool_exam_results_title: 'Nhận kết quả thi',
    event_middleschool_exam_results_desc: 'Bạn đã nhận được kết quả thi của mình.',
    choice_middleschool_exam_results_1: 'Vui mừng khoe bạn',
    log_middleschool_exam_results_1: 'Tôi rất vui với kết quả của mình và đã chia sẻ với bạn bè.',
    choice_middleschool_exam_results_2: 'Giữ im lặng',
    log_middleschool_exam_results_2: 'Tôi đã giữ kết quả cho riêng mình.',
    choice_middleschool_exam_results_3: 'Buồn bã',
    log_middleschool_exam_results_3: 'Tôi thất vọng với kết quả của mình.',

    event_middleschool_sharing_lunch_title: 'Chia sẻ đồ ăn trưa',
        event_middleschool_sharing_lunch_desc: 'Bạn đang chia sẻ bữa trưa với bạn bè.',
    choice_middleschool_sharing_lunch_1: 'Cho bạn một phần',
    log_middleschool_sharing_lunch_1: 'Tôi đã chia sẻ một phần thức ăn của mình với bạn.',
    choice_middleschool_sharing_lunch_2: 'Đổi món ăn',
    log_middleschool_sharing_lunch_2: 'Chúng tôi đã trao đổi một số món ăn của mình.',
    choice_middleschool_sharing_lunch_3: 'Giữ phần mình',
    log_middleschool_sharing_lunch_3: 'Hôm nay tôi thực sự rất đói.',

        // New Clubs
    club_science_name: 'Câu lạc bộ Khoa học',
    club_science_description: 'Khám phá thế giới khoa học và thực hiện các thí nghiệm thú vị. Dành cho các nhà khoa học tương lai.',
    club_art_name: 'Câu lạc bộ Nghệ thuật',
    club_art_description: 'Phát triển khả năng sáng tạo và thể hiện bản thân thông qua các loại hình nghệ thuật khác nhau. Dành cho các nghệ sĩ tương lai.',
    club_sports_name: 'Câu lạc bộ Thể thao',
    club_sports_description: 'Rèn luyện thể chất và tinh thần đồng đội thông qua các hoạt động thể thao. Dành cho các vận động viên tương lai.',
    club_debate_name: 'Câu lạc bộ Tranh biện',
    club_debate_description: 'Nâng cao kỹ năng tư duy phản biện và hùng biện. Dành cho các nhà lãnh đạo và luật sư tương lai.',
    club_robotics_name: 'Câu lạc bộ Robotics',
    club_robotics_description: 'Thiết kế, xây dựng và lập trình robot. Dành cho các kỹ sư và nhà phát minh tương lai.',
    club_music_name: 'Câu lạc bộ Âm nhạc',
    club_music_description: 'Khám phá thế giới âm nhạc, học chơi nhạc cụ và biểu diễn. Dành cho các nhạc sĩ tương lai.',
    club_cooking_name: 'Câu lạc bộ Nấu ăn',
    club_cooking_description: 'Học các kỹ năng nấu nướng và khám phá ẩm thực. Dành cho các đầu bếp tương lai.',
    club_coding_name: 'Câu lạc bộ Lập trình',
    club_coding_description: 'Học cách viết mã và phát triển phần mềm. Dành cho các lập trình viên tương lai.',
    club_photography_name: 'Câu lạc bộ Nhiếp ảnh',
    club_photography_description: 'Nắm bắt khoảnh khắc và kể chuyện qua ống kính. Dành cho các nhiếp ảnh gia tương lai.',
    club_writing_name: 'Câu lạc bộ Viết lách',
    club_writing_description: 'Phát triển kỹ năng viết và thể hiện ý tưởng qua văn bản. Dành cho các nhà văn và nhà báo tương lai.',
    club_entrepreneurship_name: 'Câu lạc bộ Doanh nhân',
    club_entrepreneurship_description: 'Học những điều cơ bản về kinh doanh, tài chính và lãnh đạo. Dành cho các CEO tương lai.',
    club_model_un_name: 'Câu lạc bộ Giả lập Liên Hợp Quốc (Model UN)',
    club_model_un_description: 'Tranh luận về các vấn đề toàn cầu và tìm hiểu về quan hệ quốc tế. Dành cho các nhà ngoại giao tương lai.',
    club_environmental_name: 'Câu lạc bộ Môi trường',
    club_environmental_description: 'Hành động vì các vấn đề môi trường và thúc đẩy sự bền vững. Dành cho các nhà khoa học và nhà hoạt động tương lai.',
    club_volunteering_name: 'Câu lạc bộ Tình nguyện',
    club_volunteering_description: 'Đóng góp cho cộng đồng và giúp đỡ những người gặp khó khăn. Dành cho những người làm công tác xã hội và nhân đạo tương lai.',
    club_chess_name: 'Câu lạc bộ Cờ vua',
    club_chess_description: 'Rèn luyện trí tuệ và làm chủ nghệ thuật chiến lược. Dành cho các kiện tướng tương lai trong mọi lĩnh vực.',
    club_film_media_name: 'Câu lạc bộ Phim & Truyền thông',
    club_film_media_description: 'Khám phá thế giới làm phim, từ viết kịch bản đến sản xuất. Dành cho những người kể chuyện tương lai.',
    club_medical_name: 'Câu lạc bộ Y khoa Tương lai',
    club_medical_description: 'Có một khởi đầu thuận lợi cho sự nghiệp trong ngành y. Dành cho các bác sĩ và y tá tương lai.',
    club_astronomy_name: 'Câu lạc bộ Thiên văn học',
    club_astronomy_description: 'Khám phá vũ trụ, từ các hành tinh đến các thiên hà xa xôi. Dành cho các nhà thiên văn học và kỹ sư tương lai.',
    club_literary_magazine_name: 'Câu lạc bộ Tạp chí Văn học',
    club_literary_magazine_description: 'Tạo và xuất bản tạp chí văn học của trường. Dành cho các nhà văn và biên tập viên tương lai.',
    club_architecture_engineering_name: 'Câu lạc bộ Kiến trúc & Kỹ thuật',
    club_architecture_engineering_description: 'Thiết kế và xây dựng các công trình tuyệt vời. Dành cho các kiến trúc sư và kỹ sư tương lai.',

    // New Events
    event_business_pitch_title: 'Cuộc thi Trình bày Ý tưởng Kinh doanh',
    event_business_pitch_description: 'Câu lạc bộ Doanh nhân đang tổ chức một cuộc thi trình bày ý tưởng kinh doanh. Đây là cơ hội để bạn tỏa sáng!',
    event_business_pitch_choice1: 'Trình bày ý tưởng sáng tạo của bạn.',
    event_business_pitch_choice1_log: 'Bài trình bày của tôi đã thành công rực rỡ! Tôi nghĩ mình có tương lai trong lĩnh vực kinh doanh.',
    event_business_pitch_choice2: 'Giúp một người bạn với bài thuyết trình của họ.',
    event_business_pitch_choice2_log: 'Tôi đã giúp bạn tôi và họ đã làm rất tốt. Làm việc nhóm tạo nên thành công!',

    event_model_un_title: 'Hội nghị Model UN',
    event_model_un_description: 'Câu lạc bộ Model UN đang tham dự một hội nghị khu vực. Đã đến lúc đại diện cho trường chúng ta.',
    event_model_un_choice1: 'Dẫn đầu trong cuộc tranh luận.',
    event_model_un_choice1_log: 'Tôi đã tranh luận sôi nổi về nghị quyết của chúng tôi và đã giành được một giải thưởng!',
    event_model_un_choice2: 'Tập trung vào việc kết nối với các đại biểu khác.',
    event_model_un_choice2_log: 'Tôi đã tạo được một số mối quan hệ tuyệt vời với các sinh viên từ các trường khác.',

    event_community_cleanup_title: 'Sáng kiến Dọn dẹp Cộng đồng',
    event_community_cleanup_description: 'Câu lạc bộ Môi trường đang tổ chức một ngày dọn dẹp cộng đồng.',
    event_community_cleanup_choice1: 'Tuyển tình nguyện viên và dẫn dắt một đội.',
    event_community_cleanup_choice1_log: 'Chúng tôi đã thu gom được rất nhiều rác! Thật tuyệt khi tạo ra sự khác biệt.',
    event_community_cleanup_choice2: 'Lặng lẽ làm việc một mình.',
    event_community_cleanup_choice2_log: 'Tôi tập trung vào việc dọn dẹp khu vực được giao và đã hoàn thành công việc một cách kỹ lưỡng.',

    event_charity_fundraiser_title: 'Gala Gây quỹ Từ thiện',
    event_charity_fundraiser_description: 'Câu lạc bộ Tình nguyện đang tổ chức một buổi gây quỹ cho một tổ chức từ thiện địa phương.',
    event_charity_fundraiser_choice1: 'Tổ chức hậu cần cho sự kiện.',
    event_charity_fundraiser_choice1_log: 'Sự kiện đã diễn ra suôn sẻ! Chúng tôi đã quyên góp được rất nhiều tiền cho một mục đích tốt đẹp.',
    event_charity_fundraiser_choice2: 'Quyên góp một phần lớn tiền tiêu vặt của bạn.',
    event_charity_fundraiser_choice2_log: 'Đó là một sự hy sinh lớn, nhưng nó xứng đáng để giúp đỡ người khác.',

    event_chess_tournament_title: 'Giải Cờ vua Quốc gia',
    event_chess_tournament_description: 'Câu lạc bộ Cờ vua đang thi đấu trong giải đấu quốc gia.',
    event_chess_tournament_choice1: 'Thực hiện một chiến lược xuất sắc.',
    event_chess_tournament_choice1_log: 'Chiếu tướng! Tôi đã thắng giải đấu bằng một nước thí hậu táo bạo.',
    event_chess_tournament_choice2: 'Chơi an toàn và nhắm đến một trận hòa.',
    event_chess_tournament_choice2_log: 'Tôi đã chơi một cách thận trọng và đã có được một trận hòa đáng nể trước một đối thủ khó chơi.',

    event_film_festival_title: 'Liên hoan phim ngắn',
    event_film_festival_description: 'Câu lạc bộ Phim & Truyền thông đang tổ chức liên hoan phim ngắn đầu tiên.',
    event_film_festival_choice1: 'Gửi bộ phim của riêng bạn.',
    event_film_festival_choice1_log: 'Bộ phim của tôi đã giành được giải khán giả bình chọn! Tôi rất tự hào về tác phẩm của mình.',
    event_film_festival_choice2: 'Giúp tổ chức sự kiện.',
    event_film_festival_choice2_log: 'Tôi đã giúp chạy máy chiếu và mọi thứ diễn ra suôn sẻ. Thật vui khi được ở phía sau hậu trường.',

    event_first_aid_title: 'Chương trình Chứng nhận Sơ cứu/CPR',
    event_first_aid_description: 'Câu lạc bộ Y khoa Tương lai đang cung cấp một khóa học chứng nhận sơ cứu.',
    event_first_aid_choice1: 'Nắm vững các kỹ thuật và dạy cho người khác.',
    event_first_aid_choice1_log: 'Bây giờ tôi đã được chứng nhận về CPR và sơ cứu! Tôi thậm chí còn giúp dạy một số bạn cùng lớp.',
    event_first_aid_choice2: 'Chỉ cần lấy chứng nhận.',
    event_first_aid_choice2_log: 'Tôi đã vượt qua khóa học và nhận được chứng chỉ của mình. Đó là một kỹ năng quý giá.',

    event_stargazing_title: 'Đêm ngắm sao & Chế tạo Kính thiên văn',
    event_stargazing_description: 'Câu lạc bộ Thiên văn học đang tổ chức một đêm ngắm sao.',
    event_stargazing_choice1: 'Chế tạo một chiếc kính thiên văn mạnh mẽ.',
    event_stargazing_choice1_log: 'Tôi đã tự chế tạo kính thiên văn của mình và nhìn thấy vành đai của sao Thổ! Thật không thể tin được.',
    event_stargazing_choice2: 'Chỉ cần tận hưởng khung cảnh.',
    event_stargazing_choice2_log: 'Tôi ngả lưng và ngắm các vì sao. Đó là một đêm đẹp và yên bình.',

    event_literary_journal_title: 'Ra mắt Tạp chí Văn học của Trường',
    event_literary_journal_description: 'Câu lạc bộ Tạp chí Văn học đang ra mắt số đầu tiên của tạp chí trường.',
    event_literary_journal_choice1: 'Đọc to bài thơ của bạn tại bữa tiệc ra mắt.',
    event_literary_journal_choice1_log: 'Tôi đã lo lắng, nhưng mọi người đều yêu thích bài thơ của tôi! Đó là một trải nghiệm tuyệt vời.',
    event_literary_journal_choice2: 'Làm biên tập viên cho tạp chí.',
    event_literary_journal_choice2_log: 'Tôi đã làm việc chăm chỉ để biên tập tất cả các bài gửi. Tạp chí cuối cùng trông thật tuyệt vời.',

    event_bridge_building_title: 'Cuộc thi Xây cầu',
    event_bridge_building_description: 'Câu lạc bộ Kiến trúc & Kỹ thuật đang tổ chức một cuộc thi xây cầu.',
    event_bridge_building_choice1: 'Thiết kế một cây cầu sáng tạo và chắc chắn.',
    event_bridge_building_choice1_log: 'Cây cầu của tôi đã chịu được trọng lượng lớn nhất! Thiết kế của tôi đã thành công.',
    event_bridge_building_choice2: 'Tập trung vào tính thẩm mỹ của cây cầu.',
    event_bridge_building_choice2_log: 'Cây cầu của tôi có thể không phải là mạnh nhất, nhưng nó chắc chắn là cây cầu đẹp nhất.',
};