export default {
    // Main Events
    event_newborn_first_night_crying_title: 'Đêm đầu tiên đầy thử thách',
    event_newborn_first_night_crying_desc: 'Tiếng khóc xé lòng của đứa bé sơ sinh vang vọng khắp căn nhà trong đêm đầu tiên. Bạn đã kiệt sức, nhưng bé vẫn không ngừng quấy khóc. Mỗi lựa chọn lúc này đều có thể ảnh hưởng đến tương lai của bé và sự bình yên của gia đình.',
    choice_newborn_first_night_crying_1: 'Dành trọn đêm ôm ấp, vỗ về bé',
    log_newborn_first_night_crying_1: 'Sự kiên nhẫn và tình yêu thương của bạn đã xoa dịu bé, nhưng bạn và đối tác sẽ phải đối mặt với một ngày dài mệt mỏi.',
    choice_newborn_first_night_crying_2: 'Thử cho bé bú thêm, hy vọng bé sẽ no và ngủ',
    log_newborn_first_night_crying_2: 'Bé có vẻ đã no và ngủ thiếp đi, nhưng việc cho ăn không đúng cữ có thể ảnh hưởng đến lịch sinh hoạt sau này.',
    choice_newborn_first_night_crying_3: 'Đặt bé vào nôi, bật tiếng ồn trắng và cố gắng nghỉ ngơi',
    log_newborn_first_night_crying_3: 'Tiếng ồn trắng có vẻ hiệu quả, bé dần chìm vào giấc ngủ. Tuy nhiên, bạn cảm thấy hơi tội lỗi vì không thể ở bên bé lúc này.',

    event_newborn_first_bath_title: 'Tắm lần đầu',
    event_newborn_first_bath_desc: 'Đã đến lúc cho bé tắm lần đầu tiên. Đây có thể là một trải nghiệm đáng sợ hoặc thú vị.',
    choice_newborn_first_bath_1: 'Vừa tắm vừa hát/làm trò',
    log_newborn_first_bath_1: 'Bé tỏ ra thích thú và vui vẻ nghịch nước.',
    choice_newborn_first_bath_2: 'Tắm thật nhanh cho bé đỡ sợ',
    log_newborn_first_bath_2: 'Việc tắm nhanh khiến bé hơi hoảng sợ và khóc.',
    choice_newborn_first_bath_3: 'Cho bé nghịch đồ chơi trong chậu',
    log_newborn_first_bath_3: 'Đồ chơi đã thu hút sự chú ý của bé, giúp buổi tắm diễn ra suôn sẻ.',

    event_newborn_vaccination_title: 'Tiêm chủng định kỳ',
    event_newborn_vaccination_desc: 'Đã đến lúc đưa bé đi tiêm phòng. Bé có vẻ hơi lo lắng khi thấy kim tiêm.',
    choice_newborn_vaccination_1: 'Dỗ bé bằng kẹo mút/đồ chơi sau tiêm',
    log_newborn_vaccination_1: 'Bé nín khóc ngay khi thấy món đồ chơi yêu thích.',
    choice_newborn_vaccination_2: 'Cho bé ngồi trong lòng bố mẹ',
    log_newborn_vaccination_2: 'Cảm giác an toàn trong vòng tay bố mẹ giúp bé dũng cảm hơn.',
    choice_newborn_vaccination_3: 'Để bé xem bạn khác tiêm trước',
    log_newborn_vaccination_3: 'Xem bạn khác tiêm dường như khiến bé càng sợ hãi hơn.',

    event_newborn_learning_to_roll_over_title: 'Tập lẫy',
    event_newborn_learning_to_roll_over_desc: 'Bé đang cố gắng lật người lần đầu tiên, một cột mốc quan trọng.',
    choice_newborn_learning_to_roll_over_1: 'Cổ vũ và quay video lại',
    log_newborn_learning_to_roll_over_1: 'Sự cổ vũ của gia đình đã tiếp thêm động lực cho bé.',
    choice_newborn_learning_to_roll_over_2: 'Đặt đồ chơi trước mặt làm động lực',
    log_newborn_learning_to_roll_over_2: 'Vì muốn với lấy đồ chơi, bé đã nỗ lực và lẫy thành công.',
    choice_newborn_learning_to_roll_over_3: 'Giúp bé xoay người nhẹ nhàng',
    log_newborn_learning_to_roll_over_3: 'Sự trợ giúp nhỏ đã giúp bé hiểu cách xoay người.',

    event_newborn_learning_to_crawl_title: 'Tập bò',
    event_newborn_learning_to_crawl_desc: 'Sau khi biết lẫy, bé bắt đầu có hứng thú với việc di chuyển và khám phá.',
    choice_newborn_learning_to_crawl_1: 'Dọn đồ chơi rải đường cho bé bò theo',
    log_newborn_learning_to_crawl_1: 'Bé thích thú bò theo con đường đồ chơi đầy màu sắc.',
    choice_newborn_learning_to_crawl_2: 'Cho bé bò tới bố mẹ dang tay đón',
    log_newborn_learning_to_crawl_2: 'Nhìn thấy bố mẹ, bé vui vẻ bò nhanh hết sức có thể.',
    choice_newborn_learning_to_crawl_3: 'Để bé tự do khám phá quanh phòng',
    log_newborn_learning_to_crawl_3: 'Bé tò mò khám phá mọi ngóc ngách trong phòng.',

    event_newborn_first_steps_title: 'Tập đi những bước đầu',
    event_newborn_first_steps_desc: 'Bé đang vịn vào đồ đạc để cố gắng đứng dậy và đi những bước chập chững đầu tiên.',
    choice_newborn_first_steps_1: 'Đỡ bé bằng cả hai tay',
    log_newborn_first_steps_1: 'Bé cảm thấy an toàn và tự tin đi từng bước khi có bố mẹ đỡ.',
    choice_newborn_first_steps_2: 'Để bé tự đứng lên rồi đi vài bước',
    log_newborn_first_steps_2: 'Bé rất kiên cường, ngã rồi lại tự đứng dậy.',
    choice_newborn_first_steps_3: 'Cho bé vịn xe tập đi',
    log_newborn_first_steps_3: 'Chiếc xe tập đi là một công cụ hỗ trợ tuyệt vời cho bé.',

    event_newborn_first_day_daycare_title: 'Ngày đầu gửi nhà trẻ',
    event_newborn_first_day_daycare_desc: 'Đây là lần đầu tiên bé phải xa bố mẹ và ở một môi trường mới.',
    choice_newborn_first_day_daycare_1: 'Ôm bé thật lâu rồi mới đi',
    log_newborn_first_day_daycare_1: 'Cuộc chia tay bịn rịn khiến cả hai đều buồn.',
    choice_newborn_first_day_daycare_2: 'Dặn dò ngắn gọn rồi rời nhanh',
    log_newborn_first_day_daycare_2: 'Việc rời đi nhanh chóng giúp bé dễ dàng hòa nhập hơn.',
    choice_newborn_first_day_daycare_3: 'Nhờ cô giáo đưa bé đi tham quan lớp',
    log_newborn_first_day_daycare_3: 'Bé bị thu hút bởi những thứ mới lạ và nhanh chóng quên đi nỗi buồn.',

    event_newborn_first_self_feeding_title: 'Bữa ăn đầu tự xúc',
    event_newborn_first_self_feeding_desc: 'Bé muốn tự mình xúc ăn, một kỹ năng quan trọng cần học.',
    choice_newborn_first_self_feeding_1: 'Chuẩn bị bát chống đổ và thìa nhỏ',
    log_newborn_first_self_feeding_1: 'Những dụng cụ phù hợp giúp bé học cách tự ăn dễ dàng hơn.',
    choice_newborn_first_self_feeding_2: 'Để bé thử thoải mái, không can thiệp nhiều',
    log_newborn_first_self_feeding_2: 'Mặc dù hơi bừa bộn, bé đã rất vui khi được tự do khám phá.',
    choice_newborn_first_self_feeding_3: 'Ngồi ăn cùng để bé bắt chước',
    log_newborn_first_self_feeding_3: 'Bé học rất nhanh bằng cách quan sát và bắt chước người lớn.',

    event_newborn_snatching_toys_title: 'Giờ chơi chung giật đồ chơi',
    event_newborn_snatching_toys_desc: 'Trong giờ chơi, bé và một bạn khác cùng muốn một món đồ chơi.',
    choice_newborn_snatching_toys_1: 'Hướng dẫn bé đổi món khác với bạn',
    log_newborn_snatching_toys_1: 'Bé đã học được cách đàm phán và chia sẻ.',
    choice_newborn_snatching_toys_2: 'Nhắc bé nói “cho con mượn”',
    log_newborn_snatching_toys_2: 'Lời nói lịch sự không hiệu quả, bé vẫn không có được món đồ chơi.',
    choice_newborn_snatching_toys_3: 'Tách ra chơi riêng một lúc',
    log_newborn_snatching_toys_3: 'Cả hai bé đều không vui và bắt đầu ăn vạ.',

    event_newborn_lost_in_store_title: 'Lạc mẹ ở siêu thị',
    event_newborn_lost_in_store_desc: 'Trong một khoảnh khắc lơ đãng, bé nhận ra mình không thấy mẹ đâu.',
    choice_newborn_lost_in_store_1: 'Bé đứng yên tại chỗ chờ',
    log_newborn_lost_in_store_1: 'Nhờ đứng yên, mẹ đã nhanh chóng tìm thấy bé.',
    choice_newborn_lost_in_store_2: 'Bé đi tìm mẹ theo hướng đã đi',
    log_newborn_lost_in_store_2: 'Bé càng đi càng lạc và bắt đầu hoảng sợ.',
    choice_newborn_lost_in_store_3: 'Bé chạy đến gần chú bảo vệ',
    log_newborn_lost_in_store_3: 'Hành động thông minh của bé đã giúp giải quyết tình hình nhanh chóng.',

    // Triggered Events
    event_newborn_parents_sleepless_title: 'Bố mẹ mất ngủ',
    event_newborn_parents_sleepless_desc: 'Vì chăm sóc con đêm qua, cả hai vợ chồng đều thiếu ngủ và mệt mỏi.',
    choice_newborn_parents_sleepless_1: 'Thay phiên nhau trực đêm',
    log_newborn_parents_sleepless_1: 'Chúng tôi quyết định thay phiên nhau để cả hai đều được nghỉ ngơi.',
    choice_newborn_parents_sleepless_2: 'Dùng tiếng ồn trắng để ru',
    log_newborn_parents_sleepless_2: 'Tiếng ồn trắng đã giúp cả nhà có một giấc ngủ ngon hơn.',
    choice_newborn_parents_sleepless_3: 'Nhờ ông bà hỗ trợ chăm bé',
    log_newborn_parents_sleepless_3: 'Sự giúp đỡ của ông bà thật vô giá.',

    event_newborn_fear_of_bathing_title: 'Bé sợ tắm',
    event_newborn_fear_of_bathing_desc: 'Sau lần tắm đầu tiên, bé tỏ ra sợ hãi mỗi khi đến giờ tắm.',
    choice_newborn_fear_of_bathing_1: 'Dùng ghế tắm kèm đồ chơi nổi',
    log_newborn_fear_of_bathing_1: 'Đồ chơi đã biến giờ tắm thành giờ chơi vui vẻ.',
    choice_newborn_fear_of_bathing_2: 'Cho bé ngồi tắm chung với anh/chị',
    log_newborn_fear_of_bathing_2: 'Tắm cùng anh/chị giúp bé cảm thấy an toàn và bớt sợ hơn.',
    choice_newborn_fear_of_bathing_3: 'Tắm nhanh và lau người bằng khăn ấm',
    log_newborn_fear_of_bathing_3: 'Dù nhanh, bé vẫn khóc trong suốt quá trình tắm.',

    event_newborn_fever_after_shot_title: 'Sốt sau tiêm',
    event_newborn_fever_after_shot_desc: 'Bé bị sốt nhẹ sau khi tiêm chủng, một phản ứng phụ thường gặp.',
    choice_newborn_fever_after_shot_1: 'Cho uống hạ sốt theo hướng dẫn',
    log_newborn_fever_after_shot_1: 'Thuốc hạ sốt đã phát huy tác dụng và bé cảm thấy dễ chịu hơn.',
    choice_newborn_fever_after_shot_2: 'Chườm ấm và theo dõi thêm',
    log_newborn_fever_after_shot_2: 'Phương pháp chườm ấm tự nhiên đã giúp bé hạ sốt từ từ.',
    choice_newborn_fever_after_shot_3: 'Gọi điện hỏi bác sĩ trước khi tái khám',
    log_newborn_fever_after_shot_3: 'Lời khuyên của bác sĩ giúp chúng tôi yên tâm hơn và chăm sóc bé đúng cách.',

    event_newborn_minor_scratch_title: 'Trầy xước nhẹ',
    event_newborn_minor_scratch_desc: 'Trong lúc tập lẫy, bé vô tình bị trầy xước nhẹ.',
    choice_newborn_minor_scratch_1: 'Rửa sạch bằng nước muối sinh lý',
    log_newborn_minor_scratch_1: 'Vết thương được làm sạch cẩn thận để tránh nhiễm trùng.',
    choice_newborn_minor_scratch_2: 'Dán băng nhỏ và vỗ về bé',
    log_newborn_minor_scratch_2: 'Một chiếc băng cá nhân xinh xắn và lời dỗ dành đã làm bé nín khóc.',
    choice_newborn_minor_scratch_3: 'Ngừng cho bé vận động mạnh hôm đó',
    log_newborn_minor_scratch_3: 'Bé cần nghỉ ngơi để vết thương mau lành.',

    event_newborn_parents_baby_proofing_title: 'Bố mẹ che chắn ổ điện',
    event_newborn_parents_baby_proofing_desc: 'Khi bé bắt đầu bò, các ổ điện trở thành mối nguy hiểm tiềm tàng.',
    choice_newborn_parents_baby_proofing_1: 'Dán nắp nhựa an toàn',
    log_newborn_parents_baby_proofing_1: 'Ngôi nhà đã trở nên an toàn hơn cho bé.',
    choice_newborn_parents_baby_proofing_2: 'Kê đồ chắn phía trước',
    log_newborn_parents_baby_proofing_2: 'Đây là một giải pháp tạm thời nhưng hiệu quả.',
    choice_newborn_parents_baby_proofing_3: 'Dạy bé “không chạm vào ổ điện”',
    log_newborn_parents_baby_proofing_3: 'Bé có vẻ hiểu, nhưng việc giám sát vẫn là cần thiết.',

    event_newborn_scraped_knee_title: 'Trầy đầu gối khi tập đi',
    event_newborn_scraped_knee_desc: 'Bé bị ngã và trầy đầu gối trong những nỗ lực tập đi đầu tiên.',
    choice_newborn_scraped_knee_1: 'Rửa sạch và băng vết thương nhỏ',
    log_newborn_scraped_knee_1: 'Vết thương nhỏ không thể ngăn cản bước chân của bé.',
    choice_newborn_scraped_knee_2: 'Cho bé mang tất chống trượt',
    log_newborn_scraped_knee_2: 'Đôi tất mới giúp bé đứng vững hơn.',
    choice_newborn_scraped_knee_3: 'Chỉ tập trên thảm mềm',
    log_newborn_scraped_knee_3: 'Tập đi trên thảm giúp giảm thiểu chấn thương khi ngã.',

    event_newborn_teacher_comforts_title: 'Cần cô giáo trấn an',
    event_newborn_teacher_comforts_desc: 'Bé vẫn còn khóc và không chịu vào lớp.',
    choice_newborn_teacher_comforts_1: 'Ôm bé dỗ dành',
    log_newborn_teacher_comforts_1: 'Sự dịu dàng của cô giáo đã giúp bé bình tĩnh lại.',
    choice_newborn_teacher_comforts_2: 'Dẫn bé đi tham quan lớp',
    log_newborn_teacher_comforts_2: 'Bé bị thu hút bởi đồ chơi và quên mất nỗi buồn.',
    choice_newborn_teacher_comforts_3: 'Cho bé mang gấu bông quen thuộc',
    log_newborn_teacher_comforts_3: 'Người bạn thân quen giúp bé cảm thấy an tâm hơn ở môi trường mới.',

    event_newborn_food_mess_title: 'Lau dọn & thay đồ',
    event_newborn_food_mess_desc: 'Bữa ăn tự xúc đầu tiên kết thúc với một bãi chiến trường.',
    choice_newborn_food_mess_1: 'Giúp bé xúc lại từ đầu',
    log_newborn_food_mess_1: 'Lần này, bé đã ăn gọn gàng hơn với sự giúp đỡ.',
    choice_newborn_food_mess_2: 'Dùng bát chống đổ và thìa nhỏ',
    log_newborn_food_mess_2: 'Dụng cụ phù hợp đã tạo ra sự khác biệt lớn.',
    choice_newborn_food_mess_3: 'Chuyển sang finger food dễ cầm',
    log_newborn_food_mess_3: 'Bé rất thích thú với việc tự cầm thức ăn.',

    event_newborn_parental_intervention_title: 'Cô/ba mẹ can thiệp',
    event_newborn_parental_intervention_desc: 'Cuộc tranh giành đồ chơi trở nên căng thẳng và cần sự can thiệp của người lớn.',
    choice_newborn_parental_intervention_1: 'Nhắc bé đợi lượt bằng lời nhẹ nhàng',
    log_newborn_parental_intervention_1: 'Lời khuyên nhẹ nhàng giúp bé hiểu ra vấn đề.',
    choice_newborn_parental_intervention_2: 'Tách hai bé ra một lúc',
    log_newborn_parental_intervention_2: 'Một khoảng lặng ngắn giúp cả hai bình tĩnh lại.',
    choice_newborn_parental_intervention_3: 'Khen khi bé chịu chờ',
    log_newborn_parental_intervention_3: 'Lời khen đã khuyến khích hành vi tốt của bé.',

    event_newborn_staff_assistance_title: 'Nhân viên hỗ trợ loa gọi',
    event_newborn_staff_assistance_desc: 'Nhờ sự giúp đỡ của nhân viên siêu thị, mẹ đã được thông báo qua loa.',
    choice_newborn_staff_assistance_1: 'Bé chạy đến ôm mẹ khi gặp lại',
    log_newborn_staff_assistance_1: 'Cuộc đoàn tụ thật xúc động.',
    choice_newborn_staff_assistance_2: 'Nhân viên nhắc quy tắc đứng yên – gọi người lớn',
    log_newborn_staff_assistance_2: 'Bé đã học được một bài học an toàn quan trọng.',
    choice_newborn_staff_assistance_3: 'Mẹ quyết định đeo vòng tên cho bé',
    log_newborn_staff_assistance_3: 'Một biện pháp phòng ngừa đơn giản nhưng hiệu quả.',

    // Independent Events
    event_newborn_off_nap_schedule_title: 'Ngủ trưa lệch nhịp',
    event_newborn_off_nap_schedule_desc: 'Giấc ngủ trưa của bé bị xáo trộn, ảnh hưởng đến lịch sinh hoạt của cả nhà.',
    choice_newborn_off_nap_schedule_1: 'Đưa về giờ ngủ cố định',
    log_newborn_off_nap_schedule_1: 'Sự kiên trì đã giúp bé quay lại nếp ngủ cũ.',
    choice_newborn_off_nap_schedule_2: 'Cho ngủ trên xe đẩy khi ra ngoài',
    log_newborn_off_nap_schedule_2: 'Bé dễ dàng ngủ thiếp đi khi được đẩy đi dạo.',
    choice_newborn_off_nap_schedule_3: 'Bỏ giấc trưa, đi ngủ sớm hơn',
    log_newborn_off_nap_schedule_3: 'Bé có vẻ cáu kỉnh vào cuối ngày vì thiếu ngủ.',

    event_newborn_first_tooth_title: 'Mọc răng đầu tiên',
    event_newborn_first_tooth_desc: 'Chiếc răng sữa đầu tiên đang nhú lên, khiến bé khó chịu và quấy khóc.',
    choice_newborn_first_tooth_1: 'Cho gặm vòng ngậm nướu',
    log_newborn_first_tooth_1: 'Vòng ngậm nướu mát lạnh giúp bé giảm đau hiệu quả.',
    choice_newborn_first_tooth_2: 'Massage nướu bằng khăn sạch',
    log_newborn_first_tooth_2: 'Sự tiếp xúc nhẹ nhàng giúp bé cảm thấy dễ chịu hơn.',
    choice_newborn_first_tooth_3: 'Dùng thức ăn mát (chuối nghiền lạnh)',
    log_newborn_first_tooth_3: 'Đồ ăn mát không chỉ ngon mà còn giúp làm dịu nướu.',

    event_newborn_stroller_in_park_title: 'Lần đầu đi xe đẩy ra công viên',
    event_newborn_stroller_in_park_desc: 'Bé được bố mẹ đẩy xe đi dạo và khám phá thế giới bên ngoài.',
    choice_newborn_stroller_in_park_1: 'Ngủ ngon lành trên xe',
    log_newborn_stroller_in_park_1: 'Không khí trong lành và sự rung lắc nhẹ nhàng khiến bé ngủ ngon.',
    choice_newborn_stroller_in_park_2: 'Chỉ tay gọi “chó/chim”',
    log_newborn_stroller_in_park_2: 'Bé rất tò mò và hào hứng với mọi thứ xung quanh.',
    choice_newborn_stroller_in_park_3: 'Đòi xuống tự đi',
    log_newborn_stroller_in_park_3: 'Bé muốn tự mình khám phá thế giới.',

    event_newborn_first_haircut_title: 'Lần đầu cắt tóc',
    event_newborn_first_haircut_desc: 'Mái tóc đầu tiên của bé đã dài và cần được cắt tỉa.',
    choice_newborn_first_haircut_1: 'Ngồi ghế chơi đồ chơi trong khi cắt',
    log_newborn_first_haircut_1: 'Bé mải mê chơi đến mức không nhận ra mình đang được cắt tóc.',
    choice_newborn_first_haircut_2: 'Khóc sợ tiếng tông-đơ',
    log_newborn_first_haircut_2: 'Tiếng ồn của tông-đơ làm bé sợ hãi.',
    choice_newborn_first_haircut_3: 'Ngồi trong lòng bố mẹ để cắt',
    log_newborn_first_haircut_3: 'Cảm giác an toàn khi ở trong lòng bố mẹ giúp bé yên tâm hơn.',

    event_newborn_learning_to_talk_title: 'Học nói những từ đầu tiên',
    event_newborn_learning_to_talk_desc: 'Bé đang bập bẹ và cố gắng bắt chước âm thanh của người lớn.',
    choice_newborn_learning_to_talk_1: 'Gọi “ba/mẹ”',
    log_newborn_learning_to_talk_1: 'Khoảnh khắc nghe bé gọi tiếng "ba/mẹ" đầu tiên thật thiêng liêng.',
    choice_newborn_learning_to_talk_2: 'Chỉ đồ vật và bắt chước theo',
    log_newborn_learning_to_talk_2: 'Khả năng học hỏi của bé thật đáng kinh ngạc.',
    choice_newborn_learning_to_talk_3: 'Nói lặp đi lặp lại từ chưa rõ nghĩa',
    log_newborn_learning_to_talk_3: 'Thật thú vị khi cố gắng đoán xem bé đang muốn nói gì.',

    event_newborn_bedtime_story_title: 'Đọc truyện trước giờ ngủ',
    event_newborn_bedtime_story_desc: 'Đọc truyện là một thói quen tuyệt vời để giúp bé đi vào giấc ngủ.',
    choice_newborn_bedtime_story_1: 'Nghe chăm chú và bình luận',
    log_newborn_bedtime_story_1: 'Bé bị cuốn hút vào câu chuyện và trí tưởng tượng bay xa.',
    choice_newborn_bedtime_story_2: 'Giở trang liên tục vì tò mò',
    log_newborn_bedtime_story_2: 'Bé tò mò về những hình ảnh hơn là câu chuyện.',
    choice_newborn_bedtime_story_3: 'Ngủ gục giữa chừng',
    log_newborn_bedtime_story_3: 'Giọng đọc ấm áp đã ru bé vào giấc ngủ êm đềm.',

    event_newborn_first_dentist_visit_title: 'Lần đầu đi nha sĩ',
    event_newborn_first_dentist_visit_desc: 'Đã đến lúc kiểm tra sức khỏe răng miệng cho bé.',
    choice_newborn_first_dentist_visit_1: 'Hợp tác mở miệng cho khám',
    log_newborn_first_dentist_visit_1: 'Bé rất dũng cảm và hợp tác với nha sĩ.',
    choice_newborn_first_dentist_visit_2: 'Lo lắng nhưng ngồi yên',
    log_newborn_first_dentist_visit_2: 'Dù hơi sợ, bé vẫn cố gắng ngồi yên.',
    choice_newborn_first_dentist_visit_3: 'Khóc rồi nín nhờ đồ chơi',
    log_newborn_first_dentist_visit_3: 'Một món đồ chơi nhỏ đã giúp bé vượt qua nỗi sợ hãi.',

    event_newborn_friend_birthday_title: 'Đi chơi sinh nhật bạn',
    event_newborn_friend_birthday_desc: 'Bé được mời đến dự tiệc sinh nhật của một người bạn.',
    choice_newborn_friend_birthday_1: 'Tham gia thổi bong bóng',
    log_newborn_friend_birthday_1: 'Bé đã có một khoảng thời gian tuyệt vời khi chơi cùng các bạn.',
    choice_newborn_friend_birthday_2: 'Đứng nhìn vì ngại đám đông',
    log_newborn_friend_birthday_2: 'Bé cần thời gian để làm quen với môi trường đông người.',
    choice_newborn_friend_birthday_3: 'Chơi cùng vài bạn mới quen',
    log_newborn_friend_birthday_3: 'Bữa tiệc là cơ hội tốt để bé kết bạn mới.',

    event_newborn_first_swim_title: 'Lần đầu đi bơi',
    event_newborn_first_swim_desc: 'Gia đình đưa bé đến hồ bơi để làm quen với nước.',
    choice_newborn_first_swim_1: 'Vẫy nước thích thú',
    log_newborn_first_swim_1: 'Bé không hề sợ nước và tỏ ra rất thích thú.',
    choice_newborn_first_swim_2: 'Ôm chặt người lớn không buông',
    log_newborn_first_swim_2: 'Bé cảm thấy không an toàn và cần sự bảo vệ.',
    choice_newborn_first_swim_3: 'Dùng phao tay để tập bơi',
    log_newborn_first_swim_3: 'Với sự hỗ trợ của phao, bé đã tự tin hơn trong nước.',

    event_newborn_mild_allergy_title: 'Dị ứng nhẹ với món mới',
    event_newborn_mild_allergy_desc: 'Sau khi thử một món ăn mới, bé có dấu hiệu dị ứng nhẹ.',
    choice_newborn_mild_allergy_1: 'Ngừng món đó và theo dõi',
    log_newborn_mild_allergy_1: 'Việc xác định và tránh xa tác nhân gây dị ứng là rất quan trọng.',
    choice_newborn_mild_allergy_2: 'Cho uống nước mát',
    log_newborn_mild_allergy_2: 'Nước mát giúp bé cảm thấy dễ chịu hơn.',
    choice_newborn_mild_allergy_3: 'Gọi điện hỏi ý kiến bác sĩ',
    log_newborn_mild_allergy_3: 'Luôn hỏi ý kiến chuyên gia khi không chắc chắn.',

    event_newborn_potty_training_title: 'Tập bỏ bỉm (potty training)',
    event_newborn_potty_training_desc: 'Đã đến lúc dạy bé cách sử dụng bô.',
    choice_newborn_potty_training_1: 'Báo trước khi cần đi vệ sinh',
    log_newborn_potty_training_1: 'Bé đã học được cách nhận biết và thông báo nhu cầu của mình.',
    choice_newborn_potty_training_2: 'Thỉnh thoảng lỡ ra quần',
    log_newborn_potty_training_2: 'Tai nạn nhỏ là một phần không thể tránh khỏi của quá trình học hỏi.',
    choice_newborn_potty_training_3: 'Chỉ chịu ngồi bô khi có bố/mẹ bên cạnh',
    log_newborn_potty_training_3: 'Sự có mặt của bố mẹ mang lại cho bé cảm giác an toàn.',

    event_newborn_rainy_day_inside_title: 'Ngày mưa kẹt trong nhà',
    event_newborn_rainy_day_inside_desc: 'Trời mưa và cả nhà không thể ra ngoài chơi.',
    choice_newborn_rainy_day_inside_1: 'Xếp hình/ghép khối',
    log_newborn_rainy_day_inside_1: 'Trò chơi trí tuệ giúp bé phát triển kỹ năng giải quyết vấn đề.',
    choice_newborn_rainy_day_inside_2: 'Vẽ màu lên giấy',
    log_newborn_rainy_day_inside_2: 'Vẽ tranh là một cách tuyệt vời để bé thể hiện sự sáng tạo.',
    choice_newborn_rainy_day_inside_3: 'Xem hoạt hình cùng bố mẹ',
    log_newborn_rainy_day_inside_3: 'Khoảng thời gian ấm cúng bên gia đình.',

    event_newborn_sharing_food_title: 'Chia sẻ đồ ăn',
    event_newborn_sharing_food_desc: 'Trong bữa ăn nhẹ, bé có cơ hội chia sẻ đồ ăn với bạn.',
    choice_newborn_sharing_food_1: 'Tự nguyện chia nửa cho bạn',
    log_newborn_sharing_food_1: 'Bé đang học cách trở nên hào phóng.',
    choice_newborn_sharing_food_2: 'Đổi món ăn với bạn',
    log_newborn_sharing_food_2: 'Cả hai đều có cơ hội thử những món mới.',
    choice_newborn_sharing_food_3: 'Giữ lại phần mình thích',
    log_newborn_sharing_food_3: 'Bé vẫn còn hơi ích kỷ một chút.',

    event_newborn_scared_of_thunder_title: 'Sợ tiếng sấm',
    event_newborn_scared_of_thunder_desc: 'Một cơn giông lớn với sấm sét khiến bé sợ hãi.',
    choice_newborn_scared_of_thunder_1: 'Chạy vào lòng bố/mẹ',
    log_newborn_scared_of_thunder_1: 'Vòng tay của bố mẹ là nơi an toàn nhất.',
    choice_newborn_scared_of_thunder_2: 'Bịt tai và ngồi im',
    log_newborn_scared_of_thunder_2: 'Bé cố gắng tự trấn an bản thân.',
    choice_newborn_scared_of_thunder_3: 'Đếm cùng bố mẹ để bình tĩnh',
    log_newborn_scared_of_thunder_3: 'Việc tập trung vào trò chơi đếm số giúp bé quên đi nỗi sợ.',

    event_newborn_breaks_cup_title: 'Làm rơi vỡ cốc nhựa',
    event_newborn_breaks_cup_desc: 'Bé vô tình làm rơi chiếc cốc yêu thích của mình.',
    choice_newborn_breaks_cup_1: 'Nhặt cùng người lớn',
    log_newborn_breaks_cup_1: 'Bé học cách chịu trách nhiệm với hành động của mình.',
    choice_newborn_breaks_cup_2: 'Lo lắng xin lỗi',
    log_newborn_breaks_cup_2: 'Bé hiểu rằng mình đã làm sai.',
    choice_newborn_breaks_cup_3: 'Đề nghị thử cất đồ cẩn thận hơn',
    log_newborn_breaks_cup_3: 'Bé đang học hỏi từ những sai lầm.',

    event_newborn_self_dressing_title: 'Tập tự mặc quần áo',
    event_newborn_self_dressing_desc: 'Bé muốn tự mặc quần áo mà không cần sự giúp đỡ.',
    choice_newborn_self_dressing_1: 'Mặc ngược áo',
    log_newborn_self_dressing_1: 'Dù mặc sai, nỗ lực của bé vẫn rất đáng khen.',
    choice_newborn_self_dressing_2: 'Chọn quần áo sặc sỡ',
    log_newborn_self_dressing_2: 'Bé đang thể hiện cá tính riêng của mình.',
    choice_newborn_self_dressing_3: 'Kéo khóa thành công',
    log_newborn_self_dressing_3: 'Một thành tựu nhỏ nhưng mang lại sự tự tin lớn lao.',

    event_newborn_unwilling_to_go_to_class_title: 'Buổi sáng không muốn tới lớp',
    event_newborn_unwilling_to_go_to_class_desc: 'Hôm nay bé không muốn đi học và khóc lóc.',
    choice_newborn_unwilling_to_go_to_class_1: 'Ôm tạm biệt nhanh gọn',
    log_newborn_unwilling_to_go_to_class_1: 'Việc kéo dài cuộc chia tay chỉ làm mọi thứ khó khăn hơn.',
    choice_newborn_unwilling_to_go_to_class_2: 'Dỗ bằng sticker thưởng',
    log_newborn_unwilling_to_go_to_class_2: 'Một phần thưởng nhỏ có thể tạo ra động lực lớn.',
    choice_newborn_unwilling_to_go_to_class_3: 'Ngồi chơi với bạn rồi dần quên khóc',
    log_newborn_unwilling_to_go_to_class_3: 'Niềm vui khi chơi cùng bạn bè giúp bé nhanh chóng hòa nhập.',

    event_newborn_playing_in_sand_title: 'Chơi cát/đất ở sân',
    event_newborn_playing_in_sand_desc: 'Sân chơi cát là một nơi tuyệt vời để bé khám phá.',
    choice_newborn_playing_in_sand_1: 'Xây “lâu đài” bằng xẻng',
    log_newborn_playing_in_sand_1: 'Bé thỏa sức sáng tạo với cát.',
    choice_newborn_playing_in_sand_2: 'Lỡ làm cát văng vào mắt',
    log_newborn_playing_in_sand_2: 'Một tai nạn nhỏ nhưng khó chịu.',
    choice_newborn_playing_in_sand_3: 'Mang đồ chơi dính cát vào nhà',
    log_newborn_playing_in_sand_3: 'Bé không nhận ra rằng việc này sẽ làm bẩn nhà.',

    event_newborn_drops_toy_title: 'Làm rơi thú bông yêu thích',
    event_newborn_drops_toy_desc: 'Bé làm rơi mất con thú bông yêu thích khi đang đi chơi.',
    choice_newborn_drops_toy_1: 'Tìm thấy dưới gầm giường',
    log_newborn_drops_toy_1: 'Hóa ra nó chỉ trốn ở một nơi quen thuộc.',
    choice_newborn_drops_toy_2: 'Khóc đòi tìm bằng được',
    log_newborn_drops_toy_2: 'Con thú bông có ý nghĩa rất lớn đối với bé.',
    choice_newborn_drops_toy_3: 'Chấp nhận ôm thú bông khác tạm',
    log_newborn_drops_toy_3: 'Bé học cách thích nghi với sự thay đổi.',

    event_newborn_school_festival_title: 'Lễ hội/trung thu ở trường mầm non',
    event_newborn_school_festival_desc: 'Trường mầm non tổ chức một lễ hội đặc biệt.',
    choice_newborn_school_festival_1: 'Rước đèn cùng bạn bè',
    log_newborn_school_festival_1: 'Ánh đèn lồng lung linh và tiếng cười rộn rã.',
    choice_newborn_school_festival_2: 'Đeo mặt nạ và hơi sợ',
    log_newborn_school_festival_2: 'Chiếc mặt nạ hơi đáng sợ nhưng cũng rất thú vị.',
    choice_newborn_school_festival_3: 'Ngồi xem tiết mục múa lân',
    log_newborn_school_festival_3: 'Tiếng trống múa lân thật náo nhiệt và hấp dẫn.',
};
