export default {
    event_pet_adoption_title: 'Cơ hội nhận nuôi thú cưng',
    event_pet_adoption_desc: 'Một trại cứu hộ động vật địa phương đang tổ chức một sự kiện nhận nuôi. Bạn có muốn xem qua không?',
    choice_pet_adoption_1: 'Có, hãy tìm một người bạn mới!',
    log_pet_adoption_1: 'Tôi quyết định nhận nuôi một người bạn đồng hành mới.',
    choice_pet_adoption_2: 'Không, bây giờ không phải lúc.',
    log_pet_adoption_2: 'Tôi quyết định bây giờ chưa phải lúc thích hợp để nuôi thú cưng.',
    event_pet_sick_title: 'Thú cưng bị ốm',
    event_pet_sick_desc: 'Thú cưng của bạn có vẻ không khỏe và lờ đờ.',
    choice_pet_sick_1: 'Đưa đến bác sĩ thú y.',
    log_pet_sick_1: 'Bác sĩ thú y đã cho thuốc và thú cưng của tôi đang hồi phục.',
    choice_pet_sick_2: 'Để nó tự nghỉ ngơi.',
    log_pet_sick_2: 'Tôi hy vọng thú cưng của mình sẽ tự khỏi sau khi nghỉ ngơi.',
    event_pet_damages_item_title: 'Thú cưng phá hoại',
    event_pet_damages_item_desc: 'Bạn về nhà và thấy thú cưng của mình đã làm hỏng một món đồ có giá trị.',
    choice_pet_damages_item_1: 'Tha thứ và huấn luyện lại nó.',
    log_pet_damages_item_1: 'Nó chỉ là một con vật thôi mà.',
    choice_pet_damages_item_2: 'La mắng nó thậm tệ.',
    log_pet_damages_item_2: 'Thú cưng của tôi có vẻ sợ hãi sau khi bị mắng.',
    event_pet_lost_title: 'Thú cưng bị lạc',
    event_pet_lost_desc: 'Thú cưng của bạn đã biến mất!',
    choice_pet_lost_1: 'Tìm kiếm khắp nơi.',
    log_pet_lost_1: 'Tôi đã dán áp phích và tìm kiếm khắp nơi.',
    choice_pet_lost_2: 'Chờ nó tự quay về.',
    log_pet_lost_2: 'Tôi hy vọng nó sẽ tìm được đường về nhà.',
    event_pet_contest_title: 'Cuộc thi thú cưng',
    event_pet_contest_desc: 'Có một cuộc thi thú cưng trong thị trấn.',
    choice_pet_contest_1: 'Tham gia cuộc thi.',
    log_pet_contest_1: 'Đây là cơ hội để thú cưng của tôi tỏa sáng.',
    choice_pet_contest_2: 'Không tham gia.',
    log_pet_contest_2: 'Chúng tôi không quan tâm đến các cuộc thi.',
    event_pet_gets_old_title: 'Thú cưng già đi',
    event_pet_gets_old_desc: 'Thú cưng của bạn đã già và yếu đi nhiều.',
    choice_pet_gets_old_1: 'Chăm sóc nó chu đáo.',
    log_pet_gets_old_1: 'Tôi sẽ ở bên nó trong những ngày cuối cùng.',
    choice_pet_gets_old_2: 'An tử nó.',
    log_pet_gets_old_2: 'Đó là một quyết định khó khăn, nhưng tôi không muốn nó phải chịu đau đớn.',
    // Trigger-only
    event_pet_sickness_worsens_title: 'Bệnh của thú cưng trở nặng',
    event_pet_sickness_worsens_desc: 'Tình trạng của thú cưng ngày càng tồi tệ.',
    choice_pet_sickness_worsens_1: 'Đưa đến bệnh viện thú y.',
    log_pet_sickness_worsens_1: 'Thú cưng của tôi cần được chăm sóc đặc biệt.',
    choice_pet_sickness_worsens_2: 'Chăm sóc tại nhà.',
    log_pet_sickness_worsens_2: 'Tôi sẽ làm mọi thứ có thể cho nó ở nhà.',
    event_pet_found_title: 'Tìm thấy thú cưng!',
    event_pet_found_desc: 'Một người hàng xóm đã tìm thấy thú cưng của bạn!',
    choice_pet_found_1: 'Thật là một sự nhẹ nhõm!',
    log_pet_found_1: 'Tôi rất vui khi được đoàn tụ với người bạn nhỏ của mình.',
    event_pet_lost_forever_title: 'Thú cưng mất tích mãi mãi',
    event_pet_lost_forever_desc: 'Dù đã tìm kiếm, bạn vẫn không thể tìm thấy thú cưng của mình.',
    choice_pet_lost_forever_1: 'Cảm thấy rất buồn.',
    log_pet_lost_forever_1: 'Tôi sẽ không bao giờ quên nó.',
    event_pet_contest_win_title: 'Thắng cuộc thi!',
    event_pet_contest_win_desc: 'Thú cưng của bạn đã thắng cuộc thi!',
    choice_pet_contest_win_1: 'Thật tự hào!',
    log_pet_contest_win_1: 'Thú cưng của tôi là tuyệt nhất!',
    event_pet_contest_lose_title: 'Thua cuộc thi',
    event_pet_contest_lose_desc: 'Thú cưng của bạn đã không thắng cuộc thi.',
    choice_pet_contest_lose_1: 'Không sao cả.',
    log_pet_contest_lose_1: 'Quan trọng là đã tham gia.',
    event_pet_dies_title: 'Thú cưng qua đời',
    event_pet_dies_desc: 'Thú cưng yêu quý của bạn đã qua đời.',
    choice_pet_dies_1: 'Tổ chức một lễ tang nhỏ.',
    log_pet_dies_1: 'Yên nghỉ nhé, bạn thân của tôi.',
};
