export default {
    // Main Event Titles & Descriptions
    event_relationship_first_date_title: 'Hẹn Hò Đầu Tiên',
    event_relationship_first_date_desc: 'Bạn sắp có buổi hẹn hò đầu tiên! Đi đâu bây giờ?',
    event_relationship_prom_night_title: 'Đêm Prom',
    event_relationship_prom_night_desc: 'Đây là đêm hội lớn nhất của năm học! Kế hoạch cho prom là gì?',
    event_relationship_sending_text_title: 'Gửi Tin Nhắn',
    event_relationship_sending_text_desc: 'Bạn muốn gửi một tin nhắn cho crush. Bạn sẽ nói gì?',
    event_relationship_anniversary_title: 'Ngày Kỷ Niệm',
    event_relationship_anniversary_desc: 'Hôm nay là ngày kỷ niệm của hai bạn! Nên ăn mừng thế nào đây?',
    event_relationship_meeting_friends_title: 'Gặp Gỡ Bạn Bè',
    event_relationship_meeting_friends_desc: 'Bạn sắp gặp bạn bè của đối phương lần đầu tiên. Bạn sẽ hành động thế nào?',
    event_relationship_amusement_park_title: 'Hẹn Hò ở Công Viên Giải Trí',
    event_relationship_amusement_park_desc: 'Một ngày vui vẻ ở công viên giải trí! Chơi gì đầu tiên?',
    event_relationship_first_argument_title: 'Trận Cãi Vã Đầu Tiên',
    event_relationship_first_argument_desc: 'Hai bạn đang có trận cãi vã thực sự đầu tiên. Bạn xử lý thế nào?',
    event_relationship_fancy_dinner_title: 'Bữa Tối Sang Trọng',
    event_relationship_fancy_dinner_desc: 'Hai bạn đang đi ăn tối ở một nhà hàng sang trọng. Đã đến lúc gây ấn tượng!',
    event_relationship_road_trip_title: 'Chuyến Đi Phượt',
    event_relationship_road_trip_desc: 'Đã đến lúc cho một chuyến đi phượt ngẫu hứng cùng nhau!',
    event_relationship_talk_future_title: 'Nói Về Tương Lai',
    event_relationship_talk_future_desc: 'Cuộc trò chuyện đã trở nên nghiêm túc, và hai bạn đang nói về tương lai.',

    // Choices & Logs for Main Events
    choice_relationship_first_date_1: 'Đến một quán cà phê ấm cúng',
    log_relationship_first_date_1: 'Chúng tôi đã nói chuyện cho đến khi nhân viên pha chế phải mời chúng tôi về.',
    choice_relationship_first_date_2: 'Đi ăn tối sang trọng',
    log_relationship_first_date_2: 'Thức ăn lấp lánh, ví tiền của tôi thì khóc thét.',
    choice_relationship_first_date_3: 'Đi chơi bowling',
    log_relationship_first_date_3: 'Tôi ném bóng vào rãnh nhiều hơn là trúng đích, nhưng vẫn rất vui.',

    choice_relationship_prom_night_1: 'Lộng lẫy với tuxedo/váy dạ hội',
    log_relationship_prom_night_1: 'Mọi người đều ngoái nhìn khi chúng tôi bước vào.',
    choice_relationship_prom_night_2: 'Giữ phong cách đơn giản',
    log_relationship_prom_night_2: 'Chúng tôi trông có vẻ lạc quẻ, nhưng chúng tôi mặc kệ.',
    choice_relationship_prom_night_3: 'Bỏ prom để đến quán ăn đêm',
    log_relationship_prom_night_3: 'Bánh kếp lúc nửa đêm tuyệt hơn sàn nhảy đông đúc.',
    
    choice_relationship_sending_text_1: 'Viết một tin nhắn dài đầy tâm huyết',
    log_relationship_sending_text_1: 'Câu trả lời tuy ngắn gọn nhưng đầy ấm áp.',
    choice_relationship_sending_text_2: 'Gửi một ảnh GIF hài hước',
    log_relationship_sending_text_2: 'Cả hai chúng tôi đều bật cười và cuối cùng đã lên kế hoạch hẹn hò.',
    choice_relationship_sending_text_3: 'Chỉ gửi “chào”',
    log_relationship_sending_text_3: 'Thái độ suồng sã của tôi đã gây ra một cơn bão bất ngờ.',

    choice_relationship_anniversary_1: 'Gây bất ngờ bằng hoa',
    log_relationship_anniversary_1: 'Mùi hương hoa hồng tràn ngập căn phòng và nụ cười đã nói lên tất cả.',
    choice_relationship_anniversary_2: 'Đi xem phim',
    log_relationship_anniversary_2: 'Hộp bắp rang bơ còn to hơn cả đầu chúng tôi.',
    choice_relationship_anniversary_3: 'Quên mất ngày kỷ niệm',
    log_relationship_anniversary_3: 'Sự im lặng kéo dài còn hơn cả cuộn phim.',

    choice_relationship_meeting_friends_1: 'Nói nhiều',
    log_relationship_meeting_friends_1: 'Tôi đã tham gia vào ba câu chuyện đùa nội bộ trước khi đến món tráng miệng.',
    choice_relationship_meeting_friends_2: 'Giữ im lặng',
    log_relationship_meeting_friends_2: 'Họ gọi tôi là bí ẩn; tôi gọi đó là sự sống còn.',
    choice_relationship_meeting_friends_3: 'Kể một câu chuyện cười nhạt nhẽo',
    log_relationship_meeting_friends_3: 'Câu chuyện cười của tôi đã trở thành meme của nhóm họ.',

    choice_relationship_amusement_park_1: 'Đi vòng quay Ferris',
    log_relationship_amusement_park_1: 'Khung cảnh thật tuyệt vời, việc nắm tay còn tuyệt hơn.',
    choice_relationship_amusement_park_2: 'Đi tàu lượn siêu tốc',
    log_relationship_amusement_park_2: 'Tôi hét to hơn cả một đứa trẻ năm tuổi và có một biệt danh mới.',
    choice_relationship_amusement_park_3: 'Ăn kẹo bông gòn',
    log_relationship_amusement_park_3: 'Say đường + ngón tay dính nhớp = một mớ hỗn loạn vui vẻ.',

    choice_relationship_first_argument_1: 'Nói chuyện thẳng thắn',
    log_relationship_first_argument_1: 'Lời nói đã gỡ được nút thắt giữa chúng tôi.',
    choice_relationship_first_argument_2: 'Bỏ đi',
    log_relationship_first_argument_2: 'Sự im lặng kéo dài hơn dự kiến.',
    choice_relationship_first_argument_3: 'Gửi tin nhắn “k”',
    log_relationship_first_argument_3: 'Từ ngắn nhất đã bắt đầu cuộc chiến dài nhất.',

    choice_relationship_fancy_dinner_1: 'Cực kỳ lịch sự',
    log_relationship_fancy_dinner_1: 'Người phục vụ đã gật đầu công nhận chúng tôi là “cặp đôi đẹp nhất”.',
    choice_relationship_fancy_dinner_2: 'Làm đổ đồ uống',
    log_relationship_fancy_dinner_2: 'Hành động vụng về của tôi đã trở thành trò giải trí của đêm nay.',
    choice_relationship_fancy_dinner_3: 'Gọi món đắt nhất',
    log_relationship_fancy_dinner_3: 'Miếng ngon, hóa đơn đau đớn.',

    choice_relationship_road_trip_1: 'Lên kế hoạch mọi thứ',
    log_relationship_road_trip_1: 'Cuối cùng thì GPS và tôi cũng đã trở thành bạn bè.',
    choice_relationship_road_trip_2: 'Đi ngẫu hứng',
    log_relationship_road_trip_2: 'Chúng tôi tìm thấy một xe bán taco thay vì Grand Canyon.',
    choice_relationship_road_trip_3: 'Đóng gói quá nhiều đồ',
    log_relationship_road_trip_3: 'Chiếc xe trông như thể chúng tôi đang dọn nhà.',

    choice_relationship_talk_future_1: 'Thảo luận nghiêm túc',
    log_relationship_talk_future_1: 'Những kế hoạch được viết nguệch ngoạc trên giấy ăn trông thật hơn bao giờ hết.',
    choice_relationship_talk_future_2: 'Đùa cho qua chuyện',
    log_relationship_talk_future_2: 'Chúng tôi đã cười, nhưng câu hỏi vẫn còn đó.',
    choice_relationship_talk_future_3: 'Đưa ra câu trả lời mơ hồ',
    log_relationship_talk_future_3: 'Nụ cười nửa miệng của tôi không đủ để trấn an.',

    // Trigger-based Events
    event_relationship_forgot_socks_title: 'Quên Vớ ở Sân Bowling',
    event_relationship_forgot_socks_desc: 'Bạn quên mang vớ để chơi bowling. Giờ sao?',
    choice_relationship_forgot_socks_1: 'Mượn ở quầy',
    log_relationship_forgot_socks_1: 'Đôi vớ cho thuê trông như của chú hề đã thêm phần vui nhộn.',
    choice_relationship_forgot_socks_2: 'Chơi chân trần',
    log_relationship_forgot_socks_2: 'Những ánh nhìn chằm chằm thật đáng giá cho cú strike tôi ghi được.',
    choice_relationship_forgot_socks_3: 'Nghỉ chơi sớm',
    log_relationship_forgot_socks_3: 'Chúng tôi đã biến buổi tối thành một buổi đi ăn kem.',

    event_relationship_pancake_accident_title: 'Tai Nạn Bánh Kếp',
    event_relationship_pancake_accident_desc: 'Một chiếc bánh kếp đẫm si-rô vừa rơi vào lòng đối phương!',
    choice_relationship_pancake_accident_1: 'Cười cho qua',
    log_relationship_pancake_accident_1: 'Si-rô ở khắp nơi, nụ cười cũng ở khắp nơi.',
    choice_relationship_pancake_accident_2: 'Cố gắng lau nhanh',
    log_relationship_pancake_accident_2: 'Giấy ăn thất bại, nhưng tiếng cười đã thành công.',
    choice_relationship_pancake_accident_3: 'Đổ lỗi cho cái nĩa',
    log_relationship_pancake_accident_3: 'Một lý do lố bịch nhưng lại hiệu quả một cách kỳ lạ.',

    event_relationship_misunderstood_silence_title: 'Sự Im Lặng Gây Hiểu Lầm',
    event_relationship_misunderstood_silence_desc: 'Tin nhắn "chào" của bạn đã bị đáp lại bằng sự im lặng, và giờ mọi thứ thật khó xử.',
    choice_relationship_misunderstood_silence_1: 'Gọi ngay lập tức',
    log_relationship_misunderstood_silence_1: 'Cuộc gọi kéo dài hơn bất kỳ tin nhắn nào.',
    choice_relationship_misunderstood_silence_2: 'Giả vờ không có gì xảy ra',
    log_relationship_misunderstood_silence_2: 'Sự khó xử kéo dài, nhưng sớm phai nhạt.',
    choice_relationship_misunderstood_silence_3: 'Gửi một meme ngẫu nhiên khác',
    log_relationship_misunderstood_silence_3: 'Sự bối rối biến thành tiếng cười chung.',

    event_relationship_silent_treatment_title: 'Chiến Tranh Lạnh',
    event_relationship_silent_treatment_desc: 'Việc quên ngày kỷ niệm đã dẫn đến chiến tranh lạnh.',
    choice_relationship_silent_treatment_1: 'Xin lỗi bằng món tráng miệng',
    log_relationship_silent_treatment_1: 'Bánh sô cô la đã cứu vãn tình thế.',
    choice_relationship_silent_treatment_2: 'Viết một ghi chú sến súa',
    log_relationship_silent_treatment_2: 'Một dòng chữ nguệch ngoạc trên giấy ăn đã làm tan băng.',
    choice_relationship_silent_treatment_3: 'Chờ đợi',
    log_relationship_silent_treatment_3: 'Những ánh nhìn lạnh lùng còn khắc nghiệt hơn mùa đông.',

    event_relationship_endless_teasing_title: 'Bị Trêu Chọc Không Ngừng',
    event_relationship_endless_teasing_desc: 'Câu chuyện cười nhạt nhẽo của bạn đã trở thành trò đùa nội bộ của bạn bè đối phương. Họ không chịu buông tha.',
    choice_relationship_endless_teasing_1: 'Cười cùng họ',
    log_relationship_endless_teasing_1: 'Câu chuyện cười của tôi đã trở thành huyền thoại trong nhóm chat của họ.',
    choice_relationship_endless_teasing_2: 'Đổi chủ đề',
    log_relationship_endless_teasing_2: 'Tôi đã né, nhưng họ vẫn quay lại chủ đề đó.',
    choice_relationship_endless_teasing_3: 'Kể một câu chuyện cười dở tệ khác',
    log_relationship_endless_teasing_3: 'Ít nhất thì tôi cũng nhất quán.',

    event_relationship_unexpected_scream_title: 'Tiếng Hét Tàu Lượn',
    event_relationship_unexpected_scream_desc: 'Tiếng hét của bạn trên tàu lượn... cao một cách bất ngờ.',
    choice_relationship_unexpected_scream_1: 'Giả vờ đó là cố ý',
    log_relationship_unexpected_scream_1: 'Không ai tin tôi, nhưng nó lại trở nên hài hước.',
    choice_relationship_unexpected_scream_2: 'Che mặt lại',
    log_relationship_unexpected_scream_2: 'Bức ảnh chụp trên tàu thật vô giá... một cách xấu hổ.',
    choice_relationship_unexpected_scream_3: 'Tự hào thừa nhận',
    log_relationship_unexpected_scream_3: '“Người hét to nhất” đã trở thành danh hiệu chính thức của tôi.',

    event_relationship_cold_war_title: 'Chiến Tranh Lạnh',
    event_relationship_cold_war_desc: 'Việc bỏ đi khỏi cuộc cãi vã đã bắt đầu một cuộc chiến tranh lạnh.',
    choice_relationship_cold_war_1: 'Gửi một chiếc pizza hòa giải',
    log_relationship_cold_war_1: 'Pepperoni đã kết thúc cuộc chiến nhanh hơn lời nói.',
    choice_relationship_cold_war_2: 'Chờ họ phá vỡ sự im lặng',
    log_relationship_cold_war_2: 'Sự bướng bỉnh kéo dài cho đến khi sự nhàm chán chiến thắng.',
    choice_relationship_cold_war_3: 'Đăng một trạng thái mơ hồ',
    log_relationship_cold_war_3: 'Một cú “like” đã bắt đầu cuộc đình chiến.',

    event_relationship_everyone_staring_title: 'Mọi Người Đang Nhìn Chằm Chằm',
    event_relationship_everyone_staring_desc: 'Bạn làm đổ đồ uống và giờ mọi người đang nhìn chằm chằm.',
    choice_relationship_everyone_staring_1: 'Lau bằng giấy ăn',
    log_relationship_everyone_staring_1: 'Tôi đã trở thành người hùng vụng về của buổi tối.',
    choice_relationship_everyone_staring_2: 'Cười lớn',
    log_relationship_everyone_staring_2: 'Sự tự tin của tôi đã biến tai nạn thành một trò đùa.',
    choice_relationship_everyone_staring_3: 'Giả vờ không có gì xảy ra',
    log_relationship_everyone_staring_3: 'Không thể — nhưng tôi đã thử.',

    event_relationship_getting_lost_title: 'Bị Lạc Đường',
    event_relationship_getting_lost_desc: 'Chuyến đi ngẫu hứng của bạn đã đưa bạn đến một nơi chắc chắn không có trên bản đồ.',
    choice_relationship_getting_lost_1: 'Hỏi người dân địa phương',
    log_relationship_getting_lost_1: 'Hỏi đường còn được tặng kèm taco miễn phí.',
    choice_relationship_getting_lost_2: 'Tiếp tục lái xe vô định',
    log_relationship_getting_lost_2: 'Chúng tôi tìm thấy một cái hồ mà không ai biết đến.',
    choice_relationship_getting_lost_3: 'Đổ lỗi cho GPS',
    log_relationship_getting_lost_3: 'GPS vẫn báo “đang tính toán lại”.',

    event_relationship_doubt_arises_title: 'Nghi Ngờ Nảy Sinh',
    event_relationship_doubt_arises_desc: 'Câu trả lời mơ hồ của bạn về tương lai đã tạo ra một số nghi ngờ.',
    choice_relationship_doubt_arises_1: 'Ngồi xuống nói chuyện thẳng thắn',
    log_relationship_doubt_arises_1: 'Sự trung thực đã vá lại cây cầu đang lung lay.',
    choice_relationship_doubt_arises_2: 'Đánh lạc hướng bằng sự hài hước',
    log_relationship_doubt_arises_2: 'Sự căng thẳng vỡ tan thành những tiếng cười khúc khích.',
    choice_relationship_doubt_arises_3: 'Tránh né nó',
    log_relationship_doubt_arises_3: 'Câu hỏi đã quay trở lại sau đó, lớn hơn.',

    // Independent Events
    event_relationship_netflix_chill_title: 'Netflix & Chill',
    event_relationship_netflix_chill_desc: 'Một đêm yên tĩnh ở nhà xem phim.',
    choice_relationship_netflix_chill_1: 'Thực sự xem chương trình',
    log_relationship_netflix_chill_1: 'Chúng tôi đã cày hết một mùa, quên cả thời gian.',
    choice_relationship_netflix_chill_2: 'Ngủ gật giữa chừng',
    log_relationship_netflix_chill_2: 'Nhạc nền tiếng ngáy đã tham gia vào tập phim.',
    choice_relationship_netflix_chill_3: 'Tiếp tục tạm dừng để đùa giỡn',
    log_relationship_netflix_chill_3: 'Chúng tôi cười nhiều hơn là xem.',

    event_relationship_house_party_title: 'Tiệc tại gia',
    event_relationship_house_party_desc: 'Bạn đang ở một bữa tiệc tại nhà của một người bạn.',
    choice_relationship_house_party_1: 'Nhảy điên cuồng',
    log_relationship_house_party_1: 'Những bước nhảy của tôi khiến mọi người vừa cổ vũ vừa khó đỡ.',
    choice_relationship_house_party_2: 'Canh giữ bàn đồ ăn vặt',
    log_relationship_house_party_2: 'Nachos đã biến mất dưới sự canh gác của tôi.',
    choice_relationship_house_party_3: 'Trốn trong góc',
    log_relationship_house_party_3: 'Bằng cách nào đó, tôi vẫn bị lôi vào hát karaoke.',

    event_relationship_bbq_cookout_title: 'Tiệc nướng BBQ',
    event_relationship_bbq_cookout_desc: 'Một buổi chiều nắng đẹp nướng BBQ cùng bạn bè.',
    choice_relationship_bbq_cookout_1: 'Làm chủ vỉ nướng',
    log_relationship_bbq_cookout_1: 'Bánh mì kẹp thịt hoàn hảo, có cả tiếng vỗ tay.',
    choice_relationship_bbq_cookout_2: 'Làm cháy xúc xích',
    log_relationship_bbq_cookout_2: 'Hương vị của ngày hôm nay là phong cách than củi.',
    choice_relationship_bbq_cookout_3: 'Chỉ ăn đồ ăn kèm',
    log_relationship_bbq_cookout_3: 'Salad khoai tây đã trở thành món chính của tôi.',

    event_relationship_drive_in_movie_title: 'Rạp chiếu phim ngoài trời',
    event_relationship_drive_in_movie_desc: 'Một buổi hẹn hò xem phim ngoài trời cổ điển.',
    choice_relationship_drive_in_movie_1: 'Mang theo chăn ấm cúng',
    log_relationship_drive_in_movie_1: 'Chúng tôi ôm nhau nhiều hơn là xem phim.',
    choice_relationship_drive_in_movie_2: 'Quên thuốc xịt côn trùng',
    log_relationship_drive_in_movie_2: 'Muỗi yêu tôi hơn cả bộ phim.',
    choice_relationship_drive_in_movie_3: 'Về sớm để ăn bánh mì kẹp thịt',
    log_relationship_drive_in_movie_3: 'Ánh đèn neon của quán ăn là phần kết của chúng tôi.',

    event_relationship_super_bowl_title: 'Chủ Nhật Super Bowl',
    event_relationship_super_bowl_desc: 'Hôm nay là Chủ Nhật Super Bowl. Kế hoạch là gì?',
    choice_relationship_super_bowl_1: 'Xem trận đấu một cách nghiêm túc',
    log_relationship_super_bowl_1: 'Tôi hét to hơn cả bình luận viên.',
    choice_relationship_super_bowl_2: 'Chỉ ăn đồ ăn vặt',
    log_relationship_super_bowl_2: 'Cánh gà > bóng đá, bất kể ngày nào.',
    choice_relationship_super_bowl_3: 'Cổ vũ cho đội sai',
    log_relationship_super_bowl_3: 'Đối tác của tôi gần như đã từ mặt tôi.',

    event_relationship_thanksgiving_title: 'Lễ Tạ Ơn với Gia Đình Đối Tác',
    event_relationship_thanksgiving_desc: 'Bạn đang ăn Lễ Tạ Ơn với gia đình của đối tác.',
    choice_relationship_thanksgiving_1: 'Giúp nấu ăn',
    log_relationship_thanksgiving_1: 'Món khoai tây nghiền của tôi đã thành công rực rỡ.',
    choice_relationship_thanksgiving_2: 'Xem bóng bầu dục',
    log_relationship_thanksgiving_2: 'Tôi đã thân thiết với chú của họ qua những pha touchdown.',
    choice_relationship_thanksgiving_3: 'Ngủ trên ghế sofa',
    log_relationship_thanksgiving_3: 'Cơn buồn ngủ sau khi ăn gà tây là có thật.',

    event_relationship_valentines_title: 'Ngày Lễ Tình Nhân',
    event_relationship_valentines_desc: 'Hôm nay là Lễ Tình Nhân, ngày của tình yêu.',
    choice_relationship_valentines_1: 'Bữa tối sang trọng',
    log_relationship_valentines_1: 'Nến, rượu vang, đầy đủ những thứ sáo rỗng.',
    choice_relationship_valentines_2: 'Netflix & pizza',
    log_relationship_valentines_2: 'Những chiếc hộp dính dầu mỡ chưa bao giờ trông lãng mạn đến thế.',
    choice_relationship_valentines_3: 'Quên mất ngày',
    log_relationship_valentines_3: 'Tôi đã được nhắc nhở… một cách kịch tính.',

    event_relationship_beach_day_title: 'Ngày Đi Biển',
    event_relationship_beach_day_desc: 'Một ngày hoàn hảo để đi biển.',
    choice_relationship_beach_day_1: 'Xây lâu đài cát',
    log_relationship_beach_day_1: 'Pháo đài của chúng tôi đã sụp đổ một cách đầy phong cách.',
    choice_relationship_beach_day_2: 'Chơi bóng chuyền',
    log_relationship_beach_day_2: 'Tôi bị bóng đập vào mặt, nhưng vẫn ghi điểm.',
    choice_relationship_beach_day_3: 'Chỉ tắm nắng',
    log_relationship_beach_day_3: 'Mức độ thư giãn: đỏ như tôm hùm.',

    event_relationship_camping_trip_title: 'Chuyến Đi Cắm Trại',
    event_relationship_camping_trip_desc: 'Một chuyến đi cắm trại cuối tuần giữa thiên nhiên hoang dã.',
    choice_relationship_camping_trip_1: 'Dựng lều một cách hoàn hảo',
    log_relationship_camping_trip_1: 'Lều của chúng tôi đã sẵn sàng để lên Instagram.',
    choice_relationship_camping_trip_2: 'Quên diêm',
    log_relationship_camping_trip_2: 'Xúc xích nguội đã trở thành bữa tối của chúng tôi.',
    choice_relationship_camping_trip_3: 'Kể chuyện ma',
    log_relationship_camping_trip_3: 'Chúng tôi đã tự dọa mình nhiều hơn cần thiết.',

    event_relationship_roadside_diner_title: 'Quán Ăn Ven Đường',
    event_relationship_roadside_diner_desc: 'Dừng chân tại một quán ăn ven đường cổ điển.',
    choice_relationship_roadside_diner_1: 'Gọi bánh kếp',
    log_relationship_roadside_diner_1: 'Si-rô ở khắp nơi, niềm vui ở khắp nơi.',
    choice_relationship_roadside_diner_2: 'Thử một món mới',
    log_relationship_roadside_diner_2: 'Thịt bí ẩn… tốt hơn là không nên hỏi.',
    choice_relationship_roadside_diner_3: 'Chỉ uống cà phê',
    log_relationship_roadside_diner_3: 'Cà phê được châm thêm không bao giờ kết thúc.',

    event_relationship_hiking_title: 'Đi Bộ Đường Dài',
    event_relationship_hiking_desc: 'Một chuyến đi bộ đường dài ngắm cảnh trên một con đường mòn tuyệt đẹp.',
    choice_relationship_hiking_1: 'Lên đến đỉnh',
    log_relationship_hiking_1: 'Khung cảnh thật ngoạn mục, cũng như việc leo núi.',
    choice_relationship_hiking_2: 'Bị lạc một lúc',
    log_relationship_hiking_2: 'Chúng tôi đã khám phá ra một thác nước ẩn.',
    choice_relationship_hiking_3: 'Quay lại sớm',
    log_relationship_hiking_3: 'Đồ ăn vặt trong xe cảm giác như một phần thưởng.',

    event_relationship_mini_golf_title: 'Hẹn Hò Chơi Golf Mini',
    event_relationship_mini_golf_desc: 'Một trận golf mini đầy cạnh tranh.',
    choice_relationship_mini_golf_1: 'Chơi nghiêm túc',
    log_relationship_mini_golf_1: 'Một cú hole-in-one đã cho tôi quyền khoe khoang.',
    choice_relationship_mini_golf_2: 'Gian lận cho vui',
    log_relationship_mini_golf_2: 'Tiếng cười đáng giá hơn những cú đánh phạt.',
    choice_relationship_mini_golf_3: 'Bỏ cuộc và chỉ chụp ảnh',
    log_relationship_mini_golf_3: 'Những bức ảnh tự sướng của chúng tôi mới là người chiến thắng thực sự.',

    event_relationship_ice_cream_run_title: 'Đi Ăn Kem',
    event_relationship_ice_cream_run_desc: 'Một chuyến đi nhanh đến quán kem.',
    choice_relationship_ice_cream_run_1: 'Chia sẻ một cây kem ốc quế',
    log_relationship_ice_cream_run_1: 'Nó tan chảy nhanh hơn dự kiến—một niềm vui bừa bộn.',
    choice_relationship_ice_cream_run_2: 'Thử hương vị kỳ lạ nhất',
    log_relationship_ice_cream_run_2: 'Kem dưa chua… không thể nào quên.',
    choice_relationship_ice_cream_run_3: 'Mỗi người ba muỗng',
    log_relationship_ice_cream_run_3: 'Say đường, hối hận trong tương lai.',

    event_relationship_arcade_night_title: 'Đêm Chơi Game Arcade',
    event_relationship_arcade_night_desc: 'Một đêm của những trò chơi cổ điển và những giải thưởng bằng vé.',
    choice_relationship_arcade_night_1: 'Thắng một con thú nhồi bông lớn',
    log_relationship_arcade_night_1: 'Cuối cùng máy gắp thú cũng đã nghe lời!',
    choice_relationship_arcade_night_2: 'Thua mọi trò chơi',
    log_relationship_arcade_night_2: 'Ít nhất thì những tấm vé cũng làm được một cái mũ ngầu.',
    choice_relationship_arcade_night_3: 'Chơi máy nhảy',
    log_relationship_arcade_night_3: 'Nhịp điệu của tôi đã gây ra động đất.',

    event_relationship_picnic_title: 'Dã Ngoại trong Công Viên',
    event_relationship_picnic_desc: 'Một buổi dã ngoại thư giãn trong công viên.',
    choice_relationship_picnic_1: 'Mang theo bánh mì kẹp tự làm',
    log_relationship_picnic_1: 'Hơi bị bẹp, nhưng ngon.',
    choice_relationship_picnic_2: 'Quên dụng cụ ăn uống',
    log_relationship_picnic_2: 'Khoai tây chiên đã trở thành muỗng—sự đổi mới!',
    choice_relationship_picnic_3: 'Cho vịt ăn',
    log_relationship_picnic_3: 'Chúng đã đuổi theo chúng tôi để xin thêm bánh mì.',

    event_relationship_concert_night_title: 'Đêm Hòa Nhạc',
    event_relationship_concert_night_desc: 'Đi xem một buổi hòa nhạc trực tiếp.',
    choice_relationship_concert_night_1: 'Hát theo thật to',
    log_relationship_concert_night_1: 'Giọng hát của tôi đã vô tình tham gia vào ban nhạc.',
    choice_relationship_concert_night_2: 'Quay phim mọi thứ',
    log_relationship_concert_night_2: 'Bộ nhớ của tôi đã hết trước khi đến phần encore.',
    choice_relationship_concert_night_3: 'Chỉ lặng lẽ cảm nhận',
    log_relationship_concert_night_3: 'Tiếng bass rung chuyển lồng ngực tôi trong im lặng.',

    event_relationship_holiday_shopping_title: 'Mua Sắm Ngày Lễ',
    event_relationship_holiday_shopping_desc: 'Len lỏi qua đám đông để mua sắm cho ngày lễ.',
    choice_relationship_holiday_shopping_1: 'Mua những món quà ý nghĩa',
    log_relationship_holiday_shopping_1: 'Những cuộc chiến giấy gói quà đã diễn ra sau đó.',
    choice_relationship_holiday_shopping_2: 'Chi tiêu quá tay',
    log_relationship_holiday_shopping_2: 'Ví tiền của tôi đã đình công.',
    choice_relationship_holiday_shopping_3: 'Quên danh sách',
    log_relationship_holiday_shopping_3: 'Về nhà với một con gà cao su.',

    event_relationship_coffee_run_title: 'Đi Mua Cà Phê',
    event_relationship_coffee_run_desc: 'Một chuyến đi mua cà phê đơn giản.',
    choice_relationship_coffee_run_1: 'Gọi đồ uống yêu thích của họ',
    log_relationship_coffee_run_1: 'Nụ cười đó thật đáng để xếp hàng.',
    choice_relationship_coffee_run_2: 'Gọi sai món',
    log_relationship_coffee_run_2: 'Sai latte, nhưng vẫn đúng khoảnh khắc.',
    choice_relationship_coffee_run_3: 'Quên ví của mình',
    log_relationship_coffee_run_3: 'Ôi, họ đã trả tiền.',

    event_relationship_pet_adoption_title: 'Thăm Nơi Nhận Nuôi Thú Cưng',
    event_relationship_pet_adoption_desc: 'Đến thăm một trạm cứu hộ động vật "chỉ để xem thôi."',
    choice_relationship_pet_adoption_1: 'Chơi với những chú cún con',
    log_relationship_pet_adoption_1: 'Chúng tôi suýt nữa đã về nhà với ba đứa.',
    choice_relationship_pet_adoption_2: 'Nhìn những chú mèo',
    log_relationship_pet_adoption_2: 'Một con mèo đã phán xét tôi, mãi mãi.',
    choice_relationship_pet_adoption_3: 'Quyết định “chỉ xem thôi”',
    log_relationship_pet_adoption_3: 'Chúng tôi đã xem theo cách của mình vào những trách nhiệm mới.',

    event_relationship_fireworks_title: 'Xem Pháo Hoa',
    event_relationship_fireworks_desc: 'Xem một màn trình diễn pháo hoa.',
    choice_relationship_fireworks_1: 'Lễ kỷ niệm lớn ở công viên',
    log_relationship_fireworks_1: 'Những tiếng "Ồ" và "À" ở khắp nơi.',
    choice_relationship_fireworks_2: 'Pháo bông ở sân sau',
    log_relationship_fireworks_2: 'Những ngón tay bị bỏng, những nụ cười rạng rỡ.',
    choice_relationship_fireworks_3: 'Bỏ lỡ vì ngủ quên',
    log_relationship_fireworks_3: 'Những giấc mơ có pháo hoa đẹp hơn.',
};
