export default {
    event_retired_official_retirement_day_title: 'Ngày nghỉ hưu chính thức',
    event_retired_official_retirement_day_desc: 'Hôm nay là ngày làm việc cuối cùng của bạn. Bạn cảm thấy thế nào?',
    choice_retired_official_retirement_day_1: 'Tổ chức tiệc nhỏ với gia đình',
    log_retired_official_retirement_day_1: 'Tôi đã có một bữa tiệc ấm cúng bên những người thân yêu.',
    choice_retired_official_retirement_day_2: 'Ăn mừng cùng đồng nghiệp',
    log_retired_official_retirement_day_2: 'Đó là một lời chia tay đầy ý nghĩa với những người đã cùng tôi làm việc.',
    choice_retired_official_retirement_day_3: 'Ở nhà nghỉ ngơi vì thấy mệt',
    log_retired_official_retirement_day_3: 'Sau bao nhiêu năm, cuối cùng tôi cũng có thể nghỉ ngơi thực sự.',

    event_retired_first_pension_title: 'Lần đầu nhận lương hưu',
    event_retired_first_pension_desc: 'Bạn vừa nhận được khoản lương hưu đầu tiên.',
    choice_retired_first_pension_1: 'Gửi tiết kiệm',
    log_retired_first_pension_1: 'Tôi cần phải lên kế hoạch chi tiêu cho tương lai.',
    choice_retired_first_pension_2: 'Dùng để đi du lịch',
    log_retired_first_pension_2: 'Đây là cơ hội để thực hiện những chuyến đi tôi hằng ao ước.',
    choice_retired_first_pension_3: 'Cho con cháu một phần',
    log_retired_first_pension_3: 'Nhìn thấy con cháu vui vẻ là niềm hạnh phúc của tôi.',

    event_retired_health_checkup_title: 'Đi kiểm tra sức khỏe tổng quát',
    event_retired_health_checkup_desc: 'Đã đến lúc cần đi kiểm tra sức khỏe định kỳ.',
    choice_retired_health_checkup_1: 'Làm đầy đủ theo lời bác sĩ',
    log_retired_health_checkup_1: 'Sức khỏe là vốn quý nhất, tôi cần phải chăm sóc nó cẩn thận.',
    choice_retired_health_checkup_2: 'Bỏ qua vài xét nghiệm',
    log_retired_health_checkup_2: 'Tôi cảm thấy vẫn khỏe, không cần làm quá nhiều xét nghiệm.',
    choice_retired_health_checkup_3: 'Hoãn sang lần sau vì thấy mệt',
    log_retired_health_checkup_3: 'Tôi sẽ đi khám vào một ngày khác.',

    event_retired_volunteering_title: 'Tham gia hoạt động tình nguyện',
    event_retired_volunteering_desc: 'Bạn đang cân nhắc tham gia một hoạt động tình nguyện tại địa phương.',
    choice_retired_volunteering_1: 'Giúp tại thư viện',
    log_retired_volunteering_1: 'Công việc ở thư viện thật yên tĩnh và ý nghĩa.',
    choice_retired_volunteering_2: 'Giúp nhà dưỡng lão',
    log_retired_volunteering_2: 'Trò chuyện với những người bạn già khác mang lại cho tôi niềm vui.',
    choice_retired_volunteering_3: 'Giúp phát đồ ăn từ thiện',
    log_retired_volunteering_3: 'Giúp đỡ những người khó khăn khiến tôi cảm thấy cuộc sống có ý nghĩa hơn.',

    event_retired_long_trip_title: 'Đi du lịch dài ngày',
    event_retired_long_trip_desc: 'Đây là chuyến du lịch dài ngày đầu tiên của bạn sau khi nghỉ hưu.',
    choice_retired_long_trip_1: 'Đi road trip xuyên bang',
    log_retired_long_trip_1: 'Chuyến đi thật tuyệt vời với những cảnh đẹp ven đường.',
    choice_retired_long_trip_2: 'Đi cruise (du thuyền)',
    log_retired_long_trip_2: 'Tận hưởng biển cả và dịch vụ sang trọng thật thư giãn.',
    choice_retired_long_trip_3: 'Bay sang châu Âu',
    log_retired_long_trip_3: 'Khám phá những nền văn hóa mới là một trải nghiệm khó quên.',

    event_retired_amusement_park_title: 'Con cháu rủ đi công viên giải trí',
    event_retired_amusement_park_desc: 'Đàn cháu rủ bạn đi công viên giải trí.',
    choice_retired_amusement_park_1: 'Đi chơi hết trò mạo hiểm',
    log_retired_amusement_park_1: 'Tôi cảm thấy mình như trẻ lại 20 tuổi!',
    choice_retired_amusement_park_2: 'Chỉ đứng xem',
    log_retired_amusement_park_2: 'Nhìn thấy các cháu vui vẻ là tôi cũng vui rồi.',
    choice_retired_amusement_park_3: 'Ngồi nghỉ vì không theo kịp con cháu',
    log_retired_amusement_park_3: 'Sức khỏe không cho phép tôi chạy nhảy nhiều nữa.',

    event_retired_seniors_club_title: 'Gia nhập câu lạc bộ người cao tuổi',
    event_retired_seniors_club_desc: 'Bạn quyết định tham gia câu lạc bộ người cao tuổi ở địa phương.',
    choice_retired_seniors_club_1: 'Tham gia khiêu vũ',
    log_retired_seniors_club_1: 'Khiêu vũ giúp tôi cảm thấy khỏe khoắn và yêu đời hơn.',
    choice_retired_seniors_club_2: 'Chơi cờ cùng hội',
    log_retired_seniors_club_2: 'Những ván cờ cân não giúp trí óc tôi minh mẫn.',
    choice_retired_seniors_club_3: 'Chỉ ngồi nghe chuyện vì mệt',
    log_retired_seniors_club_3: 'Tôi thích nghe mọi người trò chuyện hơn.',

    event_retired_supermarket_sale_title: 'Đi siêu thị giảm giá',
    event_retired_supermarket_sale_desc: 'Bạn bè rủ bạn đi săn hàng giảm giá ở siêu thị.',
    choice_retired_supermarket_sale_1: 'Mua sắm hăng hái',
    log_retired_supermarket_sale_1: 'Tôi đã mua được rất nhiều món hời.',
    choice_retired_supermarket_sale_2: 'Đi dạo ngắm hàng',
    log_retired_supermarket_sale_2: 'Tôi chỉ đi xem cho vui thôi.',
    choice_retired_supermarket_sale_3: 'Ngồi chờ bạn mua sắm vì mỏi chân',
    log_retired_supermarket_sale_3: 'Đi bộ nhiều khiến tôi mỏi chân.',

    event_retired_class_reunion_title: 'Buổi họp mặt lớp cũ',
    event_retired_class_reunion_desc: 'Bạn tham dự buổi họp mặt lớp sau nhiều năm xa cách.',
    choice_retired_class_reunion_1: 'Tham gia trò chuyện nhiệt tình',
    log_retired_class_reunion_1: 'Thật tuyệt khi được ôn lại kỷ niệm xưa với bạn bè.',
    choice_retired_class_reunion_2: 'Hát cùng bạn cũ',
    log_retired_class_reunion_2: 'Chúng tôi đã cùng nhau hát lại những bài hát một thời.',
    choice_retired_class_reunion_3: 'Ngồi lắng nghe vì không còn nhớ nhiều',
    log_retired_class_reunion_3: 'Trí nhớ của tôi không còn tốt như xưa.',

    event_retired_family_dinner_title: 'Bữa cơm gia đình cuối tuần',
    event_retired_family_dinner_desc: 'Gia đình quây quần bên bữa cơm cuối tuần.',
    choice_retired_family_dinner_1: 'Giúp nấu ăn',
    log_retired_family_dinner_1: 'Tôi vẫn muốn tự tay chuẩn bị bữa ăn cho cả nhà.',
    choice_retired_family_dinner_2: 'Chơi với cháu',
    log_retired_family_dinner_2: 'Chơi với các cháu là niềm vui lớn nhất của tôi.',
    choice_retired_family_dinner_3: 'Ngồi nghỉ để con cháu lo liệu',
    log_retired_family_dinner_3: 'Đã đến lúc để thế hệ trẻ gánh vác.',
    
    // Triggered Events
    event_retired_feeling_empty_title: 'Dễ thấy trống trải',
    event_retired_feeling_empty_desc: 'Sau khi nghỉ hưu, bạn cảm thấy trống trải và thiếu mục đích.',
    choice_retired_feeling_empty_1: 'Đi dạo',
    log_retired_feeling_empty_1: 'Đi dạo giúp tôi khuây khỏa.',
    choice_retired_feeling_empty_2: 'Gọi điện bạn bè',
    log_retired_feeling_empty_2: 'Trò chuyện với bạn bè giúp tôi cảm thấy tốt hơn.',
    choice_retired_feeling_empty_3: 'Ngồi một mình suy nghĩ',
    log_retired_feeling_empty_3: 'Tôi cần thời gian để thích nghi với cuộc sống mới.',

    event_retired_insufficient_funds_title: 'Thấy tiền không đủ chi tiêu',
    event_retired_insufficient_funds_desc: 'Bạn nhận ra rằng lương hưu có thể không đủ cho các chi tiêu lâu dài.',
    choice_retired_insufficient_funds_1: 'Tìm việc làm thêm',
    log_retired_insufficient_funds_1: 'Tôi vẫn còn đủ sức khỏe để làm một công việc nhẹ nhàng.',
    choice_retired_insufficient_funds_2: 'Xin tư vấn tài chính',
    log_retired_insufficient_funds_2: 'Một chuyên gia đã giúp tôi lên kế hoạch chi tiêu hợp lý.',
    choice_retired_insufficient_funds_3: 'Tiết kiệm chi tiêu tối đa',
    log_retired_insufficient_funds_3: 'Tôi cần phải thắt chặt chi tiêu hơn nữa.',

    event_retired_illness_discovered_title: 'Phát hiện bệnh cần điều trị',
    event_retired_illness_discovered_desc: 'Kết quả kiểm tra sức khỏe cho thấy bạn có một căn bệnh cần điều trị.',
    choice_retired_illness_discovered_1: 'Nghe theo bác sĩ',
    log_retired_illness_discovered_1: 'Tôi tin tưởng vào y học hiện đại.',
    choice_retired_illness_discovered_2: 'Thử thuốc nam',
    log_retired_illness_discovered_2: 'Tôi muốn thử các phương pháp chữa trị tự nhiên.',
    choice_retired_illness_discovered_3: 'Chần chừ chưa chữa',
    log_retired_illness_discovered_3: 'Tôi cảm thấy sợ hãi và chưa muốn đối mặt với nó.',

    event_retired_cant_keep_up_volunteer_title: 'Không theo được tình nguyện',
    event_retired_cant_keep_up_volunteer_desc: 'Bạn nhận ra công việc tình nguyện đòi hỏi nhiều sức lực hơn bạn nghĩ.',
    choice_retired_cant_keep_up_volunteer_1: 'Xin nghỉ',
    log_retired_cant_keep_up_volunteer_1: 'Tôi đã xin nghỉ để giữ gìn sức khỏe.',
    choice_retired_cant_keep_up_volunteer_2: 'Chỉ hỗ trợ nhẹ',
    log_retired_cant_keep_up_volunteer_2: 'Tôi đã chuyển sang những công việc nhẹ nhàng hơn.',
    choice_retired_cant_keep_up_volunteer_3: 'Dừng hẳn',
    log_retired_cant_keep_up_volunteer_3: 'Tôi quyết định dừng hẳn việc tình nguyện.',

    event_retired_travel_fatigue_title: 'Mệt mỏi vì lịch trình du lịch',
    event_retired_travel_fatigue_desc: 'Lịch trình dày đặc của chuyến đi khiến bạn cảm thấy kiệt sức.',
    choice_retired_travel_fatigue_1: 'Nghỉ ngơi nhiều',
    log_retired_travel_fatigue_1: 'Tôi đã dành nhiều thời gian hơn để nghỉ ngơi.',
    choice_retired_travel_fatigue_2: 'Giảm bớt chuyến đi',
    log_retired_travel_fatigue_2: 'Chúng tôi đã hủy một vài điểm đến để có một chuyến đi thư giãn hơn.',
    choice_retired_travel_fatigue_3: 'Kết thúc chuyến sớm',
    log_retired_travel_fatigue_3: 'Sức khỏe là trên hết, chúng tôi quyết định về nhà sớm.',

    event_retired_heatstroke_title: 'Bị say nắng',
    event_retired_heatstroke_desc: 'Do thời tiết nóng bức, bạn bị say nắng và cần nghỉ ngơi.',
    choice_retired_heatstroke_1: 'Tìm chỗ mát',
    log_retired_heatstroke_1: 'Tôi đã tìm một nơi râm mát để nghỉ.',
    choice_retired_heatstroke_2: 'Uống nước',
    log_retired_heatstroke_2: 'Uống nhiều nước giúp tôi cảm thấy tốt hơn.',
    choice_retired_heatstroke_3: 'Về nhà nghỉ',
    log_retired_heatstroke_3: 'Tôi đã quyết định về nhà để nghỉ ngơi hoàn toàn.',

    event_retired_difficulty_integrating_title: 'Khó hòa nhập ban đầu',
    event_retired_difficulty_integrating_desc: 'Bạn cảm thấy khó hòa nhập với các thành viên khác trong câu lạc bộ.',
    choice_retired_difficulty_integrating_1: 'Kiên trì',
    log_retired_difficulty_integrating_1: 'Tôi đã kiên trì tham gia và dần dần kết bạn được.',
    choice_retired_difficulty_integrating_2: 'Tìm nhóm nhỏ hơn',
    log_retired_difficulty_integrating_2: 'Tôi đã tìm được một nhóm nhỏ hợp với mình hơn.',
    choice_retired_difficulty_integrating_3: 'Dừng không tham gia',
    log_retired_difficulty_integrating_3: 'Có lẽ nơi này không dành cho tôi.',

    event_retired_missed_promotions_title: 'Bỏ lỡ nhiều khuyến mãi',
    event_retired_missed_promotions_desc: 'Vì mỏi chân, bạn đã bỏ lỡ nhiều món hàng giảm giá tốt.',
    choice_retired_missed_promotions_1: 'Nhờ bạn mua hộ',
    log_retired_missed_promotions_1: 'Bạn tôi đã tốt bụng mua giúp tôi vài món.',
    choice_retired_missed_promotions_2: 'Lên mạng mua',
    log_retired_missed_promotions_2: 'Mua sắm trực tuyến tiện lợi hơn nhiều.',
    choice_retired_missed_promotions_3: 'Bỏ qua',
    log_retired_missed_promotions_3: 'Dù sao thì tôi cũng không thực sự cần chúng.',

    event_retired_loneliness_after_reunion_title: 'Cảm giác cô đơn sau họp lớp',
    event_retired_loneliness_after_reunion_desc: 'Sau buổi họp lớp, bạn cảm thấy một nỗi cô đơn khó tả.',
    choice_retired_loneliness_after_reunion_1: 'Gọi điện bạn',
    log_retired_loneliness_after_reunion_1: 'Trò chuyện với một người bạn thân đã giúp tôi cảm thấy tốt hơn.',
    choice_retired_loneliness_after_reunion_2: 'Viết nhật ký',
    log_retired_loneliness_after_reunion_2: 'Viết ra những suy nghĩ của mình giúp tôi giải tỏa cảm xúc.',
    choice_retired_loneliness_after_reunion_3: 'Ngồi buồn',
    log_retired_loneliness_after_reunion_3: 'Tôi chìm trong những ký ức xưa.',

    event_retired_lose_central_role_title: 'Thấy mình không còn vai trò trung tâm',
    event_retired_lose_central_role_desc: 'Bạn nhận ra rằng mình không còn là trung tâm của gia đình nữa.',
    choice_retired_lose_central_role_1: 'Chủ động hỗ trợ nhỏ',
    log_retired_lose_central_role_1: 'Tôi tìm thấy niềm vui trong việc giúp đỡ con cháu những việc nhỏ.',
    choice_retired_lose_central_role_2: 'Nói chuyện với con cháu',
    log_retired_lose_central_role_2: 'Tôi đã chia sẻ cảm xúc của mình với các con.',
    choice_retired_lose_central_role_3: 'Chấp nhận im lặng',
    log_retired_lose_central_role_3: 'Đây là quy luật tự nhiên của cuộc sống.',

    // Independent Events
    event_retired_morning_routine_title: 'Buổi sáng thường nhật',
    event_retired_morning_routine_desc: 'Một buổi sáng bình thường của một người đã nghỉ hưu.',
    choice_retired_morning_routine_1: 'Đi bộ thể dục',
    log_retired_morning_routine_1: 'Tập thể dục buổi sáng giúp tôi cảm thấy sảng khoái.',
    choice_retired_morning_routine_2: 'Ngồi đọc báo',
    log_retired_morning_routine_2: 'Cập nhật tin tức là một thói quen tốt.',
    choice_retired_morning_routine_3: 'Ở nhà nghỉ vì mệt',
    log_retired_morning_routine_3: 'Hôm nay tôi cảm thấy không được khỏe.',

    event_retired_watching_tv_title: 'Xem TV',
    event_retired_watching_tv_desc: 'Bạn đang dành thời gian xem TV.',
    choice_retired_watching_tv_1: 'Xem thời sự',
    log_retired_watching_tv_1: 'Tôi luôn muốn biết những gì đang xảy ra trên thế giới.',
    choice_retired_watching_tv_2: 'Xem phim cũ',
    log_retired_watching_tv_2: 'Những bộ phim cũ gợi lại nhiều kỷ niệm đẹp.',
    choice_retired_watching_tv_3: 'Ngủ gật khi xem',
    log_retired_watching_tv_3: 'Tôi đã ngủ thiếp đi lúc nào không hay.',
    
    event_retired_playing_with_grandkids_title: 'Chơi với cháu',
    event_retired_playing_with_grandkids_desc: 'Bạn đang dành thời gian chơi với các cháu.',
    choice_retired_playing_with_grandkids_1: 'Dẫn cháu đi chơi',
    log_retired_playing_with_grandkids_1: 'Chúng tôi đã có một ngày vui vẻ ở công viên.',
    choice_retired_playing_with_grandkids_2: 'Kể chuyện cổ tích',
    log_retired_playing_with_grandkids_2: 'Các cháu rất thích nghe tôi kể chuyện.',
    choice_retired_playing_with_grandkids_3: 'Ngồi nhìn cháu chơi vì mệt',
    log_retired_playing_with_grandkids_3: 'Nhìn chúng vui đùa là đủ rồi.',

    event_retired_meet_old_friend_title: 'Gặp bạn cũ',
    event_retired_meet_old_friend_desc: 'Bạn tình cờ gặp lại một người bạn cũ.',
    choice_retired_meet_old_friend_1: 'Trà chuyện trò',
    log_retired_meet_old_friend_1: 'Chúng tôi đã ngồi lại và ôn lại những câu chuyện xưa.',
    choice_retired_meet_old_friend_2: 'Cùng đi dạo',
    log_retired_meet_old_friend_2: 'Một cuộc đi dạo ngắn cũng đủ để hâm nóng tình bạn.',
    choice_retired_meet_old_friend_3: 'Ngồi nghe bạn kể',
    log_retired_meet_old_friend_3: 'Tôi thích lắng nghe câu chuyện của bạn mình hơn.',

    event_retired_grocery_shopping_title: 'Đi chợ',
    event_retired_grocery_shopping_desc: 'Đã đến lúc đi mua thực phẩm cho tuần.',
    choice_retired_grocery_shopping_1: 'Mua đồ đầy đủ',
    log_retired_grocery_shopping_1: 'Tôi đã mua đủ mọi thứ cần thiết.',
    choice_retired_grocery_shopping_2: 'Mua ít cho nhẹ',
    log_retired_grocery_shopping_2: 'Tôi không muốn mang vác nặng.',
    choice_retired_grocery_shopping_3: 'Ngồi quán nước chờ vì mỏi',
    log_retired_grocery_shopping_3: 'Tôi đã nhờ con cháu đi mua hộ.',
    
    event_retired_visiting_temple_title: 'Đi nhà thờ/chùa',
    event_retired_visiting_temple_desc: 'Bạn đến một nơi thờ tự để tìm sự bình yên.',
    choice_retired_visiting_temple_1: 'Tham gia lễ chính',
    log_retired_visiting_temple_1: 'Tôi cảm thấy tâm hồn thanh thản.',
    choice_retired_visiting_temple_2: 'Nói chuyện bạn đạo',
    log_retired_visiting_temple_2: 'Trò chuyện với những người cùng tín ngưỡng thật thú vị.',
    choice_retired_visiting_temple_3: 'Ngồi nghỉ ngoài sân',
    log_retired_visiting_temple_3: 'Không khí trong lành ở đây thật dễ chịu.',

    event_retired_grandchild_birthday_title: 'Sinh nhật con cháu',
    event_retired_grandchild_birthday_desc: 'Hôm nay là sinh nhật của một đứa cháu.',
    choice_retired_grandchild_birthday_1: 'Tặng quà',
    log_retired_grandchild_birthday_1: 'Món quà nhỏ của tôi đã làm nó rất vui.',
    choice_retired_grandchild_birthday_2: 'Chụp ảnh kỷ niệm',
    log_retired_grandchild_birthday_2: 'Những bức ảnh sẽ lưu giữ lại khoảnh khắc này.',
    choice_retired_grandchild_birthday_3: 'Ngồi xem các cháu vui',
    log_retired_grandchild_birthday_3: 'Niềm vui của chúng là niềm vui của tôi.',

    event_retired_visit_children_title: 'Thăm con xa',
    event_retired_visit_children_desc: 'Bạn đang cân nhắc đi thăm đứa con đang sống ở xa.',
    choice_retired_visit_children_1: 'Đi xe bus',
    log_retired_visit_children_1: 'Chuyến đi hơi mệt nhưng rất đáng giá.',
    choice_retired_visit_children_2: 'Đi máy bay',
    log_retired_visit_children_2: 'Đi máy bay nhanh và tiện lợi hơn.',
    choice_retired_visit_children_3: 'Quyết định không đi vì mệt',
    log_retired_visit_children_3: 'Tôi sẽ đợi chúng về thăm.',

    event_retired_hot_afternoon_title: 'Buổi trưa nắng nóng',
    event_retired_hot_afternoon_desc: 'Thời tiết buổi trưa rất nóng nực và oi ả.',
    choice_retired_hot_afternoon_1: 'Ngủ trưa',
    log_retired_hot_afternoon_1: 'Một giấc ngủ trưa giúp tôi lấy lại năng lượng.',
    choice_retired_hot_afternoon_2: 'Uống nước mát',
    log_retired_hot_afternoon_2: 'Một ly nước mát thật sảng khoái.',
    choice_retired_hot_afternoon_3: 'Nằm nghỉ cả chiều',
    log_retired_hot_afternoon_3: 'Tôi không muốn làm gì cả trong thời tiết này.',

    event_retired_park_visit_title: 'Đi công viên',
    event_retired_park_visit_desc: 'Bạn đi dạo ở công viên gần nhà.',
    choice_retired_park_visit_1: 'Tập dưỡng sinh',
    log_retired_park_visit_1: 'Tập dưỡng sinh giúp cơ thể tôi dẻo dai hơn.',
    choice_retired_park_visit_2: 'Ngồi nói chuyện',
    log_retired_park_visit_2: 'Tôi đã có một cuộc trò chuyện vui vẻ với những người bạn già.',
    choice_retired_park_visit_3: 'Ngồi yên ngắm cảnh',
    log_retired_park_visit_3: 'Ngắm nhìn thiên nhiên thật yên bình.',

    event_retired_village_festival_title: 'Đi hội làng',
    event_retired_village_festival_desc: 'Ngôi làng đang tổ chức lễ hội truyền thống.',
    choice_retired_village_festival_1: 'Xem văn nghệ',
    log_retired_village_festival_1: 'Các tiết mục văn nghệ thật đặc sắc.',
    choice_retired_village_festival_2: 'Ăn quà vặt',
    log_retired_village_festival_2: 'Những món ăn vặt ở đây thật ngon.',
    choice_retired_village_festival_3: 'Ngồi nghỉ dưới bóng cây',
    log_retired_village_festival_3: 'Không khí lễ hội thật náo nhiệt.',

    event_retired_new_class_title: 'Tham gia lớp học mới',
    event_retired_new_class_desc: 'Bạn quyết định tham gia một lớp học mới như vẽ hoặc nhạc.',
    choice_retired_new_class_1: 'Hăng hái học',
    log_retired_new_class_1: 'Học một kỹ năng mới khiến tôi cảm thấy trẻ ra.',
    choice_retired_new_class_2: 'Thử vài buổi',
    log_retired_new_class_2: 'Tôi đã thử vài buổi để xem có hợp không.',
    choice_retired_new_class_3: 'Nghỉ vì thấy khó',
    log_retired_new_class_3: 'Nó khó hơn tôi tưởng.',

    event_retired_periodic_checkup_title: 'Khám bệnh định kỳ',
    event_retired_periodic_checkup_desc: 'Đã đến lúc đi khám bệnh định kỳ.',
    choice_retired_periodic_checkup_1: 'Làm đủ xét nghiệm',
    log_retired_periodic_checkup_1: 'Tôi muốn chắc chắn về sức khỏe của mình.',
    choice_retired_periodic_checkup_2: 'Làm một nửa',
    log_retired_periodic_checkup_2: 'Tôi chỉ làm những xét nghiệm cần thiết nhất.',
    choice_retired_periodic_checkup_3: 'Hủy vì mệt',
    log_retired_periodic_checkup_3: 'Tôi cảm thấy không muốn đi khám hôm nay.',

    event_retired_rainy_day_title: 'Ngày mưa',
    event_retired_rainy_day_desc: 'Một ngày mưa buồn và ảm đạm.',
    choice_retired_rainy_day_1: 'Ngồi đọc sách',
    log_retired_rainy_day_1: 'Đọc sách bên cửa sổ mưa là một thú vui tao nhã.',
    choice_retired_rainy_day_2: 'Ngủ trưa',
    log_retired_rainy_day_2: 'Tiếng mưa rơi là bài hát ru tuyệt vời nhất.',
    choice_retired_rainy_day_3: 'Ngồi nhìn mưa',
    log_retired_rainy_day_3: 'Tôi chỉ ngồi yên và ngắm nhìn những hạt mưa.',

    event_retired_visit_relatives_title: 'Đi thăm họ hàng',
    event_retired_visit_relatives_desc: 'Bạn đi thăm họ hàng ở xa.',
    choice_retired_visit_relatives_1: 'Trò chuyện vui',
    log_retired_visit_relatives_1: 'Gặp gỡ họ hàng luôn là một dịp vui vẻ.',
    choice_retired_visit_relatives_2: 'Ăn cùng họ',
    log_retired_visit_relatives_2: 'Bữa cơm gia đình thật ấm cúng.',
    choice_retired_visit_relatives_3: 'Ngồi yên nghe chuyện',
    log_retired_visit_relatives_3: 'Tôi thích lắng nghe câu chuyện của mọi người.',

    event_retired_watching_sports_title: 'Xem thể thao',
    event_retired_watching_sports_desc: 'Bạn đang xem một trận đấu thể thao trên TV.',
    choice_retired_watching_sports_1: 'Cổ vũ đội yêu thích',
    log_retired_watching_sports_1: 'Trận đấu thật hấp dẫn!',
    choice_retired_watching_sports_2: 'Nói chuyện cùng bạn',
    log_retired_watching_sports_2: 'Xem cùng bạn bè vui hơn nhiều.',
    choice_retired_watching_sports_3: 'Ngủ gật giữa chừng',
    log_retired_watching_sports_3: 'Tôi đã ngủ quên mất lúc nào không hay.',

    event_retired_insomnia_title: 'Mất ngủ',
    event_retired_insomnia_desc: 'Bạn không thể ngủ được vào ban đêm.',
    choice_retired_insomnia_1: 'Đếm cừu',
    log_retired_insomnia_1: 'Đếm đến con cừu thứ 1000 mà tôi vẫn tỉnh.',
    choice_retired_insomnia_2: 'Uống sữa',
    log_retired_insomnia_2: 'Một ly sữa ấm giúp tôi dễ ngủ hơn.',
    choice_retired_insomnia_3: 'Ngồi yên chờ sáng',
    log_retired_insomnia_3: 'Lại một đêm dài nữa.',

    event_retired_community_festival_title: 'Lễ hội cộng đồng',
    event_retired_community_festival_desc: 'Cộng đồng nơi bạn ở đang tổ chức một lễ hội.',
    choice_retired_community_festival_1: 'Tham gia nhiệt tình',
    log_retired_community_festival_1: 'Tôi đã có một khoảng thời gian tuyệt vời.',
    choice_retired_community_festival_2: 'Đi dạo quanh',
    log_retired_community_festival_2: 'Tôi chỉ đi dạo một vòng để xem không khí.',
    choice_retired_community_festival_3: 'Ngồi nghỉ sớm vì mệt',
    log_retired_community_festival_3: 'Tôi không còn đủ sức để tham gia lâu.',

    event_retired_surprise_gift_title: 'Nhận quà bất ngờ',
    event_retired_surprise_gift_desc: 'Bạn nhận được một món quà bất ngờ từ một người bạn cũ.',
    choice_retired_surprise_gift_1: 'Vui mừng',
    log_retired_surprise_gift_1: 'Món quà thật ý nghĩa!',
    choice_retired_surprise_gift_2: 'Cảm động',
    log_retired_surprise_gift_2: 'Tôi rất xúc động trước tấm lòng của bạn.',
    choice_retired_surprise_gift_3: 'Ngại ngùng',
    log_retired_surprise_gift_3: 'Tôi không biết phải làm gì để đáp lại.',

    event_retired_sharing_with_grandkids_title: 'Chia sẻ đồ ăn với cháu',
    event_retired_sharing_with_grandkids_desc: 'Bạn có một món ăn ngon và các cháu đang nhìn.',
    choice_retired_sharing_with_grandkids_1: 'Cho cháu nhiều',
    log_retired_sharing_with_grandkids_1: 'Tôi dành phần ngon nhất cho các cháu.',
    choice_retired_sharing_with_grandkids_2: 'Chia đều',
    log_retired_sharing_with_grandkids_2: 'Mỗi người một phần.',
    choice_retired_sharing_with_grandkids_3: 'Giữ phần nhỏ cho mình',
    log_retired_sharing_with_grandkids_3: 'Tôi cũng muốn ăn một chút.',
};
