export default {
    // Main Events
    event_university_first_day_title: 'Ngày nhập học đầu tiên',
    event_university_first_day_desc: 'Hôm nay là ngày đầu tiên của bạn ở trường đại học, một khởi đầu mới.',
    choice_university_first_day_1: 'Tham gia đầy đủ',
    log_university_first_day_1: 'Tôi đã tham gia tất cả các sự kiện định hướng và kết bạn mới.',
    choice_university_first_day_2: 'Ngủ quên',
    log_university_first_day_2: 'Tôi đã ngủ quên và bỏ lỡ lễ chào mừng.',
    choice_university_first_day_3: 'Đi trễ một chút',
    log_university_first_day_3: 'Tôi đến hơi muộn nhưng đã bắt kịp.',

    event_university_forgot_registration_title: 'Quên đăng ký môn học',
    event_university_forgot_registration_desc: 'Bạn đã quên đăng ký môn học đúng hạn.',
    choice_university_forgot_registration_1: 'Nhờ thầy/cố vấn giúp',
    log_university_forgot_registration_1: 'Cố vấn đã giúp tôi vào được các lớp tôi cần.',
    choice_university_forgot_registration_2: 'Đăng ký trễ',
    log_university_forgot_registration_2: 'Tôi phải đăng ký muộn và một số lớp đã hết chỗ.',
    choice_university_forgot_registration_3: 'Quyết định đăng ký muộn kỳ sau',
    log_university_forgot_registration_3: 'Tôi quyết định thư giãn học kỳ này và đăng ký nhiều môn hơn sau.',

    event_university_noisy_roommate_title: 'Bạn cùng phòng ồn ào',
    event_university_noisy_roommate_desc: 'Bạn cùng phòng của bạn mở nhạc ầm ĩ suốt đêm.',
    choice_university_noisy_roommate_1: 'Nói chuyện thẳng thắn',
    log_university_noisy_roommate_1: 'Chúng tôi đã nói chuyện và đồng ý về một số giờ yên tĩnh.',
    choice_university_noisy_roommate_2: 'Phàn nàn với quản lý ký túc',
    log_university_noisy_roommate_2: 'Tôi đã báo cáo vấn đề với Quản lý Ký túc xá.',
    choice_university_noisy_roommate_3: 'Đeo tai nghe để chịu đựng',
    log_university_noisy_roommate_3: 'Tôi quyết định chỉ cần chặn tiếng ồn bằng tai nghe của mình.',

    event_university_group_presentation_title: 'Thuyết trình nhóm',
    event_university_group_presentation_desc: 'Bạn có một bài thuyết trình nhóm trước lớp.',
    choice_university_group_presentation_1: 'Chuẩn bị kỹ',
    log_university_group_presentation_1: 'Nhóm chúng tôi đã làm việc chăm chỉ và có một bài thuyết trình tuyệt vời.',
    choice_university_group_presentation_2: 'Đùn đẩy việc',
    log_university_group_presentation_2: 'Tôi đã không làm phần việc của mình.',
    choice_university_group_presentation_3: 'Không chuẩn bị gì',
    log_university_group_presentation_3: 'Tôi hoàn toàn không chuẩn bị cho bài thuyết trình.',

    event_university_midterm_exam_title: 'Thi giữa kỳ',
    event_university_midterm_exam_desc: 'Đã đến lúc thi giữa kỳ.',
    choice_university_midterm_exam_1: 'Học đầy đủ',
    log_university_midterm_exam_1: 'Tôi đã học chăm chỉ và cảm thấy tự tin cho kỳ thi.',
    choice_university_midterm_exam_2: 'Học tủ',
    log_university_midterm_exam_2: 'Tôi đã thức cả đêm để học tủ cho bài kiểm tra.',
    choice_university_midterm_exam_3: 'Không đi thi',
    log_university_midterm_exam_3: 'Tôi quyết định bỏ thi.',

    event_university_football_game_title: 'Trận bóng đá của trường',
    event_university_football_game_desc: 'Có một trận bóng đá lớn của đội tuyển trường.',
    choice_university_football_game_1: 'Đi cổ vũ nhiệt tình',
    log_university_football_game_1: 'Tôi đã đến trận đấu và cổ vũ hết mình cho đội của chúng tôi.',
    choice_university_football_game_2: 'Bỏ học đi xem',
    log_university_football_game_2: 'Trận đấu hôm nay quan trọng hơn lớp học.',
    choice_university_football_game_3: 'Ở ký túc ngủ/đi làm thêm',
    log_university_football_game_3: 'Tôi quyết định ngủ bù thay vì đi xem trận đấu.',

    event_university_dorm_party_title: 'Tiệc trong ký túc xá',
    event_university_dorm_party_desc: 'Có một bữa tiệc trong ký túc xá của bạn.',
    choice_university_dorm_party_1: 'Tham gia vui vẻ',
    log_university_dorm_party_1: 'Tôi đã đến bữa tiệc và đã có một khoảng thời gian tuyệt vời.',
    choice_university_dorm_party_2: 'Uống quá nhiều',
    log_university_dorm_party_2: 'Tôi đã uống hơi quá và mọi thứ trở nên mờ ảo.',
    choice_university_dorm_party_3: 'Ngồi một góc chơi điện thoại',
    log_university_dorm_party_3: 'Tiệc tùng không thực sự là sở thích của tôi, nên tôi chỉ ngồi một mình.',

    event_university_internship_interview_title: 'Phỏng vấn xin việc thực tập',
    event_university_internship_interview_desc: 'Bạn có một cuộc phỏng vấn xin thực tập.',
    choice_university_internship_interview_1: 'Chuẩn bị kỹ lưỡng',
    log_university_internship_interview_1: 'Tôi đã nghiên cứu công ty và luyện tập các câu trả lời của mình.',
    choice_university_internship_interview_2: 'Đến muộn',
    log_university_internship_interview_2: 'Tôi đã đánh giá sai tình hình giao thông và đến muộn.',
    choice_university_internship_interview_3: 'Trả lời qua loa',
    log_university_internship_interview_3: 'Tôi không thực sự coi trọng cuộc phỏng vấn này.',

    event_university_night_class_title: 'Đi học buổi tối',
    event_university_night_class_desc: 'Bạn có một lớp học buổi tối.',
    choice_university_night_class_1: 'Chăm chú nghe giảng',
    log_university_night_class_1: 'Tôi đã chú ý và ghi chép cẩn thận.',
    choice_university_night_class_2: 'Lén chơi điện thoại',
    log_university_night_class_2: 'Tôi đã chán và lướt điện thoại.',
    choice_university_night_class_3: 'Học nhóm với bạn',
    log_university_night_class_3: 'Chúng tôi đã làm việc cùng nhau và giúp nhau hiểu bài.',

    event_university_submit_essay_title: 'Nộp bài tiểu luận',
    event_university_submit_essay_desc: 'Bạn có một bài tiểu luận phải nộp.',
    choice_university_submit_essay_1: 'Nộp đúng hạn',
    log_university_submit_essay_1: 'Tôi đã hoàn thành bài tiểu luận và nộp trước thời hạn.',
    choice_university_submit_essay_2: 'Nộp trễ',
    log_university_submit_essay_2: 'Tôi không thể hoàn thành đúng hạn và phải nộp muộn.',
    choice_university_submit_essay_3: 'Không nộp luôn',
    log_university_submit_essay_3: 'Tôi đã không làm bài tập.',

    // Triggered Events
    event_university_missed_info_title: 'Bỏ lỡ thông tin quan trọng',
    event_university_missed_info_desc: 'Bạn đã bỏ lỡ một số thông tin quan trọng vì ngủ quên.',
    choice_university_missed_info_1: 'Hỏi lại bạn',
    log_university_missed_info_1: 'Bạn tôi đã kể cho tôi nghe những gì tôi đã bỏ lỡ.',
    choice_university_missed_info_2: 'Đọc email trường gửi',
    log_university_missed_info_2: 'Tôi đã tìm thấy thông tin trong một email từ trường.',
    choice_university_missed_info_3: 'Đoán mò',
    log_university_missed_info_3: 'Tôi chỉ cố gắng đoán những gì tôi đã bỏ lỡ.',

    event_university_class_full_title: 'Hết chỗ môn cần học',
    event_university_class_full_desc: 'Lớp học bắt buộc bạn muốn tham gia đã hết chỗ.',
    choice_university_class_full_1: 'Chọn môn khác',
    log_university_class_full_1: 'Tôi đã phải chọn một môn tự chọn khác.',
    choice_university_class_full_2: 'Xin vào danh sách chờ',
    log_university_class_full_2: 'Tôi đã ghi tên mình vào danh sách chờ và hy vọng điều tốt nhất.',
    choice_university_class_full_3: 'Nhờ giáo sư mở thêm lớp',
    log_university_class_full_3: 'Tôi đã gửi email cho giáo sư để xem liệu họ có thể thêm sinh viên không.',

    event_university_roommate_angry_title: 'Bạn cùng phòng giận',
    event_university_roommate_angry_desc: 'Bạn cùng phòng của bạn tức giận vì bạn đã phàn nàn về họ.',
    choice_university_roommate_angry_1: 'Xin lỗi',
    log_university_roommate_angry_1: 'Tôi đã xin lỗi để mọi chuyện êm xuôi.',
    choice_university_roommate_angry_2: 'Giải thích',
    log_university_roommate_angry_2: 'Tôi đã cố gắng giải thích quan điểm của mình.',
    choice_university_roommate_angry_3: 'Im lặng chiến tranh lạnh',
    log_university_roommate_angry_3: 'Chúng tôi chỉ lờ nhau đi.',

    event_university_group_dislikes_you_title: 'Cả nhóm ghét',
    event_university_group_dislikes_you_desc: 'Nhóm của bạn không thích bạn vì đã đùn đẩy trách nhiệm.',
    choice_university_group_dislikes_you_1: 'Cố gắng làm phần còn lại',
    log_university_group_dislikes_you_1: 'Tôi đã cố gắng bù đắp bằng cách làm phần còn lại của công việc.',
    choice_university_group_dislikes_you_2: 'Xin lỗi',
    log_university_group_dislikes_you_2: 'Tôi đã xin lỗi các thành viên trong nhóm.',
    choice_university_group_dislikes_you_3: 'Bị loại khỏi nhóm',
    log_university_group_dislikes_you_3: 'Họ đã đuổi tôi ra khỏi nhóm.',

    event_university_exam_off_topic_title: 'Đề thi không đúng phần học tủ',
    event_university_exam_off_topic_desc: 'Các câu hỏi trong bài kiểm tra không thuộc các chủ đề bạn đã học tủ.',
    choice_university_exam_off_topic_1: 'Lo lắng cố gắng làm',
    log_university_exam_off_topic_1: 'Tôi đã cố gắng hết sức để trả lời những gì có thể.',
    choice_university_exam_off_topic_2: 'Bỏ qua câu khó',
    log_university_exam_off_topic_2: 'Tôi đã bỏ qua những câu hỏi tôi không biết.',
    choice_university_exam_off_topic_3: 'Nộp bài sớm',
    log_university_exam_off_topic_3: 'Tôi đã từ bỏ và nộp bài sớm.',

    event_university_marked_absent_title: 'Bị thầy ghi tên vắng',
    event_university_marked_absent_desc: 'Giáo viên đã ghi bạn vắng mặt vì bỏ học đi xem trận đấu.',
    choice_university_marked_absent_1: 'Xin lỗi',
    log_university_marked_absent_1: 'Tôi đã xin lỗi giáo viên.',
    choice_university_marked_absent_2: 'Đổ lỗi giao thông',
    log_university_marked_absent_2: 'Tôi đã bịa ra một lý do về giao thông.',
    choice_university_marked_absent_3: 'Chấp nhận bị trừ điểm',
    log_university_marked_absent_3: 'Tôi đã chấp nhận hậu quả.',

    event_university_caught_by_ra_title: 'Bị quản lý ký túc phát hiện',
    event_university_caught_by_ra_desc: 'Quản lý ký túc xá đã bắt gặp bạn uống quá nhiều.',
    choice_university_caught_by_ra_1: 'Giải thích do bạn bè ép',
    log_university_caught_by_ra_1: 'Tôi đã cố giải thích rằng đó không phải là ý của tôi.',
    choice_university_caught_by_ra_2: 'Im lặng chấp nhận',
    log_university_caught_by_ra_2: 'Tôi không tranh cãi và chấp nhận bị phạt.',
    choice_university_caught_by_ra_3: 'Xin lỗi',
    log_university_caught_by_ra_3: 'Tôi đã xin lỗi vì hành vi của mình.',

    event_university_rejected_immediately_title: 'Bị loại ngay',
    event_university_rejected_immediately_desc: 'Bạn đã bị loại ngay lập tức vì đến muộn phỏng vấn.',
    choice_university_rejected_immediately_1: 'Xin cơ hội khác',
    log_university_rejected_immediately_1: 'Tôi đã hỏi liệu có thể sắp xếp lại lịch không.',
    choice_university_rejected_immediately_2: 'Đổ lỗi giao thông',
    log_university_rejected_immediately_2: 'Tôi đã cố giải thích về tình hình giao thông.',
    choice_university_rejected_immediately_3: 'Bỏ luôn không xin nữa',
    log_university_rejected_immediately_3: 'Tôi quyết định không theo đuổi cơ hội thực tập này nữa.',

    event_university_reprimanded_by_teacher_title: 'Bị giáo viên nhắc nhở',
    event_university_reprimanded_by_teacher_desc: 'Giáo viên đã nhắc nhở bạn vì chơi trên điện thoại.',
    choice_university_reprimanded_by_teacher_1: 'Cất điện thoại',
    log_university_reprimanded_by_teacher_1: 'Tôi đã cất điện thoại và chú ý.',
    choice_university_reprimanded_by_teacher_2: 'Lén tiếp tục',
    log_university_reprimanded_by_teacher_2: 'Tôi đã cố gắng kín đáo hơn.',
    choice_university_reprimanded_by_teacher_3: 'Giải thích đang tra cứu bài',
    log_university_reprimanded_by_teacher_3: 'Tôi khẳng định tôi đang dùng nó để nghiên cứu.',

    event_university_points_deducted_title: 'Bị trừ điểm',
    event_university_points_deducted_desc: 'Điểm của bạn đã bị trừ vì nộp bài tiểu luận muộn.',
    choice_university_points_deducted_1: 'Xin tha',
    log_university_points_deducted_1: 'Tôi đã hỏi giáo sư liệu họ có thể bỏ qua không.',
    choice_university_points_deducted_2: 'Chấp nhận điểm thấp',
    log_university_points_deducted_2: 'Tôi đã chấp nhận bị phạt.',
    choice_university_points_deducted_3: 'Đổ lỗi máy hỏng',
    log_university_points_deducted_3: 'Tôi nói rằng tôi gặp sự cố máy tính.',

    // Independent Events
    event_university_choose_elective_title: 'Chọn môn tự chọn',
    event_university_choose_elective_desc: 'Bạn đang chọn một môn học tự chọn.',
    choice_university_choose_elective_1: 'Chọn môn dễ',
    log_university_choose_elective_1: 'Tôi đã chọn một lớp dễ để tăng điểm trung bình.',
    choice_university_choose_elective_2: 'Chọn môn theo sở thích',
    log_university_choose_elective_2: 'Tôi đã chọn một lớp mà tôi thực sự quan tâm.',
    choice_university_choose_elective_3: 'Chọn theo bạn bè',
    log_university_choose_elective_3: 'Tôi đã đăng ký cùng lớp với bạn bè của mình.',

    event_university_library_visit_title: 'Đi thư viện',
    event_university_library_visit_desc: 'Bạn đang ở thư viện.',
    choice_university_library_visit_1: 'Học nghiêm túc',
    log_university_library_visit_1: 'Tôi đã có một buổi học hiệu quả.',
    choice_university_library_visit_2: 'Ngủ gục',
    log_university_library_visit_2: 'Tôi vô tình ngủ gật khi đang học.',
    choice_university_library_visit_3: 'Lướt mạng',
    log_university_library_visit_3: 'Tôi bị phân tâm và dành thời gian lướt web.',

    event_university_join_club_title: 'Tham gia câu lạc bộ',
    event_university_join_club_desc: 'Bạn đang nghĩ đến việc tham gia một câu lạc bộ.',
    choice_university_join_club_1: 'Nhiệt tình hoạt động',
    log_university_join_club_1: 'Tôi đã trở thành một thành viên tích cực của câu lạc bộ.',
    choice_university_join_club_2: 'Tham gia cho vui',
    log_university_join_club_2: 'Tôi chỉ tham gia để đi chơi với bạn bè.',
    choice_university_join_club_3: 'Bỏ ngang',
    log_university_join_club_3: 'Tôi mất hứng thú và rời câu lạc bộ.',

    event_university_professor_praise_title: 'Được giáo sư khen',
    event_university_professor_praise_desc: 'Một giáo sư đã khen ngợi bạn.',
    choice_university_professor_praise_1: 'Vui mừng',
    log_university_professor_praise_1: 'Thật tuyệt khi được công nhận.',
    choice_university_professor_praise_2: 'Ngại ngùng',
    log_university_professor_praise_2: 'Tôi hơi xấu hổ vì lời khen.',
    choice_university_professor_praise_3: 'Giả vờ bình thường',
    log_university_professor_praise_3: 'Tôi đã hành động như thể đó không phải là chuyện lớn.',

    event_university_professor_criticism_title: 'Bị giáo sư phê bình',
    event_university_professor_criticism_desc: 'Một giáo sư đã phê bình bạn.',
    choice_university_professor_criticism_1: 'Im lặng',
    log_university_professor_criticism_1: 'Tôi đã im lặng nhận lời phê bình.',
    choice_university_professor_criticism_2: 'Cãi lại',
    log_university_professor_criticism_2: 'Tôi đã cố gắng bảo vệ công việc của mình.',
    choice_university_professor_criticism_3: 'Xin lỗi',
    log_university_professor_criticism_3: 'Tôi đã xin lỗi vì sai lầm của mình.',

    event_university_part_time_job_title: 'Đi làm thêm',
    event_university_part_time_job_desc: 'Bạn đang làm một công việc bán thời gian.',
    choice_university_part_time_job_1: 'Làm chăm chỉ',
    log_university_part_time_job_1: 'Tôi đã làm việc chăm chỉ và kiếm được một ít tiền tiêu vặt.',
    choice_university_part_time_job_2: 'Lười biếng',
    log_university_part_time_job_2: 'Tôi đã hơi lơ là trong công việc.',
    choice_university_part_time_job_3: 'Học việc nhanh',
    log_university_part_time_job_3: 'Tôi đã nhanh chóng học được các kỹ năng cho công việc.',

    event_university_study_group_title: 'Buổi học nhóm',
    event_university_study_group_desc: 'Bạn đang trong một buổi học nhóm.',
    choice_university_study_group_1: 'Học nghiêm túc',
    log_university_study_group_1: 'Chúng tôi tập trung vào việc học.',
    choice_university_study_group_2: 'Tám chuyện',
    log_university_study_group_2: 'Cuối cùng chúng tôi chỉ tán gẫu thay vì học.',
    choice_university_study_group_3: 'Ngồi nghe',
    log_university_study_group_3: 'Tôi để bạn bè giải thích nhiều hơn.',

    event_university_class_trip_title: 'Dã ngoại cùng lớp',
    event_university_class_trip_desc: 'Bạn đang đi dã ngoại cùng lớp.',
    choice_university_class_trip_1: 'Tham gia trò chơi',
    log_university_class_trip_1: 'Các trò chơi rất vui.',
    choice_university_class_trip_2: 'Ngồi ăn uống',
    log_university_class_trip_2: 'Tôi tập trung vào đồ ăn.',
    choice_university_class_trip_3: 'Đi chụp ảnh',
    log_university_class_trip_3: 'Tôi đã chụp rất nhiều ảnh phong cảnh.',

    event_university_surprise_test_title: 'Kiểm tra bất ngờ',
    event_university_surprise_test_desc: 'Có một bài kiểm tra bất ngờ trong lớp.',
    choice_university_surprise_test_1: 'Làm nghiêm túc',
    log_university_surprise_test_1: 'Tôi đã làm hết sức mình trong bài kiểm tra bất ngờ.',
    choice_university_surprise_test_2: 'Nhìn bài bạn',
    log_university_surprise_test_2: 'Tôi cần một chút giúp đỡ.',
    choice_university_surprise_test_3: 'Đoán mò',
    log_university_surprise_test_3: 'Tôi đã phải đoán hầu hết các câu trả lời.',

    event_university_club_interview_title: 'Phỏng vấn câu lạc bộ',
    event_university_club_interview_desc: 'Bạn có một cuộc phỏng vấn để tham gia một câu lạc bộ.',
    choice_university_club_interview_1: 'Chuẩn bị kỹ',
    log_university_club_interview_1: 'Tôi đã chuẩn bị kỹ cho cuộc phỏng vấn.',
    choice_university_club_interview_2: 'Trả lời tự tin',
    log_university_club_interview_2: 'Tôi đã trả lời tất cả các câu hỏi một cách tự tin.',
    choice_university_club_interview_3: 'Nói ngập ngừng',
    log_university_club_interview_3: 'Tôi lo lắng và nói lắp bắp.',

    event_university_sports_day_title: 'Ngày hội thể thao',
    event_university_sports_day_desc: 'Hôm nay là ngày hội thể thao của trường đại học.',
    choice_university_sports_day_1: 'Chơi bóng',
    log_university_sports_day_1: 'Tôi đã chơi trong một trận bóng rổ.',
    choice_university_sports_day_2: 'Chạy',
    log_university_sports_day_2: 'Tôi đã tham gia một cuộc thi chạy.',
    choice_university_sports_day_3: 'Ngồi cổ vũ',
    log_university_sports_day_3: 'Tôi đã cổ vũ cho bạn bè.',

    event_university_friends_party_title: 'Tiệc bạn bè',
    event_university_friends_party_desc: 'Bạn đang ở một bữa tiệc với bạn bè.',
    choice_university_friends_party_1: 'Tham gia nhiệt tình',
    log_university_friends_party_1: 'Tôi đã có một khoảng thời gian tuyệt vời tại bữa tiệc.',
    choice_university_friends_party_2: 'Ngồi một góc',
    log_university_friends_party_2: 'Tôi ngồi một mình.',
    choice_university_friends_party_3: 'Ra về sớm',
    log_university_friends_party_3: 'Tôi không có tâm trạng tiệc tùng và đã về sớm.',

    event_university_museum_visit_title: 'Tham quan bảo tàng',
    event_university_museum_visit_desc: 'Bạn đang tham quan một bảo tàng.',
    choice_university_museum_visit_1: 'Nghe hướng dẫn',
    log_university_museum_visit_1: 'Tôi đã học được rất nhiều từ hướng dẫn viên.',
    choice_university_museum_visit_2: 'Đi loanh quanh',
    log_university_museum_visit_2: 'Tôi chỉ tự mình khám phá bảo tàng.',
    choice_university_museum_visit_3: 'Chụp ảnh',
    log_university_museum_visit_3: 'Tôi đã chụp rất nhiều ảnh.',

    event_university_major_group_project_title: 'Bài tập lớn nhóm',
    event_university_major_group_project_desc: 'Bạn có một bài tập lớn nhóm.',
    choice_university_major_group_project_1: 'Làm hết mình',
    log_university_major_group_project_1: 'Tôi đã đóng góp rất nhiều cho dự án.',
    choice_university_major_group_project_2: 'Đùn đẩy',
    log_university_major_group_project_2: 'Tôi để các thành viên trong nhóm làm hầu hết công việc.',
    choice_university_major_group_project_3: 'Làm một phần',
    log_university_major_group_project_3: 'Tôi chỉ làm phần việc được giao.',

    event_university_holiday_festival_title: 'Lễ hội ở trường',
    event_university_holiday_festival_desc: 'Trường đại học đang tổ chức một lễ hội.',
    choice_university_holiday_festival_1: 'Tham gia lễ hội',
    log_university_holiday_festival_1: 'Lễ hội rất vui.',
    choice_university_holiday_festival_2: 'Ở ký túc',
    log_university_holiday_festival_2: 'Tôi thích ở lại và thư giãn hơn.',
    choice_university_holiday_festival_3: 'Đi chơi riêng',
    log_university_holiday_festival_3: 'Tôi đã tự lên kế hoạch với bạn bè.',

    event_university_meet_professor_outside_title: 'Gặp giáo sư ngoài trường',
    event_university_meet_professor_outside_desc: 'Bạn gặp một giáo sư ở ngoài trường đại học.',
    choice_university_meet_professor_outside_1: 'Chào hỏi',
    log_university_meet_professor_outside_1: 'Tôi đã chào giáo sư của mình.',
    choice_university_meet_professor_outside_2: 'Cười gượng',
    log_university_meet_professor_outside_2: 'Hơi khó xử một chút.',
    choice_university_meet_professor_outside_3: 'Giả vờ không thấy',
    log_university_meet_professor_outside_3: 'Tôi đã tránh họ.',

    event_university_online_class_title: 'Học online',
    event_university_online_class_desc: 'Bạn đang tham gia một lớp học trực tuyến.',
    choice_university_online_class_1: 'Chăm chú',
    log_university_online_class_1: 'Tôi tập trung vào bài giảng trực tuyến.',
    choice_university_online_class_2: 'Mở tab khác',
    log_university_online_class_2: 'Tôi bị phân tâm và lướt các trang web khác.',
    choice_university_online_class_3: 'Vừa học vừa ăn',
    log_university_online_class_3: 'Tôi đã ăn nhẹ trong giờ học.',

    event_university_first_internship_day_title: 'Buổi thực tập đầu tiên',
    event_university_first_internship_day_desc: 'Hôm nay là ngày đầu tiên bạn đi thực tập.',
    choice_university_first_internship_day_1: 'Làm nghiêm túc',
    log_university_first_internship_day_1: 'Tôi đã cố gắng tạo ấn tượng tốt.',
    choice_university_first_internship_day_2: 'Lúng túng',
    log_university_first_internship_day_2: 'Tôi hơi choáng ngợp và đã mắc một số lỗi.',
    choice_university_first_internship_day_3: 'Hỏi han',
    log_university_first_internship_day_3: 'Tôi đã hỏi rất nhiều để học hỏi.',

    event_university_exam_results_title: 'Nhận kết quả thi',
    event_university_exam_results_desc: 'Bạn đã nhận được kết quả thi của mình.',
    choice_university_exam_results_1: 'Vui mừng',
    log_university_exam_results_1: 'Tôi hài lòng với điểm số của mình.',
    choice_university_exam_results_2: 'Im lặng',
    log_university_exam_results_2: 'Tôi giữ kết quả cho riêng mình.',
    choice_university_exam_results_3: 'Buồn bã',
    log_university_exam_results_3: 'Tôi thất vọng với kết quả của mình.',

    event_university_share_food_title: 'Chia sẻ đồ ăn',
    event_university_share_food_desc: 'Bạn đang chia sẻ đồ ăn.',
    choice_university_share_food_1: 'Cho bạn một phần',
    log_university_share_food_1: 'Tôi đã chia sẻ đồ ăn vặt của mình.',
    choice_university_share_food_2: 'Đổi món ăn',
    log_university_share_food_2: 'Chúng tôi đã trao đổi một số món ăn của mình.',
    choice_university_share_food_3: 'Giữ phần mình',
    log_university_share_food_3: 'Hôm nay tôi đói quá không chia sẻ được.',
};
