export default {
    // Event Titles
   event_workinglife_first_day_title: 'Ngày đầu đi làm',
event_workinglife_first_day_desc: 'Ngày đầu ở công việc mới. Ấn tượng đầu tiên sẽ theo bạn lâu dài.',
choice_workinglife_first_day_1: 'Đến thật sớm',
log_workinglife_first_day_1: 'Tôi gây ấn tượng với sếp, nhưng ngồi chờ một mình thấy lạc lõng.',
choice_workinglife_first_day_2: 'Đến đúng giờ',
log_workinglife_first_day_2: 'Tôi hòa nhập tự nhiên, nhưng vài người bảo tôi thiếu chủ động.',
choice_workinglife_first_day_3: 'Đến trễ vài phút',
log_workinglife_first_day_3: 'Chỉ hơi trễ, nhưng đủ để đồng nghiệp nhíu mày.',

event_workinglife_team_meeting_title: 'Họp nhóm buổi sáng',
event_workinglife_team_meeting_desc: 'Buổi họp sáng đầu tiên định hình vai trò của bạn trong nhóm.',
choice_workinglife_team_meeting_1: 'Chia sẻ ý tưởng táo bạo',
log_workinglife_team_meeting_1: 'Tôi nổi bật nhiệt huyết, nhưng vài người đi trước tỏ vẻ nghi ngờ.',
choice_workinglife_team_meeting_2: 'Chủ yếu im lặng',
log_workinglife_team_meeting_2: 'Tôi tránh sai sót, nhưng dễ bị lãng quên.',
choice_workinglife_team_meeting_3: 'Chỉ góp lời đồng tình',
log_workinglife_team_meeting_3: 'Tôi tỏ ra ủng hộ, nhưng ai đó thì thầm “nói hùa”.',

event_workinglife_forgot_laptop_title: 'Quên laptop ở nhà',
event_workinglife_forgot_laptop_desc: 'Hoảng hốt khi phát hiện laptop không có trong cặp.',
choice_workinglife_forgot_laptop_1: 'Mượn laptop dự phòng',
log_workinglife_forgot_laptop_1: 'Tôi xoay sở được, nhưng giờ mang nợ ân tình với đồng nghiệp.',
choice_workinglife_forgot_laptop_2: 'Vội chạy về nhà lấy',
log_workinglife_forgot_laptop_2: 'Tôi mang về, nhưng lỡ mất phần họp sáng.',
choice_workinglife_forgot_laptop_3: 'Dùng máy bàn chung',
log_workinglife_forgot_laptop_3: 'Tôi làm việc tạm ổn, nhưng lúng túng vì công cụ lạ.',

event_workinglife_urgent_deadline_title: 'Hạn chót gấp rút',
event_workinglife_urgent_deadline_desc: 'Một dự án được giao với hạn chót gần như bất khả thi.',
choice_workinglife_urgent_deadline_1: 'Ở lại muộn để làm',
log_workinglife_urgent_deadline_1: 'Tôi kịp nộp, nhưng quầng thâm khiến ai cũng nhận ra.',
choice_workinglife_urgent_deadline_2: 'Xin gia hạn',
log_workinglife_urgent_deadline_2: 'Được thêm thời gian, nhưng tiếng thở dài của sếp khiến tôi chột dạ.',
choice_workinglife_urgent_deadline_3: 'Chia việc với đồng nghiệp',
log_workinglife_urgent_deadline_3: 'Xong nhanh hơn, nhưng tin đồn lan rằng tôi “không chịu áp lực nổi”.',

event_workinglife_difficult_task_title: 'Nhiệm vụ khó',
event_workinglife_difficult_task_desc: 'Sếp giao một nhiệm vụ vượt ngoài khả năng hiện tại.',
choice_workinglife_difficult_task_1: 'Nhận và cố gắng',
log_workinglife_difficult_task_1: 'Tôi học hỏi nhiều, nhưng sai sót suýt làm hỏng tiến độ.',
choice_workinglife_difficult_task_2: 'Xin giảm phạm vi',
log_workinglife_difficult_task_2: 'Nguy cơ ít hơn, nhưng trông tôi kém tham vọng.',
choice_workinglife_difficult_task_3: 'Nhờ đồng nghiệp dày dạn',
log_workinglife_difficult_task_3: 'Được hướng dẫn và xong việc, nhưng ai đó để ý tôi dựa dẫm.',

event_workinglife_late_after_lunch_title: 'Trễ giờ sau bữa trưa',
event_workinglife_late_after_lunch_desc: 'Bạn trở lại văn phòng trễ sau giờ nghỉ trưa.',
choice_workinglife_late_after_lunch_1: 'Thành thật xin lỗi',
log_workinglife_late_after_lunch_1: 'Sếp chấp nhận, nhưng đồng nghiệp chọc ghẹo vui.',
choice_workinglife_late_after_lunch_2: 'Lén lút quay lại',
log_workinglife_late_after_lunch_2: 'Không ai để ý, nhưng cảm giác áy náy đeo bám.',
choice_workinglife_late_after_lunch_3: 'Nói đang đi gặp gỡ',
log_workinglife_late_after_lunch_3: 'Lý do nghe hợp lý, nhưng không phải ai cũng tin.',

event_workinglife_company_presentation_title: 'Thuyết trình toàn công ty',
event_workinglife_company_presentation_desc: 'Bạn phải trình bày trước toàn thể công ty.',
choice_workinglife_company_presentation_1: 'Chuẩn bị kỹ lưỡng',
log_workinglife_company_presentation_1: 'Slide mượt mà, nhưng ánh đèn sân khấu khiến tôi kiệt sức.',
choice_workinglife_company_presentation_2: 'Nói ứng biến',
log_workinglife_company_presentation_2: 'Tôi nói năng hứng khởi, nhưng lỗi nhỏ vẫn xuất hiện.',
choice_workinglife_company_presentation_3: 'Đọc trực tiếp từ slide',
log_workinglife_company_presentation_3: 'Thông tin được truyền tải, nhưng tôi bị đánh giá nhạt nhòa.',

event_workinglife_team_building_title: 'Team building cuối tuần',
event_workinglife_team_building_desc: 'Công ty tổ chức sự kiện team building cuối tuần.',
choice_workinglife_team_building_1: 'Tham gia tất cả trò chơi',
log_workinglife_team_building_1: 'Tôi gắn kết hơn, nhưng về nhà rã rời.',
choice_workinglife_team_building_2: 'Tham gia chút rồi về',
log_workinglife_team_building_2: 'Tôi có mặt cho đủ, nhưng bỏ lỡ cơ hội thân thiết hơn.',
choice_workinglife_team_building_3: 'Không tham dự',
log_workinglife_team_building_3: 'Tôi tận hưởng thời gian riêng, nhưng sáng thứ Hai họ kể chuyện rôm rả mà thiếu tôi.',

event_workinglife_delayed_salary_title: 'Trễ lương',
event_workinglife_delayed_salary_desc: 'Lương tháng này bị chậm chuyển.',
choice_workinglife_delayed_salary_1: 'Hỏi thẳng HR',
log_workinglife_delayed_salary_1: 'Tôi được giải thích, nhưng dễ bị gắn mác nóng vội.',
choice_workinglife_delayed_salary_2: 'Lặng lẽ chờ',
log_workinglife_delayed_salary_2: 'Lương về muộn, còn tôi thì thêm căng thẳng.',
choice_workinglife_delayed_salary_3: 'Cùng than với đồng nghiệp',
log_workinglife_delayed_salary_3: 'Chúng tôi xả bực, nhưng không khí tiêu cực lan ra cả văn phòng.',

event_workinglife_difficult_client_title: 'Khách hàng khó tính',
event_workinglife_difficult_client_desc: 'Bạn gặp một khách hàng vừa đòi hỏi vừa nóng nảy.',
choice_workinglife_difficult_client_1: 'Đặt kỳ vọng rõ ràng',
log_workinglife_difficult_client_1: 'Họ bớt căng, nhưng không hết gay gắt.',
choice_workinglife_difficult_client_2: 'Hứa hẹn quá mức',
log_workinglife_difficult_client_2: 'Tạm làm họ hài lòng, nhưng áp lực tương lai tăng gấp đôi.',
choice_workinglife_difficult_client_3: 'Chuyển cho sếp xử lý',
log_workinglife_difficult_client_3: 'Sếp can thiệp, nhưng tôi trông kém năng lực hơn.',

event_workinglife_boss_notices_title: 'Sếp nhận ra bạn đi trễ',
event_workinglife_boss_notices_desc: 'Sếp thấy bạn vào muộn và hơi nhíu mày.',
choice_workinglife_boss_notices_1: 'Thành thật xin lỗi',
log_workinglife_boss_notices_1: 'Lời xin lỗi xoa dịu phần nào, nhưng ấn tượng ban đầu vẫn còn.',
choice_workinglife_boss_notices_2: 'Đưa ra cái cớ nhanh',
log_workinglife_boss_notices_2: 'Cái cớ giúp tôi qua được lúc đó, nhưng niềm tin bị sứt mẻ.',
choice_workinglife_boss_notices_3: 'Giữ im lặng',
log_workinglife_boss_notices_3: 'Im lặng tránh va chạm, nhưng trông tôi bất cẩn hơn.',

event_workinglife_boss_reprimand_title: 'Bị sếp phê bình',
event_workinglife_boss_reprimand_desc: 'Trong cuộc họp, sếp nhắc bạn vì không tham gia tích cực.',
choice_workinglife_boss_reprimand_1: 'Phát biểu nhiều hơn',
log_workinglife_boss_reprimand_1: 'Tôi gỡ gạc lại, nhưng đồng nghiệp trêu “nói gượng ép.”',
choice_workinglife_boss_reprimand_2: 'Bình tĩnh giải thích',
log_workinglife_boss_reprimand_2: 'Tôi nói lý do, nhưng sếp vẫn không mấy tin.',
choice_workinglife_boss_reprimand_3: 'Chấp nhận im lặng',
log_workinglife_boss_reprimand_3: 'Tôi nuốt lời phê bình, nhưng nó ám ảnh nhiều ngày.',

event_workinglife_missed_deadline_title: 'Trễ hạn chót',
event_workinglife_missed_deadline_desc: 'Một hạn chót quan trọng trượt khỏi tay bạn.',
choice_workinglife_missed_deadline_1: 'Nộp muộn vẫn nộp',
log_workinglife_missed_deadline_1: 'Bài xong, nhưng vết nhơ trong hồ sơ vẫn còn.',
choice_workinglife_missed_deadline_2: 'Xin thêm thời gian',
log_workinglife_missed_deadline_2: 'Được gia hạn, nhưng tin đồn về sự thiếu tin cậy lan ra.',
choice_workinglife_missed_deadline_3: 'Nhờ đồng nghiệp giúp',
log_workinglife_missed_deadline_3: 'Công việc hoàn thành, nhưng tôi mang nợ lớn.',

event_workinglife_client_complaint_title: 'Khách hàng phàn nàn',
event_workinglife_client_complaint_desc: 'Khách hàng gọi điện tức giận vì sự chậm trễ.',
choice_workinglife_client_complaint_1: 'Thành thật xin lỗi',
log_workinglife_client_complaint_1: 'Cơn giận nguội dần, nhưng niềm tin chưa trở lại.',
choice_workinglife_client_complaint_2: 'Giải thích lý do',
log_workinglife_client_complaint_2: 'Họ hiểu phần nào, nhưng vẫn ép tiến độ.',
choice_workinglife_client_complaint_3: 'Chuyển cho sếp xử lý',
log_workinglife_client_complaint_3: 'Khách hàng dịu xuống, nhưng sếp trông thất vọng.',

event_workinglife_boss_disappointed_title: 'Sếp thất vọng',
event_workinglife_boss_disappointed_desc: 'Sếp tỏ rõ sự thất vọng khi bạn từ chối nhiệm vụ khó.',
choice_workinglife_boss_disappointed_1: 'Xin lỗi và giải thích',
log_workinglife_boss_disappointed_1: 'Tôi xoa dịu phần nào, nhưng bị nghi ngờ thiếu tham vọng.',
choice_workinglife_boss_disappointed_2: 'Đề nghị thử lại',
log_workinglife_boss_disappointed_2: 'Tôi gỡ điểm lại, nhưng áp lực tăng gấp đôi.',
choice_workinglife_boss_disappointed_3: 'Giữ im lặng',
log_workinglife_boss_disappointed_3: 'Tôi tránh đối đầu, nhưng sự tôn trọng trôi dần.',

event_workinglife_colleagues_laugh_title: 'Đồng nghiệp cười',
event_workinglife_colleagues_laugh_desc: 'Đồng nghiệp bật cười khi bạn lén quay lại muộn.',
choice_workinglife_colleagues_laugh_1: 'Cười theo cùng họ',
log_workinglife_colleagues_laugh_1: 'Không khí nhẹ đi, nhưng uy tín giảm sút.',
choice_workinglife_colleagues_laugh_2: 'Giải thích nhanh',
log_workinglife_colleagues_laugh_2: 'Họ gật gù, nhưng biệt danh trêu chọc bám theo.',
choice_workinglife_colleagues_laugh_3: 'Lờ đi im lặng',
log_workinglife_colleagues_laugh_3: 'Tôi giữ bình tĩnh, nhưng tiếng cười ám trong đầu.',

event_workinglife_lose_points_with_boss_title: 'Mất điểm với sếp',
event_workinglife_lose_points_with_boss_desc: 'Bài thuyết trình của bạn không làm sếp hài lòng.',
choice_workinglife_lose_points_with_boss_1: 'Ứng biến nhanh',
log_workinglife_lose_points_with_boss_1: 'Tôi cứu vãn được phần nào, nhưng vết trượt vẫn nhớ mãi.',
choice_workinglife_lose_points_with_boss_2: 'Thú nhận sai sót',
log_workinglife_lose_points_with_boss_2: 'Thành thật làm dịu bớt, nhưng điểm yếu bị ghi lại.',
choice_workinglife_lose_points_with_boss_3: 'Nhờ đồng nghiệp hỗ trợ',
log_workinglife_lose_points_with_boss_3: 'Bài thuyết trình sống sót, nhưng sự phụ thuộc lộ rõ.',

event_workinglife_feel_isolated_title: 'Cảm thấy cô lập',
event_workinglife_feel_isolated_desc: 'Bỏ lỡ hoạt động khiến bạn cảm thấy tách biệt với đồng nghiệp.',
choice_workinglife_feel_isolated_1: 'Đứng ngoài quan sát',
log_workinglife_feel_isolated_1: 'Tôi thấy họ gắn bó hơn, còn mình mãi ở rìa.',
choice_workinglife_feel_isolated_2: 'Chủ động kết nối lại',
log_workinglife_feel_isolated_2: 'Dần dần tôi bắt nhịp lại, nhưng vẫn thấy chậm chân.',
choice_workinglife_feel_isolated_3: 'Tiếp tục rút lui',
log_workinglife_feel_isolated_3: 'Tôi tránh khó xử, nhưng nỗi cô đơn dày thêm.',

event_workinglife_financial_trouble_title: 'Khó khăn tài chính',
event_workinglife_financial_trouble_desc: 'Lương chậm khiến bạn chật vật tiền bạc.',
choice_workinglife_financial_trouble_1: 'Mượn bạn bè',
log_workinglife_financial_trouble_1: 'Tôi thở phào, nhưng lòng tự trọng bị tổn thương.',
choice_workinglife_financial_trouble_2: 'Xin tạm ứng',
log_workinglife_financial_trouble_2: 'HR đồng ý, nhưng tôi thấy mình mang ơn công ty.',
choice_workinglife_financial_trouble_3: 'Thắt lưng buộc bụng',
log_workinglife_financial_trouble_3: 'Tôi chịu đựng kham khổ, nhưng căng thẳng tăng thêm.',

event_workinglife_client_unhappy_title: 'Khách hàng không hài lòng',
event_workinglife_client_unhappy_desc: 'Khách hàng tỏ ra khó chịu sau những lời hứa của bạn.',
choice_workinglife_client_unhappy_1: 'Trực tiếp xin lỗi',
log_workinglife_client_unhappy_1: 'Không khí dịu lại, nhưng kỳ vọng vẫn đè nặng.',
choice_workinglife_client_unhappy_2: 'Nhờ sếp xử lý',
log_workinglife_client_unhappy_2: 'Khách hàng bình tĩnh, nhưng uy tín của tôi mất điểm.',
choice_workinglife_client_unhappy_3: 'Đề nghị giảm giá hoặc ưu đãi',
log_workinglife_client_unhappy_3: 'Họ mỉm cười lại, nhưng yêu cầu sau này tăng nhiều hơn.',

event_workinglife_overtime_title: 'Làm thêm giờ',
event_workinglife_overtime_desc: 'Đã khuya mà việc vẫn chưa xong.',
choice_workinglife_overtime_1: 'Ở lại làm cho xong',
log_workinglife_overtime_1: 'Việc hoàn thành, nhưng hôm sau tôi mệt rã rời.',
choice_workinglife_overtime_2: 'Vừa làm vừa than',
log_workinglife_overtime_2: 'Tôi xả bực tức, nhưng lan cả không khí chán nản.',
choice_workinglife_overtime_3: 'Để mai làm tiếp',
log_workinglife_overtime_3: 'Tôi về đúng giờ, nhưng ám ảnh tội lỗi cả tối.',

event_workinglife_new_project_title: 'Dự án mới',
event_workinglife_new_project_desc: 'Sếp mời bạn tham gia một dự án mới.',
choice_workinglife_new_project_1: 'Nhận lời hăng hái',
log_workinglife_new_project_1: 'Tôi thể hiện tham vọng, nhưng việc chất chồng nhanh chóng.',
choice_workinglife_new_project_2: 'Nhận với dè chừng',
log_workinglife_new_project_2: 'Tôi tham gia nhưng giữ vai trò nhỏ, an toàn nhưng ít nổi bật.',
choice_workinglife_new_project_3: 'Từ chối khéo léo',
log_workinglife_new_project_3: 'Tôi giữ khối lượng ổn định, nhưng trông thiếu tham vọng.',
log_workinglife_project_bonus: '{name} đã nhận được khoản thưởng {amount}$ cho công việc xuất sắc trong dự án mới!',

event_workinglife_boss_praise_title: 'Được sếp khen',
event_workinglife_boss_praise_desc: 'Sếp khen ngợi hiệu suất làm việc của bạn.',
choice_workinglife_boss_praise_1: 'Cảm ơn nồng nhiệt',
log_workinglife_boss_praise_1: 'Sự biết ơn tạo thiện cảm, nhưng ánh mắt ghen tị thoáng qua.',
choice_workinglife_boss_praise_2: 'Khiêm tốn',
log_workinglife_boss_praise_2: 'Khiêm nhường khiến vài người ấn tượng, nhưng người khác bảo tôi thiếu tự tin.',
choice_workinglife_boss_praise_3: 'Tỏ ra tự hào',
log_workinglife_boss_praise_3: 'Tôi thấy tự tin hơn, nhưng có lời thì thầm kiêu ngạo.',

event_workinglife_boss_criticism_title: 'Bị sếp chê',
event_workinglife_boss_criticism_desc: 'Sếp phê bình bạn trước mặt nhiều người.',
choice_workinglife_boss_criticism_1: 'Nghe im lặng',
log_workinglife_boss_criticism_1: 'Tôi chịu đựng, nhưng xấu hổ lan khắp phòng.',
choice_workinglife_boss_criticism_2: 'Bình tĩnh giải thích',
log_workinglife_boss_criticism_2: 'Tôi giải thích, vài người gật gù nhưng sếp vẫn nghiêm khắc.',
choice_workinglife_boss_criticism_3: 'Hứa sẽ cải thiện',
log_workinglife_boss_criticism_3: 'Lời hứa giúp lấy lại niềm tin, nhưng áp lực tăng gấp đôi.',

event_workinglife_training_session_title: 'Buổi đào tạo',
event_workinglife_training_session_desc: 'Bạn tham dự một buổi đào tạo bắt buộc.',
choice_workinglife_training_session_1: 'Tập trung hoàn toàn',
log_workinglife_training_session_1: 'Tôi học thêm kỹ năng, nhưng danh sách việc cần làm dài thêm.',
choice_workinglife_training_session_2: 'Tranh thủ làm việc riêng',
log_workinglife_training_session_2: 'Tôi giải quyết được việc cá nhân, nhưng bỏ lỡ kiến thức chính.',
choice_workinglife_training_session_3: 'Lén bỏ buổi',
log_workinglife_training_session_3: 'Tôi tiết kiệm thời gian, nhưng sự vắng mặt bị ghi nhận.',

event_workinglife_new_colleague_title: 'Đồng nghiệp mới',
event_workinglife_new_colleague_desc: 'Một đồng nghiệp mới gia nhập văn phòng.',
choice_workinglife_new_colleague_1: 'Chào đón nồng nhiệt',
log_workinglife_new_colleague_1: 'Tôi có thêm bạn, nhưng bị trêu “quá thân thiện.”',
choice_workinglife_new_colleague_2: 'Giữ khoảng cách',
log_workinglife_new_colleague_2: 'Tôi an toàn, nhưng lỡ mất cơ hội gắn kết.',
choice_workinglife_new_colleague_3: 'Hỏi thăm về họ',
log_workinglife_new_colleague_3: 'Sự tò mò tạo kết nối, nhưng hơi bị coi là tọc mạch.',

event_workinglife_office_lunch_title: 'Bữa trưa công ty',
event_workinglife_office_lunch_desc: 'Đến giờ ăn trưa, đồng nghiệp rủ bạn tham gia.',
choice_workinglife_office_lunch_1: 'Ăn cùng họ',
log_workinglife_office_lunch_1: 'Tiếng cười rộn rã, nhưng chuyện công việc xen vào.',
choice_workinglife_office_lunch_2: 'Ăn một mình tại bàn',
log_workinglife_office_lunch_2: 'Tôi tận hưởng yên tĩnh, nhưng bỏ lỡ câu chuyện chung.',
choice_workinglife_office_lunch_3: 'Ra ngoài ăn riêng',
log_workinglife_office_lunch_3: 'Món ăn ngon miệng, nhưng tôi trông ít hoà đồng hơn.',

event_workinglife_client_meeting_title: 'Gặp khách hàng',
event_workinglife_client_meeting_desc: 'Bạn ngồi đối diện một khách hàng quan trọng.',
choice_workinglife_client_meeting_1: 'Chuẩn bị kỹ lưỡng',
log_workinglife_client_meeting_1: 'Chuẩn bị kỹ giúp tôi tự tin, dù vẫn hơi run.',
choice_workinglife_client_meeting_2: 'Chủ yếu lắng nghe',
log_workinglife_client_meeting_2: 'Tôi tránh sai sót, nhưng dễ bị xem là thụ động.',
choice_workinglife_client_meeting_3: 'Nói ít thôi',
log_workinglife_client_meeting_3: 'Lời nói ít nhưng nặng ký, khoảng lặng thì gượng gạo.',

event_workinglife_group_work_title: 'Làm việc nhóm',
event_workinglife_group_work_desc: 'Bạn cùng đồng nghiệp làm một nhiệm vụ.',
choice_workinglife_group_work_1: 'Đóng góp tích cực',
log_workinglife_group_work_1: 'Ý tưởng trôi chảy, nhưng xung đột cũng nảy sinh.',
choice_workinglife_group_work_2: 'Giữ im lặng',
log_workinglife_group_work_2: 'Không mắc lỗi, nhưng cũng không có công lao.',
choice_workinglife_group_work_3: 'Đi theo người khác',
log_workinglife_group_work_3: 'Tôi tránh trách nhiệm, nhưng cũng trở nên mờ nhạt.',

event_workinglife_company_party_title: 'Tiệc công ty',
event_workinglife_company_party_desc: 'Công ty tổ chức một bữa tiệc sau giờ làm.',
choice_workinglife_company_party_1: 'Hoà mình tham gia',
log_workinglife_company_party_1: 'Tôi gắn kết thêm nhiều người, nhưng đêm khuya lấy hết sức lực.',
choice_workinglife_company_party_2: 'Ngồi yên một góc',
log_workinglife_company_party_2: 'Tôi tránh khó xử, nhưng sau đó thiếu chuyện để góp vui.',
choice_workinglife_company_party_3: 'Về sớm',
log_workinglife_company_party_3: 'Tôi giữ được sức, nhưng lỡ mất cơ hội kết nối.',

event_workinglife_business_trip_title: 'Chuyến công tác',
event_workinglife_business_trip_desc: 'Bạn đi công tác xa cho công việc.',
choice_workinglife_business_trip_1: 'Chuẩn bị kỹ lưỡng',
log_workinglife_business_trip_1: 'Cuộc họp diễn ra trôi chảy, nhưng tôi kiệt sức khi về.',
choice_workinglife_business_trip_2: 'Quên vài tài liệu',
log_workinglife_business_trip_2: 'Tôi vất vả xoay xở, căng thẳng tăng cao.',
choice_workinglife_business_trip_3: 'Dựa vào đồng nghiệp',
log_workinglife_business_trip_3: 'Họ che chở cho tôi, nhưng tin đồn bất cẩn lan ra.',

event_workinglife_end_of_day_title: 'Kết thúc ngày làm việc',
event_workinglife_end_of_day_desc: 'Đồng hồ điểm 5 giờ. Bạn sẽ kết thúc ngày thế nào?',
choice_workinglife_end_of_day_1: 'Rời đi ngay',
log_workinglife_end_of_day_1: 'Tôi giữ cân bằng, nhưng có người thì thầm “thiếu cống hiến.”',
choice_workinglife_end_of_day_2: 'Ở lại làm thêm',
log_workinglife_end_of_day_2: 'Tôi được khen, nhưng mất thời gian nghỉ ngơi.',
choice_workinglife_end_of_day_3: 'Ngồi trò chuyện chút',
log_workinglife_end_of_day_3: 'Tôi cười vui vẻ, nhưng công việc chất thêm.',

event_workinglife_work_delayed_title: 'Công việc bị chậm',
event_workinglife_work_delayed_desc: 'Tiến độ công việc tụt lại sau kế hoạch.',
choice_workinglife_work_delayed_1: 'Cố gắng hết sức',
log_workinglife_work_delayed_1: 'Tôi bắt kịp, nhưng kiệt sức rõ rệt.',
choice_workinglife_work_delayed_2: 'Xin thêm thời gian',
log_workinglife_work_delayed_2: 'Thời gian cứu tôi, nhưng uy tín giảm.',
choice_workinglife_work_delayed_3: 'Nhờ đồng nghiệp giúp',
log_workinglife_work_delayed_3: 'Cùng nhau hoàn thành, nhưng tôi lộ sự phụ thuộc.',

event_workinglife_pay_raise_title: 'Được tăng lương',
event_workinglife_pay_raise_desc: 'Mức lương của bạn vừa được tăng.',
choice_workinglife_pay_raise_1: 'Ăn mừng công khai',
log_workinglife_pay_raise_1: 'Niềm vui rõ rệt, nhưng ghen tị lan ra.',
choice_workinglife_pay_raise_2: 'Cảm ơn sếp nhỏ nhẹ',
log_workinglife_pay_raise_2: 'Sự biết ơn tạo gắn kết, nhưng không quá hứng khởi.',
choice_workinglife_pay_raise_3: 'Giữ bí mật',
log_workinglife_pay_raise_3: 'Tôi tránh được ganh ghét, nhưng chẳng ai chia sẻ niềm vui cùng.',

event_workinglife_bonus_cut_title: 'Bị cắt thưởng',
event_workinglife_bonus_cut_desc: 'Khoản thưởng mong đợi của bạn bị giảm bớt.',
choice_workinglife_bonus_cut_1: 'Công khai than phiền',
log_workinglife_bonus_cut_1: 'Tôi xả bực tức, nhưng dễ bị xem là thiếu chuyên nghiệp.',
choice_workinglife_bonus_cut_2: 'Im lặng chấp nhận',
log_workinglife_bonus_cut_2: 'Tôi tránh xung đột, nhưng cay đắng kéo dài.',
choice_workinglife_bonus_cut_3: 'Cân nhắc tìm việc mới',
log_workinglife_bonus_cut_3: 'Tôi bắt đầu tìm cơ hội khác, nhưng lo âu lẩn khuất.',

event_workinglife_policy_change_title: 'Thay đổi chính sách',
event_workinglife_policy_change_desc: 'Công ty công bố một chính sách mới quan trọng.',
choice_workinglife_policy_change_1: 'Đọc kỹ toàn bộ',
log_workinglife_policy_change_1: 'Tôi hiểu rõ, nhưng bị chọc là “lo xa.”',
choice_workinglife_policy_change_2: 'Đặt câu hỏi',
log_workinglife_policy_change_2: 'Tôi được giải thích, nhưng dễ bị coi là hoài nghi.',
choice_workinglife_policy_change_3: 'Tạm lờ đi',
log_workinglife_policy_change_3: 'Tôi tiết kiệm thời gian, nhưng sau đó bối rối.',

event_workinglife_computer_broken_title: 'Máy tính hỏng',
event_workinglife_computer_broken_desc: 'Máy tính văn phòng của bạn đột ngột sập nguồn.',
choice_workinglife_computer_broken_1: 'Báo IT',
log_workinglife_computer_broken_1: 'IT sửa, nhưng tôi mất vài giờ quý giá.',
choice_workinglife_computer_broken_2: 'Tự sửa',
log_workinglife_computer_broken_2: 'Tôi bất ngờ tự xoay được, nhưng rủi ro hỏng thêm.',
choice_workinglife_computer_broken_3: 'Mượn máy đồng nghiệp',
log_workinglife_computer_broken_3: 'Việc vẫn chạy, nhưng tôi làm phiền họ.',

event_workinglife_lost_motivation_title: 'Mất động lực',
event_workinglife_lost_motivation_desc: 'Gần đây bạn thấy chán nản với công việc.',
choice_workinglife_lost_motivation_1: 'Nghỉ ngắn',
log_workinglife_lost_motivation_1: 'Tôi hồi phục, nhưng việc chất đống.',
choice_workinglife_lost_motivation_2: 'Chia sẻ với bạn bè',
log_workinglife_lost_motivation_2: 'Nói ra giúp tôi nhẹ lòng, nhưng dễ bị coi là than vãn.',
choice_workinglife_lost_motivation_3: 'Tiếp tục cố gắng',
log_workinglife_lost_motivation_3: 'Tôi kiên trì, nhưng khoảng trống trong lòng thêm lớn.',

event_workinglife_performance_review_title: 'Đánh giá hiệu suất',
event_workinglife_performance_review_desc: 'Bạn vừa nhận kết quả đánh giá công việc.',
choice_workinglife_performance_review_1: 'Ăn mừng nếu tốt',
log_workinglife_performance_review_1: 'Niềm vui nâng tôi lên, nhưng ghen tị len lỏi.',
choice_workinglife_performance_review_2: 'Giữ thái độ trung lập',
log_workinglife_performance_review_2: 'Tôi tránh rắc rối, nhưng niềm vui cũng nhạt.',
choice_workinglife_performance_review_3: 'Suy ngẫm nếu kém',
log_workinglife_performance_review_3: 'Cú sốc làm đau, nhưng giúp tôi trưởng thành.',

event_workinglife_share_office_snacks_title: 'Chia sẻ đồ ăn vặt',
event_workinglife_share_office_snacks_desc: 'Đồng nghiệp để ý bạn có đồ ăn vặt trên bàn.',
choice_workinglife_share_office_snacks_1: 'Mời mọi người',
log_workinglife_share_office_snacks_1: 'Nụ cười lan toả, nhưng phần ăn của tôi cạn nhanh.',
choice_workinglife_share_office_snacks_2: 'Đổi món với người khác',
log_workinglife_share_office_snacks_2: 'Chúng tôi cười vui khi trao đổi, nhưng không phải ai cũng chia lại.',
choice_workinglife_share_office_snacks_3: 'Giữ cho riêng mình',
log_workinglife_share_office_snacks_3: 'Tôi no đủ, nhưng tiếng xì xào keo kiệt vang sau lưng.',

    // Career Tracks
    career_track_unskilled_name: 'Unskilled Labor',
    career_track_unskilled_desc: 'General labor jobs that do not require specialized training.',
    career_track_trade_name: 'Skilled Trade',
    career_track_trade_desc: 'A hands-on career like an electrician or plumber.',
    career_track_business_name: 'Business',
    career_track_business_desc: 'A corporate career in analysis and management.',
    career_track_technology_name: 'Technology',
    career_track_technology_desc: 'A career in software development and engineering.',
    career_track_arts_name: 'Arts',
    career_track_arts_desc: 'A creative career in design and media.',
    career_track_medicine_name: 'Medicine',
    career_track_medicine_desc: 'A prestigious and demanding career in the healthcare field.',
};