export default {
    // Event Titles
    event_workinglife_first_day_title: 'Đi làm ngày đầu tiên',
    event_workinglife_team_meeting_title: 'Họp nhóm buổi sáng',
    event_workinglife_forgot_laptop_title: 'Quên laptop ở nhà',
    event_workinglife_urgent_deadline_title: 'Deadline gấp',
    event_workinglife_difficult_task_title: 'Được giao việc khó',
    event_workinglife_late_after_lunch_title: 'Đi muộn sau giờ nghỉ trưa',
    event_workinglife_company_presentation_title: 'Thuyết trình trước công ty',
    event_workinglife_team_building_title: 'Team building cuối tuần',
    event_workinglife_delayed_salary_title: 'Lương bị trả chậm',
    event_workinglife_difficult_client_title: 'Gặp khách hàng khó tính',
    event_workinglife_boss_notices_title: 'Sếp để ý vì đi trễ',
    event_workinglife_boss_reprimand_title: 'Bị sếp nhắc nhở',
    event_workinglife_missed_deadline_title: 'Bị trễ deadline',
    event_workinglife_client_complaint_title: 'Bị khách hàng phàn nàn',
    event_workinglife_boss_disappointed_title: 'Sếp thất vọng',
    event_workinglife_colleagues_laugh_title: 'Bị đồng nghiệp cười',
    event_workinglife_lose_points_with_boss_title: 'Bị mất điểm với sếp',
    event_workinglife_feel_isolated_title: 'Bị lạc lõng',
    event_workinglife_financial_trouble_title: 'Gặp khó khăn tài chính',
    event_workinglife_client_unhappy_title: 'Bị khách hàng không hài lòng',
    event_workinglife_overtime_title: 'Làm thêm giờ',
    event_workinglife_new_project_title: 'Tham gia dự án mới',
    event_workinglife_boss_praise_title: 'Bị sếp khen',
    event_workinglife_boss_criticism_title: 'Bị sếp phê bình',
    event_workinglife_training_session_title: 'Tham gia đào tạo',
    event_workinglife_new_colleague_title: 'Gặp đồng nghiệp mới',
    event_workinglife_office_lunch_title: 'Bữa trưa văn phòng',
    event_workinglife_client_meeting_title: 'Họp với khách hàng',
    event_workinglife_group_work_title: 'Làm việc nhóm',
    event_workinglife_company_party_title: 'Công ty liên hoan',
    event_workinglife_business_trip_title: 'Đi công tác',
    event_workinglife_end_of_day_title: 'Hết giờ làm',
    event_workinglife_work_delayed_title: 'Công việc bị trễ',
    event_workinglife_pay_raise_title: 'Được tăng lương',
    event_workinglife_bonus_cut_title: 'Bị cắt giảm lương thưởng',
    event_workinglife_policy_change_title: 'Công ty đổi chính sách',
    event_workinglife_computer_broken_title: 'Máy tính bị hỏng',
    event_workinglife_lost_motivation_title: 'Mất động lực',
    event_workinglife_performance_review_title: 'Nhận kết quả đánh giá',
    event_workinglife_share_office_snacks_title: 'Chia sẻ đồ ăn văn phòng',

    // Event Descriptions
    event_workinglife_first_day_desc: 'Hôm nay là ngày đầu tiên bạn đi làm. Bạn sẽ tiếp cận nó như thế nào?',
    event_workinglife_team_meeting_desc: 'Trong cuộc họp buổi sáng, bạn tham gia như thế nào?',
    event_workinglife_forgot_laptop_desc: 'Bạn nhận ra mình đã để quên laptop làm việc ở nhà.',
    event_workinglife_urgent_deadline_desc: 'Một dự án với deadline rất gấp vừa được giao cho bạn.',
    event_workinglife_difficult_task_desc: 'Sếp giao cho bạn một nhiệm vụ vượt quá khả năng hiện tại của bạn.',
    event_workinglife_late_after_lunch_desc: 'Bạn đã trở lại văn phòng muộn sau giờ nghỉ trưa.',
    event_workinglife_company_presentation_desc: 'Bạn phải thuyết trình trước toàn công ty.',
    event_workinglife_team_building_desc: 'Công ty đang tổ chức một sự kiện team building vào cuối tuần.',
    event_workinglife_delayed_salary_desc: 'Lương của bạn đã bị trả chậm trong tháng này.',
    event_workinglife_difficult_client_desc: 'Bạn đang làm việc với một khách hàng rất khắt khe và khó tính.',
    event_workinglife_boss_notices_desc: 'Sếp đã để ý bạn đi trễ vào ngày đầu tiên và có vẻ không hài lòng.',
    event_workinglife_boss_reprimand_desc: 'Sếp gọi bạn ra nhắc nhở vì không tham gia tích cực trong cuộc họp.',
    event_workinglife_missed_deadline_desc: 'Vì phải về nhà lấy laptop, bạn đã bỏ lỡ một deadline quan trọng.',
    event_workinglife_client_complaint_desc: 'Khách hàng đã phàn nàn vì bạn xin thêm thời gian.',
    event_workinglife_boss_disappointed_desc: 'Sếp thất vọng vì bạn đã từ chối công việc khó.',
    event_workinglife_colleagues_laugh_desc: 'Đồng nghiệp đang cười vì bạn đã cố gắng lẻn vào muộn.',
    event_workinglife_lose_points_with_boss_desc: 'Bạn đã mất điểm với sếp vì bài thuyết trình kém.',
    event_workinglife_feel_isolated_desc: 'Bạn cảm thấy bị cô lập và lạc lõng vì đã không tham gia sự kiện team building.',
    event_workinglife_financial_trouble_desc: 'Việc trả lương chậm đã gây ra một số khó khăn tài chính.',
    event_workinglife_client_unhappy_desc: 'Khách hàng không hài lòng với việc bạn hứa hẹn quá mức.',
    event_workinglife_overtime_desc: 'Bạn phải làm thêm giờ.',
    event_workinglife_new_project_desc: 'Bạn được mời tham gia một dự án mới.',
    event_workinglife_boss_praise_desc: 'Sếp của bạn khen ngợi bạn.',
    event_workinglife_boss_criticism_desc: 'Sếp của bạn phê bình bạn.',
    event_workinglife_training_session_desc: 'Bạn đang tham gia một buổi đào tạo.',
    event_workinglife_new_colleague_desc: 'Bạn gặp một đồng nghiệp mới.',
    event_workinglife_office_lunch_desc: 'Đã đến giờ ăn trưa tại văn phòng.',
    event_workinglife_client_meeting_desc: 'Bạn đang trong một cuộc họp với khách hàng.',
    event_workinglife_group_work_desc: 'Bạn đang làm việc trong một nhóm.',
    event_workinglife_company_party_desc: 'Công ty đang tổ chức một bữa tiệc.',
    event_workinglife_business_trip_desc: 'Bạn đang đi công tác.',
    event_workinglife_end_of_day_desc: 'Ngày làm việc đã kết thúc.',
    event_workinglife_work_delayed_desc: 'Công việc của bạn bị trễ.',
    event_workinglife_pay_raise_desc: 'Bạn được tăng lương.',
    event_workinglife_bonus_cut_desc: 'Tiền thưởng của bạn đã bị cắt giảm.',
    event_workinglife_policy_change_desc: 'Công ty đã thay đổi chính sách.',
    event_workinglife_computer_broken_desc: 'Máy tính của bạn bị hỏng.',
    event_workinglife_lost_motivation_desc: 'Bạn đã mất động lực làm việc.',
    event_workinglife_performance_review_desc: 'Bạn đã nhận được kết quả đánh giá hiệu suất của mình.',
    event_workinglife_share_office_snacks_desc: 'Bạn đang chia sẻ đồ ăn vặt tại văn phòng.',

    // Choices
    choice_workinglife_first_day_1: 'Đến sớm.',
    choice_workinglife_first_day_2: 'Đi trễ.',
    choice_workinglife_first_day_3: 'Quên chuẩn bị gì đó.',
    choice_workinglife_team_meeting_1: 'Tham gia đầy đủ.',
    choice_workinglife_team_meeting_2: 'Chỉ gật đầu cho qua.',
    choice_workinglife_team_meeting_3: 'Phát biểu tích cực.',
    choice_workinglife_forgot_laptop_1: 'Mượn đồng nghiệp.',
    choice_workinglife_forgot_laptop_2: 'Xin phép về lấy.',
    choice_workinglife_forgot_laptop_3: 'Cố làm bằng điện thoại.',
    choice_workinglife_urgent_deadline_1: 'Làm xuyên đêm.',
    choice_workinglife_urgent_deadline_2: 'Hoãn xin thêm thời gian.',
    choice_workinglife_urgent_deadline_3: 'Trì hoãn cố tình.',
    choice_workinglife_difficult_task_1: 'Nhận làm.',
    choice_workinglife_difficult_task_2: 'Từ chối khéo.',
    choice_workinglife_difficult_task_3: 'Nhờ đồng nghiệp hỗ trợ.',
    choice_workinglife_late_after_lunch_1: 'Xin lỗi.',
    choice_workinglife_late_after_lunch_2: 'Lén vào.',
    choice_workinglife_late_after_lunch_3: 'Giả vờ họp bận.',
    choice_workinglife_company_presentation_1: 'Chuẩn bị kỹ.',
    choice_workinglife_company_presentation_2: 'Quên nội dung.',
    choice_workinglife_company_presentation_3: 'Đọc slide chép lại.',
    choice_workinglife_team_building_1: 'Tham gia nhiệt tình.',
    choice_workinglife_team_building_2: 'Không tham gia.',
    choice_workinglife_team_building_3: 'Ngồi một chỗ chơi điện thoại.',
    choice_workinglife_delayed_salary_1: 'Hỏi HR.',
    choice_workinglife_delayed_salary_2: 'Chờ thêm.',
    choice_workinglife_delayed_salary_3: 'Than phiền với đồng nghiệp.',
    choice_workinglife_difficult_client_1: 'Giải thích rõ ràng.',
    choice_workinglife_difficult_client_2: 'Hứa hẹn quá mức.',
    choice_workinglife_difficult_client_3: 'Nhờ sếp hỗ trợ.',
    choice_workinglife_boss_notices_1: 'Xin lỗi.',
    choice_workinglife_boss_notices_2: 'Giải thích.',
    choice_workinglife_boss_notices_3: 'Chấp nhận bị đánh giá xấu.',
    choice_workinglife_boss_reprimand_1: 'Chủ động nói thêm.',
    choice_workinglife_boss_reprimand_2: 'Giải thích đang mệt.',
    choice_workinglife_boss_reprimand_3: 'Im lặng.',
    choice_workinglife_missed_deadline_1: 'Nộp muộn.',
    choice_workinglife_missed_deadline_2: 'Xin gia hạn.',
    choice_workinglife_missed_deadline_3: 'Nhờ đồng nghiệp hỗ trợ.',
    choice_workinglife_client_complaint_1: 'Xin lỗi khách.',
    choice_workinglife_client_complaint_2: 'Giải thích.',
    choice_workinglife_client_complaint_3: 'Bị mất hợp đồng.',
    choice_workinglife_boss_disappointed_1: 'Xin lỗi.',
    choice_workinglife_boss_disappointed_2: 'Cố gắng nhận lại.',
    choice_workinglife_boss_disappointed_3: 'Bị giao việc nhẹ hơn.',
    choice_workinglife_colleagues_laugh_1: 'Cười trừ.',
    choice_workinglife_colleagues_laugh_2: 'Giải thích.',
    choice_workinglife_colleagues_laugh_3: 'Im lặng ngồi xuống.',
    choice_workinglife_lose_points_with_boss_1: 'Cố gắng ứng biến.',
    choice_workinglife_lose_points_with_boss_2: 'Xin lỗi.',
    choice_workinglife_lose_points_with_boss_3: 'Nhờ đồng nghiệp bổ sung.',
    choice_workinglife_feel_isolated_1: 'Đứng ngoài nhìn.',
    choice_workinglife_feel_isolated_2: 'Bị bạn xa lánh.',
    choice_workinglife_feel_isolated_3: 'Chủ động kết nối sau.',
    choice_workinglife_financial_trouble_1: 'Vay bạn.',
    choice_workinglife_financial_trouble_2: 'Xin tạm ứng.',
    choice_workinglife_financial_trouble_3: 'Tiết kiệm chi tiêu.',
    choice_workinglife_client_unhappy_1: 'Xin lỗi khách.',
    choice_workinglife_client_unhappy_2: 'Nhờ sếp xử lý.',
    choice_workinglife_client_unhappy_3: 'Bị nhắc nhở.',
    choice_workinglife_overtime_1: 'Hoàn thành công việc.',
    choice_workinglife_overtime_2: 'Than thở.',
    choice_workinglife_overtime_3: 'Về sớm.',
    choice_workinglife_new_project_1: 'Nhiệt tình.',
    choice_workinglife_new_project_2: 'Miễn cưỡng.',
    choice_workinglife_new_project_3: 'Từ chối.',
    choice_workinglife_boss_praise_1: 'Cảm ơn.',
    choice_workinglife_boss_praise_2: 'Ngại ngùng.',
    choice_workinglife_boss_praise_3: 'Tự tin hơn.',
    choice_workinglife_boss_criticism_1: 'Im lặng nghe.',
    choice_workinglife_boss_criticism_2: 'Giải thích.',
    choice_workinglife_boss_criticism_3: 'Buồn bã.',
    choice_workinglife_training_session_1: 'Học nghiêm túc.',
    choice_workinglife_training_session_2: 'Vừa học vừa làm việc riêng.',
    choice_workinglife_training_session_3: 'Vắng mặt.',
    choice_workinglife_new_colleague_1: 'Làm quen.',
    choice_workinglife_new_colleague_2: 'Giữ khoảng cách.',
    choice_workinglife_new_colleague_3: 'Hỏi thăm.',
    choice_workinglife_office_lunch_1: 'Ăn cùng đồng nghiệp.',
    choice_workinglife_office_lunch_2: 'Ăn một mình.',
    choice_workinglife_office_lunch_3: 'Đi ăn ngoài.',
    choice_workinglife_client_meeting_1: 'Chuẩn bị kỹ.',
    choice_workinglife_client_meeting_2: 'Ngồi nghe.',
    choice_workinglife_client_meeting_3: 'Nói ít.',
    choice_workinglife_group_work_1: 'Đưa ý kiến.',
    choice_workinglife_group_work_2: 'Im lặng.',
    choice_workinglife_group_work_3: 'Làm theo người khác.',
    choice_workinglife_company_party_1: 'Tham gia hết mình.',
    choice_workinglife_company_party_2: 'Ngồi một góc.',
    choice_workinglife_company_party_3: 'Về sớm.',
    choice_workinglife_business_trip_1: 'Chuẩn bị kỹ.',
    choice_workinglife_business_trip_2: 'Quên giấy tờ.',
    choice_workinglife_business_trip_3: 'Hỏi đường liên tục.',
    choice_workinglife_end_of_day_1: 'Về ngay.',
    choice_workinglife_end_of_day_2: 'Ở lại làm tiếp.',
    choice_workinglife_end_of_day_3: 'Ngồi chơi.',
    choice_workinglife_work_delayed_1: 'Cố gắng làm nhanh.',
    choice_workinglife_work_delayed_2: 'Xin gia hạn.',
    choice_workinglife_work_delayed_3: 'Nhờ người giúp.',
    choice_workinglife_pay_raise_1: 'Vui mừng.',
    choice_workinglife_pay_raise_2: 'Cảm ơn.',
    choice_workinglife_pay_raise_3: 'Giữ im lặng.',
    choice_workinglife_bonus_cut_1: 'Phàn nàn.',
    choice_workinglife_bonus_cut_2: 'Chấp nhận.',
    choice_workinglife_bonus_cut_3: 'Tìm việc mới.',
    choice_workinglife_policy_change_1: 'Tìm hiểu kỹ.',
    choice_workinglife_policy_change_2: 'Thắc mắc.',
    choice_workinglife_policy_change_3: 'Lờ đi.',
    choice_workinglife_computer_broken_1: 'Báo IT.',
    choice_workinglife_computer_broken_2: 'Tự sửa.',
    choice_workinglife_computer_broken_3: 'Mượn máy bạn.',
    choice_workinglife_lost_motivation_1: 'Nghỉ phép ngắn.',
    choice_workinglife_lost_motivation_2: 'Chia sẻ với bạn.',
    choice_workinglife_lost_motivation_3: 'Tiếp tục cố.',
    choice_workinglife_performance_review_1: 'Vui mừng.',
    choice_workinglife_performance_review_2: 'Im lặng.',
    choice_workinglife_performance_review_3: 'Thất vọng.',
    choice_workinglife_share_office_snacks_1: 'Cho bạn một phần.',
    choice_workinglife_share_office_snacks_2: 'Đổi món ăn.',
    choice_workinglife_share_office_snacks_3: 'Giữ phần mình.',

    // Logs
    log_workinglife_first_day_1: 'Tôi đã đến sớm để tạo ấn tượng tốt.',
    log_workinglife_first_day_2: 'Đi trễ vào ngày đầu tiên không phải là một khởi đầu tốt.',
    log_workinglife_first_day_3: 'Tôi cảm thấy không chuẩn bị và lúng túng.',
    log_workinglife_team_meeting_1: 'Tôi đã đóng góp những ý tưởng có giá trị cho cuộc thảo luận.',
    log_workinglife_team_meeting_2: 'Sự thiếu tham gia của tôi đã bị chú ý.',
    log_workinglife_team_meeting_3: 'Thái độ tích cực của tôi đã được đón nhận.',
    log_workinglife_forgot_laptop_1: 'Đồng nghiệp của tôi là một vị cứu tinh!',
    log_workinglife_forgot_laptop_2: 'Về nhà lấy nó đã làm tôi mất thời gian quý báu.',
    log_workinglife_forgot_laptop_3: 'Làm việc trên điện thoại rất không hiệu quả.',
    log_workinglife_urgent_deadline_1: 'Tôi đã kiệt sức nhưng đã hoàn thành đúng hạn.',
    log_workinglife_urgent_deadline_2: 'Yêu cầu thêm thời gian có vẻ không chuyên nghiệp.',
    log_workinglife_urgent_deadline_3: 'Trì hoãn là một sai lầm lớn.',
    log_workinglife_difficult_task_1: 'Tôi đã vượt qua thử thách và thành công.',
    log_workinglife_difficult_task_2: 'Từ chối nhiệm vụ khiến tôi trông có vẻ không có năng lực.',
    log_workinglife_difficult_task_3: 'Làm việc nhóm đã giúp nhiệm vụ khó khăn trở nên dễ quản lý hơn.',
    log_workinglife_late_after_lunch_1: 'Tôi đã xin lỗi vì sự chậm trễ của mình.',
    log_workinglife_late_after_lunch_2: 'Tôi nghĩ mình đã thoát, nhưng mọi người đã để ý.',
    log_workinglife_late_after_lunch_3: 'Lý do của tôi không thuyết phục lắm.',
    log_workinglife_company_presentation_1: 'Sự chuẩn bị của tôi đã được đền đáp bằng một bài thuyết trình thành công.',
    log_workinglife_company_presentation_2: 'Quên nội dung thật là xấu hổ.',
    log_workinglife_company_presentation_3: 'Đọc từ slide khiến tôi có vẻ không chuẩn bị.',
    log_workinglife_team_building_1: 'Sự kiện team building là một cách tuyệt vời để gắn kết với đồng nghiệp.',
    log_workinglife_team_building_2: 'Bỏ qua sự kiện khiến tôi cảm thấy xa cách với nhóm.',
    log_workinglife_team_building_3: 'Tôi có mặt nhưng không thực sự tham gia.',
    log_workinglife_delayed_salary_1: 'Phòng nhân sự đã làm rõ vấn đề và lương đã được chuyển ngay sau đó.',
    log_workinglife_delayed_salary_2: 'Chờ đợi đã gây cho tôi rất nhiều căng thẳng.',
    log_workinglife_delayed_salary_3: 'Than phiền với đồng nghiệp đã tạo ra một không khí tiêu cực.',
    log_workinglife_difficult_client_1: 'Một lời giải thích rõ ràng đã giúp quản lý kỳ vọng của khách hàng.',
    log_workinglife_difficult_client_2: 'Tôi không thể thực hiện lời hứa của mình, điều này làm mọi thứ tồi tệ hơn.',
    log_workinglife_difficult_client_3: 'Sếp của tôi đã can thiệp và xử lý tình hình.',
    log_workinglife_boss_notices_1: 'Tôi đã xin lỗi và hứa sẽ đúng giờ.',
    log_workinglife_boss_notices_2: 'Lý do của tôi dường như không thuyết phục được sếp.',
    log_workinglife_boss_notices_3: 'Ấn tượng đầu tiên của tôi đã bị hoen ố.',
    log_workinglife_boss_reprimand_1: 'Tôi bắt đầu tham gia tích cực hơn sau lời nhắc nhở.',
    log_workinglife_boss_reprimand_2: 'Sếp dường như không quan tâm đến lý do của tôi.',
    log_workinglife_boss_reprimand_3: 'Sự im lặng của tôi bị hiểu là không có năng lực.',
    log_workinglife_missed_deadline_1: 'Nộp muộn đã gây hậu quả tiêu cực cho dự án.',
    log_workinglife_missed_deadline_2: 'Tôi được gia hạn, nhưng nó phản ánh không tốt về tôi.',
    log_workinglife_missed_deadline_3: 'Một đồng nghiệp đã giúp tôi hoàn thành, và tôi nợ họ một lần.',
    log_workinglife_client_complaint_1: 'Một lời xin lỗi chân thành đã giúp làm dịu khách hàng.',
    log_workinglife_client_complaint_2: 'Giải thích không làm thay đổi ý kiến của khách hàng.',
    log_workinglife_client_complaint_3: 'Khách hàng không hài lòng đến mức họ đã hủy hợp đồng.',
    log_workinglife_boss_disappointed_1: 'Tôi đã xin lỗi và giải thích lý do của mình.',
    log_workinglife_boss_disappointed_2: 'Sếp đánh giá cao sự sẵn lòng xem xét lại của tôi.',
    log_workinglife_boss_disappointed_3: 'Sau đó, tôi được giao những công việc ít quan trọng hơn.',
    log_workinglife_colleagues_laugh_1: 'Cười cùng họ là cách tốt nhất để xử lý nó.',
    log_workinglife_colleagues_laugh_2: 'Giải thích chỉ làm tôi trông có vẻ tội lỗi hơn.',
    log_workinglife_colleagues_laugh_3: 'Phớt lờ họ là phản ứng chuyên nghiệp nhất.',
    log_workinglife_lose_points_with_boss_1: 'Suy nghĩ nhanh của tôi đã cứu bài thuyết trình khỏi thảm họa.',
    log_workinglife_lose_points_with_boss_2: 'Một lời xin lỗi đơn giản là điều tốt nhất tôi có thể làm.',
    log_workinglife_lose_points_with_boss_3: 'Đồng nghiệp của tôi đã giúp điền vào những khoảng trống.',
    log_workinglife_feel_isolated_1: 'Tôi chỉ đứng nhìn mọi người khác vui vẻ.',
    log_workinglife_feel_isolated_2: 'Đồng nghiệp dường như xa lánh tôi sau đó.',
    log_workinglife_feel_isolated_3: 'Tôi đã cố gắng kết nối lại với đồng nghiệp tại nơi làm việc.',
    log_workinglife_financial_trouble_1: 'Một người bạn đã giúp tôi thoát khỏi tình thế khó khăn.',
    log_workinglife_financial_trouble_2: 'Công ty đã đồng ý cho tôi tạm ứng lương.',
    log_workinglife_financial_trouble_3: 'Tôi đã phải rất tiết kiệm cho đến khi lương về.',
    log_workinglife_client_unhappy_1: 'Xin lỗi khách hàng là điều cần thiết.',
    log_workinglife_client_unhappy_2: 'Sếp của tôi đã phải can thiệp để giải quyết vấn đề.',
    log_workinglife_client_unhappy_3: 'Tôi đã bị khiển trách vì sự không hài lòng của khách hàng.',
    log_workinglife_overtime_1: 'Tôi đã hoàn thành công việc, nhưng cảm thấy kiệt sức.',
    log_workinglife_overtime_2: 'Than phiền không làm công việc biến mất.',
    log_workinglife_overtime_3: 'Tôi về đúng giờ, nhưng công việc vẫn còn đó vào ngày mai.',
    log_workinglife_new_project_1: 'Tôi rất hào hứng khi đối mặt với một thử thách mới.',
    log_workinglife_project_bonus: '{name} đã nhận được một khoản thưởng {amount}$ cho sự đóng góp xuất sắc trong dự án mới!',
    log_workinglife_new_project_2: 'Tôi không mấy hào hứng, nhưng tôi đã làm phần việc của mình.',
    log_workinglife_new_project_3: 'Tôi đã từ chối cơ hội.',
    log_workinglife_boss_praise_1: 'Lời khen là một động lực lớn.',
    log_workinglife_boss_praise_2: 'Tôi hơi xấu hổ vì được khen ngợi công khai.',
    log_workinglife_boss_praise_3: 'Sự công nhận đã làm tăng sự tự tin của tôi.',
    log_workinglife_boss_criticism_1: 'Tôi đã tiếp thu ý kiến một cách xây dựng.',
    log_workinglife_boss_criticism_2: 'Tôi đã cố gắng giải thích quan điểm của mình.',
    log_workinglife_boss_criticism_3: 'Lời phê bình thật khó nghe.',
    log_workinglife_training_session_1: 'Buổi đào tạo rất có ích.',
    log_workinglife_training_session_2: 'Tôi không học được nhiều từ buổi học.',
    log_workinglife_training_session_3: 'Bỏ lỡ buổi học là một ý kiến tồi.',
    log_workinglife_new_colleague_1: 'Tôi đã cố gắng chào đón đồng nghiệp mới.',
    log_workinglife_new_colleague_2: 'Tôi giữ khoảng cách với bản thân.',
    log_workinglife_new_colleague_3: 'Tôi đã tìm hiểu một chút về người mới.',
    log_workinglife_office_lunch_1: 'Ăn trưa với đồng nghiệp là một kỳ nghỉ tuyệt vời.',
    log_workinglife_office_lunch_2: 'Ăn một mình cho tôi chút thời gian yên tĩnh.',
    log_workinglife_office_lunch_3: 'Thật tuyệt khi ra khỏi văn phòng để ăn trưa.',
    log_workinglife_client_meeting_1: 'Chuẩn bị kỹ lưỡng đã giúp cuộc họp thành công.',
    log_workinglife_client_meeting_2: 'Tôi đã học được rất nhiều bằng cách lắng nghe.',
    log_workinglife_client_meeting_3: 'Tôi không đóng góp nhiều cho cuộc họp.',
    log_workinglife_group_work_1: 'Tôi đã đóng vai trò tích cực trong nhóm.',
    log_workinglife_group_work_2: 'Tôi để người khác dẫn dắt.',
    log_workinglife_group_work_3: 'Tôi chỉ làm nhiệm vụ được giao.',
    log_workinglife_company_party_1: 'Tôi đã có một khoảng thời gian tuyệt vời tại bữa tiệc của công ty.',
    log_workinglife_company_party_2: 'Tôi không có tâm trạng xã giao.',
    log_workinglife_company_party_3: 'Tôi đã đến rồi về sớm.',
    log_workinglife_business_trip_1: 'Chuyến đi hiệu quả và thành công.',
    log_workinglife_business_trip_2: 'Quên giấy tờ là một cơn đau đầu lớn.',
    log_workinglife_business_trip_3: 'Tôi đã dành rất nhiều thời gian bị lạc.',
    log_workinglife_end_of_day_1: 'Tôi coi trọng sự cân bằng giữa công việc và cuộc sống.',
    log_workinglife_end_of_day_2: 'Đôi khi bạn phải làm thêm giờ.',
    log_workinglife_end_of_day_3: 'Tôi đã thư giãn một chút trước khi về nhà.',
    log_workinglife_work_delayed_1: 'Tôi đã cố gắng bắt kịp.',
    log_workinglife_work_delayed_2: 'Yêu cầu gia hạn là lựa chọn duy nhất.',
    log_workinglife_work_delayed_3: 'Một đồng nghiệp đã giúp tôi.',
    log_workinglife_pay_raise_1: 'Tôi rất vui vì được tăng lương!',
    log_workinglife_pay_raise_2: 'Tôi rất biết ơn vì sự gia tăng.',
    log_workinglife_pay_raise_3: 'Tôi giữ tin tức cho riêng mình.',
    log_workinglife_bonus_cut_1: 'Tôi rất không vui về việc cắt giảm tiền thưởng.',
    log_workinglife_bonus_cut_2: 'Thật đáng thất vọng, nhưng tôi hiểu.',
    log_workinglife_bonus_cut_3: 'Có lẽ đã đến lúc tìm một công việc mới.',
    log_workinglife_policy_change_1: 'Điều quan trọng là phải hiểu các quy tắc mới.',
    log_workinglife_policy_change_2: 'Tôi có một số câu hỏi về những thay đổi.',
    log_workinglife_policy_change_3: 'Tôi quyết định cứ để nó trôi qua.',
    log_workinglife_computer_broken_1: 'IT đã xử lý nhanh chóng.',
    log_workinglife_computer_broken_2: 'Tôi đã tự sửa được!',
    log_workinglife_computer_broken_3: 'Đồng nghiệp của tôi đã cho tôi dùng máy tính của họ.',
    log_workinglife_lost_motivation_1: 'Một kỳ nghỉ ngắn là điều tôi cần.',
    log_workinglife_lost_motivation_2: 'Nói chuyện với một người bạn đã giúp tôi lấy lại quan điểm.',
    log_workinglife_lost_motivation_3: 'Tôi chỉ cần phải vượt qua nó.',
    log_workinglife_performance_review_1: 'Tôi hài lòng với đánh giá của mình.',
    log_workinglife_performance_review_2: 'Đánh giá ổn, không có gì đặc biệt.',
    log_workinglife_performance_review_3: 'Tôi thất vọng với đánh giá của mình.',
    log_workinglife_share_office_snacks_1: 'Chia sẻ đồ ăn vặt là một cách tốt để gắn kết.',
    log_workinglife_share_office_snacks_2: 'Thật vui khi được thử các loại đồ ăn vặt khác nhau.',
    log_workinglife_share_office_snacks_3: 'Tôi đang để dành đồ ăn vặt của mình cho sau này.',

    // Career Tracks
    career_track_unskilled_name: 'Lao động phổ thông',
    career_track_unskilled_desc: 'Các công việc lao động phổ thông không yêu cầu đào tạo chuyên môn.',
    career_track_trade_name: 'Nghề kỹ thuật',
    career_track_trade_desc: 'Một nghề nghiệp thực hành như thợ điện hoặc thợ sửa ống nước.',
    career_track_business_name: 'Kinh doanh',
    career_track_business_desc: 'Một sự nghiệp văn phòng trong lĩnh vực phân tích và quản lý.',
    career_track_technology_name: 'Công nghệ',
    career_track_technology_desc: 'Một sự nghiệp trong lĩnh vực phát triển phần mềm và kỹ thuật.',
    career_track_arts_name: 'Nghệ thuật',
    career_track_arts_desc: 'Một sự nghiệp sáng tạo trong thiết kế và truyền thông.',
    career_track_medicine_name: 'Y khoa',
    career_track_medicine_desc: 'Một sự nghiệp danh giá và đòi hỏi cao trong lĩnh vực chăm sóc sức khỏe.',
};