import { Club, ClubEventDraft, LifePhase, GameState, Character, EventChoiceDraft } from './types';

// Define 20 Clubs with corrected career influences
export const CLUBS: Club[] = [
  // Original 10 Clubs, re-mapped
  {
    id: 'science_club',
    nameKey: 'club_science_name',
    descriptionKey: 'club_science_description',
    prerequisites: { age: 12, stats: { iq: 60 } },
    effects: { iq: 0.5, skill: 0.2 },
    careerInfluence: ['major_medicine', 'major_engineering', 'major_technology'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'art_club',
    nameKey: 'club_art_name',
    descriptionKey: 'club_art_description',
    prerequisites: { age: 12 },
    effects: { happiness: 0.5 },
    careerInfluence: ['major_arts'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'sports_club',
    nameKey: 'club_sports_name',
    descriptionKey: 'club_sports_description',
    prerequisites: { age: 12, stats: { health: 50 } },
    effects: { health: 0.5 },
    careerInfluence: ['major_kinesiology'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'debate_club',
    nameKey: 'club_debate_name',
    descriptionKey: 'club_debate_description',
    prerequisites: { age: 13, stats: { iq: 70, eq: 60 } },
    effects: { iq: 0.3, eq: 0.7 },
    careerInfluence: ['major_business', 'major_marketing'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'robotics_club',
    nameKey: 'club_robotics_name',
    descriptionKey: 'club_robotics_description',
    prerequisites: { age: 13, stats: { iq: 75 } },
    effects: { iq: 0.7, skill: 0.3 },
    careerInfluence: ['major_engineering', 'major_technology'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'music_club',
    nameKey: 'club_music_name',
    descriptionKey: 'club_music_description',
    prerequisites: { age: 12 },
    effects: { happiness: 0.7 },
    careerInfluence: ['major_arts'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'cooking_club',
    nameKey: 'club_cooking_name',
    descriptionKey: 'club_cooking_description',
    prerequisites: { age: 12 },
    effects: { health: 0.3, happiness: 0.3 },
    careerInfluence: ['major_culinary'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'coding_club',
    nameKey: 'club_coding_name',
    descriptionKey: 'club_coding_description',
    prerequisites: { age: 13, stats: { iq: 65 } },
    effects: { iq: 0.6, skill: 0.4 },
    careerInfluence: ['major_technology'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'photography_club',
    nameKey: 'club_photography_name',
    descriptionKey: 'club_photography_description',
    prerequisites: { age: 12 },
    effects: { happiness: 0.4 },
    careerInfluence: ['major_arts'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'writing_club',
    nameKey: 'club_writing_name',
    descriptionKey: 'club_writing_description',
    prerequisites: { age: 13, stats: { iq: 55 } },
    effects: { iq: 0.4, eq: 0.2 },
    careerInfluence: ['major_arts', 'major_marketing'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  // New 10 Clubs
  {
    id: 'entrepreneurship_club',
    nameKey: 'club_entrepreneurship_name',
    descriptionKey: 'club_entrepreneurship_description',
    prerequisites: { age: 14, stats: { iq: 70, eq: 70 } },
    effects: { iq: 0.4, eq: 0.4, skill: 0.2 },
    careerInfluence: ['major_business', 'major_finance'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'model_un_club',
    nameKey: 'club_model_un_name',
    descriptionKey: 'club_model_un_description',
    prerequisites: { age: 14, stats: { iq: 75, eq: 65 } },
    effects: { iq: 0.5, eq: 0.5 },
    careerInfluence: ['major_business'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'environmental_club',
    nameKey: 'club_environmental_name',
    descriptionKey: 'club_environmental_description',
    prerequisites: { age: 12 },
    effects: { eq: 0.4, happiness: 0.3 },
    careerInfluence: ['major_agriculture'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'volunteering_club',
    nameKey: 'club_volunteering_name',
    descriptionKey: 'club_volunteering_description',
    prerequisites: { age: 12 },
    effects: { eq: 0.6, happiness: 0.4 },
    careerInfluence: ['major_medicine'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'chess_club',
    nameKey: 'club_chess_name',
    descriptionKey: 'club_chess_description',
    prerequisites: { age: 12, stats: { iq: 65 } },
    effects: { iq: 0.6 },
    careerInfluence: ['major_finance', 'major_technology', 'major_logistics'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'film_media_club',
    nameKey: 'club_film_media_name',
    descriptionKey: 'club_film_media_description',
    prerequisites: { age: 13 },
    effects: { eq: 0.3, happiness: 0.5 },
    careerInfluence: ['major_arts', 'major_marketing'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'medical_club',
    nameKey: 'club_medical_name',
    descriptionKey: 'club_medical_description',
    prerequisites: { age: 14, stats: { iq: 80 } },
    effects: { iq: 0.5, skill: 0.3 },
    careerInfluence: ['major_medicine'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'astronomy_club',
    nameKey: 'club_astronomy_name',
    descriptionKey: 'club_astronomy_description',
    prerequisites: { age: 13, stats: { iq: 70 } },
    effects: { iq: 0.7 },
    careerInfluence: ['major_engineering'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'literary_magazine_club',
    nameKey: 'club_literary_magazine_name',
    descriptionKey: 'club_literary_magazine_description',
    prerequisites: { age: 13, stats: { iq: 60 } },
    effects: { iq: 0.3, eq: 0.3 },
    careerInfluence: ['major_arts'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
  {
    id: 'architecture_engineering_club',
    nameKey: 'club_architecture_engineering_name',
    descriptionKey: 'club_architecture_engineering_description',
    prerequisites: { age: 14, stats: { iq: 75 } },
    effects: { iq: 0.6, skill: 0.4 },
    careerInfluence: ['major_engineering'],
    lifePhase: [LifePhase.MiddleSchool, LifePhase.HighSchool],
  },
];

// Define 20 Club Events
export const CLUB_EVENT_DRAFTS: ClubEventDraft[] = [
  // Original 10 Events
  {
    id: 'science_fair',
    titleKey: 'event_science_fair_title',
    descriptionKey: 'event_science_fair_description',
    clubId: 'science_club',
    choices: [
      { textKey: 'event_science_fair_choice1', effect: { statChanges: { iq: 5, skill: 3 }, logKey: 'event_science_fair_choice1_log' } },
      { textKey: 'event_science_fair_choice2', effect: { statChanges: { happiness: 5 }, logKey: 'event_science_fair_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.iq > 70,
  },
  {
    id: 'art_exhibition',
    titleKey: 'event_art_exhibition_title',
    descriptionKey: 'event_art_exhibition_description',
    clubId: 'art_club',
    choices: [
      { textKey: 'event_art_exhibition_choice1', effect: { statChanges: { happiness: 7 }, logKey: 'event_art_exhibition_choice1_log' } },
      { textKey: 'event_art_exhibition_choice2', effect: { statChanges: { eq: 3 }, logKey: 'event_art_exhibition_choice2_log' } },
    ],
  },
  {
    id: 'sports_tournament',
    titleKey: 'event_sports_tournament_title',
    descriptionKey: 'event_sports_tournament_description',
    clubId: 'sports_club',
    choices: [
      { textKey: 'event_sports_tournament_choice1', effect: { statChanges: { health: 5, skill: 2 }, logKey: 'event_sports_tournament_choice1_log' } },
      { textKey: 'event_sports_tournament_choice2', effect: { statChanges: { happiness: 3 }, logKey: 'event_sports_tournament_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.health > 60,
  },
  {
    id: 'debate_championship',
    titleKey: 'event_debate_championship_title',
    descriptionKey: 'event_debate_championship_description',
    clubId: 'debate_club',
    choices: [
      { textKey: 'event_debate_championship_choice1', effect: { statChanges: { iq: 4, eq: 4 }, logKey: 'event_debate_championship_choice1_log' } },
      { textKey: 'event_debate_championship_choice2', effect: { statChanges: { happiness: 2 }, logKey: 'event_debate_championship_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.eq > 70,
  },
  {
    id: 'robotics_competition',
    titleKey: 'event_robotics_competition_title',
    descriptionKey: 'event_robotics_competition_description',
    clubId: 'robotics_club',
    choices: [
      { textKey: 'event_robotics_competition_choice1', effect: { statChanges: { iq: 6, skill: 4 }, logKey: 'event_robotics_competition_choice1_log' } },
      { textKey: 'event_robotics_competition_choice2', effect: { statChanges: { happiness: 3 }, logKey: 'event_robotics_competition_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.iq > 80,
  },
  {
    id: 'school_concert',
    titleKey: 'event_school_concert_title',
    descriptionKey: 'event_school_concert_description',
    clubId: 'music_club',
    choices: [
      { textKey: 'event_school_concert_choice1', effect: { statChanges: { happiness: 6, eq: 2 }, logKey: 'event_school_concert_choice1_log' } },
      { textKey: 'event_school_concert_choice2', effect: { statChanges: { skill: 1 }, logKey: 'event_school_concert_choice2_log' } },
    ],
  },
  {
    id: 'cooking_challenge',
    titleKey: 'event_cooking_challenge_title',
    descriptionKey: 'event_cooking_challenge_description',
    clubId: 'cooking_club',
    choices: [
      { textKey: 'event_cooking_challenge_choice1', effect: { statChanges: { health: 2, skill: 3 }, logKey: 'event_cooking_challenge_choice1_log' } },
      { textKey: 'event_cooking_challenge_choice2', effect: { statChanges: { happiness: 4 }, logKey: 'event_cooking_challenge_choice2_log' } },
    ],
  },
  {
    id: 'hackathon',
    titleKey: 'event_hackathon_title',
    descriptionKey: 'event_hackathon_description',
    clubId: 'coding_club',
    choices: [
      { textKey: 'event_hackathon_choice1', effect: { statChanges: { iq: 7, skill: 5 }, logKey: 'event_hackathon_choice1_log' } },
      { textKey: 'event_hackathon_choice2', effect: { statChanges: { happiness: 2 }, logKey: 'event_hackathon_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.iq > 75,
  },
  {
    id: 'photo_walk',
    titleKey: 'event_photo_walk_title',
    descriptionKey: 'event_photo_walk_description',
    clubId: 'photography_club',
    choices: [
      { textKey: 'event_photo_walk_choice1', effect: { statChanges: { happiness: 5, eq: 1 }, logKey: 'event_photo_walk_choice1_log' } },
      { textKey: 'event_photo_walk_choice2', effect: { statChanges: { skill: 2 }, logKey: 'event_photo_walk_choice2_log' } },
    ],
  },
  {
    id: 'story_slam',
    titleKey: 'event_story_slam_title',
    descriptionKey: 'event_story_slam_description',
    clubId: 'writing_club',
    choices: [
      { textKey: 'event_story_slam_choice1', effect: { statChanges: { iq: 3, eq: 5 }, logKey: 'event_story_slam_choice1_log' } },
      { textKey: 'event_story_slam_choice2', effect: { statChanges: { happiness: 3 }, logKey: 'event_story_slam_choice2_log' } },
    ],
  },
  // New 10 Events
  {
    id: 'business_pitch_competition',
    titleKey: 'event_business_pitch_title',
    descriptionKey: 'event_business_pitch_description',
    clubId: 'entrepreneurship_club',
    choices: [
      { textKey: 'event_business_pitch_choice1', effect: { statChanges: { iq: 5, skill: 5 }, logKey: 'event_business_pitch_choice1_log' } },
      { textKey: 'event_business_pitch_choice2', effect: { statChanges: { eq: 5 }, logKey: 'event_business_pitch_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.iq > 75 && char.stats.eq > 75,
  },
  {
    id: 'model_un_conference',
    titleKey: 'event_model_un_title',
    descriptionKey: 'event_model_un_description',
    clubId: 'model_un_club',
    choices: [
      { textKey: 'event_model_un_choice1', effect: { statChanges: { iq: 5, eq: 5 }, logKey: 'event_model_un_choice1_log' } },
      { textKey: 'event_model_un_choice2', effect: { statChanges: { happiness: 4 }, logKey: 'event_model_un_choice2_log' } },
    ],
  },
  {
    id: 'community_cleanup',
    titleKey: 'event_community_cleanup_title',
    descriptionKey: 'event_community_cleanup_description',
    clubId: 'environmental_club',
    choices: [
      { textKey: 'event_community_cleanup_choice1', effect: { statChanges: { health: 3, happiness: 5 }, logKey: 'event_community_cleanup_choice1_log' } },
      { textKey: 'event_community_cleanup_choice2', effect: { statChanges: { eq: 3 }, logKey: 'event_community_cleanup_choice2_log' } },
    ],
  },
  {
    id: 'charity_fundraiser',
    titleKey: 'event_charity_fundraiser_title',
    descriptionKey: 'event_charity_fundraiser_description',
    clubId: 'volunteering_club',
    choices: [
      { textKey: 'event_charity_fundraiser_choice1', effect: { statChanges: { eq: 6, happiness: 4 }, logKey: 'event_charity_fundraiser_choice1_log' } },
      { textKey: 'event_charity_fundraiser_choice2', effect: { statChanges: { skill: 4 }, logKey: 'event_charity_fundraiser_choice2_log' } },
    ],
  },
  {
    id: 'national_chess_tournament',
    titleKey: 'event_chess_tournament_title',
    descriptionKey: 'event_chess_tournament_description',
    clubId: 'chess_club',
    choices: [
      { textKey: 'event_chess_tournament_choice1', effect: { statChanges: { iq: 8 }, logKey: 'event_chess_tournament_choice1_log' } },
      { textKey: 'event_chess_tournament_choice2', effect: { statChanges: { happiness: 3 }, logKey: 'event_chess_tournament_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.iq > 85,
  },
  {
    id: 'short_film_festival',
    titleKey: 'event_film_festival_title',
    descriptionKey: 'event_film_festival_description',
    clubId: 'film_media_club',
    choices: [
      { textKey: 'event_film_festival_choice1', effect: { statChanges: { happiness: 6, skill: 4 }, logKey: 'event_film_festival_choice1_log' } },
      { textKey: 'event_film_festival_choice2', effect: { statChanges: { eq: 4 }, logKey: 'event_film_festival_choice2_log' } },
    ],
  },
  {
    id: 'first_aid_certification',
    titleKey: 'event_first_aid_title',
    descriptionKey: 'event_first_aid_description',
    clubId: 'medical_club',
    choices: [
      { textKey: 'event_first_aid_choice1', effect: { statChanges: { skill: 6, eq: 4 }, logKey: 'event_first_aid_choice1_log' } },
      { textKey: 'event_first_aid_choice2', effect: { statChanges: { health: 4 }, logKey: 'event_first_aid_choice2_log' } },
    ],
  },
  {
    id: 'stargazing_night',
    titleKey: 'event_stargazing_title',
    descriptionKey: 'event_stargazing_description',
    clubId: 'astronomy_club',
    choices: [
      { textKey: 'event_stargazing_choice1', effect: { statChanges: { iq: 6, happiness: 4 }, logKey: 'event_stargazing_choice1_log' } },
      { textKey: 'event_stargazing_choice2', effect: { statChanges: { happiness: 5 }, logKey: 'event_stargazing_choice2_log' } },
    ],
  },
  {
    id: 'literary_journal_launch',
    titleKey: 'event_literary_journal_title',
    descriptionKey: 'event_literary_journal_description',
    clubId: 'literary_magazine_club',
    choices: [
      { textKey: 'event_literary_journal_choice1', effect: { statChanges: { eq: 5, happiness: 5 }, logKey: 'event_literary_journal_choice1_log' } },
      { textKey: 'event_literary_journal_choice2', effect: { statChanges: { iq: 4, skill: 2 }, logKey: 'event_literary_journal_choice2_log' } },
    ],
  },
  {
    id: 'bridge_building_competition',
    titleKey: 'event_bridge_building_title',
    descriptionKey: 'event_bridge_building_description',
    clubId: 'architecture_engineering_club',
    choices: [
      { textKey: 'event_bridge_building_choice1', effect: { statChanges: { iq: 7, skill: 6 }, logKey: 'event_bridge_building_choice1_log' } },
      { textKey: 'event_bridge_building_choice2', effect: { statChanges: { happiness: 4 }, logKey: 'event_bridge_building_choice2_log' } },
    ],
    condition: (state: GameState, char: Character) => char.stats.iq > 80,
  },
];