export default {
    // UI
    game_title: 'Generations',
    game_subtitle: 'A Life Simulation VN',
    family_fund_label: 'Family Fund',
    family_log_title: 'Family Log',
    year_label: 'Year',
    family_tree_title: 'Family Tree',
    default_family_name_placeholder: 'Family Name',
    family_suffix: "'s Family",
    settings_button: 'Settings',
    settings_modal_title: 'Game Settings',
    language_label: 'Language',
    game_speed_label: 'Game Speed',
    play_again_button: 'Play Again',
    how_to_play_button: 'How to Play',
    quit_game_button: 'Quit',
    resume_button: 'Resume',
    pause_button: 'Pause',
    speed_slow: 'Slow',
    speed_normal: 'Normal',
    speed_fast: 'Fast',
    speed_very_fast: 'Very Fast',
    tab_log: 'Log',
    tab_assets: 'Assets',
    tab_businesses: 'Businesses',
    tab_details: 'Details',
    tab_life_events: 'Life Events',
    scene_tree: 'Tree',
    scene_log: 'Log',
    scene_assets: 'Assets',
    scene_business: 'Business',
    event_for: 'Event for',
    for_char_label: 'For',
    cost_label: 'Cost',
    cancel_button: 'Cancel',
    back_button: 'Back',
    close_button: 'Close',
    claim_button_text: 'Claim',
    claimed_text: 'Claimed',
    // Stats
    stat_iq: 'IQ',
    stat_happiness: 'Happiness',
    stat_eq: 'EQ',
    stat_health: 'Health',
    stat_skill: 'Skill',
    // Character Details
    character_age: '{age} years old',
    age_short: 'yo',
    deceased_at: 'Deceased at',
    relationship_status_label: 'Status: {status}',
    relationship_label: 'Status',
    with_person: 'with',
    pet_label: 'Pet',
    the_pet_type: '',
    education_label: 'Education',
    major_label: 'Major',
    career_label: 'Career',
    working_at_label: 'Working at',
    clubs_label: 'Clubs',
    life_events_label: 'Life Events',
    education_none: 'None',
    education_high_school: 'High School Diploma',
    education_vocational_diploma: 'Vocational Diploma',
    education_university_display: 'University ({major_name})',
    none: 'None',
    customize_button: 'Customize',
    no_events_for_character: 'No events for this character.',
    // Welcome Back & Start Menu
    welcome_back_title: 'Welcome Back!',
    welcome_back_subtitle: 'Your previous session has been saved.',
    continue_game_button: 'Continue Game',
    start_new_game_button: 'Start New Game',
    start_game_button: 'Start', // New key
    story_button: 'Story', // New key
    choose_story_mode: 'Choose a Story Mode', // New key
    // Instructions
    instructions_title: 'How to Play',
    instructions_objective_title: 'Objective',
    instructions_objective_desc: 'Your goal is to lead a family dynasty and survive until the 6th generation is born.',
    instructions_gameplay_title: 'Gameplay',
    instructions_gameplay_desc: 'The game progresses automatically day by day. You can pause, resume, and change the speed. Time will stop when a random event or a major life choice (like choosing a school) occurs, requiring you to make a decision.',
    instructions_events_title: 'Events & Choices',
    instructions_events_desc: "Life is full of choices. When an event occurs, you must decide how your character reacts. Each choice has consequences, some immediate, some far-reaching. Choose wisely.",
    instructions_stats_title: 'Stats & Avatars',
    instructions_stats_desc: 'Click on any character\'s avatar to view their detailed stats (IQ, Happiness, etc.).',
    instructions_phases_title: 'Life Phases',
    instructions_phases_desc: 'Characters will go through different life phases, from Newborn to Retired. Each phase unlocks new events and opportunities.',
    instructions_finance_title: 'Family & Finances',
    instructions_finance_desc: 'Characters can marry and have children. Spouses will have jobs and contribute to the shared Family Fund. Use it wisely for education, businesses, and other needs.',
    // Summary Screen
    summary_victory_title: 'Congratulations!',
    summary_gameover_title: 'Game Over',
    summary_victory_desc: 'You have successfully sustained your family line to the 6th generation.',
    summary_gameover_desc: 'Your family has gone bankrupt due to running out of money. You must manage your finances more wisely next time.',
    summary_gameover_desc_debt: "Your family dynasty has crumbled under the weight of debt after failing to repay a loan.",
    summary_total_generations: 'Total Generations',
    summary_total_members: 'Total Members',
    summary_living_members: 'Living Members',
    summary_deceased_members: 'Deceased Members',
    summary_highest_education: 'Highest Education',
    summary_highest_career: 'Highest Career',
    summary_final_funds: 'Final Funds',
    summary_asset_value: 'Asset Value',
    summary_ending_year: 'Ending Year',
    // Modals
    modal_school_title: 'Choose a School',
    modal_school_desc: "It's time for {name} to go to school! Choose an educational path.",
    modal_university_title: 'Higher Education',
    modal_university_desc: 'Should {name} go to University? It will be costly but may open up better career opportunities.',
    university_choice_yes: 'Yes, invest in the future',
    university_choice_no: 'No, enter the workforce now',
    modal_major_title: 'Choose a Major',
    modal_major_desc: 'What will {name} study at University?',
    modal_major_no_money: 'You do not have enough funds to afford any of these majors.',
    modal_career_title: 'Choose a Career Path',
    modal_career_desc: '{name} has finished their education. What career path should they pursue?',
    modal_loan_title: "Financial Assistance",
    modal_loan_desc: "Your family's funds have fallen into the negative! To avoid immediate bankruptcy, you must take out a loan. Please select an amount and a repayment term.",
    loan_amount_label: "Loan Amount",
    loan_term_label: "Repayment Term (Years)",
    accept_loan_button: "Accept Loan",
    modal_promotion_title: "Promotion Opportunity!",
    modal_promotion_desc: "{name}'s hard work has been recognized! They have been offered a promotion to the position of {title}. Congratulations!",
    accept_promotion_button: "Excellent!",
    modal_underqualified_title: 'Underqualified for Position',
    modal_underqualified_desc: '{name} has the right major for the {careerName} track, but doesn\'t meet all the requirements. How should they proceed?',
    underqualified_choice_trainee: 'Become a Trainee',
    underqualified_choice_trainee_desc: 'Start at a very low salary. Your required stats will increase over time until you qualify for an entry-level position.',
    underqualified_choice_penalized: 'Accept Penalized Position',
    underqualified_choice_penalized_desc: 'Start at the lowest salary. Your skill gain and promotion speed will be penalized based on how much your stats are lacking.',
    underqualified_tooltip: 'Missing Requirements:',
    underqualified_tooltip_iq: 'IQ ({shortfall} points)',
    underqualified_tooltip_conf: 'EQ ({shortfall} points)',
    modal_club_choice_title: 'Choose a Club',
    modal_club_choice_desc: 'It\'s time for {name} to join an after-school club! This can help shape their future career.',
    join_club: 'Join',
    skip_clubs: 'Skip for now',
    // Assets & Businesses
    family_assets_title: 'Family Assets',
    total_value_label: 'Total Value',
    no_assets_message: 'No assets yet. You can purchase assets below.',
    family_businesses_title: 'Family Businesses',
    no_businesses_message: 'No businesses owned yet. Purchase one below!',
    level_label: 'Lvl',
    upgrade_button: 'Upgrade',
    req_major_label: 'Req.',
    unskilled_major: 'Unskilled',
    unassigned_option: 'Unassigned',
    hire_robot_option: 'Hire Robot',
    family_members_label: 'Family Members',
    purchase_business_title: 'Purchase New Business',
    base_revenue_label: 'Base Revenue',
    buy_button: 'Buy',
    manage_button: 'Manage',
    manage_business_title: 'Manage Business',
    select_business_to_manage: 'Select which business you\'d like to manage',
    business_map_intro: 'View the city map to purchase or manage your businesses.',
    salary_label: 'Salary',
    sell_button: 'Sell',
    // Life Phases
    phase_Newborn: 'Newborn',
    phase_Elementary_School: 'Elementary School',
    phase_Middle_School: 'Middle School',
    phase_High_School: 'High School',
    phase_University: 'University',
    phase_Working_Life: 'Working Life',
    phase_Retired: 'Retired',
    // Character Status
    status_Idle: 'Idle',
    status_In_Education: 'In Education',
    status_Working: 'Working',
    status_Unemployed: 'Unemployed',
    status_Internship: 'Internship',
    status_Vocational_Training: 'Vocational Training',
    status_Retired: 'Retired',
    status_Trainee: 'Trainee',
    // Relationship Status
    relationship_Single: 'Single',
    relationship_Married: 'Married',
    // Scenarios
    scenario_classic_name: 'Classic',
    scenario_classic_desc: 'Start at age 24 with $50,000 and a random profession. It\'s up to you to build a legacy from scratch.',
    scenario_mila_name: 'Mila\'s Family',
    scenario_mila_desc: 'Step into the life of an established family, overcome challenges, and lead them to prosperity.',
    // Schools
    school_public: 'Public School',
    school_private: 'Private School',
    school_royal: 'Royal Academy',
    school_public_high: 'Public High School',
    school_private_high: 'Private High School',
    school_royal_high: 'Royal Academy (High School)',
    // Majors
    major_business: 'Business',
    major_business_desc: 'Opens career paths in management and entrepreneurship.',
    major_finance: 'Finance',
    major_finance_desc: 'Opens career paths in finance and accounting.',
    major_marketing: 'Marketing',
    major_marketing_desc: 'Opens career paths in marketing and public relations.',
    major_technology: 'Technology',
    major_technology_desc: 'Opens career paths in programming and IT.',
    major_engineering: 'Engineering',
    major_engineering_desc: 'Opens career paths in various engineering fields.',
    major_arts: 'Arts',
    major_arts_desc: 'Opens creative careers like design and writing.',
    major_medicine: 'Medicine',
    major_medicine_desc: 'Opens high-paying medical careers.',
    major_culinary: 'Culinary Arts',
    major_culinary_desc: 'Opens career paths in cooking and restaurant management.',
    major_kinesiology: 'Kinesiology',
    major_kinesiology_desc: 'Opens career paths in fitness and coaching.',
    major_agriculture: 'Agriculture',
    major_agriculture_desc: 'Opens career paths in farming and animal husbandry.',
    major_logistics: 'Logistics',
    major_logistics_desc: 'Opens career paths in warehouse and supply chain management.',
    // Careers - Unskilled
    career_unskilled_1: 'Janitor',
    career_unskilled_2: 'Cashier',
    career_unskilled_3: 'Sales Associate',
    career_unskilled_4: 'Store Supervisor',
    // Careers - Trade
    career_trade_1: 'Apprentice Electrician',
    career_trade_2: 'Journeyman Electrician',
    career_trade_3: 'Master Electrician',
    career_trade_4: 'Foreman',
    // Careers - Business
    career_business_1: 'Junior Analyst',
    career_business_2: 'Senior Analyst',
    career_business_3: 'Manager',
    career_business_4: 'Director',
    // Careers - Technology
    career_technology_1: 'Junior Developer',
    career_technology_2: 'Software Engineer',
    career_technology_3: 'Senior Engineer',
    career_technology_4: 'Principal Engineer',
    // Careers - Arts
    career_arts_1: 'Artist Assistant',
    career_arts_2: 'Graphic Designer',
    career_arts_3: 'Art Director',
    career_arts_4: 'Creative Director',
    // Careers - Medicine
    career_medicine_1: 'Resident Doctor',
    career_medicine_2: 'General Practitioner',
    career_medicine_3: 'Surgeon',
    career_medicine_4: 'Chief of Medicine',
    // Career Options
    career_option_job: 'Find a Job',
    career_option_job_desc: 'Start looking for an entry-level job immediately.',
    career_option_internship: 'Do an Internship',
    career_option_internship_desc: 'A 1-year internship. Low pay but a chance for a job offer.',
    career_option_vocational: 'Vocational Training',
    career_option_vocational_desc: 'A 3-year program to learn a skilled trade.',
    major_match_tooltip: 'Matches your major',
    // Pets
    pet_dog: 'Dog',
    pet_cat: 'Cat',
    pet_parrot: 'Parrot',
    pet_horse: 'Horse',
    pet_fish: 'Fish/Turtle',
    // Business Roles
    role_nurse: 'Nurse',
    role_doctor: 'Doctor',
    role_head_nurse: 'Head Nurse',
    role_surgeon: 'Surgeon',
    role_admin_staff: 'Admin Staff',
    role_chief_physician: 'Chief Physician',
    role_chief_surgeon: 'Chief Surgeon',
    role_researcher: 'Researcher',
    role_manager: 'Manager',
    role_bank_teller: 'Bank Teller',
    role_loan_officer: 'Loan Officer',
    role_financial_analyst: 'Financial Analyst',
    role_investment_analyst: 'Investment Analyst',
    role_it_support: 'IT Support',
    role_senior_manager: 'Senior Manager',
    role_chief_accountant: 'Chief Accountant',
    role_director: 'Director',
    role_lead_developer: 'Lead Developer',
    role_copywriter: 'Copywriter',
    role_designer: 'Designer',
    role_account_manager: 'Account Manager',
    role_media_planner: 'Media Planner',
    role_art_director: 'Art Director',
    role_marketing_lead: 'Marketing Lead',
    role_pr_manager: 'PR Manager',
    role_senior_editor: 'Senior Editor',
    role_qa_tester: 'QA Tester',
    role_project_manager: 'Project Manager',
    role_devops_engineer: 'DevOps Engineer',
    role_machine_maintenance: 'Machine Maintenance',
    role_mechanical_engineer: 'Mechanical Engineer',
    role_civil_engineer: 'Civil Engineer',
    role_production_engineer: 'Production Engineer',
    role_quality_control: 'Quality Control',
    role_receptionist: 'Receptionist',
    role_curator: 'Curator',
    role_art_historian: 'Art Historian',
    role_art_teacher: 'Art Teacher',
    role_cashier: 'Cashier',
    role_service_staff: 'Service Staff',
    role_head_chef: 'Head Chef',
    role_mixologist: 'Mixologist',
    role_head_trainer: 'Head Trainer',
    role_lifeguard: 'Lifeguard',
    role_swimming_coach: 'Swimming Coach',
    role_kinesiologist: 'Kinesiologist',
    role_general_laborer: 'General Laborer',
    role_farm_manager: 'Farm Manager',
    role_agronomist: 'Agronomist',
    role_agricultural_engineer: 'Agricultural Engineer',
    role_supply_chain_manager: 'Supply Chain Manager',
    role_stocker: 'Stocker',
    role_forklift_operator: 'Forklift Operator',
    role_warehouse_manager: 'Warehouse Manager',
    role_logistics_coordinator: 'Logistics Coordinator',
    // Business Names (Tiers 1-3)
    business_medicine_t1_name: 'Local Clinic',
    business_medicine_t2_name: 'Community Hospital',
    business_medicine_t3_name: 'Medical Research Center',
    business_finance_t1_name: 'Credit Union',
    business_finance_t2_name: 'Investment Firm',
    business_finance_t3_name: 'Major Bank Headquarters',
    business_marketing_t1_name: 'Local Ad Agency',
    business_marketing_t2_name: 'Digital Marketing Firm',
    business_marketing_t3_name: 'Global Advertising Conglomerate',
    business_technology_t1_name: 'IT Support Shop',
    business_technology_t2_name: 'Software Development Studio',
    business_technology_t3_name: 'Big Tech Campus',
    business_engineering_t1_name: 'Repair Workshop',
    business_engineering_t2_name: 'Construction Company',
    business_engineering_t3_name: 'Advanced Manufacturing Plant',
    business_arts_t1_name: 'Art Gallery',
    business_arts_t2_name: 'Design Studio',
    business_arts_t3_name: 'Major Publishing House',
    business_culinary_t1_name: 'Diner',
    business_culinary_t2_name: 'Fine Dining Restaurant',
    business_culinary_t3_name: '5-Star Hotel & Restaurant',
    business_kinesiology_t1_name: 'Gym & Fitness Center',
    business_kinesiology_t2_name: 'Public Swimming Pool',
    business_kinesiology_t3_name: 'Professional Sports Complex',
    business_agriculture_t1_name: 'Family Farm',
    business_agriculture_t2_name: 'Commercial Farm',
    business_agriculture_t3_name: 'AgriTech Corporation',
    business_logistics_t1_name: 'Small Warehouse',
    business_logistics_t2_name: 'Distribution Center',
    business_logistics_t3_name: 'International Shipping Port',
     // Log Event Titles
    event_birthday_title: 'Birthday',
    event_new_phase_title: 'New Life Phase',
    event_retirement_title: 'Retirement',
    event_school_choice_title: 'School Choice',
    event_university_decision_title: 'University Decision',
    event_major_choice_title: 'Major Choice',
    event_career_choice_title: 'Career Choice',
    event_underqualified_decision_title: 'Career Decision',
    event_loan_decision_title: 'Loan Decision',
    event_promotion_title: 'Promotion',
    event_business_assignment_title: 'Business Assignment',
    event_business_upgrade_title: 'Business Upgrade',
    event_business_purchase_title: 'Business Purchase',
    event_asset_purchase_title: 'Asset Purchase',
    event_marriage_title: 'Marriage',
    event_birth_title: 'Birth',
    event_death_title: 'Passed Away',
    event_pet_adoption_log_title: 'Pet Adoption',
    event_club_join_title: 'Joined a Club',
    // Game Log Messages
    log_first_generation: '{name} was born, starting the first generation.',
    log_alone_start: '{name} has graduated and started a new life with $50,000.',
    log_mila_start: 'You begin your journey with Mila\'s family.',
    log_birthday: '{name} has turned {age} years old.',
    log_new_phase: '{name} is now in the {phase} phase.',
    log_retired: '{name} has retired.',
    log_promoted: '{name} has been promoted to {title}!',
    log_internship_success: "{name}'s internship was a success! They were offered a job as a {title}.",
    log_internship_fail: "{name}'s internship ended without a job offer.",
    log_status_end_unemployed: '{name} has finished their {status} and is now unemployed.',
    log_passed_away: '{name} passed away at the age of {age}.',
    log_business_position_vacant: "{name}'s position at {businessName} has been vacated.",
    log_enrolled_public_elementary: '{name} has been enrolled in Public Elementary School.',
    log_enrolled_private_elementary: '{name} has been enrolled in a prestigious Private Elementary School.',
    log_enrolled_royal_elementary: '{name} has been accepted into the exclusive Royal Elementary Academy.',
    log_enrolled_public_middle: '{name} is now attending Public Middle School.',
    log_enrolled_private_middle: '{name} is now attending a fine Private Middle School.',
    log_enrolled_royal_middle: '{name} continues their studies at the Royal Middle Academy.',
    log_enrolled_public_high: '{name} has started at the local Public High School.',
    log_enrolled_private_high: '{name} has started at a well-regarded Private High School.',
    log_enrolled_royal_high: '{name} has entered the final stage of their education at the Royal Academy.',
    log_graduated_enter_workforce: '{name} has graduated and is now ready to enter the workforce.',
    log_vocational_enter_workforce: '{name} has completed vocational training and is now ready to enter the workforce.',
    log_enrolled_university: '{name} has enrolled in University to major in {major}.',
    log_abandon_university_for_work: '{name} couldn\'t afford any majors and had to enter the workforce.',
    log_found_job: '{name} has found a job as a {title}.',
    log_became_trainee: '{name} has become a Trainee in the {careerName} track to gain the necessary experience.',
    log_accepted_penalized_job: '{name} has accepted a penalized position as a {title} due to missing some requirements.',
    log_accepted_mismatched_job: '{name} has accepted a job as a {title}. Lacking the required major, their career progression will be slower.',
    log_accepted_severely_underqualified_job: '{name} has accepted a job as a {title}. Lacking both the required major and stats, their career progression will be severely penalized.',
    log_promoted_from_trainee: 'After a period of training, {name} has been promoted to a full-time {title}!',
    log_started_internship: '{name} has started an internship.',
    log_enrolled_vocational: '{name} has enrolled in vocational training.',
    log_left_business_unemployed: '{name} left their position at {businessName} and is now unemployed.',
    log_quit_job_for_business: '{name} quit their job as a {oldJob} to work at {businessName}.',
    log_started_at_business: '{name} has started working at {businessName}.',
    log_business_upgraded: '{businessName} has been upgraded!',
    log_business_upgrade_fail: 'Not enough funds to upgrade {businessName}.',
    log_business_purchase_fail: 'Not enough funds to purchase {businessName}.',
    log_business_purchased: 'The family has purchased {businessName}!',
    log_married: '{name1} has married {name2}!',
    log_spouse_joined_family: '{name} has joined the family, working as a {title}.',
    log_had_child: '{parent1} and {parent2} had a child named {childName}.',
    log_had_twins: '{parent1} and {parent2} were blessed with twins: {childName1} and {childName2}.',
    log_had_triplets: '{parent1} and {parent2} welcomed triplets into the world: {childName1}, {childName2}, and {childName3}.',
    log_pet_already_owned: '{name} considered getting another pet, but decided one is enough.',
    log_pet_adopted: '{name} adopted a {petType} named {petName}!',
    log_loan_taken: "The family took out a loan of ${amount} due in {term} years.",
    log_loan_repaid: "The family has successfully repaid a loan of ${amount}.",
    log_loan_repayment_due: "A loan of ${amount} is due for repayment this year.",
    log_joined_club: '{name} has joined the {clubName}.',
    club_sports: 'Sports Club',
    club_sports_desc: 'Join the sports club to improve your health and physical skills.',
    club_art: 'Art Club',
    club_art_desc: 'Unleash your creativity and emotional intelligence in the art club.',
    club_science: 'Science Club',
    club_science_desc: 'Explore the wonders of science and boost your IQ and problem-solving skills.',
    log_business_locked: "You need to have {requiredChildren} children to unlock the business feature.",
    event_business_locked_title: "Feature Locked",
    avatar_customization_locked: "You need to have {requiredChildren} children to unlock avatar customization.",

    // Unlockables
    unlocks_button_title: "Goals & Unlocks",
    unlocks_modal_title: "Goals & Unlocks",
    unlocked: "Unlocked",
    unlock_condition_children: 'Children: {current} / {required}',
    unlock_business_name: "Business",
    unlock_business_desc: "Start your own business and build a commercial empire.",
    unlock_custom_avatar_name: "Avatar Customization",
    unlock_custom_avatar_desc: "Freely customize the appearance of your family members.",
    unlock_twins_name: "Twin Births",
    unlock_twins_desc: "Increases the chance of having twins.",
    unlock_triplets_name: "Triplet Births",
    unlock_triplets_desc: "A small chance of having triplets.",
    feature_mystery_box_name: "Mystery Box",
    feature_mystery_box_desc: "A mysterious box containing a random reward. It could be anything from a cash injection to a stat boost for a family member!",
    log_feature_unlocked: "{featureName} has been unlocked!",
    event_feature_unlocked_title: "Feature Unlocked",
    unlock_notification_title: "Congratulations!",
    unlock_notification_body: "You have unlocked the {featureName} feature!",
    unlock_notification_button: "Awesome!",
    log_customize_avatar: "{name} spent {amount} to customize their avatar.",
    log_customize_avatar_ad: "{name} customized their avatar for free by watching an ad.",
    event_customize_avatar_title: "Avatar Customized",
};
