export default {
    // Main Events
    event_elementary_first_day_title: 'First Day of School',
event_elementary_first_day_desc: 'The schoolyard is crowded, everyone is watching. What will you do during the opening ceremony?',
choice_elementary_first_day_1: 'Sit nicely with the class.',
log_elementary_first_day_1: 'You stayed quiet and got praised, though it felt boring. Next time teachers may trust you more with seating.',
choice_elementary_first_day_2: 'Whisper with your friend.',
log_elementary_first_day_2: 'You were happy to talk again, but got reminded in front of the class. Next time teachers might separate you two.',
choice_elementary_first_day_3: 'Play a small game while waiting.',
log_elementary_first_day_3: 'You had fun but almost got caught. Next time classmates may see you as the one who stirs things up.',

event_elementary_forgot_notebook_title: 'Forgot Notebook',
event_elementary_forgot_notebook_desc: 'You forgot your notebook in class, teachers and friends are noticing.',
choice_elementary_forgot_notebook_1: 'Borrow some paper from a friend.',
log_elementary_forgot_notebook_1: 'A friend helped you, but might hesitate if you forget again.',
choice_elementary_forgot_notebook_2: 'Ask the teacher for a sheet.',
log_elementary_forgot_notebook_2: 'The teacher gave you paper but noted it down. Next time you might be called out.',
choice_elementary_forgot_notebook_3: 'Doodle on scratch paper.',
log_elementary_forgot_notebook_3: 'You missed the lesson and got noticed. Next time your parent may be contacted.',

event_elementary_math_test_title: 'Math Test',
event_elementary_math_test_desc: 'The class is silent, the test begins.',
choice_elementary_math_test_1: 'Do the test seriously.',
log_elementary_math_test_1: 'You tried your best, though it was stressful. Next time teachers will trust your effort.',
choice_elementary_math_test_2: 'Peek at a friend\'s answers.',
log_elementary_math_test_2: 'You copied some answers but raised suspicion. Next time you may lose friends’ trust.',
choice_elementary_math_test_3: 'Ask to leave mid-test.',
log_elementary_math_test_3: 'You used health as an excuse, escaped for a bit. But teachers noted it and may call your parents next time.',

event_elementary_fire_alarm_title: 'Fire Alarm',
event_elementary_fire_alarm_desc: 'The alarm rings, the class is panicked.',
choice_elementary_fire_alarm_1: 'Line up with your class.',
log_elementary_fire_alarm_1: 'You stayed calm, teachers felt reassured. Next time you may lead the line.',
choice_elementary_fire_alarm_2: 'Run around wildly.',
log_elementary_fire_alarm_2: 'You made things chaotic and got warned. Next time you may be moved away from friends.',
choice_elementary_fire_alarm_3: 'Hold a friend\'s hand and run outside.',
log_elementary_fire_alarm_3: 'You stayed safe together but didn’t follow line rules. Next time teachers may watch you closely.',

event_elementary_oral_exam_title: 'Oral Exam',
event_elementary_oral_exam_desc: 'The teacher is calling on students to answer.',
choice_elementary_oral_exam_1: 'Answer correctly.',
log_elementary_oral_exam_1: 'You were confident and got praised, but now classmates notice you more. Next time you may be called often.',
choice_elementary_oral_exam_2: 'Stutter and forget.',
log_elementary_oral_exam_2: 'You froze and couldn’t recall. Next time the teacher may write it down.',
choice_elementary_oral_exam_3: 'Pretend to cough.',
log_elementary_oral_exam_3: 'You avoided this time, but the teacher remembers. Next time you might be called suddenly.',

event_elementary_pe_class_title: 'P.E. Class',
event_elementary_pe_class_desc: 'The whistle blows, time to move.',
choice_elementary_pe_class_1: 'Join the running.',
log_elementary_pe_class_1: 'You trained well, teacher noticed. Next time you may lead the group.',
choice_elementary_pe_class_2: 'Pretend stomachache.',
log_elementary_pe_class_2: 'You skipped running, but teachers suspected. Next time you may be watched closely.',
choice_elementary_pe_class_3: 'Play basketball instead.',
log_elementary_pe_class_3: 'You had fun but missed the main exercise. Next time teachers may limit the game.',

event_elementary_recess_title: 'Recess',
event_elementary_recess_desc: 'The bell rings, everyone is excited.',
choice_elementary_recess_1: 'Play with friends.',
log_elementary_recess_1: 'You had fun and bonded. Next time friends will invite you more.',
choice_elementary_recess_2: 'Argue with a friend.',
log_elementary_recess_2: 'It got tense, teacher noted it. Next time you may be separated.',
choice_elementary_recess_3: 'Read a comic quietly.',
log_elementary_recess_3: 'You enjoyed peace but seemed distant. Next time friends may not invite you.',

event_elementary_lunchtime_title: 'Lunch in the Cafeteria',
event_elementary_lunchtime_desc: 'The cafeteria is noisy, many are watching.',
choice_elementary_lunchtime_1: 'Eat your own food.',
log_elementary_lunchtime_1: 'You enjoyed the meal, teacher praised your manners. Next time you may sit with more friends.',
choice_elementary_lunchtime_2: 'Spill the tray.',
log_elementary_lunchtime_2: 'You spilled food and felt embarrassed. Next time classmates may tease you.',
choice_elementary_lunchtime_3: 'Trade food with a friend.',
log_elementary_lunchtime_3: 'You got your favorite dish but teacher warned you. Next time trading may be banned.',

event_elementary_performance_prep_title: 'Performance Practice',
event_elementary_performance_prep_desc: 'The class is preparing for a show.',
choice_elementary_performance_prep_1: 'Practice seriously.',
log_elementary_performance_prep_1: 'You learned your lines, teacher pleased. Next time you may get a lead role.',
choice_elementary_performance_prep_2: 'Forget the lines.',
log_elementary_performance_prep_2: 'You froze, the group struggled. Next time you may get a smaller role.',
choice_elementary_performance_prep_3: 'Sing loudly off-key.',
log_elementary_performance_prep_3: 'Class laughed, you felt awkward. Next time friends may remember you as the funny one.',

event_elementary_homework_title: 'Homework',
event_elementary_homework_desc: 'School is over, homework awaits.',
choice_elementary_homework_1: 'Finish it all.',
log_elementary_homework_1: 'You completed it, teacher praised you. Next time your reputation rises.',
choice_elementary_homework_2: 'Forget to do it.',
log_elementary_homework_2: 'You got a note in the log. Next time parents may be called.',
choice_elementary_homework_3: 'Rush through it.',
log_elementary_homework_3: 'You turned it in but with many mistakes. Next time teachers may check harder.',


    // Triggered Events
    event_elementary_teacher_reprimand_opening_title: 'Reprimanded at Opening Ceremony',
event_elementary_teacher_reprimand_opening_desc: 'The teacher caught you talking during the opening ceremony and reprimanded you. How will you react?',
choice_elementary_teacher_reprimand_opening_1: 'Sit quietly and focus.',
log_elementary_teacher_reprimand_opening_1: 'You showed respect and avoided further trouble. Next time the teacher may see you more positively.',
choice_elementary_teacher_reprimand_opening_2: 'Apologize sincerely and promise not to repeat.',
log_elementary_teacher_reprimand_opening_2: 'Your apology was accepted, but the incident was noted. Next time the teacher will watch you closely.',
choice_elementary_teacher_reprimand_opening_3: 'Keep whispering softly, hoping not to be noticed.',
log_elementary_teacher_reprimand_opening_3: 'You ignored the warning, risking harsher punishment. Next time you might lose conduct points or have your parents called.',

event_elementary_teacher_punishment_notebook_title: 'Punished for Forgetting Notebook',
event_elementary_teacher_punishment_notebook_desc: 'The teacher punished you for not bringing your notebook.',
choice_elementary_teacher_punishment_notebook_1: 'Copy lines on another sheet.',
log_elementary_teacher_punishment_notebook_1: 'You had to write tiring lines. Next time the teacher will check your notebook more carefully.',
choice_elementary_teacher_punishment_notebook_2: 'Stay after class to submit.',
log_elementary_teacher_punishment_notebook_2: 'You lost recess finishing it. Next time you may get a note in the log.',
choice_elementary_teacher_punishment_notebook_3: 'Lose diligence points.',
log_elementary_teacher_punishment_notebook_3: 'Your grade dropped, affecting your record. Next time your parents may be informed.',

event_elementary_invigilator_warning_title: 'Warning During Test',
event_elementary_invigilator_warning_desc: 'The invigilator stared at you and gave a warning during the test. What will you do?',
choice_elementary_invigilator_warning_1: 'Pretend not to hear and continue.',
log_elementary_invigilator_warning_1: 'You took the risk of being caught. Next time punishment will be harsher.',
choice_elementary_invigilator_warning_2: 'Sit up straight and focus on your own work.',
log_elementary_invigilator_warning_2: 'You corrected yourself quickly and avoided more trouble, but the invigilator kept watching.',
choice_elementary_invigilator_warning_3: 'Panic and stop writing.',
log_elementary_invigilator_warning_3: 'Fear overwhelmed you, leaving the test unfinished. Next time your grade and reputation may suffer.',

event_elementary_lost_from_class_title: 'Lost During Fire Drill',
event_elementary_lost_from_class_desc: 'You got separated from your class during the drill. What will you do?',
choice_elementary_lost_from_class_1: 'Follow another group.',
log_elementary_lost_from_class_1: 'You joined another group, but the teacher noted it. Next time you may be kept close to the teacher.',
choice_elementary_lost_from_class_2: 'Wait in the yard.',
log_elementary_lost_from_class_2: 'You stayed calm until your class found you. Next time teachers will remind you to stay close.',
choice_elementary_lost_from_class_3: 'Run frantically to find the teacher.',
log_elementary_lost_from_class_3: 'You caused a scene, so next time the teacher may assign someone to guide you.',

event_elementary_punishment_writing_title: 'Copying Punishment',
event_elementary_punishment_writing_desc: 'You were told to copy as punishment for not memorizing your lesson, and classmates are watching.',
choice_elementary_punishment_writing_1: 'Start copying right away.',
log_elementary_punishment_writing_1: 'You finished and avoided a parent call, but the teacher will check your preparation more.',
choice_elementary_punishment_writing_2: 'Ask a classmate to remind you in exchange for supplies.',
log_elementary_punishment_writing_2: 'You got help today, but the teacher noticed and may change your seat.',
choice_elementary_punishment_writing_3: 'Ask for mercy at the risk of a note.',
log_elementary_punishment_writing_3: 'You avoided copying, but the teacher wrote a note and warned that next time your parents will be called.',

event_elementary_teased_by_friends_title: 'Teased by Friends',
event_elementary_teased_by_friends_desc: 'Your friends teased you for faking a stomachache.',
choice_elementary_teased_by_friends_1: 'Laugh it off.',
log_elementary_teased_by_friends_1: 'You laughed to keep the peace, but friends may bring it up again.',
choice_elementary_teased_by_friends_2: 'Insist you were honest.',
log_elementary_teased_by_friends_2: 'You tried convincing them, but trust decreased. Next time they may doubt you.',
choice_elementary_teased_by_friends_3: 'Run to play to prove it.',
log_elementary_teased_by_friends_3: 'You proved yourself but felt embarrassed. Next time friends may challenge you more.',

event_elementary_called_to_office_title: 'Called to the Office',
event_elementary_called_to_office_desc: 'You were sent to the office after arguing.',
choice_elementary_called_to_office_1: 'Argue back to defend yourself.',
log_elementary_called_to_office_1: 'You defended your side but were seen as defiant. Next time you may get a discipline note.',
choice_elementary_called_to_office_2: 'Stay silent and take it.',
log_elementary_called_to_office_2: 'You avoided more trouble but seemed unresponsive. Teachers may think you lack accountability.',
choice_elementary_called_to_office_3: 'Apologize quickly to end it.',
log_elementary_called_to_office_3: 'You apologized, and the matter ended. Next time teachers may expect you to be proactive.',

event_elementary_clean_up_mess_title: 'Clean the Table',
event_elementary_clean_up_mess_desc: 'You had to clean the whole table after spilling your tray.',
choice_elementary_clean_up_mess_1: 'Clean carefully.',
log_elementary_clean_up_mess_1: 'You cleaned well, showing responsibility. Next time teachers trust you more.',
choice_elementary_clean_up_mess_2: 'Do it carelessly.',
log_elementary_clean_up_mess_2: 'You wiped quickly and friends teased you. Next time you may get more chores.',
choice_elementary_clean_up_mess_3: 'Ask a friend to help.',
log_elementary_clean_up_mess_3: 'A friend helped, but you seemed dependent. Next time the teacher may watch you closely.',

event_elementary_role_replaced_title: 'Role Replaced',
event_elementary_role_replaced_desc: 'You lost your role for not knowing your lines.',
choice_elementary_role_replaced_1: 'Ask for a smaller role.',
log_elementary_role_replaced_1: 'You still participated but less noticeably. Next time the teacher may value your persistence.',
choice_elementary_role_replaced_2: 'Watch from the audience.',
log_elementary_role_replaced_2: 'You sat out and felt sad. Next time friends may not rely on you.',
choice_elementary_role_replaced_3: 'Practice hard and ask for another chance.',
log_elementary_role_replaced_3: 'You worked hard, and the teacher noticed. Next time you may be given another try.',

event_elementary_teacher_reprimand_homework_title: 'Reprimanded for Homework',
event_elementary_teacher_reprimand_homework_desc: 'The teacher scolded you for forgetting homework.',
choice_elementary_teacher_reprimand_homework_1: 'Apologize to the teacher.',
log_elementary_teacher_reprimand_homework_1: 'You admitted your mistake, but the teacher will keep watch.',
choice_elementary_teacher_reprimand_homework_2: 'Blame circumstances.',
log_elementary_teacher_reprimand_homework_2: 'You made excuses, but trust decreased. Next time parents may be called.',
choice_elementary_teacher_reprimand_homework_3: 'Promise to do it next time.',
log_elementary_teacher_reprimand_homework_3: 'You promised, but the teacher remembered. Next time you may face harsher consequences.',


    // Independent Events
   event_elementary_toy_dispute_title: 'Fighting Over a Toy',
event_elementary_toy_dispute_desc: 'You and a classmate are fighting over a toy.',
choice_elementary_toy_dispute_1: 'Talk and share.',
log_elementary_toy_dispute_1: 'You decided to take turns. Next time you may be praised for fairness.',
choice_elementary_toy_dispute_2: 'Cry and tell the teacher.',
log_elementary_toy_dispute_2: 'You told the teacher and it was solved, but classmates may tease you as weak.',
choice_elementary_toy_dispute_3: 'Find another toy.',
log_elementary_toy_dispute_3: 'You avoided conflict by playing with something else. Next time friends may see you as adaptable.',

event_elementary_art_class_title: 'Drawing in Art Class',
event_elementary_art_class_desc: 'It is art class, and you are drawing.',
choice_elementary_art_class_1: 'Draw according to the theme.',
log_elementary_art_class_1: 'You followed directions, pleasing the teacher but lacking creativity.',
choice_elementary_art_class_2: 'Add creative details.',
log_elementary_art_class_2: 'You were praised as unique, though some friends teased you as odd.',
choice_elementary_art_class_3: 'Borrow colors from a friend.',
log_elementary_art_class_3: 'You spent time borrowing crayons, not drawing much. Next time you may be reminded to bring supplies.',

event_elementary_rainy_recess_title: 'Rainy Recess',
event_elementary_rainy_recess_desc: 'It is raining during recess.',
choice_elementary_rainy_recess_1: 'Play inside the classroom.',
log_elementary_rainy_recess_1: 'You played board games indoors. Next time classmates may invite you for indoor fun.',
choice_elementary_rainy_recess_2: 'Run outside in the drizzle.',
log_elementary_rainy_recess_2: 'You had fun but got wet, risking a cold.',
choice_elementary_rainy_recess_3: 'Watch the rain from the hallway.',
log_elementary_rainy_recess_3: 'You enjoyed the peace. Next time friends may see you as quiet.',

event_elementary_birthday_party_title: 'Classmate\'s Birthday',
event_elementary_birthday_party_desc: 'You are at a classmate\'s birthday party.',
choice_elementary_birthday_party_1: 'Give a small gift.',
log_elementary_birthday_party_1: 'Your gift made your friend happy.',
choice_elementary_birthday_party_2: 'Sing Happy Birthday.',
log_elementary_birthday_party_2: 'You sang loudly, and everyone joined. Next time friends may want you in celebrations.',
choice_elementary_birthday_party_3: 'Eat cake and candy.',
log_elementary_birthday_party_3: 'The cake was delicious, but teachers may notice if you eat too much.',

event_elementary_first_speech_title: 'First Time Speaking Up',
event_elementary_first_speech_desc: 'You have a chance to speak for the first time.',
choice_elementary_first_speech_1: 'Speak clearly and confidently.',
log_elementary_first_speech_1: 'You were nervous but spoke up. Next time teachers may trust you more.',
choice_elementary_first_speech_2: 'Speak quietly while trembling.',
log_elementary_first_speech_2: 'You were too shy to be heard. Next time classmates may pay less attention.',
choice_elementary_first_speech_3: 'Forget what to say.',
log_elementary_first_speech_3: 'You froze, and the class stared. Next time teachers may remind you to prepare.',

event_elementary_extracurricular_club_title: 'Extracurricular Club',
event_elementary_extracurricular_club_desc: 'You are thinking about joining a club.',
choice_elementary_extracurricular_club_1: 'Register seriously.',
log_elementary_extracurricular_club_1: 'You were excited, and the teacher encouraged you. Next time you may be given a role.',
choice_elementary_extracurricular_club_2: 'Try one session then quit.',
log_elementary_extracurricular_club_2: 'You found it boring and left. Next time teachers may hesitate to let you join.',
choice_elementary_extracurricular_club_3: 'Join to make friends.',
log_elementary_extracurricular_club_3: 'You made new friends, but sometimes ignored the activity.',

event_elementary_playing_soccer_title: 'Playing Soccer in the Yard',
event_elementary_playing_soccer_desc: 'You are playing soccer with friends.',
choice_elementary_playing_soccer_1: 'Play enthusiastically.',
log_elementary_playing_soccer_1: 'You had fun and were cheered. Next time friends want you on their team.',
choice_elementary_playing_soccer_2: 'Be a cheerleader.',
log_elementary_playing_soccer_2: 'You supported loudly but missed playing. Next time you may not be picked for the team.',
choice_elementary_playing_soccer_3: 'Be the goalie.',
log_elementary_playing_soccer_3: 'You blocked some shots and felt proud. Next time you may keep that role.',

event_elementary_sports_day_title: 'Sports Day',
event_elementary_sports_day_desc: 'It is the annual school sports day.',
choice_elementary_sports_day_1: 'Run in the sprint.',
log_elementary_sports_day_1: 'You ran as fast as you could. Next time you may be chosen again.',
choice_elementary_sports_day_2: 'Jump rope.',
log_elementary_sports_day_2: 'You had fun jumping. Next time friends may invite you to play.',
choice_elementary_sports_day_3: 'Cheer loudly.',
log_elementary_sports_day_3: 'You stood out as a supporter. Next time teachers may assign you as cheer captain.',

event_elementary_classroom_game_title: 'Classroom Game',
event_elementary_classroom_game_desc: 'The teacher organizes a game.',
choice_elementary_classroom_game_1: 'Play by the rules.',
log_elementary_classroom_game_1: 'You played fair and had fun. Next time friends trust you more.',
choice_elementary_classroom_game_2: 'Cheat a little.',
log_elementary_classroom_game_2: 'You won but were caught. Next time your reputation drops.',
choice_elementary_classroom_game_3: 'Quit halfway.',
log_elementary_classroom_game_3: 'You got bored and stopped. Next time you may not be picked.',

event_elementary_museum_trip_title: 'First Museum Trip',
event_elementary_museum_trip_desc: 'You are visiting the museum for the first time.',
choice_elementary_museum_trip_1: 'Listen to the guide.',
log_elementary_museum_trip_1: 'You learned many things. Next time the teacher praises your focus.',
choice_elementary_museum_trip_2: 'Look at objects only.',
log_elementary_museum_trip_2: 'The artifacts amazed you, but you missed the explanations.',
choice_elementary_museum_trip_3: 'Chat with friends.',
log_elementary_museum_trip_3: 'You missed the content while talking. Next time teachers may warn you.',

event_elementary_spelling_test_title: 'Spelling Test',
event_elementary_spelling_test_desc: 'Today is the spelling test.',
choice_elementary_spelling_test_1: 'Write seriously.',
log_elementary_spelling_test_1: 'You spelled confidently and did well. Next time you are seen as diligent.',
choice_elementary_spelling_test_2: 'Look at a friend\'s paper.',
log_elementary_spelling_test_2: 'You peeked for help but got noticed.',
choice_elementary_spelling_test_3: 'Write a different sentence instead.',
log_elementary_spelling_test_3: 'You avoided hard words, losing points. Next time you need practice.',

event_elementary_good_student_award_title: 'Receive a Good Student Certificate',
event_elementary_good_student_award_desc: 'You received a certificate for being a good student.',
choice_elementary_good_student_award_1: 'Show it proudly to parents.',
log_elementary_good_student_award_1: 'Your parents were proud. Next time they encourage you more.',
choice_elementary_good_student_award_2: 'Show it to friends.',
log_elementary_good_student_award_2: 'Your friends congratulated you. Next time they respect you more.',
choice_elementary_good_student_award_3: 'Put it quietly in your bag.',
log_elementary_good_student_award_3: 'You felt happy but humble. Next time you are seen as modest.',

event_elementary_singing_class_title: 'Singing in Class',
event_elementary_singing_class_desc: 'You are singing during music class.',
choice_elementary_singing_class_1: 'Sing in tune.',
log_elementary_singing_class_1: 'You enjoyed singing and got praise. Next time you may be chosen to solo.',
choice_elementary_singing_class_2: 'Sing very quietly.',
log_elementary_singing_class_2: 'You were shy and quiet. Next time teachers may encourage you more.',
choice_elementary_singing_class_3: 'Giggle while singing.',
log_elementary_singing_class_3: 'You laughed and disrupted. Next time teachers may warn you.',

event_elementary_praised_by_teacher_title: 'Praised by Teacher',
event_elementary_praised_by_teacher_desc: 'The teacher praised you in front of the class.',
choice_elementary_praised_by_teacher_1: 'Blush shyly.',
log_elementary_praised_by_teacher_1: 'You were not used to attention. Next time teachers may encourage you again.',
choice_elementary_praised_by_teacher_2: 'Smile proudly.',
log_elementary_praised_by_teacher_2: 'You felt happy being recognized. Next time friends admire you.',
choice_elementary_praised_by_teacher_3: 'Act casual.',
log_elementary_praised_by_teacher_3: 'You acted calm but felt proud inside.',

event_elementary_talking_in_class_title: 'Reprimanded for Talking',
event_elementary_talking_in_class_desc: 'The teacher scolded you for talking in class.',
choice_elementary_talking_in_class_1: 'Sit quietly.',
log_elementary_talking_in_class_1: 'You stopped and avoided more trouble. Next time the teacher keeps an eye on you.',
choice_elementary_talking_in_class_2: 'Argue back.',
log_elementary_talking_in_class_2: 'You defended yourself but looked defiant. Next time parents may be called.',
choice_elementary_talking_in_class_3: 'Apologize.',
log_elementary_talking_in_class_3: 'You apologized, and it ended. Next time the teacher expects better behavior.',

event_elementary_first_bad_grade_title: 'First Bad Grade',
event_elementary_first_bad_grade_desc: 'You got your first bad grade.',
choice_elementary_first_bad_grade_1: 'Cry sadly.',
log_elementary_first_bad_grade_1: 'You were disappointed. Next time you are more determined.',
choice_elementary_first_bad_grade_2: 'Hide it from parents.',
log_elementary_first_bad_grade_2: 'You kept it secret but risk being found out.',
choice_elementary_first_bad_grade_3: 'Decide to study harder.',
log_elementary_first_bad_grade_3: 'You promised yourself to improve. Next time teachers may encourage you.',

event_elementary_group_work_title: 'Group Work',
event_elementary_group_work_desc: 'You are working on a group project.',
choice_elementary_group_work_1: 'Share ideas.',
log_elementary_group_work_1: 'You led the discussion. Next time friends rely on you more.',
choice_elementary_group_work_2: 'Let friends decide.',
log_elementary_group_work_2: 'You stayed quiet. Next time your role may be smaller.',
choice_elementary_group_work_3: 'Only do your part.',
log_elementary_group_work_3: 'You did your task. Next time you may be seen as supportive.',

event_elementary_found_item_title: 'Found a Lost Item',
event_elementary_found_item_desc: 'You found a lost item.',
choice_elementary_found_item_1: 'Return it to the owner.',
log_elementary_found_item_1: 'Your friend was happy. Next time you are praised as honest.',
choice_elementary_found_item_2: 'Turn it in to the teacher.',
log_elementary_found_item_2: 'The teacher helped find the owner. Next time you are trusted.',
choice_elementary_found_item_3: 'Keep it for yourself.',
log_elementary_found_item_3: 'You kept it but risk being caught. Next time your reputation drops.',

event_elementary_class_monitor_title: 'Appointed Class Monitor',
event_elementary_class_monitor_desc: 'You were appointed class monitor.',
choice_elementary_class_monitor_1: 'Accept happily.',
log_elementary_class_monitor_1: 'You promised responsibility. Next time the teacher trusts you more.',
choice_elementary_class_monitor_2: 'Decline.',
log_elementary_class_monitor_2: 'You avoided responsibility. Next time teachers pick someone else.',
choice_elementary_class_monitor_3: 'Suggest another friend.',
log_elementary_class_monitor_3: 'You thought your friend fit better. Next time teachers reconsider.',

event_elementary_craft_class_title: 'Craft Class',
event_elementary_craft_class_desc: 'You are in craft class.',
choice_elementary_craft_class_1: 'Fold as instructed.',
log_elementary_craft_class_1: 'You followed carefully. Next time teachers praise your diligence.',
choice_elementary_craft_class_2: 'Fold creatively into another shape.',
log_elementary_craft_class_2: 'You made a paper airplane, fun but off-task.',
choice_elementary_craft_class_3: 'Work slowly and not finish.',
log_elementary_craft_class_3: 'You ran out of time. Next time teachers remind you to be faster.',

};
