export default {
    // Main Events
    event_highschool_late_for_school_title: 'Late for School',
    event_highschool_late_for_school_desc: 'You were late for school due to a traffic jam.',
    choice_highschool_late_for_school_1: 'Apologize to the teacher.',
    log_highschool_late_for_school_1: 'I apologized and was let into class.',
    choice_highschool_late_for_school_2: 'Blame the traffic.',
    log_highschool_late_for_school_2: 'I explained it was the traffic, but the teacher was still skeptical.',
    choice_highschool_late_for_school_3: 'Sneak into class.',
    log_highschool_late_for_school_3: 'I tried to slip in unnoticed.',

    event_highschool_forgot_presentation_book_title: 'Forgot Presentation Book',
    event_highschool_forgot_presentation_book_desc: 'You forgot to bring a book needed for your presentation.',
    choice_highschool_forgot_presentation_book_1: 'Borrow from a friend.',
    log_highschool_forgot_presentation_book_1: 'A friend lent me their book, saving the day.',
    choice_highschool_forgot_presentation_book_2: 'Ask the teacher for a pass.',
    log_highschool_forgot_presentation_book_2: 'I asked the teacher for forgiveness, and they were understanding.',
    choice_highschool_forgot_presentation_book_3: 'Hide it.',
    log_highschool_forgot_presentation_book_3: 'I tried to get through the presentation without anyone noticing.',

    event_highschool_football_practice_title: 'Football Practice',
    event_highschool_football_practice_desc: 'It\'s time for football practice.',
    choice_highschool_football_practice_1: 'Focus on training.',
    log_highschool_football_practice_1: 'I gave it my all during practice.',
    choice_highschool_football_practice_2: 'Be lazy.',
    log_highschool_football_practice_2: 'I slacked off during drills.',
    choice_highschool_football_practice_3: 'Chat with friends.',
    log_highschool_football_practice_3: 'I spent most of the practice talking with teammates.',

    event_highschool_college_prep_workshop_title: 'College Prep Workshop',
    event_highschool_college_prep_workshop_desc: 'The school is holding a workshop to prepare for college applications.',
    choice_highschool_college_prep_workshop_1: 'Participate seriously.',
    log_highschool_college_prep_workshop_1: 'I took the workshop seriously and learned a lot.',
    choice_highschool_college_prep_workshop_2: 'Sit and play.',
    log_highschool_college_prep_workshop_2: 'I was bored and just messed around on my phone.',
    choice_highschool_college_prep_workshop_3: 'Sneak out.',
    log_highschool_college_prep_workshop_3: 'I slipped out when no one was looking.',

    event_highschool_sat_act_test_title: 'Mock SAT/ACT Test',
    event_highschool_sat_act_test_desc: 'You are taking a practice test for college entrance exams.',
    choice_highschool_sat_act_test_1: 'Take it seriously.',
    log_highschool_sat_act_test_1: 'I focused and did my best to prepare for the real thing.',
    choice_highschool_sat_act_test_2: 'Talk during the test.',
    log_highschool_sat_act_test_2: 'I got caught whispering to a friend.',
    choice_highschool_sat_act_test_3: 'Rush through it to finish.',
    log_highschool_sat_act_test_3: 'I didn\'t take it seriously and just wanted to be done.',

    event_highschool_promposal_title: 'Promposal',
    event_highschool_promposal_desc: 'It\'s time to ask your crush to the prom.',
    choice_highschool_promposal_1: 'Prepare a romantic gesture.',
    log_highschool_promposal_1: 'I planned a big, romantic promposal.',
    choice_highschool_promposal_2: 'Ask hastily.',
    log_highschool_promposal_2: 'I just quickly and awkwardly asked them.',
    choice_highschool_promposal_3: 'Get help from friends.',
    log_highschool_promposal_3: 'My friends helped me come up with a cool idea.',

    event_highschool_prom_cafeteria_title: 'Finding a Prom Date',
    event_highschool_prom_cafeteria_desc: 'You\'re in the cafeteria, and your crush is nearby. It\'s a good chance to talk about prom.',
    choice_highschool_prom_cafeteria_1: 'Sit with your best friend.',
    log_highschool_prom_cafeteria_1: 'I decided to sit with my friend instead.',
    choice_highschool_prom_cafeteria_2: 'Sit next to your crush.',
    log_highschool_prom_cafeteria_2: 'I gathered my courage and sat next to them.',
    choice_highschool_prom_cafeteria_3: 'Sit alone.',
    log_highschool_prom_cafeteria_3: 'I was too nervous and ended up sitting by myself.',

    event_highschool_homecoming_game_title: 'Homecoming Parade & Game',
    event_highschool_homecoming_game_desc: 'It\'s the day of the big homecoming game and parade.',
    choice_highschool_homecoming_game_1: 'Cheer enthusiastically.',
    log_highschool_homecoming_game_1: 'I showed my school spirit and cheered loudly.',
    choice_highschool_homecoming_game_2: 'Sneak away to hang out.',
    log_highschool_homecoming_game_2: 'The game was boring, so I left with some friends.',
    choice_highschool_homecoming_game_3: 'Sit in a corner and watch.',
    log_highschool_homecoming_game_3: 'I watched the game quietly from the stands.',

    event_highschool_class_test_title: 'In-Class Test',
    event_highschool_class_test_desc: 'You have an in-class test.',
    choice_highschool_class_test_1: 'Do it seriously.',
    log_highschool_class_test_1: 'I focused on doing my own work.',
    choice_highschool_class_test_2: 'Look at a friend\'s paper.',
    log_highschool_class_test_2: 'I peeked at my friend\'s answers for a tough question.',
    choice_highschool_class_test_3: 'Just write down a few lines.',
    log_highschool_class_test_3: 'I didn\'t know the answers, so I just wrote something down.',

    event_highschool_literature_discussion_title: 'Literature Group Discussion',
    event_highschool_literature_discussion_desc: 'Your group is discussing a book in literature class.',
    choice_highschool_literature_discussion_1: 'Share your opinions.',
    log_highschool_literature_discussion_1: 'I actively participated and shared my analysis.',
    choice_highschool_literature_discussion_2: 'Sit quietly and listen.',
    log_highschool_literature_discussion_2: 'I preferred to hear what others had to say.',
    choice_highschool_literature_discussion_3: 'Argue heatedly.',
    log_highschool_literature_discussion_3: 'I got into a heated debate over the book\'s theme.',

    // Triggered Events
    event_highschool_late_slip_title: 'Got a Late Slip',
    event_highschool_late_slip_desc: 'You were written up for being late.',
    choice_highschool_late_slip_1: 'Apologize and promise not to repeat it.',
    log_highschool_late_slip_1: 'I apologized and promised it wouldn\'t happen again.',
    choice_highschool_late_slip_2: 'Accept the punishment.',
    log_highschool_late_slip_2: 'I accepted the detention.',
    choice_highschool_late_slip_3: 'Argue back with a valid reason.',
    log_highschool_late_slip_3: 'I argued that the traffic was a valid excuse.',

    event_highschool_teacher_discovers_hiding_title: 'Teacher Found Out',
    event_highschool_teacher_discovers_hiding_desc: 'The teacher discovered you didn\'t have your book and were trying to hide it.',
    choice_highschool_teacher_discovers_hiding_1: 'Apologize.',
    log_highschool_teacher_discovers_hiding_1: 'I apologized for forgetting and for not being honest.',
    choice_highschool_teacher_discovers_hiding_2: 'Make an excuse.',
    log_highschool_teacher_discovers_hiding_2: 'I tried to come up with a reason.',
    choice_highschool_teacher_discovers_hiding_3: 'Accept a deduction in grade.',
    log_highschool_teacher_discovers_hiding_3: 'I accepted that my grade would be lowered.',

    event_highschool_coach_punishment_title: 'Punished by the Coach',
    event_highschool_coach_punishment_desc: 'The coach punished you for being lazy during practice.',
    choice_highschool_coach_punishment_1: 'Run extra laps.',
    log_highschool_coach_punishment_1: 'I had to run extra laps as punishment.',
    choice_highschool_coach_punishment_2: 'Sit on the penalty bench.',
    log_highschool_coach_punishment_2: 'I had to sit out for the rest of the practice.',
    choice_highschool_coach_punishment_3: 'Try to practice seriously.',
    log_highschool_coach_punishment_3: 'I started practicing harder to make up for it.',

    event_highschool_counselor_reprimand_title: 'Reprimanded by Counselor',
    event_highschool_counselor_reprimand_desc: 'The school counselor reprimanded you for not taking the workshop seriously.',
    choice_highschool_counselor_reprimand_1: 'Go back and participate.',
    log_highschool_counselor_reprimand_1: 'I rejoined the workshop and paid attention.',
    choice_highschool_counselor_reprimand_2: 'Pretend to take notes.',
    log_highschool_counselor_reprimand_2: 'I pretended to be engaged.',
    choice_highschool_counselor_reprimand_3: 'Secretly continue scrolling on the phone.',
    log_highschool_counselor_reprimand_3: 'I just kept looking at my phone.',

    event_highschool_invigilator_warning_test_title: 'Warning from Invigilator',
    event_highschool_invigilator_warning_test_desc: 'The invigilator warned you during the test.',
    choice_highschool_invigilator_warning_test_1: 'Put your head down and continue.',
    log_highschool_invigilator_warning_test_1: 'I focused on my test.',
    choice_highschool_invigilator_warning_test_2: 'Argue back, "I was just asking a friend".',
    log_highschool_invigilator_warning_test_2: 'I tried to defend myself.',
    choice_highschool_invigilator_warning_test_3: 'Silently accept the point deduction.',
    log_highschool_invigilator_warning_test_3: 'I accepted the consequences.',

    event_highschool_crush_rejects_promposal_title: 'Rejected by Crush',
    event_highschool_crush_rejects_promposal_desc: 'Your crush rejected your promposal.',
    choice_highschool_crush_rejects_promposal_1: 'Laugh it off.',
    log_highschool_crush_rejects_promposal_1: 'I played it cool and laughed it off.',
    choice_highschool_crush_rejects_promposal_2: 'Avoid them awkwardly.',
    log_highschool_crush_rejects_promposal_2: 'It was too embarrassing to face them.',
    choice_highschool_crush_rejects_promposal_3: 'Still invite them to go with a group.',
    log_highschool_crush_rejects_promposal_3: 'I suggested we could all go as friends.',

    event_highschool_teased_by_friends_crush_title: 'Teased by Friends',
    event_highschool_teased_by_friends_crush_desc: 'Your friends are teasing you for sitting next to your crush.',
    choice_highschool_teased_by_friends_crush_1: 'Laugh it off.',
    log_highschool_teased_by_friends_crush_1: 'I just laughed along with them.',
    choice_highschool_teased_by_friends_crush_2: 'Move to another seat.',
    log_highschool_teased_by_friends_crush_2: 'I got flustered and moved away.',
    choice_highschool_teased_by_friends_crush_3: 'Joke back.',
    log_highschool_teased_by_friends_crush_3: 'I teased them right back.',

    event_highschool_caught_skipping_title: 'Caught Skipping',
    event_highschool_caught_skipping_desc: 'A monitor caught you skipping the game.',
    choice_highschool_caught_skipping_1: 'Claim "I was going to the restroom".',
    log_highschool_caught_skipping_1: 'I made up an excuse.',
    choice_highschool_caught_skipping_2: 'Accept being written up.',
    log_highschool_caught_skipping_2: 'I accepted the punishment.',
    choice_highschool_caught_skipping_3: 'Sneak back to class.',
    log_highschool_caught_skipping_3: 'I tried to sneak back to avoid getting in more trouble.',

    event_highschool_teacher_reprimand_cheating_title: 'Reprimanded for Cheating',
    event_highschool_teacher_reprimand_cheating_desc: 'The teacher reprimanded you for looking at your friend\'s paper.',
    choice_highschool_teacher_reprimand_cheating_1: 'Apologize.',
    log_highschool_teacher_reprimand_cheating_1: 'I admitted my mistake and apologized.',
    choice_highschool_teacher_reprimand_cheating_2: 'Explain "I was just looking around".',
    log_highschool_teacher_reprimand_cheating_2: 'I tried to make an excuse.',
    choice_highschool_teacher_reprimand_cheating_3: 'Accept the point deduction.',
    log_highschool_teacher_reprimand_cheating_3: 'I accepted the penalty.',

    event_highschool_argument_with_friend_title: 'Argument with Friend',
    event_highschool_argument_with_friend_desc: 'You got into an argument with your friend during the discussion.',
    choice_highschool_argument_with_friend_1: 'Apologize.',
    log_highschool_argument_with_friend_1: 'I apologized to smooth things over.',
    choice_highschool_argument_with_friend_2: 'Continue the debate.',
    log_highschool_argument_with_friend_2: 'We continued to debate our points.',
    choice_highschool_argument_with_friend_3: 'Withdraw silently.',
    log_highschool_argument_with_friend_3: 'I decided to drop the subject.',

    // Independent Events
    event_highschool_club_activity_title: 'Club Activity',
    event_highschool_club_activity_desc: 'You are at a club meeting.',
    choice_highschool_club_activity_1: 'Participate actively.',
    log_highschool_club_activity_1: 'I was very engaged in the club\'s activities.',
    choice_highschool_club_activity_2: 'Just sit and listen.',
    log_highschool_club_activity_2: 'I preferred to just listen this time.',
    choice_highschool_club_activity_3: 'Try one session and then quit.',
    log_highschool_club_activity_3: 'The club wasn\'t for me.',

    event_highschool_playing_sports_title: 'Playing Sports at School',
    event_highschool_playing_sports_desc: 'You are playing sports in the schoolyard.',
    choice_highschool_playing_sports_1: 'Join a soccer game.',
    log_highschool_playing_sports_1: 'I joined a pickup soccer game.',
    choice_highschool_playing_sports_2: 'Be a cheerleader.',
    log_highschool_playing_sports_2: 'I cheered for my friends.',
    choice_highschool_playing_sports_3: 'Sit and eat snacks.',
    log_highschool_playing_sports_3: 'I just relaxed and had some snacks.',

    event_highschool_lunchtime_title: 'Lunchtime',
    event_highschool_lunchtime_desc: 'It\'s lunchtime.',
    choice_highschool_lunchtime_1: 'Eat with your close friends.',
    log_highschool_lunchtime_1: 'I had lunch with my best friends.',
    choice_highschool_lunchtime_2: 'Sit with another class.',
    log_highschool_lunchtime_2: 'I sat with some people from another class.',
    choice_highschool_lunchtime_3: 'Eat quickly and leave.',
    log_highschool_lunchtime_3: 'I had other things to do, so I ate quickly.',

    event_highschool_surprise_oral_exam_title: 'Surprise Oral Exam',
    event_highschool_surprise_oral_exam_desc: 'The teacher gives a surprise oral exam.',
    choice_highschool_surprise_oral_exam_1: 'Answer correctly.',
    log_highschool_surprise_oral_exam_1: 'I was able to answer the question.',
    choice_highschool_surprise_oral_exam_2: 'Stutter.',
    log_highschool_surprise_oral_exam_2: 'I was caught off guard and couldn\'t answer well.',
    choice_highschool_surprise_oral_exam_3: 'Laugh and ask the teacher to skip.',
    log_highschool_surprise_oral_exam_3: 'I tried to charm my way out of it.',

    event_highschool_library_study_group_title: 'Library Study Group',
    event_highschool_library_study_group_desc: 'You are in a study group at the library.',
    choice_highschool_library_study_group_1: 'Study diligently.',
    log_highschool_library_study_group_1: 'We were very productive.',
    choice_highschool_library_study_group_2: 'Study while talking.',
    log_highschool_library_study_group_2: 'We studied a bit, but mostly just chatted.',
    choice_highschool_library_study_group_3: 'Mostly listen.',
    log_highschool_library_study_group_3: 'I let others do most of the talking.',

    event_highschool_teacher_praise_title: 'Praised by Teacher',
    event_highschool_teacher_praise_desc: 'The teacher praised you in front of the class.',
    choice_highschool_teacher_praise_1: 'Feel shy.',
    log_highschool_teacher_praise_1: 'I was embarrassed by the praise.',
    choice_highschool_teacher_praise_2: 'Feel proud.',
    log_highschool_teacher_praise_2: 'It felt great to be recognized.',
    choice_highschool_teacher_praise_3: 'Pretend to be indifferent.',
    log_highschool_teacher_praise_3: 'I acted like it wasn\'t a big deal.',

    event_highschool_teacher_criticism_title: 'Criticized by Teacher',
    event_highschool_teacher_criticism_desc: 'The teacher criticized you.',
    choice_highschool_teacher_criticism_1: 'Listen silently.',
    log_highschool_teacher_criticism_1: 'I accepted the criticism.',
    choice_highschool_teacher_criticism_2: 'Argue back.',
    log_highschool_teacher_criticism_2: 'I tried to defend myself.',
    choice_highschool_teacher_criticism_3: 'Think sadly.',
    log_highschool_teacher_criticism_3: 'The criticism made me feel bad.',

    event_highschool_class_trip_title: 'Class Trip',
    event_highschool_class_trip_desc: 'You are on a class trip.',
    choice_highschool_class_trip_1: 'Take souvenir photos.',
    log_highschool_class_trip_1: 'I took a lot of pictures to remember the trip.',
    choice_highschool_class_trip_2: 'Participate in games.',
    log_highschool_class_trip_2: 'I joined in all the fun activities.',
    choice_highschool_class_trip_3: 'Sit and have a private conversation.',
    log_highschool_class_trip_3: 'I spent the time chatting with a close friend.',

    event_highschool_class_debate_title: 'Class Debate',
    event_highschool_class_debate_desc: 'You are in a class debate.',
    choice_highschool_class_debate_1: 'Voice your opinion strongly.',
    log_highschool_class_debate_1: 'I made a strong case for my point of view.',
    choice_highschool_class_debate_2: 'Listen to your friends.',
    log_highschool_class_debate_2: 'I listened to what others had to say.',
    choice_highschool_class_debate_3: 'Chime in with a few sentences.',
    log_highschool_class_debate_3: 'I added a few comments to the discussion.',

    event_highschool_class_birthday_party_title: 'Classmate\'s Birthday Party',
    event_highschool_class_birthday_party_desc: 'Your class is celebrating a birthday.',
    choice_highschool_class_birthday_party_1: 'Sing "Happy Birthday".',
    log_highschool_class_birthday_party_1: 'I sang along with everyone.',
    choice_highschool_class_birthday_party_2: 'Eat cake.',
    log_highschool_class_birthday_party_2: 'The cake was the best part.',
    choice_highschool_class_birthday_party_3: 'Joke around.',
    log_highschool_class_birthday_party_3: 'I was the life of the party.',

    event_highschool_sports_day_title: 'Sports Day',
    event_highschool_sports_day_desc: 'It\'s the school sports day.',
    choice_highschool_sports_day_1: 'Compete in the race.',
    log_highschool_sports_day_1: 'I competed in a running event.',
    choice_highschool_sports_day_2: 'Do the long jump.',
    log_highschool_sports_day_2: 'I tried my best in the long jump.',
    choice_highschool_sports_day_3: 'Be a cheerleader.',
    log_highschool_sports_day_3: 'I cheered for my friends.',

    event_highschool_chemistry_test_title: 'Chemistry Test',
    event_highschool_chemistry_test_desc: 'You have a chemistry test.',
    choice_highschool_chemistry_test_1: 'Follow the procedures correctly.',
    log_highschool_chemistry_test_1: 'I was careful and followed all the steps.',
    choice_highschool_chemistry_test_2: 'Try to be creative.',
    log_highschool_chemistry_test_2: 'I experimented a bit.',
    choice_highschool_chemistry_test_3: 'Ask the person next to you.',
    log_highschool_chemistry_test_3: 'I needed some help from my classmate.',

    event_highschool_meeting_teacher_outside_title: 'Meeting a Teacher Outside School',
    event_highschool_meeting_teacher_outside_desc: 'You run into a teacher outside of school.',
    choice_highschool_meeting_teacher_outside_1: 'Greet them.',
    log_highschool_meeting_teacher_outside_1: 'I said hello to my teacher.',
    choice_highschool_meeting_teacher_outside_2: 'Give a forced smile.',
    log_highschool_meeting_teacher_outside_2: 'It was a bit awkward.',
    choice_highschool_meeting_teacher_outside_3: 'Pretend not to see them.',
    log_highschool_meeting_teacher_outside_3: 'I avoided eye contact.',

    event_highschool_international_visitor_title: 'International Visitor in Class',
    event_highschool_international_visitor_desc: 'There is an international visitor in your class.',
    choice_highschool_international_visitor_1: 'Speak English with them.',
    log_highschool_international_visitor_1: 'I practiced my English with the visitor.',
    choice_highschool_international_visitor_2: 'Smile and say hello.',
    log_highschool_international_visitor_2: 'I gave them a friendly greeting.',
    choice_highschool_international_visitor_3: 'Sit quietly.',
    log_highschool_international_visitor_3: 'I was too shy to say anything.',

    event_highschool_parent_teacher_meeting_title: 'Parent-Teacher Meeting',
    event_highschool_parent_teacher_meeting_desc: 'It\'s the day of parent-teacher meetings.',
    choice_highschool_parent_teacher_meeting_1: 'Sit quietly and listen.',
    log_highschool_parent_teacher_meeting_1: 'I listened to what the teacher had to say.',
    choice_highschool_parent_teacher_meeting_2: 'Feel nervous.',
    log_highschool_parent_teacher_meeting_2: 'I was worried about what the teacher would say.',
    choice_highschool_parent_teacher_meeting_3: 'Whisper to your friend.',
    log_highschool_parent_teacher_meeting_3: 'My friend and I whispered during the meeting.',

    event_highschool_museum_trip_title: 'Museum Field Trip',
    event_highschool_museum_trip_desc: 'You are on a field trip to a museum.',
    choice_highschool_museum_trip_1: 'Listen attentively.',
    log_highschool_museum_trip_1: 'I found the exhibits very interesting.',
    choice_highschool_museum_trip_2: 'Just look around.',
    log_highschool_museum_trip_2: 'I mostly just wandered around.',
    choice_highschool_museum_trip_3: 'Make small jokes.',
    log_highschool_museum_trip_3: 'I goofed off with my friends.',

    event_highschool_prom_prep_title: 'Preparing for Prom',
    event_highschool_prom_prep_desc: 'Prom is coming up, and you need to prepare.',
    choice_highschool_prom_prep_1: 'Buy clothes.',
    log_highschool_prom_prep_1: 'I went shopping for the perfect outfit.',
    choice_highschool_prom_prep_2: 'Go with a group of friends.',
    log_highschool_prom_prep_2: 'I decided to go to prom with my friends.',
    choice_highschool_prom_prep_3: 'Stay home and watch a movie.',
    log_highschool_prom_prep_3: 'Prom isn\'t really my thing.',

    event_highschool_talent_show_title: 'Class Talent Show',
    event_highschool_talent_show_desc: 'Your class is having a talent show.',
    choice_highschool_talent_show_1: 'Participate in singing and dancing.',
    log_highschool_talent_show_1: 'I decided to perform in the show.',
    choice_highschool_talent_show_2: 'Work backstage.',
    log_highschool_talent_show_2: 'I helped out with the logistics.',
    choice_highschool_talent_show_3: 'Sit and watch.',
    log_highschool_talent_show_3: 'I enjoyed watching my classmates perform.',

    event_highschool_exam_results_title: 'Receive Exam Results',
    event_highschool_exam_results_desc: 'You have received your exam results.',
    choice_highschool_exam_results_1: 'Joyfully show them off.',
    log_highschool_exam_results_1: 'I was proud of my results.',
    choice_highschool_exam_results_2: 'Keep them quiet.',
    log_highschool_exam_results_2: 'I kept my results to myself.',
    choice_highschool_exam_results_3: 'Feel sad.',
    log_highschool_exam_results_3: 'I was disappointed with my scores.',

    event_highschool_sharing_food_title: 'Sharing Food',
    event_highschool_sharing_food_desc: 'You are sharing food with friends.',
    choice_highschool_sharing_food_1: 'Give a portion to a friend.',
    log_highschool_sharing_food_1: 'I shared my snack with a friend.',
    choice_highschool_sharing_food_2: 'Trade dishes.',
    log_highschool_sharing_food_2: 'We traded some of our lunch items.',
    choice_highschool_sharing_food_3: 'Keep your portion.',
    log_highschool_sharing_food_3: 'I was too hungry to share.',
};
