
export default {
    event_flu_title: 'Caught the Flu',
    event_flu_desc: 'You have a bad flu, feeling weak and achy.',
    choice_flu_1: 'See a doctor and take medicine.',
    log_flu_1: 'The medicine helped me recover quickly.',
    choice_flu_2: 'Rest at home and drink plenty of water.',
    log_flu_2: 'I decided to treat it myself at home.',
    event_sickness_worsens_title: 'Sickness Worsens',
    event_sickness_worsens_desc: 'Your condition has worsened. You feel much weaker.',
    choice_sickness_worsens_1: 'Go to the hospital immediately.',
    log_sickness_worsens_1: 'I received proper treatment at the hospital and started to feel better.',
    choice_sickness_worsens_2: 'Continue to rest at home, hoping it will pass.',
    log_sickness_worsens_2: 'I hoped it would go away on its own, but it didn\'t.',
    event_chronic_illness_title: 'Chronic Illness',
    event_chronic_illness_desc: "The doctor diagnosed you with a chronic illness.",
    choice_chronic_illness_1: 'Follow the treatment and stay optimistic.',
    log_chronic_illness_1: 'I learned to live with the illness and not let it affect my life.',
    choice_chronic_illness_2: 'Feel hopeless and neglect your health.',
    log_chronic_illness_2: 'This illness has taken away my joy of living.',
    event_traffic_accident_title: 'Traffic Accident',
    event_traffic_accident_desc: "You've been involved in a minor traffic accident.",
    choice_traffic_accident_1: 'Settle it peacefully and pay compensation.',
    log_traffic_accident_1: 'Luckily, no one was seriously injured.',
    choice_traffic_accident_2: 'Argue and blame the other person.',
    log_traffic_accident_2: 'The argument solved nothing and only made things worse.',
    event_sued_title: 'Sued',
    event_sued_desc: 'You received a summons from the court.',
    choice_sued_1: 'Hire a lawyer and resolve it.',
    log_sued_1: 'The lawsuit was settled amicably.',
    choice_sued_2: 'Defend yourself.',
    log_sued_2: 'I lost the case and had to pay a large compensation.',
    event_lottery_win_title: 'Lottery Win!',
    event_lottery_win_desc: "You've won a big lottery prize!",
    choice_lottery_win_1: 'Invest wisely.',
    log_lottery_win_1: 'This money will secure my family\'s future.',
    choice_lottery_win_2: 'Spend it and enjoy.',
    log_lottery_win_2: 'Money comes and goes, the important thing is to be happy!',
    event_friends_exploit_title: 'Friends Take Advantage',
    event_friends_exploit_desc: 'After you won the lottery, many old friends suddenly appeared and asked to borrow money.',
    choice_friends_exploit_1: 'Help them.',
    log_friends_exploit_1: 'I lent them some money.',
    choice_friends_exploit_2: 'Politely refuse.',
    log_friends_exploit_2: 'I realized who my true friends are.',
    event_lose_friend_title: 'Lost a Friend',
    event_lose_friend_desc: 'A friend is no longer talking to you.',
    choice_lose_friend_1: 'Feel sad.',
    log_lose_friend_1: 'I lost a good friend.',
    choice_lose_friend_2: 'Do not care.',
    log_lose_friend_2: "If they don't want to be friends, I don't need them either.",
    event_lost_wallet_title: 'Lost Wallet',
    event_lost_wallet_desc: "You realize you've lost your wallet.",
    choice_lost_wallet_1: 'Report to the police and get new documents.',
    log_lost_wallet_1: 'What an unlucky day.',
    choice_lost_wallet_2: 'Hope someone returns it.',
    log_lost_wallet_2: 'My wallet was never found.',
    event_buy_house_title: 'Buy a House',
    event_buy_house_desc: 'Your family is considering buying a new house.',
    choice_buy_house_1: 'Buy a large house.',
    log_buy_house_1: 'We bought a dream house.',
    choice_buy_house_2: 'Buy a small house.',
    log_buy_house_2: 'A cozy house is enough for us.',
    choice_buy_house_3: 'Continue renting.',
    log_buy_house_3: "Now is not the right time to buy a house.",
    event_buy_car_title: 'Buy a Car',
    event_buy_car_desc: "You're thinking about buying a car.",
    choice_buy_car_1: 'Buy a luxury car.',
    log_buy_car_1: 'The new car is amazing.',
    choice_buy_car_2: 'Buy a standard car.',
    log_buy_car_2: 'The car serves the family\'s needs well.',
    choice_buy_car_3: 'Use public transport.',
    log_buy_car_3: "I don't really need a car.",
    event_burglary_title: 'Burglary',
    event_burglary_desc: 'Your house was broken into by a burglar.',
    choice_burglary_1: 'Report to the police and enhance security.',
    log_burglary_1: 'We installed a new alarm system.',
    choice_burglary_2: 'Confront the burglar.',
    log_burglary_2: 'It was a foolish act, I got injured.',
    event_online_scam_title: 'Online Scam',
    event_online_scam_desc: 'You received a suspicious email promising a large profit.',
    choice_online_scam_1: 'Fell for it.',
    log_online_scam_1: 'I lost a large amount of money because I was too trusting.',
    choice_online_scam_2: 'Realized it was a scam.',
    log_online_scam_2: 'Luckily, I was sober enough to realize it.',
    event_charity_donation_title: 'Charity Donation',
    event_charity_donation_desc: 'A charity is asking for donations.',
    choice_charity_donation_1: 'Donate a large amount.',
    log_charity_donation_1: 'I am happy to be able to help others.',
    choice_charity_donation_2: 'Donate a small amount.',
    log_charity_donation_2: 'Every little bit helps.',
    choice_charity_donation_3: 'Do not donate.',
    log_charity_donation_3: 'I need to take care of my family first.',
    event_job_loss_social_crisis_title: 'Job Loss due to Crisis',
    event_job_loss_social_crisis_desc: 'Due to an economic crisis, your company had to downsize, and you were among those laid off.',
    choice_job_loss_social_crisis_1: 'Accept it and look for new opportunities.',
    log_job_loss_social_crisis_1: "It's a challenge, but I'll get through it.",
    choice_job_loss_social_crisis_2: 'Feel hopeless.',
    log_job_loss_social_crisis_2: "I don't know what to do now.",
    event_natural_disaster_title: 'Natural Disaster',
    event_natural_disaster_desc: 'A natural disaster has occurred in your area.',
    choice_natural_disaster_1: 'Your family is safe.',
    log_natural_disaster_1: 'Thankfully, everyone is safe.',
    choice_natural_disaster_2: 'Your house was damaged.',
    log_natural_disaster_2: 'We will have to repair the house.',
    event_street_assault_title: 'Street Assault',
    event_street_assault_desc: 'You were attacked by a stranger on the street.',
    choice_street_assault_1: 'Fight back and run.',
    log_street_assault_1: 'Luckily, I managed to escape.',
    choice_street_assault_2: 'Got robbed and injured.',
    log_street_assault_2: 'It was a terrifying experience.',
    log_asset_lost_robbery: '{name} was robbed and lost a valuable item: {assetName}.',
    event_getting_lost_title: 'Getting Lost',
    event_getting_lost_desc: 'You got lost in an unfamiliar place.',
    choice_getting_lost_1: 'Found your way home.',
    log_getting_lost_1: 'I finally found my way back.',
    choice_getting_lost_2: 'Encountered danger.',
    log_getting_lost_2: 'I got into trouble when I was lost.',
    event_unpaid_debt_title: 'Unpaid Debt',
    event_unpaid_debt_desc: 'An old friend is asking for a debt you forgot about.',
    choice_unpaid_debt_1: 'Pay it back.',
    log_unpaid_debt_1: 'I paid back the full amount I owed.',
    choice_unpaid_debt_2: 'Avoid them.',
    log_unpaid_debt_2: "I don't have the money to pay right now.",
    event_tax_evasion_discovered_title: 'Tax Evasion Discovered',
    event_tax_evasion_discovered_desc: 'The tax office has discovered an error in your records.',
    choice_tax_evasion_discovered_1: 'Pay the fine and comply.',
    log_tax_evasion_discovered_1: 'I had to pay a large fine.',
    choice_tax_evasion_discovered_2: 'Try to deny it.',
    log_tax_evasion_discovered_2: 'This only made things worse.',
    event_investment_opportunity_title: 'Investment Opportunity',
    event_investment_opportunity_desc: 'You have a promising investment opportunity.',
    choice_investment_opportunity_1: 'Invest a large amount.',
    log_investment_opportunity_1: 'High risk, high reward.',
    choice_investment_opportunity_2: 'Invest a small amount.',
    log_investment_opportunity_2: "Let's give it a try.",
    choice_investment_opportunity_3: 'Ignore it.',
    log_investment_opportunity_3: "I don't want to take the risk.",
    event_investment_failure_title: 'Investment Failure',
    event_investment_failure_desc: 'Your investment has failed.',
    choice_investment_failure_1: 'Lost all the money.',
    log_investment_failure_1: 'It was an expensive lesson.',
    choice_investment_failure_2: 'Luckily, only lost a part of it.',
    log_investment_failure_2: 'Maybe I should not invest anymore.',
    event_small_lottery_title: 'Small Lottery Win',
    event_small_lottery_desc: 'You won a small lottery prize.',
    choice_small_lottery_1: 'Even a small amount is nice.',
    log_small_lottery_1: "I'll use this money to buy a nice meal.",
    choice_small_lottery_2: 'Buy more lottery tickets.',
    log_small_lottery_2: 'I used all the winnings to buy more tickets and won nothing.',
    event_get_a_pet_title: 'Get a Pet',
    event_get_a_pet_desc: "You're considering getting a pet.",
    choice_get_a_pet_1: 'Brings joy.',
    log_get_a_pet_1: 'The pet has become an indispensable member of the family.',
    choice_get_a_pet_2: 'Causes a lot of trouble.',
    log_get_a_pet_2: 'Raising a pet is more work than I thought.',
    event_loan_shark_title: 'Loan Shark',
    event_loan_shark_desc: 'Due to a shortage of money, you considered borrowing from a loan shark.',
    choice_loan_shark_1: 'No, too dangerous.',
    log_loan_shark_1: "I'll find another solution.",
    choice_loan_shark_2: 'Borrow a small amount.',
    log_loan_shark_2: 'I hope I can pay it back soon.',
    event_loan_shark_enforcers_title: 'Debt Collectors',
    event_loan_shark_enforcers_desc: 'The loan sharks came to collect the debt.',
    choice_loan_shark_enforcers_1: 'Pay the money.',
    log_loan_shark_enforcers_1: 'I had to pay a much larger amount than I borrowed.',
    choice_loan_shark_enforcers_2: 'Got beaten up.',
    log_loan_shark_enforcers_2: 'I learned a painful lesson.',
    event_relative_is_sick_title: 'Relative is Sick',
    event_relative_is_sick_desc: 'A relative of yours is seriously ill.',
    choice_relative_is_sick_1: 'Help with medical expenses.',
    log_relative_is_sick_1: 'Family is the most important thing.',
    choice_relative_is_sick_2: 'Can only offer moral support.',
    log_relative_is_sick_2: 'I wish I could do more.',
    event_self_development_seminar_title: 'Self-Development Seminar',
    event_self_development_seminar_desc: 'You are invited to a self-development seminar.',
    choice_self_development_seminar_1: 'Attend and learn.',
    log_self_development_seminar_1: 'I learned many useful things.',
    choice_self_development_seminar_2: 'Decline.',
    log_self_development_seminar_2: "I don't believe in these things.",
    event_minor_accident_title: 'Minor Accident',
    event_minor_accident_desc: 'You had a minor accident in your daily life.',
    choice_minor_accident_1: 'Go to the doctor and get treatment.',
    log_minor_accident_1: 'The injury was not too serious.',
    choice_minor_accident_2: 'Treat it at home.',
    log_minor_accident_2: 'The injury seems worse than I thought.',
    event_pyramid_scheme_title: 'Pyramid Scheme',
    event_pyramid_scheme_desc: 'A friend introduces you to a pyramid scheme.',
    choice_pyramid_scheme_1: 'Join.',
    log_pyramid_scheme_1: 'I lost all my money.',
    choice_pyramid_scheme_2: 'Decline.',
    log_pyramid_scheme_2: "I don't believe in those promises.",
    event_relative_death_title: 'Relative Passes Away',
    event_relative_death_desc: 'You receive sad news that a distant relative (not in the family tree) has passed away.',
    choice_relative_death_1: 'Organize a funeral.',
    log_relative_death_1: 'It is a great loss.',
    choice_relative_death_2: 'Feel devastated.',
    log_relative_death_2: 'I cannot accept this reality.',
    event_large_gift_title: 'Large Gift',
    event_large_gift_desc: 'You received a large gift from a relative.',
    choice_large_gift_1: 'Feel grateful.',
    log_large_gift_1: 'This gift means a lot to me.',
    choice_large_gift_2: 'Feel awkward.',
    log_large_gift_2: "I don't know what to do in return.",
    event_stranger_asks_for_help_title: 'Stranger Asks for Help',
    event_stranger_asks_for_help_desc: 'A stranger asks for your help.',
    choice_stranger_asks_for_help_1: 'Help them.',
    log_stranger_asks_for_help_1: 'Doing a good deed makes me feel happy.',
    choice_stranger_asks_for_help_2: 'Decline.',
    log_stranger_asks_for_help_2: "I don't want to get into trouble.",
    event_social_movement_title: 'Social Movement',
    event_social_movement_desc: 'A social movement is growing in the city. Many people are protesting for change.',
    choice_social_movement_1: 'Join the movement and fight for what is right.',
    log_social_movement_1: 'I feel empowered by joining the social movement.',
    choice_social_movement_2: 'Stay away from it. Too risky.',
    log_social_movement_2: 'I decided it was best to stay away from the protests.',
    event_homeless_person_title: 'Homeless Person',
    event_homeless_person_desc: 'You encounter a homeless person on the street.',
    choice_homeless_person_1: 'Give them some money.',
    log_homeless_person_1: 'I hope it helps them a little.',
    choice_homeless_person_2: 'Walk by.',
    log_homeless_person_2: 'I have nothing to give.',
    event_lost_valuable_item_title: 'Lost a Valuable Item',
    event_lost_valuable_item_desc: 'You lost a valuable item.',
    choice_lost_valuable_item_1: 'Found it again.',
    log_lost_valuable_item_1: 'What a relief!',
    choice_lost_valuable_item_2: 'Lost it for good.',
    log_lost_valuable_item_2: 'I was very sad.',
    event_rescued_from_accident_title: 'Rescued from an Accident',
    event_rescued_from_accident_desc: 'You were about to have an accident but were saved by a stranger.',
    choice_rescued_from_accident_1: 'Feel grateful.',
    log_rescued_from_accident_1: 'I thanked the person profusely.',
    choice_rescued_from_accident_2: 'Feel shocked.',
    log_rescued_from_accident_2: "I'm still shaking.",
    event_falsely_accused_title: 'Falsely Accused',
    event_falsely_accused_desc: 'You were falsely accused of something you did not do.',
    choice_falsely_accused_1: 'Proved your innocence.',
    log_falsely_accused_1: 'The truth finally came out.',
    choice_falsely_accused_2: 'Could not prove it.',
    log_falsely_accused_2: 'No one believed me.',
    event_surprise_gift_title: 'Surprise Gift',
    event_surprise_gift_desc: 'You received a surprise gift.',
    choice_surprise_gift_1: 'Very happy.',
    log_surprise_gift_1: 'The gift is wonderful!',
    choice_surprise_gift_2: 'A bit confused.',
    log_surprise_gift_2: "I don't know why I received it.",
    // Trigger-only
    event_investment_success_large_title: 'Investment Success!',
    event_investment_success_large_desc: 'Your large investment has yielded a huge profit!',
    choice_investment_success_large_1: 'Wonderful!',
    log_investment_success_large_1: 'The risk paid off.',
    choice_investment_success_large_2: 'Reinvest immediately.',
    log_investment_success_large_2: "I'll use this money to continue investing.",
    event_investment_success_small_title: 'Investment Success',
    event_investment_success_small_desc: 'Your small investment has yielded a decent profit.',
    choice_investment_success_small_1: 'A good start.',
    log_investment_success_small_1: 'This is a good sign.',
    choice_investment_success_small_2: 'Celebrate this success.',
    log_investment_success_small_2: "I'll treat myself a little.",
};
