export default {
    event_flu_title: 'Caught the Flu',
    event_flu_desc: 'You have a bad flu, feeling weak and achy.',
    choice_flu_1: 'See a doctor and take medicine.',
    log_flu_1: 'The medicine helped me recover quickly.',
    choice_flu_2: 'Rest at home and drink plenty of water.',
    log_flu_2: 'I decided to treat it myself at home, and recovered slowly.',
    choice_flu_3: 'Ignore it and go to school/work.',
    log_flu_3: 'The sickness got worse and I was criticized by others.',

    event_sickness_worsens_title: 'Sickness Worsens',
    event_sickness_worsens_desc: 'Your condition has worsened. You feel much weaker.',
    choice_sickness_worsens_1: 'Go to the hospital immediately.',
    log_sickness_worsens_1: 'I received proper treatment at the hospital and started to feel better.',
    choice_sickness_worsens_2: 'Continue to rest at home, hoping it will pass.',
    log_sickness_worsens_2: 'The sickness lingered on and on.',
    choice_sickness_worsens_3: 'Ask family to take care of you.',
    log_sickness_worsens_3: 'My spirits improved, but I still felt weak.',

    event_chronic_illness_title: 'Chronic Illness',
    event_chronic_illness_desc: "The doctor diagnosed you with a chronic illness.",
    choice_chronic_illness_1: 'Follow the treatment and stay optimistic.',
    log_chronic_illness_1: 'I managed the illness and kept it stable.',
    choice_chronic_illness_2: 'Ignore the doctor\'s advice.',
    log_chronic_illness_2: 'My condition became much worse.',
    choice_chronic_illness_3: 'Join a patient support group.',
    log_chronic_illness_3: 'I found encouragement and comfort.',

    event_traffic_accident_title: 'Traffic Accident',
    event_traffic_accident_desc: "You've been involved in a minor traffic accident.",
    choice_traffic_accident_1: 'Settle it peacefully and pay reasonable compensation.',
    log_traffic_accident_1: 'Everything was resolved smoothly.',
    choice_traffic_accident_2: 'Argue and blame the other person.',
    log_traffic_accident_2: 'The argument just wasted time.',
    choice_traffic_accident_3: 'Call the traffic police.',
    log_traffic_accident_3: 'It took longer to resolve, but it was fair.',

    event_sued_title: 'Sued',
    event_sued_desc: 'You received a summons from the court.',
    choice_sued_1: 'Hire a lawyer to defend you.',
    log_sued_1: 'The lawsuit was settled amicably.',
    choice_sued_2: 'Defend yourself.',
    log_sued_2: 'I lost the case and suffered heavy damages.',
    choice_sued_3: 'Negotiate with the other party.',
    log_sued_3: 'We settled, but my reputation was damaged.',

    event_lottery_win_title: 'Lottery Win!',
    event_lottery_win_desc: "You've won a big lottery prize!",
    choice_lottery_win_1: 'Invest for the long term.',
    log_lottery_win_1: 'The money generated profit, securing my future.',
    choice_lottery_win_2: 'Spend it and enjoy.',
    log_lottery_win_2: 'The joy was short-lived, the money quickly ran out.',
    choice_lottery_win_3: 'Deposit it in the bank.',
    log_lottery_win_3: 'The money is safe, but the interest is low.',

    event_friends_exploit_title: 'Friends Take Advantage',
    event_friends_exploit_desc: 'After you won the lottery, many old friends suddenly appeared and asked to borrow money.',
    choice_friends_exploit_1: 'Lend them some money.',
    log_friends_exploit_1: 'Some were grateful, some never paid me back.',
    choice_friends_exploit_2: 'Politely refuse.',
    log_friends_exploit_2: 'I realized who my true friends are.',
    choice_friends_exploit_3: 'Cut off contact.',
    log_friends_exploit_3: 'I avoided trouble but felt lonely.',

    event_lose_friend_title: 'Lost a Friend',
    event_lose_friend_desc: 'A friend is no longer talking to you.',
    choice_lose_friend_1: 'Proactively ask for the reason.',
    log_lose_friend_1: 'We started talking again, but it was a bit awkward.',
    choice_lose_friend_2: 'Accept it and move on.',
    log_lose_friend_2: 'I was sad, but I moved on with my life.',
    choice_lose_friend_3: 'Ignore them back.',
    log_lose_friend_3: 'The friendship quietly ended.',

    event_lost_wallet_title: 'Lost Wallet',
    event_lost_wallet_desc: "You realize you've lost your wallet.",
    choice_lost_wallet_1: 'Report to the police and get new documents.',
    log_lost_wallet_1: 'It was a hassle, but at least I was safe.',
    choice_lost_wallet_2: 'Hope someone returns it.',
    log_lost_wallet_2: 'My wallet was never found.',
    choice_lost_wallet_3: 'Borrow money from friends temporarily.',
    log_lost_wallet_3: 'My friends helped me through the tough time.',

    event_buy_house_title: 'Buy a House',
    event_buy_house_desc: 'Your family is considering buying a new house.',
    choice_buy_house_1: 'Buy a large house.',
    log_buy_house_1: 'We lived in a spacious house but were deep in debt.',
    choice_buy_house_2: 'Buy a small, affordable house.',
    log_buy_house_2: 'It was cozy and easy to manage.',
    choice_buy_house_3: 'Continue renting.',
    log_buy_house_3: "It was flexible, but not stable.",

    event_buy_car_title: 'Buy a Car',
    event_buy_car_desc: "You're thinking about buying a car.",
    choice_buy_car_1: 'Buy a luxury car.',
    log_buy_car_1: 'The car was beautiful but a financial drain.',
    choice_buy_car_2: 'Buy a standard car.',
    log_buy_car_2: 'It served our daily needs well.',
    choice_buy_car_3: 'Use public transport.',
    log_buy_car_3: "It was economical, but inconvenient.",

    event_burglary_title: 'Burglary',
    event_burglary_desc: 'Your house was broken into by a burglar.',
    choice_burglary_1: 'Report to the police and enhance security.',
    log_burglary_1: 'We installed a new alarm system.',
    choice_burglary_2: 'Confront the burglar.',
    log_burglary_2: 'It was a foolish act, I got injured.',
    choice_burglary_3: 'Hide and call the neighbors.',
    log_burglary_3: 'We got help in time and were safe.',

    event_online_scam_title: 'Online Scam',
    event_online_scam_desc: 'You received a suspicious email promising a large profit.',
    choice_online_scam_1: 'Fell for it and clicked.',
    log_online_scam_1: 'I lost a large amount of money because I was too trusting.',
    choice_online_scam_2: 'Ignored it.',
    log_online_scam_2: 'I was safe and didn\'t fall into the trap.',
    choice_online_scam_3: 'Report it as a scam.',
    log_online_scam_3: 'Others were also warned.',

    event_charity_donation_title: 'Charity Donation',
    event_charity_donation_desc: 'A charity is asking for donations.',
    choice_charity_donation_1: 'Donate a large amount.',
    log_charity_donation_1: 'I am happy to be able to help many people.',
    choice_charity_donation_2: 'Donate a small amount.',
    log_charity_donation_2: 'A small amount, but meaningful.',
    choice_charity_donation_3: 'Do not donate.',
    log_charity_donation_3: 'I kept the money to take care of my family.',

    event_job_loss_social_crisis_title: 'Job Loss due to Crisis',
    event_job_loss_social_crisis_desc: 'Due to an economic crisis, your company had to downsize, and you were among those laid off.',
    choice_job_loss_social_crisis_1: 'Quickly look for a new job.',
    log_job_loss_social_crisis_1: "I found a new opportunity, but it was very stressful.",
    choice_job_loss_social_crisis_2: 'Take a temporary break.',
    log_job_loss_social_crisis_2: "I felt relaxed but lost my income.",
    choice_job_loss_social_crisis_3: 'Learn a new skill.',
    log_job_loss_social_crisis_3: 'It was difficult at first but opened up a new path.',

    event_natural_disaster_title: 'Natural Disaster',
    event_natural_disaster_desc: 'A natural disaster has occurred in your area.',
    choice_natural_disaster_1: 'Protect the family first.',
    log_natural_disaster_1: 'Everyone was safe, but terrified.',
    choice_natural_disaster_2: 'Save your belongings.',
    log_natural_disaster_2: 'I saved my property, but it was very dangerous.',
    choice_natural_disaster_3: 'Join the community relief efforts.',
    log_natural_disaster_3: 'It was difficult, but I was proud to have helped.',

    event_street_assault_title: 'Street Assault',
    event_street_assault_desc: 'You were attacked by a stranger on the street.',
    choice_street_assault_1: 'Fight back and run.',
    log_street_assault_1: 'I managed to escape, but was injured.',
    choice_street_assault_2: 'Give them your belongings to stay safe.',
    log_street_assault_2: 'I was safe, but lost my valuables.',
    choice_street_assault_3: 'Scream for help.',
    log_street_assault_3: 'People nearby came to help.',
    log_asset_lost_robbery: '{name} was robbed and lost a valuable item: {assetName}.',

    event_getting_lost_title: 'Getting Lost',
    event_getting_lost_desc: 'You got lost in an unfamiliar place.',
    choice_getting_lost_1: 'Use a map/GPS.',
    log_getting_lost_1: 'I found my way back.',
    choice_getting_lost_2: 'Ask a stranger for directions.',
    log_getting_lost_2: 'Their helpful advice got me out of the situation.',
    choice_getting_lost_3: 'Wander around until you find a familiar road.',
    log_getting_lost_3: 'It took me hours to get back.',

    event_unpaid_debt_title: 'Unpaid Debt',
    event_unpaid_debt_desc: 'An old friend is asking for a debt you forgot about.',
    choice_unpaid_debt_1: 'Pay it all back immediately.',
    log_unpaid_debt_1: 'I kept my reputation but lost money.',
    choice_unpaid_debt_2: 'Avoid them.',
    log_unpaid_debt_2: "The debt haunted me.",
    choice_unpaid_debt_3: 'Negotiate a payment plan.',
    log_unpaid_debt_3: 'We agreed to pay it back in installments.',

    event_tax_evasion_discovered_title: 'Tax Evasion Discovered',
    event_tax_evasion_discovered_desc: 'The tax office has discovered an error in your records.',
    choice_tax_evasion_discovered_1: 'Pay the fine immediately.',
    log_tax_evasion_discovered_1: 'I lost money but avoided bigger trouble.',
    choice_tax_evasion_discovered_2: 'Deny responsibility.',
    log_tax_evasion_discovered_2: 'The fine increased after an investigation.',
    choice_tax_evasion_discovered_3: 'Hire an accountant to fix the records.',
    log_tax_evasion_discovered_3: 'Professional help minimized the risk.',

    event_investment_opportunity_title: 'Investment Opportunity',
    event_investment_opportunity_desc: 'You have a promising investment opportunity.',
    choice_investment_opportunity_1: 'Invest a large amount.',
    log_investment_opportunity_1: 'High potential, but risky.',
    choice_investment_opportunity_2: 'Invest a small amount to test it.',
    log_investment_opportunity_2: "I was cautious, but the profit was small.",
    choice_investment_opportunity_3: 'Ignore the offer.',
    log_investment_opportunity_3: "I avoided the risk but missed the opportunity.",

    event_investment_failure_title: 'Investment Failure',
    event_investment_failure_desc: 'Your recent investment has failed.',
    choice_investment_failure_1: 'Accept the loss and stop.',
    log_investment_failure_1: 'I stopped before losing more.',
    choice_investment_failure_2: 'Analyze the mistake to learn from it.',
    log_investment_failure_2: 'It was costly, but I gained experience.',
    choice_investment_failure_3: 'Invest elsewhere to recoup the loss.',
    log_investment_failure_3: 'I took a bigger risk hoping to recover.',

    event_small_lottery_title: 'Small Lottery Win',
    event_small_lottery_desc: 'You won a small lottery prize.',
    choice_small_lottery_1: 'Treat yourself to a nice meal.',
    log_small_lottery_1: "I'll use this money to buy a nice meal.",
    choice_small_lottery_2: 'Buy more lottery tickets.',
    log_small_lottery_2: 'I gambled and got nothing.',
    choice_small_lottery_3: 'Save it.',
    log_small_lottery_3: 'A small addition to my savings.',

    event_get_a_pet_title: 'Get a Pet',
    event_get_a_pet_desc: "You're considering getting a pet.",
    choice_get_a_pet_1: 'Adopt and take good care of it.',
    log_get_a_pet_1: 'The pet has become an indispensable member of the family.',
    choice_get_a_pet_2: 'Adopt but neglect your responsibility.',
    log_get_a_pet_2: 'The pet caused more stress than joy.',
    choice_get_a_pet_3: 'Foster temporarily first.',
    log_get_a_pet_3: 'I tried it out before making a long-term commitment.',

    event_loan_shark_title: 'Loan Shark',
    event_loan_shark_desc: 'Due to a shortage of money, you considered borrowing from a loan shark.',
    choice_loan_shark_1: 'No, too dangerous.',
    log_loan_shark_1: "I was safe, even though I was still short on money.",
    choice_loan_shark_2: 'Borrow a small amount.',
    log_loan_shark_2: 'A temporary solution, but a risk later on.',
    choice_loan_shark_3: 'Look for a bank or family loan.',
    log_loan_shark_3: 'I found a safer solution.',

    event_loan_shark_enforcers_title: 'Debt Collectors',
    event_loan_shark_enforcers_desc: 'The loan sharks came to collect the debt.',
    choice_loan_shark_enforcers_1: 'Pay them all.',
    log_loan_shark_enforcers_1: 'I had to pay a much larger amount than I borrowed.',
    choice_loan_shark_enforcers_2: 'Refuse and face the violence.',
    log_loan_shark_enforcers_2: 'I was injured and terrified.',
    choice_loan_shark_enforcers_3: 'Call the police for help.',
    log_loan_shark_enforcers_3: 'The authorities protected me, but I still owed money.',

    event_relative_is_sick_title: 'Relative is Sick',
    event_relative_is_sick_desc: 'A relative of yours is seriously ill.',
    choice_relative_is_sick_1: 'Help with medical expenses.',
    log_relative_is_sick_1: 'It was expensive, but family is the most important thing.',
    choice_relative_is_sick_2: 'Can only offer moral support.',
    log_relative_is_sick_2: 'I was by their side, even without money.',
    choice_relative_is_sick_3: 'Organize a fundraiser.',
    log_relative_is_sick_3: 'Community support eased the burden.',

    event_self_development_seminar_title: 'Self-Development Seminar',
    event_self_development_seminar_desc: 'You are invited to a self-development seminar.',
    choice_self_development_seminar_1: 'Attend and take notes.',
    log_self_development_seminar_1: 'I learned many new skills and ideas.',
    choice_self_development_seminar_2: 'Politely decline.',
    log_self_development_seminar_2: "I missed out on some useful advice.",
    choice_self_development_seminar_3: 'Learn online instead.',
    log_self_development_seminar_3: 'I gained knowledge more cheaply.',

    event_minor_accident_title: 'Minor Accident',
    event_minor_accident_desc: 'You had a minor accident in your daily life.',
    choice_minor_accident_1: 'Go to the doctor and get treatment.',
    log_minor_accident_1: 'I was treated quickly and recovered.',
    choice_minor_accident_2: 'Treat it at home.',
    log_minor_accident_2: 'It got worse before it got better.',
    choice_minor_accident_3: 'File an insurance claim.',
    log_minor_accident_3: 'The paperwork was slow but it helped later.',

    event_pyramid_scheme_title: 'Pyramid Scheme',
    event_pyramid_scheme_desc: 'A friend introduces you to a pyramid scheme.',
    choice_pyramid_scheme_1: 'Join and invest.',
    log_pyramid_scheme_1: 'I lost all my money to the scam.',
    choice_pyramid_scheme_2: 'Decline to join.',
    log_pyramid_scheme_2: "I was safe and kept my distance.",
    choice_pyramid_scheme_3: 'Warn others about it.',
    log_pyramid_scheme_3: 'I protected some friends from losing money.',

    event_relative_death_title: 'Relative Passes Away',
    event_relative_death_desc: 'You receive sad news that a distant relative (not in the family tree) has passed away.',
    choice_relative_death_1: 'Help organize the funeral.',
    log_relative_death_1: 'It was a heavy but important task.',
    choice_relative_death_2: 'Grieve deeply.',
    log_relative_death_2: 'I was devastated for weeks.',
    choice_relative_death_3: 'Provide emotional support to the family.',
    log_relative_death_3: 'Together we got through the loss.',

    event_large_gift_title: 'Large Gift',
    event_large_gift_desc: 'You received a large gift from a relative.',
    choice_large_gift_1: 'Accept it gratefully.',
    log_large_gift_1: 'I felt grateful and appreciated.',
    choice_large_gift_2: 'Feel awkward.',
    log_large_gift_2: "I wasn't sure how to react.",
    choice_large_gift_3: 'Give a gift or letter in return.',
    log_large_gift_3: 'I showed my appreciation respectfully.',

    event_stranger_asks_for_help_title: 'Stranger Asks for Help',
    event_stranger_asks_for_help_desc: 'A stranger asks for your help on the street.',
    choice_stranger_asks_for_help_1: 'Help them directly.',
    log_stranger_asks_for_help_1: 'Doing a good deed makes me feel happy.',
    choice_stranger_asks_for_help_2: 'Decline and walk away.',
    log_stranger_asks_for_help_2: "I avoided risk but felt guilty.",
    choice_stranger_asks_for_help_3: 'Direct them to a place that can help.',
    log_stranger_asks_for_help_3: 'They received the proper help.',

    event_social_movement_title: 'Social Movement',
    event_social_movement_desc: 'A large protest is happening in the city.',
    choice_social_movement_1: 'Join the protest.',
    log_social_movement_1: 'I felt empowered standing with others.',
    choice_social_movement_2: 'Stay away from it.',
    log_social_movement_2: 'I avoided danger but felt helpless.',
    choice_social_movement_3: 'Support online or donate.',
    log_social_movement_3: 'I contributed safely from home.',

    event_homeless_person_title: 'Homeless Person',
    event_homeless_person_desc: 'You encounter a homeless person on the street.',
    choice_homeless_person_1: 'Give them some money.',
    log_homeless_person_1: 'I hope it helps them a little.',
    choice_homeless_person_2: 'Walk by.',
    log_homeless_person_2: 'I felt guilty for ignoring them.',
    choice_homeless_person_3: 'Buy them food or direct them to a shelter.',
    log_homeless_person_3: 'I helped in a practical way.',

    event_lost_valuable_item_title: 'Lost a Valuable Item',
    event_lost_valuable_item_desc: 'You lost a valuable item.',
    choice_lost_valuable_item_1: 'Search for it thoroughly.',
    log_lost_valuable_item_1: 'I found it after a stressful search.',
    choice_lost_valuable_item_2: 'Accept the loss.',
    log_lost_valuable_item_2: 'I was sad but I moved on.',
    choice_lost_valuable_item_3: 'Post a notice or offer a reward.',
    log_lost_valuable_item_3: 'I increased my chances of getting it back.',

    event_rescued_from_accident_title: 'Rescued from an Accident',
    event_rescued_from_accident_desc: 'You were about to have an accident but were saved by a stranger.',
    choice_rescued_from_accident_1: 'Thank them sincerely.',
    log_rescued_from_accident_1: 'I expressed my deep gratitude.',
    choice_rescued_from_accident_2: 'Still in shock.',
    log_rescued_from_accident_2: "I couldn't calm down for hours.",
    choice_rescued_from_accident_3: 'Give a gift or keep in touch.',
    log_rescued_from_accident_3: 'I built a relationship with my rescuer.',

    event_falsely_accused_title: 'Falsely Accused',
    event_falsely_accused_desc: 'You were falsely accused of something you did not do.',
    choice_falsely_accused_1: 'Provide proof of your innocence.',
    log_falsely_accused_1: 'The truth cleared my name.',
    choice_falsely_accused_2: 'Stay silent and endure it.',
    log_falsely_accused_2: 'No one believed me.',
    choice_falsely_accused_3: 'Seek legal help.',
    log_falsely_accused_3: 'A lawyer helped me defend myself.',

    event_surprise_gift_title: 'Surprise Gift',
    event_surprise_gift_desc: 'You received a surprise gift.',
    choice_surprise_gift_1: 'Accept it with joy.',
    log_surprise_gift_1: 'The gift made me very happy!',
    choice_surprise_gift_2: 'Feel a bit confused.',
    log_surprise_gift_2: "I don't know why I received it.",
    choice_surprise_gift_3: 'Share the joy with others.',
    log_surprise_gift_3: 'I spread the happiness by showing it to my friends.',

    log_death_low_happiness: "{name} passed away due to prolonged unhappiness.",
    log_death_low_health: "{name} passed away due to prolonged poor health.",
    log_death_low_happiness_and_health: "{name} passed away due to prolonged unhappiness and poor health.",
    log_happiness_no_promotion: "{name}'s happiness is decreasing due to lack of promotion in {jobTitle}.",

    // Trigger-only
    event_investment_success_large_title: 'Investment Success!',
    event_investment_success_large_desc: 'Your large investment has yielded a huge profit!',
    choice_investment_success_large_1: 'Wonderful!',
    log_investment_success_large_1: 'The risk paid off handsomely.',
    choice_investment_success_large_2: 'Reinvest immediately.',
    log_investment_success_large_2: "I'll use this money to continue investing.",
    choice_investment_success_large_3: 'Keep the money safe in the bank.',
    log_investment_success_large_3: 'I decided to secure the profit I just made.',
    
    event_investment_success_small_title: 'Investment Success',
    event_investment_success_small_desc: 'Your small investment has yielded a decent profit.',
    choice_investment_success_small_1: 'A good start.',
    log_investment_success_small_1: 'This is a good sign.',
    choice_investment_success_small_2: 'Celebrate this success.',
    log_investment_success_small_2: "I'll treat myself a little.",
    choice_investment_success_small_3: 'Continue investing in a controlled manner.',
    log_investment_success_small_3: 'I will use this experience to grow gradually.',
};