export default {
    // Main Events
    event_middleschool_late_for_school_title: 'Late for School',
    event_middleschool_late_for_school_desc: 'You were late for school due to a bus traffic jam.',
    choice_middleschool_late_for_school_1: 'Apologize to the teacher.',
    log_middleschool_late_for_school_1: 'I apologized and was allowed into class.',
    choice_middleschool_late_for_school_2: 'Sneak into class.',
    log_middleschool_late_for_school_2: 'I tried to sneak in without the teacher noticing.',
    choice_middleschool_late_for_school_3: 'Explain the reason to her.',
    log_middleschool_late_for_school_3: 'The teacher understood my situation.',

    event_middleschool_locker_trouble_title: 'Forgot to Open Locker',
    event_middleschool_locker_trouble_desc: 'You forgot to open your locker on time.',
    choice_middleschool_locker_trouble_1: 'Ask a friend for help.',
    log_middleschool_locker_trouble_1: 'My friend helped me get my books.',
    choice_middleschool_locker_trouble_2: 'Go ask the monitor.',
    log_middleschool_locker_trouble_2: 'I went to find the monitor to get my locker opened.',
    choice_middleschool_locker_trouble_3: 'Wait until recess to open it.',
    log_middleschool_locker_trouble_3: 'I decided to wait until recess, even if it meant missing some notes.',

    event_middleschool_science_project_title: 'Science Group Project',
    event_middleschool_science_project_desc: 'You are working on a science project with your group.',
    choice_middleschool_science_project_1: 'Work together.',
    log_middleschool_science_project_1: 'We collaborated well and made good progress.',
    choice_middleschool_science_project_2: 'Do minimal work.',
    log_middleschool_science_project_2: 'I didn\'t contribute much to the project.',
    choice_middleschool_science_project_3: 'Argue heatedly with a friend.',
    log_middleschool_science_project_3: 'We had a big argument over the project details.',

    event_middleschool_pe_basketball_title: 'P.E. Class: Basketball',
    event_middleschool_pe_basketball_desc: 'It\'s time for basketball in P.E. class.',
    choice_middleschool_pe_basketball_1: 'Play your best.',
    log_middleschool_pe_basketball_1: 'I had a great time playing and got some good exercise.',
    choice_middleschool_pe_basketball_2: 'Say you\'re tired and sit out.',
    log_middleschool_pe_basketball_2: 'I wasn\'t feeling up for it today.',
    choice_middleschool_pe_basketball_3: 'Sit on the sidelines and cheer.',
    log_middleschool_pe_basketball_3: 'I supported my friends from the bench.',

    event_middleschool_english_presentation_title: 'English Presentation',
    event_middleschool_english_presentation_desc: 'You have to give a presentation in English class.',
    choice_middleschool_english_presentation_1: 'Prepare thoroughly.',
    log_middleschool_english_presentation_1: 'I was well-prepared and gave a confident presentation.',
    choice_middleschool_english_presentation_2: 'Read from the paper.',
    log_middleschool_english_presentation_2: 'I just read my notes without making eye contact.',
    choice_middleschool_english_presentation_3: 'Speak hesitantly and without confidence.',
    log_middleschool_english_presentation_3: 'I was too nervous to speak clearly.',

    event_middleschool_student_council_title: 'Student Council',
    event_middleschool_student_council_desc: 'You are considering running for student council.',
    choice_middleschool_student_council_1: 'Run for office seriously.',
    log_middleschool_student_council_1: 'I gave a serious speech and campaigned hard.',
    choice_middleschool_student_council_2: 'Make slightly exaggerated promises.',
    log_middleschool_student_council_2: 'I might have promised more than I can deliver.',
    choice_middleschool_student_council_3: 'Speak little, mostly listen.',
    log_middleschool_student_council_3: 'I decided to observe this year instead of running.',

    event_middleschool_cafeteria_lunch_title: 'Lunch in the Cafeteria',
    event_middleschool_cafeteria_lunch_desc: 'It\'s lunchtime. Who do you sit with?',
    choice_middleschool_cafeteria_lunch_1: 'Sit with your best friend.',
    log_middleschool_cafeteria_lunch_1: 'I had a nice chat with my best friend over lunch.',
    choice_middleschool_cafeteria_lunch_2: 'Sit with your crush.',
    log_middleschool_cafeteria_lunch_2: 'My heart was pounding the whole time!',
    choice_middleschool_cafeteria_lunch_3: 'Sit alone quietly.',
    log_middleschool_cafeteria_lunch_3: 'I enjoyed some peaceful time by myself.',

    event_middleschool_school_dance_title: 'School Dance',
    event_middleschool_school_dance_desc: 'There\'s a small school dance happening.',
    choice_middleschool_school_dance_1: 'Ask a friend to dance.',
    log_middleschool_school_dance_1: 'We had a lot of fun dancing together.',
    choice_middleschool_school_dance_2: 'Stand shyly on the sidelines.',
    log_middleschool_school_dance_2: 'I was too shy to ask anyone to dance.',
    choice_middleschool_school_dance_3: 'Stand in a corner and observe.',
    log_middleschool_school_dance_3: 'I enjoyed watching everyone else have fun.',

    event_middleschool_science_experiment_title: 'Science Experiment',
    event_middleschool_science_experiment_desc: 'You are conducting a science experiment.',
    choice_middleschool_science_experiment_1: 'Follow the instructions.',
    log_middleschool_science_experiment_1: 'The experiment went smoothly.',
    choice_middleschool_science_experiment_2: 'Try your own way.',
    log_middleschool_science_experiment_2: 'I decided to experiment a little on my own.',
    choice_middleschool_science_experiment_3: 'Observe to learn.',
    log_middleschool_science_experiment_3: 'I watched my classmates to see how they did it.',

    event_middleschool_pop_quiz_title: 'Pop Quiz',
    event_middleschool_pop_quiz_desc: 'The teacher announces a surprise pop quiz.',
    choice_middleschool_pop_quiz_1: 'Do your best.',
    log_middleschool_pop_quiz_1: 'I answered to the best of my ability.',
    choice_middleschool_pop_quiz_2: 'Look at a friend\'s paper.',
    log_middleschool_pop_quiz_2: 'I tried to get a little help from my friend.',
    choice_middleschool_pop_quiz_3: 'Just write down anything to finish.',
    log_middleschool_pop_quiz_3: 'I just wanted to get it over with.',

    // Triggered Events
    event_middleschool_late_slip_title: 'Got a Late Slip',
    event_middleschool_late_slip_desc: 'You were caught sneaking in and got a late slip.',
    choice_middleschool_late_slip_1: 'Ask the teacher for a chance.',
    log_middleschool_late_slip_1: 'I pleaded with the teacher, but still got the slip.',
    choice_middleschool_late_slip_2: 'Accept the punishment.',
    log_middleschool_late_slip_2: 'I accepted the consequences of my actions.',
    choice_middleschool_late_slip_3: 'Explain the bus broke down.',
    log_middleschool_late_slip_3: 'I tried to explain my situation.',

    event_middleschool_punished_for_tardiness_title: 'Punished for Tardiness',
    event_middleschool_punished_for_tardiness_desc: 'You were punished for being late to class because of your locker.',
    choice_middleschool_punished_for_tardiness_1: 'Apologize to the teacher.',
    log_middleschool_punished_for_tardiness_1: 'I apologized for being late.',
    choice_middleschool_punished_for_tardiness_2: 'Accept writing a reflection.',
    log_middleschool_punished_for_tardiness_2: 'I had to write a reflection paper.',
    choice_middleschool_punished_for_tardiness_3: 'Suggest changing locker opening times.',
    log_middleschool_punished_for_tardiness_3: 'I suggested a change to the school rules.',

    event_middleschool_group_ostracized_title: 'Ostracized by the Group',
    event_middleschool_group_ostracized_desc: 'Your group members are ignoring you for not contributing.',
    choice_middleschool_group_ostracized_1: 'Apologize and make up for it.',
    log_middleschool_group_ostracized_1: 'I apologized and promised to do my share.',
    choice_middleschool_group_ostracized_2: 'Find another group.',
    log_middleschool_group_ostracized_2: 'I decided to find a new group to work with.',
    choice_middleschool_group_ostracized_3: 'Try to prove your ability.',
    log_middleschool_group_ostracized_3: 'I tried to show them I could be a valuable member.',

    event_middleschool_teacher_reprimand_pe_title: 'Reprimanded by Teacher in P.E.',
    event_middleschool_teacher_reprimand_pe_desc: 'The teacher reprimanded you for skipping P.E.',
    choice_middleschool_teacher_reprimand_pe_1: 'Go back and participate.',
    log_middleschool_teacher_reprimand_pe_1: 'I rejoined the class activity.',
    choice_middleschool_teacher_reprimand_pe_2: 'Explain you were really tired.',
    log_middleschool_teacher_reprimand_pe_2: 'I insisted that I wasn\'t feeling well.',
    choice_middleschool_teacher_reprimand_pe_3: 'Accept a deduction in grade.',
    log_middleschool_teacher_reprimand_pe_3: 'I accepted that my grade would be lowered.',

    event_middleschool_teacher_reprimand_presentation_title: 'Reprimanded for Reading from Paper',
    event_middleschool_teacher_reprimand_presentation_desc: 'The teacher reprimanded you for reading directly from your paper.',
    choice_middleschool_teacher_reprimand_presentation_1: 'Try to speak in your own words.',
    log_middleschool_teacher_reprimand_presentation_1: 'I tried to ad-lib the rest of my presentation.',
    choice_middleschool_teacher_reprimand_presentation_2: 'Apologize and continue.',
    log_middleschool_teacher_reprimand_presentation_2: 'I apologized and continued reading.',
    choice_middleschool_teacher_reprimand_presentation_3: 'Sit down and wait for another turn.',
    log_middleschool_teacher_reprimand_presentation_3: 'I was too embarrassed to continue.',

    event_middleschool_teased_by_friends_council_title: 'Teased by Friends',
    event_middleschool_teased_by_friends_council_desc: 'Your friends are teasing you for your exaggerated promises.',
    choice_middleschool_teased_by_friends_council_1: 'Joke back to lighten the mood.',
    log_middleschool_teased_by_friends_council_1: 'I laughed along with them.',
    choice_middleschool_teased_by_friends_council_2: 'Explain your good intentions.',
    log_middleschool_teased_by_friends_council_2: 'I tried to explain what I meant.',
    choice_middleschool_teased_by_friends_council_3: 'Silently ignore it.',
    log_middleschool_teased_by_friends_council_3: 'I didn\'t let their teasing bother me.',

    event_middleschool_teased_by_friends_crush_title: 'Teased for Sitting with Crush',
    event_middleschool_teased_by_friends_crush_desc: 'Your friends are teasing you for sitting with your crush.',
    choice_middleschool_teased_by_friends_crush_1: 'Pretend not to hear.',
    log_middleschool_teased_by_friends_crush_1: 'I acted like I didn\'t hear them.',
    choice_middleschool_teased_by_friends_crush_2: 'Smile and continue sitting.',
    log_middleschool_teased_by_friends_crush_2: 'I wasn\'t going to let them ruin the moment.',
    choice_middleschool_teased_by_friends_crush_3: 'Move to another table.',
    log_middleschool_teased_by_friends_crush_3: 'I got flustered and moved away.',

    event_middleschool_dragged_to_dance_title: 'Dragged Out to Dance',
    event_middleschool_dragged_to_dance_desc: 'Your friends dragged you onto the dance floor.',
    choice_middleschool_dragged_to_dance_1: 'Join in and dance for fun.',
    log_middleschool_dragged_to_dance_1: 'I decided to let loose and had a great time.',
    choice_middleschool_dragged_to_dance_2: 'Smile awkwardly and stand aside.',
    log_middleschool_dragged_to_dance_2: 'I still felt too shy to dance.',
    choice_middleschool_dragged_to_dance_3: 'Try dancing for a bit then rest.',
    log_middleschool_dragged_to_dance_3: 'I danced for one song and then went back to the sidelines.',

    event_middleschool_minor_incident_title: 'Minor Incident',
    event_middleschool_minor_incident_desc: 'There was a small incident during your experiment.',
    choice_middleschool_minor_incident_1: 'Report to the teacher.',
    log_middleschool_minor_incident_1: 'I told the teacher what happened right away.',
    choice_middleschool_minor_incident_2: 'Fix it correctly.',
    log_middleschool_minor_incident_2: 'I managed to fix my mistake.',
    choice_middleschool_minor_incident_3: 'Laugh it off and continue.',
    log_middleschool_minor_incident_3: 'It wasn\'t a big deal, so I just moved on.',

    event_middleschool_invigilator_warning_quiz_title: 'Warning from Invigilator',
    event_middleschool_invigilator_warning_quiz_desc: 'The invigilator warned you for cheating.',
    choice_middleschool_invigilator_warning_quiz_1: 'Apologize.',
    log_middleschool_invigilator_warning_quiz_1: 'I apologized and stopped cheating.',
    choice_middleschool_invigilator_warning_quiz_2: 'Argue back.',
    log_middleschool_invigilator_warning_quiz_2: 'I insisted that I wasn\'t cheating.',
    choice_middleschool_invigilator_warning_quiz_3: 'Accept a poor grade.',
    log_middleschool_invigilator_warning_quiz_3: 'I accepted the consequences and got a zero.',

    // Independent Events
    event_middleschool_class_debate_title: 'Class Debate',
    event_middleschool_class_debate_desc: 'There is a debate in class.',
    choice_middleschool_class_debate_1: 'State your opinion clearly.',
    log_middleschool_class_debate_1: 'I participated actively in the debate.',
    choice_middleschool_class_debate_2: 'Remain silent and listen.',
    log_middleschool_class_debate_2: 'I preferred to listen to others\' opinions.',
    choice_middleschool_class_debate_3: 'Participate a little then stop.',
    log_middleschool_class_debate_3: 'I shared one thought and then listened.',

    event_middleschool_after_school_sports_title: 'After-School Sports',
    event_middleschool_after_school_sports_desc: 'You are playing sports after school.',
    choice_middleschool_after_school_sports_1: 'Join the team.',
    log_middleschool_after_school_sports_1: 'I decided to join the school team.',
    choice_middleschool_after_school_sports_2: 'Play for fun with friends.',
    log_middleschool_after_school_sports_2: 'We had a casual game with friends.',
    choice_middleschool_after_school_sports_3: 'Sit and cheer.',
    log_middleschool_after_school_sports_3: 'I watched my friends play.',

    event_middleschool_bookstore_trip_title: 'Class Trip to the Bookstore',
    event_middleschool_bookstore_trip_desc: 'Your class is on a trip to the bookstore.',
    choice_middleschool_bookstore_trip_1: 'Buy textbooks.',
    log_middleschool_bookstore_trip_1: 'I bought the books I needed for class.',
    choice_middleschool_bookstore_trip_2: 'Buy comic books.',
    log_middleschool_bookstore_trip_2: 'I found some cool new comics.',
    choice_middleschool_bookstore_trip_3: 'Wander around and browse.',
    log_middleschool_bookstore_trip_3: 'I just enjoyed looking at all the books.',

    event_middleschool_doing_homework_title: 'Doing Homework',
    event_middleschool_doing_homework_desc: 'It\'s time to do your homework.',
    choice_middleschool_doing_homework_1: 'Complete it fully.',
    log_middleschool_doing_homework_1: 'I finished all of my homework.',
    choice_middleschool_doing_homework_2: 'Do half of it.',
    log_middleschool_doing_homework_2: 'I only did the easy parts.',
    choice_middleschool_doing_homework_3: 'Ask a friend and copy.',
    log_middleschool_doing_homework_3: 'I copied the answers from my friend.',

    event_middleschool_teacher_praise_title: 'Praised by Teacher',
    event_middleschool_teacher_praise_desc: 'The teacher praised you.',
    choice_middleschool_teacher_praise_1: 'Smile proudly.',
    log_middleschool_teacher_praise_1: 'It felt good to be praised.',
    choice_middleschool_teacher_praise_2: 'Blush shyly.',
    log_middleschool_teacher_praise_2: 'I was a bit embarrassed by the attention.',
    choice_middleschool_teacher_praise_3: 'Pretend to be indifferent.',
    log_middleschool_teacher_praise_3: 'I acted like it was no big deal.',

    event_middleschool_teacher_criticism_title: 'Criticized by Teacher',
    event_middleschool_teacher_criticism_desc: 'The teacher criticized you.',
    choice_middleschool_teacher_criticism_1: 'Listen silently.',
    log_middleschool_teacher_criticism_1: 'I took the criticism quietly.',
    choice_middleschool_teacher_criticism_2: 'Explain the reason.',
    log_middleschool_teacher_criticism_2: 'I tried to explain my side of the story.',
    choice_middleschool_teacher_criticism_3: 'Feel sad and reflect.',
    log_middleschool_teacher_criticism_3: 'The criticism made me feel down.',

    event_middleschool_extracurricular_activity_title: 'Extracurricular Activity',
    event_middleschool_extracurricular_activity_desc: 'You are participating in an extracurricular activity.',
    choice_middleschool_extracurricular_activity_1: 'Participate enthusiastically.',
    log_middleschool_extracurricular_activity_1: 'I was very involved in the activity.',
    choice_middleschool_extracurricular_activity_2: 'Participate partially.',
    log_middleschool_extracurricular_activity_2: 'I only did the parts I was interested in.',
    choice_middleschool_extracurricular_activity_3: 'Sit and watch your friends.',
    log_middleschool_extracurricular_activity_3: 'I preferred to watch.',

    event_middleschool_class_picnic_title: 'Class Picnic',
    event_middleschool_class_picnic_desc: 'The class is having a picnic.',
    choice_middleschool_class_picnic_1: 'Participate in group games.',
    log_middleschool_class_picnic_1: 'The group games were a lot of fun.',
    choice_middleschool_class_picnic_2: 'Eat alone.',
    log_middleschool_class_picnic_2: 'I wanted some quiet time.',
    choice_middleschool_class_picnic_3: 'Go sightseeing and take pictures.',
    log_middleschool_class_picnic_3: 'I explored the area and took some photos.',

    event_middleschool_helping_a_friend_title: 'Helping a Friend with Studies',
    event_middleschool_helping_a_friend_desc: 'A friend needs help with their studies.',
    choice_middleschool_helping_a_friend_1: 'Explain it to your friend.',
    log_middleschool_helping_a_friend_1: 'I was happy to help my friend understand.',
    choice_middleschool_helping_a_friend_2: 'Lend them your notebook.',
    log_middleschool_helping_a_friend_2: 'I let them borrow my notes.',
    choice_middleschool_helping_a_friend_3: 'Study together.',
    log_middleschool_helping_a_friend_3: 'We studied together and both learned a lot.',

    event_middleschool_final_exam_day_title: 'Final Exam Day',
    event_middleschool_final_exam_day_desc: 'It is the day of the final exam.',
    choice_middleschool_final_exam_day_1: 'Review thoroughly.',
    log_middleschool_final_exam_day_1: 'I felt well-prepared for the exam.',
    choice_middleschool_final_exam_day_2: 'Review superficially.',
    log_middleschool_final_exam_day_2: 'I did a quick review before the exam.',
    choice_middleschool_final_exam_day_3: 'Guess while doing it.',
    log_middleschool_final_exam_day_3: 'I had to guess on many questions.',

    event_middleschool_class_meeting_title: 'Class Meeting',
    event_middleschool_class_meeting_desc: 'There is a class meeting.',
    choice_middleschool_class_meeting_1: 'Participate in speaking.',
    log_middleschool_class_meeting_1: 'I shared my thoughts with the class.',
    choice_middleschool_class_meeting_2: 'Sit and listen.',
    log_middleschool_class_meeting_2: 'I listened to what others had to say.',
    choice_middleschool_class_meeting_3: 'Joke with a friend.',
    log_middleschool_class_meeting_3: 'I was distracted and didn\'t pay attention.',

    event_middleschool_meeting_teacher_outside_title: 'Meeting a Teacher Outside School',
    event_middleschool_meeting_teacher_outside_desc: 'You meet a teacher outside of school.',
    choice_middleschool_meeting_teacher_outside_1: 'Greet them politely.',
    log_middleschool_meeting_teacher_outside_1: 'I greeted my teacher respectfully.',
    choice_middleschool_meeting_teacher_outside_2: 'Give a forced smile.',
    log_middleschool_meeting_teacher_outside_2: 'It was a bit awkward.',
    choice_middleschool_meeting_teacher_outside_3: 'Pretend not to see them.',
    log_middleschool_meeting_teacher_outside_3: 'I tried to avoid them.',

    event_middleschool_new_student_title: 'New Student Arrives',
    event_middleschool_new_student_desc: 'A new student has transferred to your class.',
    choice_middleschool_new_student_1: 'Actively get to know them.',
    log_middleschool_new_student_1: 'I introduced myself and made them feel welcome.',
    choice_middleschool_new_student_2: 'Sit at the same table.',
    log_middleschool_new_student_2: 'We sat together and had a nice conversation.',
    choice_middleschool_new_student_3: 'Wait for them to initiate conversation.',
    log_middleschool_new_student_3: 'I waited for them to talk to me first.',

    event_middleschool_online_gaming_title: 'Playing Online Games',
    event_middleschool_online_gaming_desc: 'You are playing online games.',
    choice_middleschool_online_gaming_1: 'Play for fun with friends.',
    log_middleschool_online_gaming_1: 'We had a great time playing together online.',
    choice_middleschool_online_gaming_2: 'Play for too long.',
    log_middleschool_online_gaming_2: 'I played for too long and felt tired the next day.',
    choice_middleschool_online_gaming_3: 'Do not participate.',
    log_middleschool_online_gaming_3: 'I\'m not interested in online games.',

    event_middleschool_sports_festival_title: 'Sports Festival',
    event_middleschool_sports_festival_desc: 'It\'s the school\'s sports festival.',
    choice_middleschool_sports_festival_1: 'Compete in the race.',
    log_middleschool_sports_festival_1: 'I ran in the race.',
    choice_middleschool_sports_festival_2: 'Compete in the long jump.',
    log_middleschool_sports_festival_2: 'I participated in the long jump event.',
    choice_middleschool_sports_festival_3: 'Be a cheerleader.',
    log_middleschool_sports_festival_3: 'I cheered for my classmates.',

    event_middleschool_chemistry_experiment_title: 'Chemistry Experiment',
    event_middleschool_chemistry_experiment_desc: 'You are doing a chemistry experiment.',
    choice_middleschool_chemistry_experiment_1: 'Follow the instructions.',
    log_middleschool_chemistry_experiment_1: 'I carefully followed the steps.',
    choice_middleschool_chemistry_experiment_2: 'Creatively add details.',
    log_middleschool_chemistry_experiment_2: 'I added a few extra steps to see what would happen.',
    choice_middleschool_chemistry_experiment_3: 'Observe your friends do it.',
    log_middleschool_chemistry_experiment_3: 'I watched how my friends did the experiment.',

    event_middleschool_foreign_visitor_title: 'Foreign Visitor in Class',
    event_middleschool_foreign_visitor_desc: 'A foreign visitor is in your class.',
    choice_middleschool_foreign_visitor_1: 'Actively start a conversation.',
    log_middleschool_foreign_visitor_1: 'I had a great conversation with the visitor.',
    choice_middleschool_foreign_visitor_2: 'Smile and say hello.',
    log_middleschool_foreign_visitor_2: 'I gave them a friendly welcome.',
    choice_middleschool_foreign_visitor_3: 'Remain silent.',
    log_middleschool_foreign_visitor_3: 'I was too shy to talk to them.',

    event_middleschool_art_class_title: 'Art Class',
    event_middleschool_art_class_desc: 'It\'s art class.',
    choice_middleschool_art_class_1: 'Draw according to the assignment.',
    log_middleschool_art_class_1: 'I followed the assignment for my drawing.',
    choice_middleschool_art_class_2: 'Draw creatively.',
    log_middleschool_art_class_2: 'I drew something from my imagination.',
    choice_middleschool_art_class_3: 'Sit and watch.',
    log_middleschool_art_class_3: 'I wasn\'t in the mood to draw today.',

    event_middleschool_exam_results_title: 'Receive Exam Results',
    event_middleschool_exam_results_desc: 'You have received your exam results.',
    choice_middleschool_exam_results_1: 'Joyfully show them to your friends.',
    log_middleschool_exam_results_1: 'I was happy with my results and shared them with my friends.',
    choice_middleschool_exam_results_2: 'Keep them quiet.',
    log_middleschool_exam_results_2: 'I kept my results to myself.',
    choice_middleschool_exam_results_3: 'Feel sad.',
    log_middleschool_exam_results_3: 'I was disappointed with my results.',

    event_middleschool_sharing_lunch_title: 'Sharing Lunch',
    event_middleschool_sharing_lunch_desc: 'You are sharing lunch with friends.',
    choice_middleschool_sharing_lunch_1: 'Give a portion to a friend.',
    log_middleschool_sharing_lunch_1: 'I shared some of my food with my friend.',
    choice_middleschool_sharing_lunch_2: 'Trade dishes.',
    log_middleschool_sharing_lunch_2: 'We traded some of our food.',
    choice_middleschool_sharing_lunch_3: 'Keep your portion.',
    log_middleschool_sharing_lunch_3: 'I was really hungry today.',

        // New Clubs
    club_entrepreneurship_name: 'Entrepreneurship Club',
    club_entrepreneurship_description: 'Learn the basics of business, finance, and leadership. For future CEOs.',
    club_model_un_name: 'Model UN Club',
    club_model_un_description: 'Debate global issues and learn about international relations. For future diplomats.',
    club_environmental_name: 'Environmental Club',
    club_environmental_description: 'Take action on environmental issues and promote sustainability. For future scientists and activists.',
    club_volunteering_name: 'Volunteering Club',
    club_volunteering_description: 'Give back to the community and help those in need. For future social workers and humanitarians.',
    club_chess_name: 'Chess Club',
    club_chess_description: 'Sharpen your mind and master the art of strategy. For future grandmasters of all fields.',
    club_film_media_name: 'Film & Media Club',
    club_film_media_description: 'Explore the world of filmmaking, from screenwriting to production. For future storytellers.',
    club_medical_name: 'Future Medical Professionals Club',
    club_medical_description: 'Get a head start on a career in medicine. For future doctors and nurses.',
    club_astronomy_name: 'Astronomy Club',
    club_astronomy_description: 'Explore the cosmos, from planets to distant galaxies. For future astronomers and engineers.',
    club_literary_magazine_name: 'Literary Magazine Club',
    club_literary_magazine_description: "Create and publish the school\'s literary journal. For future writers and editors.",
    club_architecture_engineering_name: 'Architecture & Engineering Club',
    club_architecture_engineering_description: 'Design and build amazing structures. For future architects and engineers.',

    // New Events

    event_business_pitch_title: 'Business Pitch Competition',
    event_business_pitch_description: 'The Entrepreneurship Club is hosting a business pitch competition. This is your chance to shine!',
    event_business_pitch_choice1: 'Present your innovative idea.',
    event_business_pitch_choice1_log: 'My pitch was a huge success! I think I have a future in business.',
    event_business_pitch_choice2: 'Help a friend with their presentation.',
    event_business_pitch_choice2_log: 'I helped my friend, and they did great. Teamwork makes the dream work!',

    event_model_un_title: 'Model UN Conference',
    event_model_un_description: 'The Model UN Club is attending a regional conference. It\'s time to represent our school.',
    event_model_un_choice1: 'Take the lead in debate.',
    event_model_un_choice1_log: 'I passionately debated our resolution and won an award!',
    event_model_un_choice2: 'Focus on networking with other delegates.',
    event_model_un_choice2_log: 'I made some great connections with students from other schools.',

    event_community_cleanup_title: 'Community Cleanup Initiative',
    event_community_cleanup_description: 'The Environmental Club is organizing a community cleanup day.',
    event_community_cleanup_choice1: 'Recruit volunteers and lead a team.',
    event_community_cleanup_choice1_log: 'We collected so much trash! It feels good to make a difference.',
    event_community_cleanup_choice2: 'Work quietly on your own.',
    event_community_cleanup_choice2_log: 'I focused on cleaning up my assigned area and did a thorough job.',

    event_charity_fundraiser_title: 'Charity Fundraiser Gala',
    event_charity_fundraiser_description: 'The Volunteering Club is hosting a fundraiser for a local charity.',
    event_charity_fundraiser_choice1: 'Organize the event logistics.',
    event_charity_fundraiser_choice1_log: 'The event went off without a hitch! We raised a lot of money for a good cause.',
    event_charity_fundraiser_choice2: 'Donate a large portion of your allowance.',
    event_charity_fundraiser_choice2_log: 'It was a big sacrifice, but it was worth it to help others.',

    event_chess_tournament_title: 'National Chess Tournament',
    event_chess_tournament_description: 'The Chess Club is competing in the national tournament.',
    event_chess_tournament_choice1: 'Execute a brilliant strategy.',
    event_chess_tournament_choice1_log: 'Checkmate! I won the tournament with a daring queen sacrifice.',
    event_chess_tournament_choice2: 'Play it safe and aim for a draw.',
    event_chess_tournament_choice2_log: 'I played conservatively and managed to secure a respectable draw against a tough opponent.',

    event_film_festival_title: 'Short Film Festival',
    event_film_festival_description: 'The Film & Media Club is hosting its first-ever short film festival.',
    event_film_festival_choice1: 'Submit your own film.',
    event_film_festival_choice1_log: 'My film won the audience award! I\'m so proud of my work.',
    event_film_festival_choice2: 'Help with the event organization.',
    event_film_festival_choice2_log: 'I helped run the projector and everything went smoothly. It was fun to be behind the scenes.',

    event_first_aid_title: 'First Aid/CPR Certification Drive',
    event_first_aid_description: 'The Future Medical Professionals Club is offering a first aid certification course.',
    event_first_aid_choice1: 'Master the techniques and teach others.',
    event_first_aid_choice1_log: 'I\'m now certified in CPR and first aid! I even helped teach some of my classmates.',
    event_first_aid_choice2: 'Just get the certification.',
    event_first_aid_choice2_log: 'I passed the course and got my certification. It\'s a valuable skill to have.',

    event_stargazing_title: 'Stargazing Night & Telescope Building',
    event_stargazing_description: 'The Astronomy Club is hosting a stargazing night.',
    event_stargazing_choice1: 'Build a powerful telescope.',
    event_stargazing_choice1_log: 'I built my own telescope and saw the rings of Saturn! It was incredible.',
    event_stargazing_choice2: 'Just enjoy the view.',
    event_stargazing_choice2_log: 'I lay back and watched the stars. It was a beautiful and peaceful night.',

    event_literary_journal_title: 'Launch of the School\'s Literary Journal',
    event_literary_journal_description: 'The Literary Magazine Club is launching the first issue of the school journal.',
    event_literary_journal_choice1: 'Read your poem aloud at the launch party.',
    event_literary_journal_choice1_log: 'I was nervous, but everyone loved my poem! It was a great experience.',
    event_literary_journal_choice2: 'Work as the editor for the journal.',
    event_literary_journal_choice2_log: 'I worked hard to edit all the submissions. The final journal looks amazing.',

    event_bridge_building_title: 'Bridge Building Competition',
    event_bridge_building_description: 'The Architecture & Engineering Club is hosting a bridge building competition.',
    event_bridge_building_choice1: 'Design an innovative and strong bridge.',
    event_bridge_building_choice1_log: 'My bridge held the most weight! My design was a success.',
    event_bridge_building_choice2: 'Focus on the aesthetics of the bridge.',
    event_bridge_building_choice2_log: 'My bridge might not have been the strongest, but it was definitely the best-looking one.',
};