
export default {
    event_pet_adoption_title: 'Pet Adoption Opportunity',
    event_pet_adoption_desc: 'A local animal shelter is holding an adoption event. Do you want to take a look?',
    choice_pet_adoption_1: 'Yes, let\'s find a new friend!',
    log_pet_adoption_1: 'I decided to adopt a new companion.',
    choice_pet_adoption_2: 'No, now is not the time.',
    log_pet_adoption_2: "I've decided it's not the right time to get a pet.",
    event_pet_sick_title: 'Pet is Sick',
    event_pet_sick_desc: 'Your pet seems unwell and lethargic.',
    choice_pet_sick_1: 'Take it to the vet.',
    log_pet_sick_1: 'The vet gave some medicine, and my pet is recovering.',
    choice_pet_sick_2: 'Let it rest on its own.',
    log_pet_sick_2: 'I hope my pet will recover on its own after some rest.',
    event_pet_damages_item_title: 'Pet Damages Item',
    event_pet_damages_item_desc: 'You come home to find that your pet has damaged a valuable item.',
    choice_pet_damages_item_1: 'Forgive and retrain it.',
    log_pet_damages_item_1: "It's just an animal, after all.",
    choice_pet_damages_item_2: 'Scold it harshly.',
    log_pet_damages_item_2: 'My pet seems scared after being scolded.',
    event_pet_lost_title: 'Pet is Lost',
    event_pet_lost_desc: 'Your pet has gone missing!',
    choice_pet_lost_1: 'Search everywhere.',
    log_pet_lost_1: 'I put up posters and searched everywhere.',
    choice_pet_lost_2: 'Wait for it to return on its own.',
    log_pet_lost_2: 'I hope it finds its way home.',
    event_pet_contest_title: 'Pet Contest',
    event_pet_contest_desc: "There's a pet contest in town.",
    choice_pet_contest_1: 'Enter the contest.',
    log_pet_contest_1: "This is a chance for my pet to shine.",
    choice_pet_contest_2: 'Do not participate.',
    log_pet_contest_2: "We're not interested in contests.",
    event_pet_gets_old_title: 'Pet Gets Old',
    event_pet_gets_old_desc: 'Your pet has grown old and weak.',
    choice_pet_gets_old_1: 'Take good care of it.',
    log_pet_gets_old_1: 'I will be with it in its final days.',
    choice_pet_gets_old_2: 'Euthanize it.',
    log_pet_gets_old_2: "It was a difficult decision, but I didn't want it to suffer.",
    // Trigger-only
    event_pet_sickness_worsens_title: "Pet's Sickness Worsens",
    event_pet_sickness_worsens_desc: "Your pet's condition is getting worse.",
    choice_pet_sickness_worsens_1: 'Take it to the veterinary hospital.',
    log_pet_sickness_worsens_1: 'My pet needs special care.',
    choice_pet_sickness_worsens_2: 'Care for it at home.',
    log_pet_sickness_worsens_2: "I'll do everything I can for it at home.",
    event_pet_found_title: 'Pet Found!',
    event_pet_found_desc: 'A neighbor found your pet!',
    choice_pet_found_1: 'What a relief!',
    log_pet_found_1: 'I am so happy to be reunited with my little friend.',
    event_pet_lost_forever_title: 'Pet Lost Forever',
    event_pet_lost_forever_desc: 'Despite searching, you could not find your pet.',
    choice_pet_lost_forever_1: 'Feel very sad.',
    log_pet_lost_forever_1: 'I will never forget it.',
    event_pet_contest_win_title: 'Won the Contest!',
    event_pet_contest_win_desc: 'Your pet won the contest!',
    choice_pet_contest_win_1: 'So proud!',
    log_pet_contest_win_1: 'My pet is the best!',
    event_pet_contest_lose_title: 'Lost the Contest',
    event_pet_contest_lose_desc: 'Your pet did not win the contest.',
    choice_pet_contest_lose_1: "It's okay.",
    log_pet_contest_lose_1: 'The important thing is that we participated.',
    event_pet_dies_title: 'Pet Passes Away',
    event_pet_dies_desc: 'Your beloved pet has passed away.',
    choice_pet_dies_1: 'Hold a small funeral.',
    log_pet_dies_1: 'Rest in peace, my dear friend.',
};
