export default {
    event_retired_official_retirement_day_title: 'Official Retirement Day',
    event_retired_official_retirement_day_desc: 'Today is your last day of work. How do you feel?',
    choice_retired_official_retirement_day_1: 'Have a small party with family',
    log_retired_official_retirement_day_1: 'I had a cozy party with my loved ones.',
    choice_retired_official_retirement_day_2: 'Celebrate with colleagues',
    log_retired_official_retirement_day_2: 'It was a meaningful farewell with those I worked with.',
    choice_retired_official_retirement_day_3: 'Stay home and rest because you feel tired',
    log_retired_official_retirement_day_3: 'After all these years, I can finally truly rest.',

    event_retired_first_pension_title: 'First Pension Received',
    event_retired_first_pension_desc: 'You just received your first pension payment.',
    choice_retired_first_pension_1: 'Put it into savings',
    log_retired_first_pension_1: 'I need to plan my expenses for the future.',
    choice_retired_first_pension_2: 'Use it to travel',
    log_retired_first_pension_2: 'This is a chance to take the trips I\'ve always dreamed of.',
    choice_retired_first_pension_3: 'Give a portion to children and grandchildren',
    log_retired_first_pension_3: 'Seeing my children and grandchildren happy is my happiness.',

    event_retired_health_checkup_title: 'Go for a general health check-up',
    event_retired_health_checkup_desc: 'It\'s time for a routine health check-up.',
    choice_retired_health_checkup_1: 'Do everything the doctor says',
    log_retired_health_checkup_1: 'Health is the most precious asset, I need to take care of it.',
    choice_retired_health_checkup_2: 'Skip a few tests',
    log_retired_health_checkup_2: 'I feel fine, no need for too many tests.',
    choice_retired_health_checkup_3: 'Postpone it for later because you feel tired',
    log_retired_health_checkup_3: 'I\'ll go for a check-up another day.',

    event_retired_volunteering_title: 'Participate in volunteer activities',
    event_retired_volunteering_desc: 'You are considering participating in a local volunteer activity.',
    choice_retired_volunteering_1: 'Help at the library',
    log_retired_volunteering_1: 'The work at the library is quiet and meaningful.',
    choice_retired_volunteering_2: 'Help at a nursing home',
    log_retired_volunteering_2: 'Chatting with other elderly friends brings me joy.',
    choice_retired_volunteering_3: 'Help distribute food for charity',
    log_retired_volunteering_3: 'Helping those in need makes my life feel more meaningful.',

    event_retired_long_trip_title: 'First long trip after retirement',
    event_retired_long_trip_desc: 'This is your first long trip after retiring.',
    choice_retired_long_trip_1: 'Go on a cross-state road trip',
    log_retired_long_trip_1: 'The trip was amazing with beautiful roadside scenery.',
    choice_retired_long_trip_2: 'Go on a cruise',
    log_retired_long_trip_2: 'Enjoying the sea and luxury services is so relaxing.',
    choice_retired_long_trip_3: 'Fly to Europe',
    log_retired_long_trip_3: 'Exploring new cultures is an unforgettable experience.',

    event_retired_amusement_park_title: 'Invited to an amusement park by grandchildren',
    event_retired_amusement_park_desc: 'The grandchildren invite you to an amusement park.',
    choice_retired_amusement_park_1: 'Go on all the thrill rides',
    log_retired_amusement_park_1: 'I feel like I\'m 20 years younger!',
    choice_retired_amusement_park_2: 'Just stand and watch',
    log_retired_amusement_park_2: 'Seeing the grandchildren happy makes me happy too.',
    choice_retired_amusement_park_3: 'Sit and rest because you can\'t keep up',
    log_retired_amusement_park_3: 'My health doesn\'t allow me to run around much anymore.',

    event_retired_seniors_club_title: 'Join a local seniors\' club',
    event_retired_seniors_club_desc: 'You decide to join the local seniors\' club.',
    choice_retired_seniors_club_1: 'Participate in dancing',
    log_retired_seniors_club_1: 'Dancing makes me feel healthy and vibrant.',
    choice_retired_seniors_club_2: 'Play chess with the group',
    log_retired_seniors_club_2: 'The challenging chess games keep my mind sharp.',
    choice_retired_seniors_club_3: 'Just sit and listen to stories because you\'re tired',
    log_retired_seniors_club_3: 'I prefer listening to people talk.',

    event_retired_supermarket_sale_title: 'Go to a supermarket sale with friends',
    event_retired_supermarket_sale_desc: 'Friends invite you to go bargain hunting at the supermarket.',
    choice_retired_supermarket_sale_1: 'Shop enthusiastically',
    log_retired_supermarket_sale_1: 'I got a lot of great deals.',
    choice_retired_supermarket_sale_2: 'Just browse the aisles',
    log_retired_supermarket_sale_2: 'I just went to look around for fun.',
    choice_retired_supermarket_sale_3: 'Sit and wait for friends to shop because your legs are tired',
    log_retired_supermarket_sale_3: 'Walking a lot makes my legs tired.',

    event_retired_class_reunion_title: 'Old class reunion',
    event_retired_class_reunion_desc: 'You attend a class reunion after many years apart.',
    choice_retired_class_reunion_1: 'Chat enthusiastically',
    log_retired_class_reunion_1: 'It was great to reminisce about old memories with friends.',
    choice_retired_class_reunion_2: 'Sing with old friends',
    log_retired_class_reunion_2: 'We sang the songs of our time together.',
    choice_retired_class_reunion_3: 'Sit and listen because you don\'t remember much',
    log_retired_class_reunion_3: 'My memory isn\'t as good as it used to be.',

    event_retired_family_dinner_title: 'Weekend family dinner',
    event_retired_family_dinner_desc: 'The family gathers for a weekend dinner.',
    choice_retired_family_dinner_1: 'Help with the cooking',
    log_retired_family_dinner_1: 'I still want to prepare meals for the whole family.',
    choice_retired_family_dinner_2: 'Play with grandchildren',
    log_retired_family_dinner_2: 'Playing with my grandchildren is my greatest joy.',
    choice_retired_family_dinner_3: 'Sit and rest, letting the children and grandchildren handle it',
    log_retired_family_dinner_3: 'It\'s time to let the younger generation take over.',
    
    // Triggered Events
    event_retired_feeling_empty_title: 'Feeling empty after the retirement party',
    event_retired_feeling_empty_desc: 'After retiring, you feel empty and lacking purpose.',
    choice_retired_feeling_empty_1: 'Go for a walk',
    log_retired_feeling_empty_1: 'A walk helped clear my head.',
    choice_retired_feeling_empty_2: 'Call friends',
    log_retired_feeling_empty_2: 'Talking with friends made me feel better.',
    choice_retired_feeling_empty_3: 'Sit alone and think',
    log_retired_feeling_empty_3: 'I need time to adjust to my new life.',

    event_retired_insufficient_funds_title: 'Realizing money is not enough for long-term expenses',
    event_retired_insufficient_funds_desc: 'You realize that your pension might not be enough for long-term expenses.',
    choice_retired_insufficient_funds_1: 'Find a part-time job',
    log_retired_insufficient_funds_1: 'I\'m still healthy enough to do some light work.',
    choice_retired_insufficient_funds_2: 'Seek financial advice',
    log_retired_insufficient_funds_2: 'A professional helped me create a reasonable spending plan.',
    choice_retired_insufficient_funds_3: 'Save as much as possible',
    log_retired_insufficient_funds_3: 'I need to tighten my belt even more.',

    event_retired_illness_discovered_title: 'Discovering an illness that needs treatment',
    event_retired_illness_discovered_desc: 'The health check-up results show you have an illness that requires treatment.',
    choice_retired_illness_discovered_1: 'Follow the doctor\'s advice',
    log_retired_illness_discovered_1: 'I trust modern medicine.',
    choice_retired_illness_discovered_2: 'Try herbal medicine',
    log_retired_illness_discovered_2: 'I want to try natural remedies.',
    choice_retired_illness_discovered_3: 'Hesitate to get treatment',
    log_retired_illness_discovered_3: 'I feel scared and don\'t want to face it yet.',

    event_retired_cant_keep_up_volunteer_title: 'Unable to keep up with volunteering',
    event_retired_cant_keep_up_volunteer_desc: 'You realize that volunteering requires more energy than you thought.',
    choice_retired_cant_keep_up_volunteer_1: 'Ask to leave',
    log_retired_cant_keep_up_volunteer_1: 'I asked to leave to preserve my health.',
    choice_retired_cant_keep_up_volunteer_2: 'Only provide light support',
    log_retired_cant_keep_up_volunteer_2: 'I switched to lighter tasks.',
    choice_retired_cant_keep_up_volunteer_3: 'Stop completely',
    log_retired_cant_keep_up_volunteer_3: 'I decided to stop volunteering altogether.',

    event_retired_travel_fatigue_title: 'Fatigue from a busy travel schedule',
    event_retired_travel_fatigue_desc: 'The packed schedule of the trip makes you feel exhausted.',
    choice_retired_travel_fatigue_1: 'Rest more',
    log_retired_travel_fatigue_1: 'I spent more time resting.',
    choice_retired_travel_fatigue_2: 'Reduce the number of trips',
    log_retired_travel_fatigue_2: 'We canceled a few destinations to have a more relaxing trip.',
    choice_retired_travel_fatigue_3: 'End the trip early',
    log_retired_travel_fatigue_3: 'Health comes first, we decided to go home early.',

    event_retired_heatstroke_title: 'Getting heatstroke at the park',
    event_retired_heatstroke_desc: 'Due to the hot weather, you got heatstroke and need to rest.',
    choice_retired_heatstroke_1: 'Find a cool place',
    log_retired_heatstroke_1: 'I found a shady spot to rest.',
    choice_retired_heatstroke_2: 'Drink water',
    log_retired_heatstroke_2: 'Drinking plenty of water helped me feel better.',
    choice_retired_heatstroke_3: 'Go home and rest',
    log_retired_heatstroke_3: 'I decided to go home to rest completely.',

    event_retired_difficulty_integrating_title: 'Initial difficulty integrating',
    event_retired_difficulty_integrating_desc: 'You find it difficult to integrate with other members of the club.',
    choice_retired_difficulty_integrating_1: 'Persevere',
    log_retired_difficulty_integrating_1: 'I persevered and gradually made friends.',
    choice_retired_difficulty_integrating_2: 'Find a smaller group',
    log_retired_difficulty_integrating_2: 'I found a smaller group that suited me better.',
    choice_retired_difficulty_integrating_3: 'Stop participating',
    log_retired_difficulty_integrating_3: 'Maybe this place is not for me.',

    event_retired_missed_promotions_title: 'Missed many promotions',
    event_retired_missed_promotions_desc: 'Because your legs were tired, you missed out on many good sale items.',
    choice_retired_missed_promotions_1: 'Ask a friend to buy for you',
    log_retired_missed_promotions_1: 'My friend was kind enough to buy a few items for me.',
    choice_retired_missed_promotions_2: 'Buy online',
    log_retired_missed_promotions_2: 'Online shopping is much more convenient.',
    choice_retired_missed_promotions_3: 'Skip it',
    log_retired_missed_promotions_3: 'Anyway, I don\'t really need them.',

    event_retired_loneliness_after_reunion_title: 'Feeling lonely after the reunion',
    event_retired_loneliness_after_reunion_desc: 'After the class reunion, you feel an indescribable loneliness.',
    choice_retired_loneliness_after_reunion_1: 'Call a friend',
    log_retired_loneliness_after_reunion_1: 'Talking with a close friend helped me feel better.',
    choice_retired_loneliness_after_reunion_2: 'Write in a diary',
    log_retired_loneliness_after_reunion_2: 'Writing down my thoughts helped me release my emotions.',
    choice_retired_loneliness_after_reunion_3: 'Sit sadly',
    log_retired_loneliness_after_reunion_3: 'I was lost in old memories.',

    event_retired_lose_central_role_title: 'Feeling no longer the central figure',
    event_retired_lose_central_role_desc: 'You realize that you are no longer the center of the family.',
    choice_retired_lose_central_role_1: 'Proactively offer small help',
    log_retired_lose_central_role_1: 'I find joy in helping my children and grandchildren with small things.',
    choice_retired_lose_central_role_2: 'Talk to your children and grandchildren',
    log_retired_lose_central_role_2: 'I shared my feelings with my children.',
    choice_retired_lose_central_role_3: 'Silently accept',
    log_retired_lose_central_role_3: 'This is the natural law of life.',

    // Independent Events
    event_retired_morning_routine_title: 'Daily morning',
    event_retired_morning_routine_desc: 'A normal morning for a retiree.',
    choice_retired_morning_routine_1: 'Go for a walk',
    log_retired_morning_routine_1: 'A morning walk makes me feel refreshed.',
    choice_retired_morning_routine_2: 'Sit and read the newspaper',
    log_retired_morning_routine_2: 'Keeping up with the news is a good habit.',
    choice_retired_morning_routine_3: 'Stay home and rest because you\'re tired',
    log_retired_morning_routine_3: 'I don\'t feel well today.',

    event_retired_watching_tv_title: 'Watch TV',
    event_retired_watching_tv_desc: 'You are spending time watching TV.',
    choice_retired_watching_tv_1: 'Watch the news',
    log_retired_watching_tv_1: 'I always want to know what\'s happening in the world.',
    choice_retired_watching_tv_2: 'Watch old movies',
    log_retired_watching_tv_2: 'Old movies bring back many good memories.',
    choice_retired_watching_tv_3: 'Nod off while watching',
    log_retired_watching_tv_3: 'I fell asleep without realizing it.',
    
    event_retired_playing_with_grandkids_title: 'Play with grandchildren',
    event_retired_playing_with_grandkids_desc: 'You are spending time playing with your grandchildren.',
    choice_retired_playing_with_grandkids_1: 'Take the grandchildren out to play',
    log_retired_playing_with_grandkids_1: 'We had a fun day at the park.',
    choice_retired_playing_with_grandkids_2: 'Tell fairy tales',
    log_retired_playing_with_grandkids_2: 'The grandchildren love listening to my stories.',
    choice_retired_playing_with_grandkids_3: 'Sit and watch the grandchildren play because you\'re tired',
    log_retired_playing_with_grandkids_3: 'Just watching them play is enough.',

    event_retired_meet_old_friend_title: 'Meet an old friend',
    event_retired_meet_old_friend_desc: 'You accidentally meet an old friend.',
    choice_retired_meet_old_friend_1: 'Chat over tea',
    log_retired_meet_old_friend_1: 'We sat down and reminisced about old stories.',
    choice_retired_meet_old_friend_2: 'Go for a walk together',
    log_retired_meet_old_friend_2: 'A short walk was enough to rekindle our friendship.',
    choice_retired_meet_old_friend_3: 'Sit and listen to your friend\'s stories',
    log_retired_meet_old_friend_3: 'I prefer listening to my friend\'s stories.',

    event_retired_grocery_shopping_title: 'Go to the market',
    event_retired_grocery_shopping_desc: 'It\'s time to buy groceries for the week.',
    choice_retired_grocery_shopping_1: 'Buy everything needed',
    log_retired_grocery_shopping_1: 'I bought everything I needed.',
    choice_retired_grocery_shopping_2: 'Buy less to carry lightly',
    log_retired_grocery_shopping_2: 'I don\'t want to carry heavy things.',
    choice_retired_grocery_shopping_3: 'Sit at a cafe and wait because you\'re tired',
    log_retired_grocery_shopping_3: 'I asked my children to go shopping for me.',
    
    event_retired_visiting_temple_title: 'Go to church/temple',
    event_retired_visiting_temple_desc: 'You go to a place of worship to find peace.',
    choice_retired_visiting_temple_1: 'Attend the main service',
    log_retired_visiting_temple_1: 'I feel at peace.',
    choice_retired_visiting_temple_2: 'Talk to fellow believers',
    log_retired_visiting_temple_2: 'Chatting with people of the same faith is interesting.',
    choice_retired_visiting_temple_3: 'Rest in the courtyard',
    log_retired_visiting_temple_3: 'The fresh air here is so pleasant.',

    event_retired_grandchild_birthday_title: 'Grandchild\'s birthday',
    event_retired_grandchild_birthday_desc: 'Today is a grandchild\'s birthday.',
    choice_retired_grandchild_birthday_1: 'Give a gift',
    log_retired_grandchild_birthday_1: 'My small gift made them very happy.',
    choice_retired_grandchild_birthday_2: 'Take commemorative photos',
    log_retired_grandchild_birthday_2: 'The photos will preserve this moment.',
    choice_retired_grandchild_birthday_3: 'Sit and watch the grandchildren have fun',
    log_retired_grandchild_birthday_3: 'Their joy is my joy.',

    event_retired_visit_children_title: 'Visit children living far away',
    event_retired_visit_children_desc: 'You are considering visiting your child who lives far away.',
    choice_retired_visit_children_1: 'Go by bus',
    log_retired_visit_children_1: 'The trip was a bit tiring but worth it.',
    choice_retired_visit_children_2: 'Go by plane',
    log_retired_visit_children_2: 'Flying is faster and more convenient.',
    choice_retired_visit_children_3: 'Decide not to go because you\'re tired',
    log_retired_visit_children_3: 'I\'ll wait for them to visit me.',

    event_retired_hot_afternoon_title: 'Hot sunny afternoon',
    event_retired_hot_afternoon_desc: 'The afternoon weather is very hot and humid.',
    choice_retired_hot_afternoon_1: 'Take a nap',
    log_retired_hot_afternoon_1: 'A nap helps me regain energy.',
    choice_retired_hot_afternoon_2: 'Drink cool water',
    log_retired_hot_afternoon_2: 'A glass of cool water is so refreshing.',
    choice_retired_hot_afternoon_3: 'Rest all afternoon',
    log_retired_hot_afternoon_3: 'I don\'t want to do anything in this weather.',

    event_retired_park_visit_title: 'Go to the park',
    event_retired_park_visit_desc: 'You take a walk in the nearby park.',
    choice_retired_park_visit_1: 'Practice tai chi',
    log_retired_park_visit_1: 'Tai chi helps my body become more flexible.',
    choice_retired_park_visit_2: 'Sit and talk',
    log_retired_park_visit_2: 'I had a pleasant conversation with some old friends.',
    choice_retired_park_visit_3: 'Sit quietly and enjoy the scenery',
    log_retired_park_visit_3: 'Watching nature is so peaceful.',

    event_retired_village_festival_title: 'Go to the village festival',
    event_retired_village_festival_desc: 'The village is holding a traditional festival.',
    choice_retired_village_festival_1: 'Watch cultural performances',
    log_retired_village_festival_1: 'The cultural performances were excellent.',
    choice_retired_village_festival_2: 'Eat snacks',
    log_retired_village_festival_2: 'The snacks here are delicious.',
    choice_retired_village_festival_3: 'Rest under a tree\'s shade',
    log_retired_village_festival_3: 'The festival atmosphere is so lively.',

    event_retired_new_class_title: 'Join a new class (drawing/music)',
    event_retired_new_class_desc: 'You decide to join a new class like drawing or music.',
    choice_retired_new_class_1: 'Learn enthusiastically',
    log_retired_new_class_1: 'Learning a new skill makes me feel young again.',
    choice_retired_new_class_2: 'Try a few sessions',
    log_retired_new_class_2: 'I tried a few sessions to see if I liked it.',
    choice_retired_new_class_3: 'Quit because it\'s difficult',
    log_retired_new_class_3: 'It\'s harder than I thought.',

    event_retired_periodic_checkup_title: 'Periodic medical check-up',
    event_retired_periodic_checkup_desc: 'It\'s time for a periodic medical check-up.',
    choice_retired_periodic_checkup_1: 'Do all the tests',
    log_retired_periodic_checkup_1: 'I want to be sure about my health.',
    choice_retired_periodic_checkup_2: 'Do half of them',
    log_retired_periodic_checkup_2: 'I only did the most necessary tests.',
    choice_retired_periodic_checkup_3: 'Cancel because you\'re tired',
    log_retired_periodic_checkup_3: 'I don\'t feel like going for a check-up today.',

    event_retired_rainy_day_title: 'Rainy day',
    event_retired_rainy_day_desc: 'A sad and gloomy rainy day.',
    choice_retired_rainy_day_1: 'Sit and read a book',
    log_retired_rainy_day_1: 'Reading by a rainy window is a refined pleasure.',
    choice_retired_rainy_day_2: 'Take a nap',
    log_retired_rainy_day_2: 'The sound of rain is the best lullaby.',
    choice_retired_rainy_day_3: 'Sit and watch the rain',
    log_retired_rainy_day_3: 'I just sat quietly and watched the raindrops.',

    event_retired_visit_relatives_title: 'Visit relatives',
    event_retired_visit_relatives_desc: 'You visit relatives who live far away.',
    choice_retired_visit_relatives_1: 'Have a pleasant chat',
    log_retired_visit_relatives_1: 'Meeting relatives is always a happy occasion.',
    choice_retired_visit_relatives_2: 'Eat with them',
    log_retired_visit_relatives_2: 'The family meal was so cozy.',
    choice_retired_visit_relatives_3: 'Sit quietly and listen to stories',
    log_retired_visit_relatives_3: 'I enjoy listening to everyone\'s stories.',

    event_retired_watching_sports_title: 'Watch sports',
    event_retired_watching_sports_desc: 'You are watching a sports match on TV.',
    choice_retired_watching_sports_1: 'Cheer for your favorite team',
    log_retired_watching_sports_1: 'The match was so exciting!',
    choice_retired_watching_sports_2: 'Talk with friends',
    log_retired_watching_sports_2: 'Watching with friends is much more fun.',
    choice_retired_watching_sports_3: 'Nod off in the middle',
    log_retired_watching_sports_3: 'I fell asleep without realizing it.',

    event_retired_insomnia_title: 'Insomnia',
    event_retired_insomnia_desc: 'You can\'t sleep at night.',
    choice_retired_insomnia_1: 'Count sheep',
    log_retired_insomnia_1: 'I counted up to 1000 sheep and was still awake.',
    choice_retired_insomnia_2: 'Drink milk',
    log_retired_insomnia_2: 'A warm glass of milk helps me sleep better.',
    choice_retired_insomnia_3: 'Sit quietly and wait for morning',
    log_retired_insomnia_3: 'Another long night.',

    event_retired_community_festival_title: 'Community festival',
    event_retired_community_festival_desc: 'The community where you live is holding a festival.',
    choice_retired_community_festival_1: 'Participate enthusiastically',
    log_retired_community_festival_1: 'I had a great time.',
    choice_retired_community_festival_2: 'Take a walk around',
    log_retired_community_festival_2: 'I just took a walk to see the atmosphere.',
    choice_retired_community_festival_3: 'Rest early because you\'re tired',
    log_retired_community_festival_3: 'I don\'t have enough energy to participate for long.',

    event_retired_surprise_gift_title: 'Receive a surprise gift',
    event_retired_surprise_gift_desc: 'You receive a surprise gift from an old friend.',
    choice_retired_surprise_gift_1: 'Joyful',
    log_retired_surprise_gift_1: 'The gift is so meaningful!',
    choice_retired_surprise_gift_2: 'Moved',
    log_retired_surprise_gift_2: 'I was very touched by your kindness.',
    choice_retired_surprise_gift_3: 'Shy',
    log_retired_surprise_gift_3: 'I don\'t know what to do in return.',

    event_retired_sharing_with_grandkids_title: 'Share food with grandchildren',
    event_retired_sharing_with_grandkids_desc: 'You have a tasty snack and the grandchildren are watching.',
    choice_retired_sharing_with_grandkids_1: 'Give the grandchildren a lot',
    log_retired_sharing_with_grandkids_1: 'I save the best part for the grandchildren.',
    choice_retired_sharing_with_grandkids_2: 'Share equally',
    log_retired_sharing_with_grandkids_2: 'Everyone gets a piece.',
    choice_retired_sharing_with_grandkids_3: 'Keep a small portion for yourself',
    log_retired_sharing_with_grandkids_3: 'I want to eat a little too.',
};
