export default {
    // Main Events
    event_university_first_day_title: 'First Day of University',
    event_university_first_day_desc: 'It\'s your first day of university, a fresh start.',
    choice_university_first_day_1: 'Participate fully.',
    log_university_first_day_1: 'I attended all orientation events and made some new friends.',
    choice_university_first_day_2: 'Oversleep.',
    log_university_first_day_2: 'I overslept and missed the welcome ceremony.',
    choice_university_first_day_3: 'Arrive a little late.',
    log_university_first_day_3: 'I was a bit late but managed to catch up.',

    event_university_forgot_registration_title: 'Forgot to Register for Courses',
    event_university_forgot_registration_desc: 'You forgot to register for your courses on time.',
    choice_university_forgot_registration_1: 'Ask a professor/advisor for help.',
    log_university_forgot_registration_1: 'My advisor helped me get into the classes I needed.',
    choice_university_forgot_registration_2: 'Register late.',
    log_university_forgot_registration_2: 'I had to register late and some classes were already full.',
    choice_university_forgot_registration_3: 'Decide to register late next semester.',
    log_university_forgot_registration_3: 'I decided to take it easy this semester and register for more courses later.',

    event_university_noisy_roommate_title: 'Noisy Roommate',
    event_university_noisy_roommate_desc: 'Your roommate plays loud music all night.',
    choice_university_noisy_roommate_1: 'Talk to them directly.',
    log_university_noisy_roommate_1: 'We had a chat and agreed on some quiet hours.',
    choice_university_noisy_roommate_2: 'Complain to the RA.',
    log_university_noisy_roommate_2: 'I reported the issue to the Resident Advisor.',
    choice_university_noisy_roommate_3: 'Wear headphones to endure it.',
    log_university_noisy_roommate_3: 'I decided to just block out the noise with my headphones.',

    event_university_group_presentation_title: 'Group Presentation',
    event_university_group_presentation_desc: 'You have a group presentation in front of the class.',
    choice_university_group_presentation_1: 'Prepare well.',
    log_university_group_presentation_1: 'Our group worked hard and delivered a great presentation.',
    choice_university_group_presentation_2: 'Shirk responsibility.',
    log_university_group_presentation_2: 'I didn\'t do my part of the work.',
    choice_university_group_presentation_3: 'Do nothing.',
    log_university_group_presentation_3: 'I was completely unprepared for the presentation.',

    event_university_midterm_exam_title: 'Midterm Exam',
    event_university_midterm_exam_desc: 'It\'s time for the midterm exams.',
    choice_university_midterm_exam_1: 'Study thoroughly.',
    log_university_midterm_exam_1: 'I studied hard and felt confident for the exams.',
    choice_university_midterm_exam_2: 'Cram for the test.',
    log_university_midterm_exam_2: 'I pulled an all-nighter to cram for the test.',
    choice_university_midterm_exam_3: 'Skip the exam.',
    log_university_midterm_exam_3: 'I decided to skip the exam altogether.',

    event_university_football_game_title: 'University Football Game',
    event_university_football_game_desc: 'There\'s a big football game for the university team.',
    choice_university_football_game_1: 'Go and cheer enthusiastically.',
    log_university_football_game_1: 'I went to the game and cheered my heart out for our team.',
    choice_university_football_game_2: 'Skip class to watch.',
    log_university_football_game_2: 'The game was more important than class today.',
    choice_university_football_game_3: 'Stay in the dorm to sleep/work.',
    log_university_football_game_3: 'I decided to catch up on sleep instead of going to the game.',

    event_university_dorm_party_title: 'Dorm Party',
    event_university_dorm_party_desc: 'There\'s a party in your dorm.',
    choice_university_dorm_party_1: 'Join in and have fun.',
    log_university_dorm_party_1: 'I went to the party and had a great time.',
    choice_university_dorm_party_2: 'Drink too much.',
    log_university_dorm_party_2: 'I had a bit too much to drink and things got hazy.',
    choice_university_dorm_party_3: 'Sit in a corner and play on your phone.',
    log_university_dorm_party_3: 'Parties aren\'t really my thing, so I just kept to myself.',

    event_university_internship_interview_title: 'Internship Interview',
    event_university_internship_interview_desc: 'You have an interview for an internship.',
    choice_university_internship_interview_1: 'Prepare thoroughly.',
    log_university_internship_interview_1: 'I researched the company and practiced my answers.',
    choice_university_internship_interview_2: 'Arrive late.',
    log_university_internship_interview_2: 'I misjudged the traffic and arrived late.',
    choice_university_internship_interview_3: 'Answer carelessly.',
    log_university_internship_interview_3: 'I didn\'t take the interview very seriously.',

    event_university_night_class_title: 'Night Class',
    event_university_night_class_desc: 'You have a night class.',
    choice_university_night_class_1: 'Listen attentively to the lecture.',
    log_university_night_class_1: 'I paid close attention and took good notes.',
    choice_university_night_class_2: 'Secretly play on your phone.',
    log_university_night_class_2: 'I was bored and scrolled through my phone.',
    choice_university_night_class_3: 'Study in a group with friends.',
    log_university_night_class_3: 'We worked together and helped each other understand the material.',

    event_university_submit_essay_title: 'Submit Essay',
    event_university_submit_essay_desc: 'You have an essay to submit.',
    choice_university_submit_essay_1: 'Submit on time.',
    log_university_submit_essay_1: 'I finished my essay and submitted it before the deadline.',
    choice_university_submit_essay_2: 'Submit late.',
    log_university_submit_essay_2: 'I couldn\'t finish it on time and had to submit it late.',
    choice_university_submit_essay_3: 'Don\'t submit at all.',
    log_university_submit_essay_3: 'I just didn\'t do the assignment.',

    // Triggered Events
    event_university_missed_info_title: 'Missed Important Information',
    event_university_missed_info_desc: 'You missed some important information because you overslept.',
    choice_university_missed_info_1: 'Ask a friend again.',
    log_university_missed_info_1: 'My friend filled me in on what I missed.',
    choice_university_missed_info_2: 'Read the school email.',
    log_university_missed_info_2: 'I found the information in an email from the school.',
    choice_university_missed_info_3: 'Guess.',
    log_university_missed_info_3: 'I just tried to guess what I had missed.',

    event_university_class_full_title: 'Required Class is Full',
    event_university_class_full_desc: 'The required class you wanted to take is already full.',
    choice_university_class_full_1: 'Choose another class.',
    log_university_class_full_1: 'I had to pick a different elective.',
    choice_university_class_full_2: 'Get on the waiting list.',
    log_university_class_full_2: 'I put my name on the waiting list and hoped for the best.',
    choice_university_class_full_3: 'Ask the professor to open more slots.',
    log_university_class_full_3: 'I emailed the professor to see if they could add more students.',

    event_university_roommate_angry_title: 'Roommate is Angry',
    event_university_roommate_angry_desc: 'Your roommate is angry because you complained about them.',
    choice_university_roommate_angry_1: 'Apologize.',
    log_university_roommate_angry_1: 'I apologized to smooth things over.',
    choice_university_roommate_angry_2: 'Explain.',
    log_university_roommate_angry_2: 'I tried to explain my side of the story.',
    choice_university_roommate_angry_3: 'Engage in a cold war.',
    log_university_roommate_angry_3: 'We just ignored each other.',

    event_university_group_dislikes_you_title: 'Group Dislikes You',
    event_university_group_dislikes_you_desc: 'Your group dislikes you for shirking your responsibilities.',
    choice_university_group_dislikes_you_1: 'Try to do the remaining part.',
    log_university_group_dislikes_you_1: 'I tried to make up for it by doing the rest of the work.',
    choice_university_group_dislikes_you_2: 'Apologize.',
    log_university_group_dislikes_you_2: 'I apologized to my group members.',
    choice_university_group_dislikes_you_3: 'Get kicked out of the group.',
    log_university_group_dislikes_you_3: 'They kicked me out of the group.',

    event_university_exam_off_topic_title: 'Exam Not on Crammed Topics',
    event_university_exam_off_topic_desc: 'The exam questions were not on the topics you crammed for.',
    choice_university_exam_off_topic_1: 'Anxiously try to do it.',
    log_university_exam_off_topic_1: 'I tried my best to answer what I could.',
    choice_university_exam_off_topic_2: 'Skip the difficult questions.',
    log_university_exam_off_topic_2: 'I skipped the questions I didn\'t know.',
    choice_university_exam_off_topic_3: 'Submit the paper early.',
    log_university_exam_off_topic_3: 'I just gave up and turned in my paper early.',

    event_university_marked_absent_title: 'Marked Absent by Teacher',
    event_university_marked_absent_desc: 'The teacher marked you absent for skipping class to watch the game.',
    choice_university_marked_absent_1: 'Apologize.',
    log_university_marked_absent_1: 'I apologized to the teacher.',
    choice_university_marked_absent_2: 'Blame traffic.',
    log_university_marked_absent_2: 'I made up an excuse about traffic.',
    choice_university_marked_absent_3: 'Accept the point deduction.',
    log_university_marked_absent_3: 'I accepted the consequence.',

    event_university_caught_by_ra_title: 'Caught by the RA',
    event_university_caught_by_ra_desc: 'The RA caught you drinking too much.',
    choice_university_caught_by_ra_1: 'Explain you were peer-pressured.',
    log_university_caught_by_ra_1: 'I tried to explain it wasn\'t my idea.',
    choice_university_caught_by_ra_2: 'Silently accept it.',
    log_university_caught_by_ra_2: 'I didn\'t argue and accepted the write-up.',
    choice_university_caught_by_ra_3: 'Apologize.',
    log_university_caught_by_ra_3: 'I apologized for my behavior.',

    event_university_rejected_immediately_title: 'Rejected Immediately',
    event_university_rejected_immediately_desc: 'You were rejected immediately for being late to the interview.',
    choice_university_rejected_immediately_1: 'Ask for another chance.',
    log_university_rejected_immediately_1: 'I asked if I could reschedule.',
    choice_university_rejected_immediately_2: 'Blame traffic.',
    log_university_rejected_immediately_2: 'I tried to explain about the traffic.',
    choice_university_rejected_immediately_3: 'Give up and not apply anymore.',
    log_university_rejected_immediately_3: 'I decided not to pursue the internship anymore.',

    event_university_reprimanded_by_teacher_title: 'Reprimanded by Teacher',
    event_university_reprimanded_by_teacher_desc: 'The teacher reprimanded you for playing on your phone.',
    choice_university_reprimanded_by_teacher_1: 'Put away the phone.',
    log_university_reprimanded_by_teacher_1: 'I put my phone away and paid attention.',
    choice_university_reprimanded_by_teacher_2: 'Continue secretly.',
    log_university_reprimanded_by_teacher_2: 'I tried to be more subtle about it.',
    choice_university_reprimanded_by_teacher_3: 'Explain you were looking up something for class.',
    log_university_reprimanded_by_teacher_3: 'I claimed I was using it for research.',

    event_university_points_deducted_title: 'Points Deducted',
    event_university_points_deducted_desc: 'Your points were deducted for submitting the essay late.',
    choice_university_points_deducted_1: 'Ask for forgiveness.',
    log_university_points_deducted_1: 'I asked the professor if they would make an exception.',
    choice_university_points_deducted_2: 'Accept the lower grade.',
    log_university_points_deducted_2: 'I accepted the penalty.',
    choice_university_points_deducted_3: 'Blame computer problems.',
    log_university_points_deducted_3: 'I said I had computer trouble.',

    // Independent Events
    event_university_choose_elective_title: 'Choose an Elective',
    event_university_choose_elective_desc: 'You are choosing an elective course.',
    choice_university_choose_elective_1: 'Choose an easy one.',
    log_university_choose_elective_1: 'I picked an easy class to boost my GPA.',
    choice_university_choose_elective_2: 'Choose based on interest.',
    log_university_choose_elective_2: 'I chose a class that I was genuinely interested in.',
    choice_university_choose_elective_3: 'Choose based on friends.',
    log_university_choose_elective_3: 'I signed up for the same class as my friends.',

    event_university_library_visit_title: 'Visit the Library',
    event_university_library_visit_desc: 'You are at the library.',
    choice_university_library_visit_1: 'Study seriously.',
    log_university_library_visit_1: 'I had a productive study session.',
    choice_university_library_visit_2: 'Nod off.',
    log_university_library_visit_2: 'I accidentally fell asleep while studying.',
    choice_university_library_visit_3: 'Surf the web.',
    log_university_library_visit_3: 'I got distracted and spent the time online.',

    event_university_join_club_title: 'Join a Club',
    event_university_join_club_desc: 'You are thinking about joining a club.',
    choice_university_join_club_1: 'Participate actively.',
    log_university_join_club_1: 'I became an active member of the club.',
    choice_university_join_club_2: 'Join for fun.',
    log_university_join_club_2: 'I just joined to hang out with friends.',
    choice_university_join_club_3: 'Quit midway.',
    log_university_join_club_3: 'I lost interest and quit the club.',

    event_university_professor_praise_title: 'Praised by Professor',
    event_university_professor_praise_desc: 'A professor praised you.',
    choice_university_professor_praise_1: 'Feel happy.',
    log_university_professor_praise_1: 'It felt good to be acknowledged.',
    choice_university_professor_praise_2: 'Feel shy.',
    log_university_professor_praise_2: 'I was a bit embarrassed by the praise.',
    choice_university_professor_praise_3: 'Pretend to be normal.',
    log_university_professor_praise_3: 'I acted like it wasn\'t a big deal.',

    event_university_professor_criticism_title: 'Criticized by Professor',
    event_university_professor_criticism_desc: 'A professor criticized you.',
    choice_university_professor_criticism_1: 'Remain silent.',
    log_university_professor_criticism_1: 'I took the criticism quietly.',
    choice_university_professor_criticism_2: 'Argue back.',
    log_university_professor_criticism_2: 'I tried to defend my work.',
    choice_university_professor_criticism_3: 'Apologize.',
    log_university_professor_criticism_3: 'I apologized for my mistake.',

    event_university_part_time_job_title: 'Get a Part-Time Job',
    event_university_part_time_job_desc: 'You are working a part-time job.',
    choice_university_part_time_job_1: 'Work diligently.',
    log_university_part_time_job_1: 'I worked hard and earned some extra money.',
    choice_university_part_time_job_2: 'Be lazy.',
    log_university_part_time_job_2: 'I slacked off a bit at my job.',
    choice_university_part_time_job_3: 'Learn the job quickly.',
    log_university_part_time_job_3: 'I picked up the skills for the job quickly.',

    event_university_study_group_title: 'Study Group Session',
    event_university_study_group_desc: 'You are in a study group session.',
    choice_university_study_group_1: 'Study seriously.',
    log_university_study_group_1: 'We focused on our studies.',
    choice_university_study_group_2: 'Chat.',
    log_university_study_group_2: 'We ended up just chatting instead of studying.',
    choice_university_study_group_3: 'Sit and listen.',
    log_university_study_group_3: 'I let my friends do most of the explaining.',

    event_university_class_trip_title: 'Class Trip',
    event_university_class_trip_desc: 'You are on a class trip.',
    choice_university_class_trip_1: 'Participate in games.',
    log_university_class_trip_1: 'The games were a lot of fun.',
    choice_university_class_trip_2: 'Sit and eat.',
    log_university_class_trip_2: 'I focused on the food.',
    choice_university_class_trip_3: 'Go take pictures.',
    log_university_class_trip_3: 'I took a lot of pictures of the scenery.',

    event_university_surprise_test_title: 'Surprise Test',
    event_university_surprise_test_desc: 'There is a surprise test in class.',
    choice_university_surprise_test_1: 'Do it seriously.',
    log_university_surprise_test_1: 'I did my best on the surprise test.',
    choice_university_surprise_test_2: 'Look at a friend\'s paper.',
    log_university_surprise_test_2: 'I needed a little help.',
    choice_university_surprise_test_3: 'Guess.',
    log_university_surprise_test_3: 'I had to guess most of the answers.',

    event_university_club_interview_title: 'Club Interview',
    event_university_club_interview_desc: 'You have an interview to join a club.',
    choice_university_club_interview_1: 'Prepare well.',
    log_university_club_interview_1: 'I was well-prepared for the interview.',
    choice_university_club_interview_2: 'Answer confidently.',
    log_university_club_interview_2: 'I answered all the questions with confidence.',
    choice_university_club_interview_3: 'Speak hesitantly.',
    log_university_club_interview_3: 'I was nervous and stumbled over my words.',

    event_university_sports_day_title: 'Sports Day',
    event_university_sports_day_desc: 'It\'s the university sports day.',
    choice_university_sports_day_1: 'Play ball.',
    log_university_sports_day_1: 'I played in a basketball game.',
    choice_university_sports_day_2: 'Run.',
    log_university_sports_day_2: 'I participated in a running event.',
    choice_university_sports_day_3: 'Sit and cheer.',
    log_university_sports_day_3: 'I cheered for my friends.',

    event_university_friends_party_title: 'Friends\' Party',
    event_university_friends_party_desc: 'You are at a party with friends.',
    choice_university_friends_party_1: 'Participate enthusiastically.',
    log_university_friends_party_1: 'I had a great time at the party.',
    choice_university_friends_party_2: 'Sit in a corner.',
    log_university_friends_party_2: 'I kept to myself.',
    choice_university_friends_party_3: 'Leave early.',
    log_university_friends_party_3: 'I wasn\'t feeling the party and left early.',

    event_university_museum_visit_title: 'Museum Visit',
    event_university_museum_visit_desc: 'You are visiting a museum.',
    choice_university_museum_visit_1: 'Listen to the guide.',
    log_university_museum_visit_1: 'I learned a lot from the tour guide.',
    choice_university_museum_visit_2: 'Wander around.',
    log_university_museum_visit_2: 'I just explored the museum on my own.',
    choice_university_museum_visit_3: 'Take pictures.',
    log_university_museum_visit_3: 'I took a lot of photos.',

    event_university_major_group_project_title: 'Major Group Project',
    event_university_major_group_project_desc: 'You have a major group project.',
    choice_university_major_group_project_1: 'Do your best.',
    log_university_major_group_project_1: 'I contributed a lot to the project.',
    choice_university_major_group_project_2: 'Shirk responsibility.',
    log_university_major_group_project_2: 'I let my group members do most of the work.',
    choice_university_major_group_project_3: 'Do a part.',
    log_university_major_group_project_3: 'I just did my assigned part.',

    event_university_holiday_festival_title: 'Holiday Festival at University',
    event_university_holiday_festival_desc: 'The university is holding a holiday festival.',
    choice_university_holiday_festival_1: 'Join the festival.',
    log_university_holiday_festival_1: 'The festival was a lot of fun.',
    choice_university_holiday_festival_2: 'Stay in the dorm.',
    log_university_holiday_festival_2: 'I preferred to stay in and relax.',
    choice_university_holiday_festival_3: 'Go out separately.',
    log_university_holiday_festival_3: 'I made my own plans with friends.',

    event_university_meet_professor_outside_title: 'Meet a Professor Outside University',
    event_university_meet_professor_outside_desc: 'You meet a professor outside of the university.',
    choice_university_meet_professor_outside_1: 'Greet them.',
    log_university_meet_professor_outside_1: 'I said hello to my professor.',
    choice_university_meet_professor_outside_2: 'Give a forced smile.',
    log_university_meet_professor_outside_2: 'It was a bit awkward.',
    choice_university_meet_professor_outside_3: 'Pretend not to see them.',
    log_university_meet_professor_outside_3: 'I avoided them.',

    event_university_online_class_title: 'Online Class',
    event_university_online_class_desc: 'You are taking an online class.',
    choice_university_online_class_1: 'Pay attention.',
    log_university_online_class_1: 'I focused on the online lecture.',
    choice_university_online_class_2: 'Open another tab.',
    log_university_online_class_2: 'I got distracted and browsed other websites.',
    choice_university_online_class_3: 'Study while eating.',
    log_university_online_class_3: 'I had a snack during class.',

    event_university_first_internship_day_title: 'First Day of Internship',
    event_university_first_internship_day_desc: 'It\'s your first day at your internship.',
    choice_university_first_internship_day_1: 'Work seriously.',
    log_university_first_internship_day_1: 'I tried to make a good impression.',
    choice_university_first_internship_day_2: 'Feel clumsy.',
    log_university_first_internship_day_2: 'I was a bit overwhelmed and made some mistakes.',
    choice_university_first_internship_day_3: 'Ask questions.',
    log_university_first_internship_day_3: 'I asked a lot of questions to learn the ropes.',

    event_university_exam_results_title: 'Receive Exam Results',
    event_university_exam_results_desc: 'You have received your exam results.',
    choice_university_exam_results_1: 'Feel happy.',
    log_university_exam_results_1: 'I was pleased with my grades.',
    choice_university_exam_results_2: 'Keep silent.',
    log_university_exam_results_2: 'I kept my results to myself.',
    choice_university_exam_results_3: 'Feel sad.',
    log_university_exam_results_3: 'I was disappointed with my results.',

    event_university_share_food_title: 'Share Food',
    event_university_share_food_desc: 'You are sharing food.',
    choice_university_share_food_1: 'Give a portion to a friend.',
    log_university_share_food_1: 'I shared my snack.',
    choice_university_share_food_2: 'Trade dishes.',
    log_university_share_food_2: 'We traded some of our food.',
    choice_university_share_food_3: 'Keep your portion.',
    log_university_share_food_3: 'I was too hungry to share.',
};
