export default {
    // Event Titles
    event_workinglife_first_day_title: 'First Day at Work',
    event_workinglife_team_meeting_title: 'Morning Team Meeting',
    event_workinglife_forgot_laptop_title: 'Forgot Laptop at Home',
    event_workinglife_urgent_deadline_title: 'Urgent Deadline',
    event_workinglife_difficult_task_title: 'Assigned a Difficult Task',
    event_workinglife_late_after_lunch_title: 'Late After Lunch',
    event_workinglife_company_presentation_title: 'Company-wide Presentation',
    event_workinglife_team_building_title: 'Weekend Team Building',
    event_workinglife_delayed_salary_title: 'Salary is Delayed',
    event_workinglife_difficult_client_title: 'Dealing with a Difficult Client',
    event_workinglife_boss_notices_title: 'Boss Notices Your Tardiness',
    event_workinglife_boss_reprimand_title: 'Reprimanded by Boss',
    event_workinglife_missed_deadline_title: 'Missed Deadline',
    event_workinglife_client_complaint_title: 'Client Complains',
    event_workinglife_boss_disappointed_title: 'Boss is Disappointed',
    event_workinglife_colleagues_laugh_title: 'Colleagues Laugh',
    event_workinglife_lose_points_with_boss_title: 'Lost Points with the Boss',
    event_workinglife_feel_isolated_title: 'Feeling Isolated',
    event_workinglife_financial_trouble_title: 'Financial Trouble',
    event_workinglife_client_unhappy_title: 'Client is Unhappy',
    event_workinglife_overtime_title: 'Working Overtime',
    event_workinglife_new_project_title: 'Join a New Project',
    event_workinglife_boss_praise_title: 'Praised by Boss',
    event_workinglife_boss_criticism_title: 'Criticized by Boss',
    event_workinglife_training_session_title: 'Attend a Training Session',
    event_workinglife_new_colleague_title: 'Meet a New Colleague',
    event_workinglife_office_lunch_title: 'Office Lunch',
    event_workinglife_client_meeting_title: 'Meeting with a Client',
    event_workinglife_group_work_title: 'Group Work',
    event_workinglife_company_party_title: 'Company Party',
    event_workinglife_business_trip_title: 'Business Trip',
    event_workinglife_end_of_day_title: 'End of the Workday',
    event_workinglife_work_delayed_title: 'Work is Delayed',
    event_workinglife_pay_raise_title: 'Got a Pay Raise',
    event_workinglife_bonus_cut_title: 'Bonus Cut',
    event_workinglife_policy_change_title: 'Company Policy Change',
    event_workinglife_computer_broken_title: 'Computer Broke Down',
    event_workinglife_lost_motivation_title: 'Lost Motivation',
    event_workinglife_performance_review_title: 'Performance Review Results',
    event_workinglife_share_office_snacks_title: 'Sharing Office Snacks',

    // Event Descriptions
    event_workinglife_first_day_desc: 'It\'s your first day at a new job. How do you approach it?',
    event_workinglife_team_meeting_desc: 'During the morning meeting, how do you participate?',
    event_workinglife_forgot_laptop_desc: 'You realize you left your work laptop at home.',
    event_workinglife_urgent_deadline_desc: 'A project with a very tight deadline has just been assigned to you.',
    event_workinglife_difficult_task_desc: 'Your boss assigns you a task that is beyond your current abilities.',
    event_workinglife_late_after_lunch_desc: 'You returned to the office late after your lunch break.',
    event_workinglife_company_presentation_desc: 'You have to give a presentation in front of the whole company.',
    event_workinglife_team_building_desc: 'The company is organizing a team-building event over the weekend.',
    event_workinglife_delayed_salary_desc: 'Your salary has been paid late this month.',
    event_workinglife_difficult_client_desc: 'You are dealing with a client who is very demanding and hard to please.',
    event_workinglife_boss_notices_desc: 'Your boss noticed you were late on your first day and seems displeased.',
    event_workinglife_boss_reprimand_desc: 'Your boss calls you out for not participating actively in the meeting.',
    event_workinglife_missed_deadline_desc: 'Because you had to go home to get your laptop, you missed an important deadline.',
    event_workinglife_client_complaint_desc: 'The client complained because you asked for more time.',
    event_workinglife_boss_disappointed_desc: 'The boss is disappointed that you refused the difficult task.',
    event_workinglife_colleagues_laugh_desc: 'Your colleagues are laughing because you tried to sneak in late.',
    event_workinglife_lose_points_with_boss_desc: 'You lost credibility with your boss due to the poor presentation.',
    event_workinglife_feel_isolated_desc: 'You feel isolated and out of place because you didn\'t attend the team-building event.',
    event_workinglife_financial_trouble_desc: 'The delayed salary has caused some financial difficulties.',
    event_workinglife_client_unhappy_desc: 'The client is not satisfied with your over-promising.',
    event_workinglife_overtime_desc: 'You have to work overtime.',
    event_workinglife_new_project_desc: 'You are invited to join a new project.',
    event_workinglife_boss_praise_desc: 'Your boss praises you.',
    event_workinglife_boss_criticism_desc: 'Your boss criticizes you.',
    event_workinglife_training_session_desc: 'You are attending a training session.',
    event_workinglife_new_colleague_desc: 'You meet a new colleague.',
    event_workinglife_office_lunch_desc: 'It\'s lunchtime at the office.',
    event_workinglife_client_meeting_desc: 'You are in a meeting with a client.',
    event_workinglife_group_work_desc: 'You are working in a group.',
    event_workinglife_company_party_desc: 'The company is having a party.',
    event_workinglife_business_trip_desc: 'You are on a business trip.',
    event_workinglife_end_of_day_desc: 'The workday is over.',
    event_workinglife_work_delayed_desc: 'Your work is delayed.',
    event_workinglife_pay_raise_desc: 'You got a pay raise.',
    event_workinglife_bonus_cut_desc: 'Your bonus has been cut.',
    event_workinglife_policy_change_desc: 'The company has changed its policies.',
    event_workinglife_computer_broken_desc: 'Your computer broke down.',
    event_workinglife_lost_motivation_desc: 'You have lost motivation for work.',
    event_workinglife_performance_review_desc: 'You have received your performance review results.',
    event_workinglife_share_office_snacks_desc: 'You are sharing snacks at the office.',

    // Choices
    choice_workinglife_first_day_1: 'Arrive early.',
    choice_workinglife_first_day_2: 'Arrive late.',
    choice_workinglife_first_day_3: 'Forget to prepare something.',
    choice_workinglife_team_meeting_1: 'Participate fully.',
    choice_workinglife_team_meeting_2: 'Just nod along.',
    choice_workinglife_team_meeting_3: 'Speak positively.',
    choice_workinglife_forgot_laptop_1: 'Borrow from a colleague.',
    choice_workinglife_forgot_laptop_2: 'Ask for permission to go get it.',
    choice_workinglife_forgot_laptop_3: 'Try to work on your phone.',
    choice_workinglife_urgent_deadline_1: 'Work through the night.',
    choice_workinglife_urgent_deadline_2: 'Postpone and ask for more time.',
    choice_workinglife_urgent_deadline_3: 'Intentionally delay.',
    choice_workinglife_difficult_task_1: 'Accept the task.',
    choice_workinglife_difficult_task_2: 'Politely decline.',
    choice_workinglife_difficult_task_3: 'Ask a colleague for help.',
    choice_workinglife_late_after_lunch_1: 'Apologize.',
    choice_workinglife_late_after_lunch_2: 'Sneak in.',
    choice_workinglife_late_after_lunch_3: 'Pretend you were busy in a meeting.',
    choice_workinglife_company_presentation_1: 'Prepare well.',
    choice_workinglife_company_presentation_2: 'Forget the content.',
    choice_workinglife_company_presentation_3: 'Read from the slides.',
    choice_workinglife_team_building_1: 'Participate enthusiastically.',
    choice_workinglife_team_building_2: 'Do not participate.',
    choice_workinglife_team_building_3: 'Sit in a corner and play on your phone.',
    choice_workinglife_delayed_salary_1: 'Ask HR.',
    choice_workinglife_delayed_salary_2: 'Wait a bit longer.',
    choice_workinglife_delayed_salary_3: 'Complain to colleagues.',
    choice_workinglife_difficult_client_1: 'Explain clearly.',
    choice_workinglife_difficult_client_2: 'Over-promise.',
    choice_workinglife_difficult_client_3: 'Ask the boss for help.',
    choice_workinglife_boss_notices_1: 'Apologize.',
    choice_workinglife_boss_notices_2: 'Explain.',
    choice_workinglife_boss_notices_3: 'Accept a bad evaluation.',
    choice_workinglife_boss_reprimand_1: 'Speak up more.',
    choice_workinglife_boss_reprimand_2: 'Explain you were tired.',
    choice_workinglife_boss_reprimand_3: 'Remain silent.',
    choice_workinglife_missed_deadline_1: 'Submit late.',
    choice_workinglife_missed_deadline_2: 'Ask for an extension.',
    choice_workinglife_missed_deadline_3: 'Ask a colleague for help.',
    choice_workinglife_client_complaint_1: 'Apologize to the client.',
    choice_workinglife_client_complaint_2: 'Explain.',
    choice_workinglife_client_complaint_3: 'Lose the contract.',
    choice_workinglife_boss_disappointed_1: 'Apologize.',
    choice_workinglife_boss_disappointed_2: 'Try to take the task back.',
    choice_workinglife_boss_disappointed_3: 'Get assigned easier work.',
    choice_workinglife_colleagues_laugh_1: 'Laugh it off.',
    choice_workinglife_colleagues_laugh_2: 'Explain.',
    choice_workinglife_colleagues_laugh_3: 'Sit down silently.',
    choice_workinglife_lose_points_with_boss_1: 'Try to improvise.',
    choice_workinglife_lose_points_with_boss_2: 'Apologize.',
    choice_workinglife_lose_points_with_boss_3: 'Ask a colleague to add on.',
    choice_workinglife_feel_isolated_1: 'Stand and watch from the outside.',
    choice_workinglife_feel_isolated_2: 'Get shunned by friends.',
    choice_workinglife_feel_isolated_3: 'Proactively connect later.',
    choice_workinglife_financial_trouble_1: 'Borrow from a friend.',
    choice_workinglife_financial_trouble_2: 'Ask for an advance.',
    choice_workinglife_financial_trouble_3: 'Cut back on spending.',
    choice_workinglife_client_unhappy_1: 'Apologize to the client.',
    choice_workinglife_client_unhappy_2: 'Ask the boss to handle it.',
    choice_workinglife_client_unhappy_3: 'Get reprimanded.',
    choice_workinglife_overtime_1: 'Complete the work.',
    choice_workinglife_overtime_2: 'Complain.',
    choice_workinglife_overtime_3: 'Leave early.',
    choice_workinglife_new_project_1: 'Enthusiastically.',
    choice_workinglife_new_project_2: 'Reluctantly.',
    choice_workinglife_new_project_3: 'Decline.',
    choice_workinglife_boss_praise_1: 'Thank them.',
    choice_workinglife_boss_praise_2: 'Feel shy.',
    choice_workinglife_boss_praise_3: 'Become more confident.',
    choice_workinglife_boss_criticism_1: 'Listen silently.',
    choice_workinglife_boss_criticism_2: 'Explain.',
    choice_workinglife_boss_criticism_3: 'Feel sad.',
    choice_workinglife_training_session_1: 'Study seriously.',
    choice_workinglife_training_session_2: 'Study while doing personal work.',
    choice_workinglife_training_session_3: 'Be absent.',
    choice_workinglife_new_colleague_1: 'Get to know them.',
    choice_workinglife_new_colleague_2: 'Keep a distance.',
    choice_workinglife_new_colleague_3: 'Ask about them.',
    choice_workinglife_office_lunch_1: 'Eat with colleagues.',
    choice_workinglife_office_lunch_2: 'Eat alone.',
    choice_workinglife_office_lunch_3: 'Eat out.',
    choice_workinglife_client_meeting_1: 'Prepare well.',
    choice_workinglife_client_meeting_2: 'Sit and listen.',
    choice_workinglife_client_meeting_3: 'Speak little.',
    choice_workinglife_group_work_1: 'Give opinions.',
    choice_workinglife_group_work_2: 'Remain silent.',
    choice_workinglife_group_work_3: 'Follow others.',
    choice_workinglife_company_party_1: 'Participate fully.',
    choice_workinglife_company_party_2: 'Sit in a corner.',
    choice_workinglife_company_party_3: 'Leave early.',
    choice_workinglife_business_trip_1: 'Prepare well.',
    choice_workinglife_business_trip_2: 'Forget documents.',
    choice_workinglife_business_trip_3: 'Constantly ask for directions.',
    choice_workinglife_end_of_day_1: 'Leave immediately.',
    choice_workinglife_end_of_day_2: 'Stay and continue working.',
    choice_workinglife_end_of_day_3: 'Sit and play.',
    choice_workinglife_work_delayed_1: 'Try to work faster.',
    choice_workinglife_work_delayed_2: 'Ask for an extension.',
    choice_workinglife_work_delayed_3: 'Ask for help.',
    choice_workinglife_pay_raise_1: 'Feel happy.',
    choice_workinglife_pay_raise_2: 'Thank them.',
    choice_workinglife_pay_raise_3: 'Keep quiet.',
    choice_workinglife_bonus_cut_1: 'Complain.',
    choice_workinglife_bonus_cut_2: 'Accept it.',
    choice_workinglife_bonus_cut_3: 'Look for a new job.',
    choice_workinglife_policy_change_1: 'Research it carefully.',
    choice_workinglife_policy_change_2: 'Have questions.',
    choice_workinglife_policy_change_3: 'Ignore it.',
    choice_workinglife_computer_broken_1: 'Report to IT.',
    choice_workinglife_computer_broken_2: 'Fix it yourself.',
    choice_workinglife_computer_broken_3: 'Borrow a friend\'s computer.',
    choice_workinglife_lost_motivation_1: 'Take a short break.',
    choice_workinglife_lost_motivation_2: 'Share with a friend.',
    choice_workinglife_lost_motivation_3: 'Keep trying.',
    choice_workinglife_performance_review_1: 'Feel happy.',
    choice_workinglife_performance_review_2: 'Keep quiet.',
    choice_workinglife_performance_review_3: 'Feel disappointed.',
    choice_workinglife_share_office_snacks_1: 'Give a portion to a friend.',
    choice_workinglife_share_office_snacks_2: 'Trade snacks.',
    choice_workinglife_share_office_snacks_3: 'Keep your portion.',

    // Logs
    log_workinglife_first_day_1: 'I arrived early to make a good impression.',
    log_workinglife_first_day_2: 'Being late on the first day was not a good look.',
    log_workinglife_first_day_3: 'I felt unprepared and flustered.',
    log_workinglife_team_meeting_1: 'I contributed valuable ideas to the discussion.',
    log_workinglife_team_meeting_2: 'My lack of participation was noticed.',
    log_workinglife_team_meeting_3: 'My positive attitude was well-received.',
    log_workinglife_forgot_laptop_1: 'My colleague was a lifesaver!',
    log_workinglife_forgot_laptop_2: 'Going home to get it cost me valuable time.',
    log_workinglife_forgot_laptop_3: 'Working on my phone was very inefficient.',
    log_workinglife_urgent_deadline_1: 'I was exhausted but I met the deadline.',
    log_workinglife_urgent_deadline_2: 'Asking for more time seemed unprofessional.',
    log_workinglife_urgent_deadline_3: 'Procrastinating was a huge mistake.',
    log_workinglife_difficult_task_1: 'I rose to the challenge and succeeded.',
    log_workinglife_difficult_task_2: 'Declining the task made me look incapable.',
    log_workinglife_difficult_task_3: 'Teamwork made the difficult task manageable.',
    log_workinglife_late_after_lunch_1: 'I apologized for my tardiness.',
    log_workinglife_late_after_lunch_2: 'I thought I got away with it, but people noticed.',
    log_workinglife_late_after_lunch_3: 'My excuse was not very convincing.',
    log_workinglife_company_presentation_1: 'My preparation paid off with a successful presentation.',
    log_workinglife_company_presentation_2: 'Forgetting my content was incredibly embarrassing.',
    log_workinglife_company_presentation_3: 'Reading from the slides made me seem unprepared.',
    log_workinglife_team_building_1: 'The team-building event was a great way to bond with colleagues.',
    log_workinglife_team_building_2: 'Skipping the event made me feel disconnected from the team.',
    log_workinglife_team_building_3: 'I was present but not really participating.',
    log_workinglife_delayed_salary_1: 'HR clarified the issue and the salary arrived soon after.',
    log_workinglife_delayed_salary_2: 'Waiting caused me a lot of stress.',
    log_workinglife_delayed_salary_3: 'Complaining with colleagues created a negative atmosphere.',
    log_workinglife_difficult_client_1: 'A clear explanation helped manage the client\'s expectations.',
    log_workinglife_difficult_client_2: 'I couldn\'t deliver on my promises, which made things worse.',
    log_workinglife_difficult_client_3: 'My boss stepped in and handled the situation.',
    log_workinglife_boss_notices_1: 'I apologized and promised to be punctual.',
    log_workinglife_boss_notices_2: 'My excuse didn\'t seem to convince my boss.',
    log_workinglife_boss_notices_3: 'My first impression is already tarnished.',
    log_workinglife_boss_reprimand_1: 'I started participating more actively after the reminder.',
    log_workinglife_boss_reprimand_2: 'The boss didn\'t seem to care about my excuse.',
    log_workinglife_boss_reprimand_3: 'My silence was interpreted as incompetence.',
    log_workinglife_missed_deadline_1: 'Submitting late had negative consequences for the project.',
    log_workinglife_missed_deadline_2: 'I got an extension, but it reflected poorly on me.',
    log_workinglife_missed_deadline_3: 'A colleague helped me finish, and I owe them big time.',
    log_workinglife_client_complaint_1: 'A sincere apology helped to calm the client down.',
    log_workinglife_client_complaint_2: 'Explaining didn\'t change the client\'s mind.',
    log_workinglife_client_complaint_3: 'The client was so unhappy they canceled the contract.',
    log_workinglife_boss_disappointed_1: 'I apologized and explained my reasoning.',
    log_workinglife_boss_disappointed_2: 'The boss appreciated my willingness to reconsider.',
    log_workinglife_boss_disappointed_3: 'I was given less important tasks after that.',
    log_workinglife_colleagues_laugh_1: 'Laughing along with them was the best way to handle it.',
    log_workinglife_colleagues_laugh_2: 'Explaining only made me look more guilty.',
    log_workinglife_colleagues_laugh_3: 'Ignoring them was the most professional response.',
    log_workinglife_lose_points_with_boss_1: 'My quick thinking saved the presentation from being a total disaster.',
    log_workinglife_lose_points_with_boss_2: 'A simple apology was the best I could do.',
    log_workinglife_lose_points_with_boss_3: 'My colleague helped fill in the gaps.',
    log_workinglife_feel_isolated_1: 'I just watched everyone else have fun.',
    log_workinglife_feel_isolated_2: 'My colleagues seemed to distance themselves from me after.',
    log_workinglife_feel_isolated_3: 'I tried to reconnect with my colleagues at work.',
    log_workinglife_financial_trouble_1: 'A friend helped me out of a tight spot.',
    log_workinglife_financial_trouble_2: 'The company agreed to give me a salary advance.',
    log_workinglife_financial_trouble_3: 'I had to be very frugal until my salary arrived.',
    log_workinglife_client_unhappy_1: 'Apologizing to the client was necessary.',
    log_workinglife_client_unhappy_2: 'My boss had to intervene to solve the issue.',
    log_workinglife_client_unhappy_3: 'I was reprimanded for the client\'s dissatisfaction.',
    log_workinglife_overtime_1: 'I got the job done, but felt exhausted.',
    log_workinglife_overtime_2: 'Complaining didn\'t make the work go away.',
    log_workinglife_overtime_3: 'I left on time, but the work was still there tomorrow.',
    log_workinglife_new_project_1: 'I was excited to take on a new challenge.',
    log_workinglife_project_bonus: '{name} received a bonus of ${amount} for their excellent work on the new project!',
    log_workinglife_new_project_2: 'I wasn\'t thrilled, but I did my part.',
    log_workinglife_new_project_3: 'I turned down the opportunity.',
    log_workinglife_boss_praise_1: 'The praise was a great motivator.',
    log_workinglife_boss_praise_2: 'I was a bit embarrassed by the public praise.',
    log_workinglife_boss_praise_3: 'The recognition boosted my confidence.',
    log_workinglife_boss_criticism_1: 'I took the feedback constructively.',
    log_workinglife_boss_criticism_2: 'I tried to explain my perspective.',
    log_workinglife_boss_criticism_3: 'The criticism was hard to hear.',
    log_workinglife_training_session_1: 'The training was very beneficial.',
    log_workinglife_training_session_2: 'I didn\'t get much out of the session.',
    log_workinglife_training_session_3: 'Missing the session was a bad idea.',
    log_workinglife_new_colleague_1: 'I made an effort to welcome the new colleague.',
    log_workinglife_new_colleague_2: 'I kept to myself.',
    log_workinglife_new_colleague_3: 'I learned a bit about the new person.',
    log_workinglife_office_lunch_1: 'Lunch with colleagues was a nice break.',
    log_workinglife_office_lunch_2: 'Eating alone gave me some quiet time.',
    log_workinglife_office_lunch_3: 'It was nice to get out of the office for lunch.',
    log_workinglife_client_meeting_1: 'Being prepared made the meeting a success.',
    log_workinglife_client_meeting_2: 'I learned a lot by listening.',
    log_workinglife_client_meeting_3: 'I didn\'t contribute much to the meeting.',
    log_workinglife_group_work_1: 'I took an active role in the group.',
    log_workinglife_group_work_2: 'I let others take the lead.',
    log_workinglife_group_work_3: 'I just did my assigned tasks.',
    log_workinglife_company_party_1: 'I had a great time at the company party.',
    log_workinglife_company_party_2: 'I wasn\'t in a social mood.',
    log_workinglife_company_party_3: 'I made an appearance then left.',
    log_workinglife_business_trip_1: 'The trip was productive and successful.',
    log_workinglife_business_trip_2: 'Forgetting my papers was a major headache.',
    log_workinglife_business_trip_3: 'I spent a lot of time lost.',
    log_workinglife_end_of_day_1: 'I value my work-life balance.',
    log_workinglife_end_of_day_2: 'Sometimes you have to put in extra hours.',
    log_workinglife_end_of_day_3: 'I relaxed a bit before heading home.',
    log_workinglife_work_delayed_1: 'I managed to catch up.',
    log_workinglife_work_delayed_2: 'Asking for an extension was the only option.',
    log_workinglife_work_delayed_3: 'A colleague helped me out.',
    log_workinglife_pay_raise_1: 'I was thrilled about the raise!',
    log_workinglife_pay_raise_2: 'I was grateful for the increase.',
    log_workinglife_pay_raise_3: 'I kept the news to myself.',
    log_workinglife_bonus_cut_1: 'I was very unhappy about the bonus cut.',
    log_workinglife_bonus_cut_2: 'It was disappointing, but I understand.',
    log_workinglife_bonus_cut_3: 'Maybe it\'s time to look for a new job.',
    log_workinglife_policy_change_1: 'It\'s important to understand the new rules.',
    log_workinglife_policy_change_2: 'I had some questions about the changes.',
    log_workinglife_policy_change_3: 'I decided to just go with the flow.',
    log_workinglife_computer_broken_1: 'IT handled it quickly.',
    log_workinglife_computer_broken_2: 'I managed to fix it myself!',
    log_workinglife_computer_broken_3: 'My colleague let me use their computer.',
    log_workinglife_lost_motivation_1: 'A short vacation was just what I needed.',
    log_workinglife_lost_motivation_2: 'Talking to a friend helped me regain perspective.',
    log_workinglife_lost_motivation_3: 'I just have to push through it.',
    log_workinglife_performance_review_1: 'I was happy with my review.',
    log_workinglife_performance_review_2: 'The review was okay, nothing special.',
    log_workinglife_performance_review_3: 'I was disappointed with my review.',
    log_workinglife_share_office_snacks_1: 'Sharing snacks is a good way to bond.',
    log_workinglife_share_office_snacks_2: 'It was fun to try different snacks.',
    log_workinglife_share_office_snacks_3: 'I was saving my snacks for later.',

    // Career Tracks
    career_track_unskilled_name: 'Unskilled Labor',
    career_track_unskilled_desc: 'General labor jobs that do not require specialized training.',
    career_track_trade_name: 'Skilled Trade',
    career_track_trade_desc: 'A hands-on career like an electrician or plumber.',
    career_track_business_name: 'Business',
    career_track_business_desc: 'A corporate career in analysis and management.',
    career_track_technology_name: 'Technology',
    career_track_technology_desc: 'A career in software development and engineering.',
    career_track_arts_name: 'Arts',
    career_track_arts_desc: 'A creative career in design and media.',
    career_track_medicine_name: 'Medicine',
    career_track_medicine_desc: 'A prestigious and demanding career in the healthcare field.',
};